# Swamp Mid City (Bayou Nocturne) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "bayou_thug", "name": "Bayou Thug", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 230,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (50, 180),
  "basic_attack": "swamp knife", "strong_attack": "bayou ambush",
  "player_abilities": [], "base_str": 12, "base_dex": 10, "base_con": 10, "base_int": 3, "base_hp": 280, "base_ap": 10,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "bayou_shade", "name": "Bayou Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 300,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (15, 60),
  "basic_attack": "bog touch", "strong_attack": "bayou wail",
  "player_abilities": ["dark_spirit_lv1_shade_whisper"],
  "base_str": 4, "base_dex": 10, "base_con": 6, "base_int": 12, "base_hp": 240, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "bayou_witch_mid", "name": "Bayou Witch", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 27, "rarity": "uncommon", "base_xp": 400,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (80, 280),
  "basic_attack": "voodoo hex", "strong_attack": "bayou curse",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_spirit_lv1_shade_whisper"],
  "base_str": 4, "base_dex": 8, "base_con": 6, "base_int": 18, "base_hp": 260, "base_ap": 16,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 4},
 {"id": "bayou_revenant", "name": "Bayou Revenant", "hostile_type": "undead", "role": "damage", "min_spawn_level": 33, "rarity": "common", "base_xp": 500,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (80, 280),
  "basic_attack": "necrotic claw", "strong_attack": "bog surge",
  "player_abilities": [],
  "base_str": 18, "base_dex": 8, "base_con": 16, "base_int": 4, "base_hp": 560, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
 {"id": "gator_lord_mid", "name": "Gator Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 42, "rarity": "rare", "base_xp": 1000,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (380, 1280),
  "basic_attack": "lord's bite", "strong_attack": "bayou decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 28, "base_dex": 12, "base_con": 26, "base_int": 8, "base_hp": 820, "base_ap": 10,
  "str_per_level": 5, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 1},
 {"id": "bayou_lich", "name": "Bayou Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 62, "rarity": "superrare", "base_xp": 9000,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (2000, 7000),
  "basic_attack": "bayou death bolt", "strong_attack": "lich bog storm",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
  "base_str": 8, "base_dex": 10, "base_con": 10, "base_int": 57, "base_hp": 2600, "base_ap": 47,
  "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 12},
 {"id": "bayou_titan", "name": "Bayou Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 82, "rarity": "superrare", "base_xp": 24000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (8000, 26000),
  "basic_attack": "bayou titan slam", "strong_attack": "bayou annihilation",
  "player_abilities": ["level_1_hostile_ability_bone_spear"],
  "base_str": 90, "base_dex": 12, "base_con": 84, "base_int": 12, "base_hp": 26000, "base_ap": 14,
  "str_per_level": 18, "dex_per_level": 2, "con_per_level": 17, "int_per_level": 2},
 {"id": "bayou_world_god", "name": "The Bayou World God", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 100000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (40000, 130000),
  "basic_attack": "world bayou decree", "strong_attack": "bayou nocturne apocalypse",
  "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
  "base_str": 26, "base_dex": 24, "base_con": 26, "base_int": 138, "base_hp": 80000, "base_ap": 114,
  "str_per_level": 5, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 28},
]
