# Forest Mid City (Boiling Bubble) — hostile seeds Lv 21–30.

RANDOM_HOSTILE_SEEDS = [
 {"id": "guild_enforcer_forest", "name": "Guild Enforcer", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 260,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (60, 200),
  "basic_attack": "guild punch", "strong_attack": "enforcer rush",
  "player_abilities": [],
  "base_str": 12, "base_dex": 8, "base_con": 10, "base_int": 4, "base_hp": 300, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "forest_shade_mid", "name": "Forest Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 21, "rarity": "uncommon", "base_xp": 320,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (20, 80),
  "basic_attack": "shade touch", "strong_attack": "forest whisper",
  "player_abilities": ["level_1_hostile_ability_night_whisper"],
  "base_str": 4, "base_dex": 12, "base_con": 6, "base_int": 14, "base_hp": 280, "base_ap": 14,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 3},
 {"id": "thorn_berserker", "name": "Thorn Berserker", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 25, "rarity": "common", "base_xp": 340,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (80, 280),
  "basic_attack": "thorn bash", "strong_attack": "briar fury",
  "player_abilities": [],
  "base_str": 16, "base_dex": 8, "base_con": 14, "base_int": 3, "base_hp": 380, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
 {"id": "canopy_crime_lord", "name": "Canopy Crime Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 30, "rarity": "rare", "base_xp": 800,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (300, 1000),
  "basic_attack": "lord's blade", "strong_attack": "canopy decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 22, "base_dex": 14, "base_con": 20, "base_int": 8, "base_hp": 620, "base_ap": 12,
  "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 1},
]
