# Swamp Large City (The Necropolis) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "necropolis_cultist", "name": "Necropolis Cultist", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 21, "rarity": "common", "base_xp": 260,
  "common_drop": "tome_int", "rare_drop": None, "money_range": (50, 180),
  "basic_attack": "ritual blade", "strong_attack": "death rite",
  "player_abilities": ["dark_spirit_lv1_shade_whisper"],
  "base_str": 8, "base_dex": 8, "base_con": 8, "base_int": 14, "base_hp": 280, "base_ap": 14,
  "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "swamp_revenant_lg", "name": "Swamp Revenant", "hostile_type": "undead", "role": "damage", "min_spawn_level": 22, "rarity": "common", "base_xp": 260,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (20, 80),
  "basic_attack": "necrotic claw", "strong_attack": "bog surge",
  "player_abilities": [],
  "base_str": 14, "base_dex": 6, "base_con": 12, "base_int": 4, "base_hp": 340, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 0, "con_per_level": 2, "int_per_level": 0},
 {"id": "necro_witch_lg", "name": "Necro Witch", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 27, "rarity": "uncommon", "base_xp": 440,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (90, 320),
  "basic_attack": "dark hex", "strong_attack": "necropolis curse",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_spirit_lv1_shade_whisper"],
  "base_str": 4, "base_dex": 8, "base_con": 6, "base_int": 20, "base_hp": 300, "base_ap": 18,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 4},
 {"id": "necropolis_enforcer", "name": "Necropolis Enforcer", "hostile_type": "undead", "role": "damage", "min_spawn_level": 32, "rarity": "uncommon", "base_xp": 560,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (100, 360),
  "basic_attack": "bone slam", "strong_attack": "necrotic rush",
  "player_abilities": [],
  "base_str": 18, "base_dex": 6, "base_con": 16, "base_int": 4, "base_hp": 500, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 0, "con_per_level": 3, "int_per_level": 0},
 {"id": "necro_crime_lord", "name": "Necropolis Crime Lord", "hostile_type": "undead", "role": "damage", "min_spawn_level": 40, "rarity": "rare", "base_xp": 1100,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (400, 1400),
  "basic_attack": "lord's bone blade", "strong_attack": "necropolis decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 28, "base_dex": 10, "base_con": 26, "base_int": 10, "base_hp": 900, "base_ap": 10,
  "str_per_level": 5, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 2},
 {"id": "bog_lich_lg", "name": "Bog Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 55, "rarity": "superrare", "base_xp": 7500,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (1500, 5500),
  "basic_attack": "bog death bolt", "strong_attack": "necropolis lich storm",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
  "base_str": 8, "base_dex": 10, "base_con": 10, "base_int": 56, "base_hp": 2800, "base_ap": 46,
  "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 12},
 {"id": "swamp_titan_lg", "name": "Swamp Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 75, "rarity": "superrare", "base_xp": 22000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (7000, 24000),
  "basic_attack": "swamp titan slam", "strong_attack": "necropolis annihilation",
  "player_abilities": ["level_1_hostile_ability_bone_spear"],
  "base_str": 94, "base_dex": 10, "base_con": 88, "base_int": 12, "base_hp": 30000, "base_ap": 14,
  "str_per_level": 19, "dex_per_level": 1, "con_per_level": 18, "int_per_level": 2},
 {"id": "necropolis_world_god", "name": "The Necropolis World God", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 120000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (50000, 160000),
  "basic_attack": "world death decree", "strong_attack": "necropolis world end",
  "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
  "base_str": 30, "base_dex": 24, "base_con": 28, "base_int": 140, "base_hp": 100000, "base_ap": 115,
  "str_per_level": 6, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 28},
]
