# Mountains Mid City (Gallows Rift) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "rift_raider", "name": "Rift Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 240,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (50, 180),
  "basic_attack": "rift slash", "strong_attack": "cliff ambush",
  "player_abilities": [], "base_str": 12, "base_dex": 10, "base_con": 10, "base_int": 3, "base_hp": 300, "base_ap": 10,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "gallows_shade", "name": "Gallows Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 300,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (20, 80),
  "basic_attack": "gallows touch", "strong_attack": "rift wail",
  "player_abilities": ["level_1_hostile_ability_night_whisper"],
  "base_str": 4, "base_dex": 10, "base_con": 6, "base_int": 12, "base_hp": 260, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "cliff_berserker", "name": "Cliff Berserker", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 27, "rarity": "common", "base_xp": 340,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (100, 340),
  "basic_attack": "cliff rush", "strong_attack": "avalanche fury",
  "player_abilities": [], "base_str": 16, "base_dex": 8, "base_con": 14, "base_int": 2, "base_hp": 380, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
 {"id": "rift_sorcerer", "name": "Rift Sorcerer", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 33, "rarity": "uncommon", "base_xp": 500,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (100, 360),
  "basic_attack": "rift bolt", "strong_attack": "gallows hex",
  "player_abilities": ["earth_magic_lv1_tremor", "earth_earth_magic_lv2_quake_field"],
  "base_str": 4, "base_dex": 8, "base_con": 6, "base_int": 20, "base_hp": 320, "base_ap": 18,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 5},
 {"id": "rift_golem", "name": "Rift Golem", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 42, "rarity": "rare", "base_xp": 900,
  "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 40),
  "basic_attack": "rift slam", "strong_attack": "cliff collapse",
  "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
  "base_str": 32, "base_dex": 2, "base_con": 28, "base_int": 6, "base_hp": 1100, "base_ap": 8,
  "str_per_level": 6, "dex_per_level": 0, "con_per_level": 5, "int_per_level": 1},
 {"id": "gallows_lich", "name": "Gallows Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 58, "rarity": "superrare", "base_xp": 6500,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (1500, 5000),
  "basic_attack": "gallows death bolt", "strong_attack": "lich rift storm",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
  "base_str": 8, "base_dex": 10, "base_con": 10, "base_int": 52, "base_hp": 2200, "base_ap": 44,
  "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 11},
 {"id": "rift_titan", "name": "Rift Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 80, "rarity": "superrare", "base_xp": 24000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (8000, 26000),
  "basic_attack": "titan rift slam", "strong_attack": "gallows annihilation",
  "player_abilities": ["earth_earth_earth_magic_lv3_earthshaker"],
  "base_str": 90, "base_dex": 10, "base_con": 86, "base_int": 12, "base_hp": 28000, "base_ap": 14,
  "str_per_level": 18, "dex_per_level": 1, "con_per_level": 17, "int_per_level": 2},
 {"id": "gallows_world_god", "name": "The Gallows World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 100000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (40000, 130000),
  "basic_attack": "world rift decree", "strong_attack": "gallows apocalypse",
  "player_abilities": ["earth_earth_earth_magic_lv3_earthshaker"],
  "base_str": 24, "base_dex": 28, "base_con": 24, "base_int": 140, "base_hp": 80000, "base_ap": 115,
  "str_per_level": 5, "dex_per_level": 5, "con_per_level": 5, "int_per_level": 28},
]
