# Grassland shared hostiles - rarity-coverage fill, Lv 1-20.
#
# Reusable across all grassland city sizes (large / mid / small) and the
# grassland wilderness. Self-sufficient for ANY zone: one seed of EVERY rarity
# at each 5-level mark (Lv 5, 10, 15, 20). A seed at level N covers the
# validator's sliding windows starting N-4..N, so multiples of 5 guarantee full
# REGION_HOSTILE_RARITY_GAP coverage regardless of a zone's existing seeds.
#
# Ability ids are reused from existing loaded band files (known-valid against
# PLAYER_ABILITY_SEEDS). Theme: bandit cavalry, wind elementals, rogue nomads,
# grass serpents.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 5 ???????????????????????????????????????????????????????????????
    {"id": "grassland_shared_field_stray", "name": "Field Stray", "hostile_type": "creature", "role": "damage", "min_spawn_level": 5, "rarity": "common", "base_xp": 40,
     "common_drop": "herb_minor", "rare_drop": None, "money_range": (5, 30),
     "basic_attack": "nipping bite", "strong_attack": "lunging snap",
     "player_abilities": [],
     "base_str": 5, "base_dex": 6, "base_con": 5, "base_int": 2, "base_hp": 42, "base_ap": 5,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 0},
    {"id": "grassland_shared_roadside_cutpurse", "name": "Roadside Cutpurse", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 5, "rarity": "uncommon", "base_xp": 55,
     "common_drop": "herb_minor", "rare_drop": "stimulant_small", "money_range": (10, 45),
     "basic_attack": "quick shiv", "strong_attack": "purse snatch strike",
     "player_abilities": ["fire_technique_lv1_scorch_slash"],
     "base_str": 5, "base_dex": 7, "base_con": 5, "base_int": 3, "base_hp": 46, "base_ap": 6,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 0},
    {"id": "grassland_shared_breeze_sprite", "name": "Breeze Sprite", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 5, "rarity": "rare", "base_xp": 75,
     "common_drop": "herb_minor", "rare_drop": "herb_med", "money_range": (12, 55),
     "basic_attack": "gusting flick", "strong_attack": "whirl snare",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 4, "base_dex": 8, "base_con": 5, "base_int": 8, "base_hp": 48, "base_ap": 7,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 1},
    {"id": "grassland_shared_dust_phantom", "name": "Dust Phantom", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 5, "rarity": "superrare", "base_xp": 90,
     "common_drop": "herb_minor", "rare_drop": "stimulant_med", "money_range": (20, 90),
     "basic_attack": "grit whisper", "strong_attack": "choking gust",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 5, "base_dex": 8, "base_con": 5, "base_int": 9, "base_hp": 52, "base_ap": 7,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 1},

    # ?? Lv 10 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_grass_serpent", "name": "Grass Serpent", "hostile_type": "creature", "role": "damage", "min_spawn_level": 10, "rarity": "common", "base_xp": 80,
     "common_drop": "herb_minor", "rare_drop": None, "money_range": (10, 50),
     "basic_attack": "coiling bite", "strong_attack": "venom lash",
     "player_abilities": [],
     "base_str": 8, "base_dex": 9, "base_con": 7, "base_int": 3, "base_hp": 70, "base_ap": 6,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 0},
    {"id": "grassland_shared_saddle_bandit", "name": "Saddle Bandit", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 10, "rarity": "uncommon", "base_xp": 105,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (18, 70),
     "basic_attack": "saber slash", "strong_attack": "charging cut",
     "player_abilities": ["fire_technique_lv1_scorch_slash"],
     "base_str": 10, "base_dex": 9, "base_con": 8, "base_int": 3, "base_hp": 78, "base_ap": 7,
     "str_per_level": 2, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 0},
    {"id": "grassland_shared_gale_warden", "name": "Gale Warden", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 10, "rarity": "rare", "base_xp": 150,
     "common_drop": "herb_med", "rare_drop": "herb_med", "money_range": (24, 90),
     "basic_attack": "wind volley", "strong_attack": "cyclone snare",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 8, "base_dex": 12, "base_con": 9, "base_int": 12, "base_hp": 84, "base_ap": 9,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 2},
    {"id": "grassland_shared_stormcalf_horror", "name": "Stormcalf Horror", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 10, "rarity": "superrare", "base_xp": 190,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (30, 120),
     "basic_attack": "static gore", "strong_attack": "thunderhead rend",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "level_1_hostile_ability_poison_dart"],
     "base_str": 12, "base_dex": 13, "base_con": 10, "base_int": 10, "base_hp": 92, "base_ap": 9,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 2},

    # ?? Lv 15 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_plains_prowler", "name": "Plains Prowler", "hostile_type": "creature", "role": "damage", "min_spawn_level": 15, "rarity": "common", "base_xp": 120,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (16, 70),
     "basic_attack": "stalking swipe", "strong_attack": "sprinting pounce",
     "player_abilities": [],
     "base_str": 11, "base_dex": 11, "base_con": 10, "base_int": 3, "base_hp": 100, "base_ap": 7,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "grassland_shared_nomad_outrider", "name": "Nomad Outrider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 15, "rarity": "uncommon", "base_xp": 150,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (24, 95),
     "basic_attack": "lance jab", "strong_attack": "riding charge",
     "player_abilities": ["fire_technique_lv1_scorch_slash"],
     "base_str": 12, "base_dex": 13, "base_con": 10, "base_int": 4, "base_hp": 105, "base_ap": 8,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 1, "int_per_level": 0},
    {"id": "grassland_shared_windsong_shaman", "name": "Windsong Shaman", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 15, "rarity": "rare", "base_xp": 220,
     "common_drop": "tome_int", "rare_drop": "herb_med", "money_range": (30, 120),
     "basic_attack": "gale hex", "strong_attack": "howling curse",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 7, "base_dex": 12, "base_con": 9, "base_int": 16, "base_hp": 100, "base_ap": 11,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 3},
    {"id": "grassland_shared_hollow_gale_wraith", "name": "Hollow Gale Wraith", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 15, "rarity": "superrare", "base_xp": 280,
     "common_drop": "tome_int", "rare_drop": "stimulant_large", "money_range": (40, 160),
     "basic_attack": "spectral gust", "strong_attack": "keening squall",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 9, "base_dex": 14, "base_con": 10, "base_int": 18, "base_hp": 118, "base_ap": 12,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 3},

    # ?? Lv 20 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_menhir_golem", "name": "Menhir Golem", "hostile_type": "construct", "role": "damage", "min_spawn_level": 20, "rarity": "common", "base_xp": 160,
     "common_drop": None, "rare_drop": "herb_med", "money_range": (0, 40),
     "basic_attack": "standing-stone slam", "strong_attack": "monolith crush",
     "player_abilities": [],
     "base_str": 14, "base_dex": 5, "base_con": 14, "base_int": 3, "base_hp": 150, "base_ap": 7,
     "str_per_level": 2, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
    {"id": "grassland_shared_steppe_lancer", "name": "Steppe Lancer", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 20, "rarity": "uncommon", "base_xp": 200,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (28, 110),
     "basic_attack": "couched lance", "strong_attack": "cavalry break",
     "player_abilities": ["fire_technique_lv1_scorch_slash"],
     "base_str": 15, "base_dex": 14, "base_con": 12, "base_int": 4, "base_hp": 135, "base_ap": 9,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "grassland_shared_tempest_druid", "name": "Tempest Druid", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 20, "rarity": "rare", "base_xp": 300,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (40, 150),
     "basic_attack": "static touch", "strong_attack": "storm bloom",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 8, "base_dex": 13, "base_con": 12, "base_int": 18, "base_hp": 140, "base_ap": 12,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 3},
    {"id": "grassland_shared_skyborne_terror", "name": "Skyborne Terror", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 20, "rarity": "superrare", "base_xp": 400,
     "common_drop": "herb_major", "rare_drop": "stimulant_large", "money_range": (60, 220),
     "basic_attack": "diving talon", "strong_attack": "cyclone descent",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 16, "base_dex": 16, "base_con": 14, "base_int": 16, "base_hp": 170, "base_ap": 12,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 2},
]
