# Grassland shared hostiles - rarity-coverage fill, Lv 21-40.
#
# Reusable across all grassland city sizes and the grassland wilderness. One
# seed of every rarity at each 5-level mark (Lv 25, 30, 35, 40) guarantees full
# sliding-window coverage for any zone. Ability ids reused from loaded band
# files. Theme (mid): storm riders, dust wraiths, arcane nomad mages, steppe
# predators.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 25 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_prairie_raider", "name": "Prairie Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 25, "rarity": "common", "base_xp": 220,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (30, 130),
     "basic_attack": "raiding slash", "strong_attack": "flanking charge",
     "player_abilities": [],
     "base_str": 14, "base_dex": 12, "base_con": 12, "base_int": 4, "base_hp": 160, "base_ap": 8,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "grassland_shared_steppe_predator", "name": "Steppe Predator", "hostile_type": "creature", "role": "damage", "min_spawn_level": 25, "rarity": "uncommon", "base_xp": 280,
     "common_drop": "herb_med", "rare_drop": "stimulant_large", "money_range": (40, 150),
     "basic_attack": "hamstring bite", "strong_attack": "pack takedown",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 15, "base_dex": 17, "base_con": 13, "base_int": 5, "base_hp": 155, "base_ap": 9,
     "str_per_level": 3, "dex_per_level": 4, "con_per_level": 2, "int_per_level": 0},
    {"id": "grassland_shared_storm_rider", "name": "Storm Rider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 25, "rarity": "rare", "base_xp": 380,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (60, 220),
     "basic_attack": "lightning lance", "strong_attack": "thunder charge",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "fire_technique_lv1_scorch_slash"],
     "base_str": 16, "base_dex": 18, "base_con": 13, "base_int": 8, "base_hp": 175, "base_ap": 10,
     "str_per_level": 3, "dex_per_level": 4, "con_per_level": 2, "int_per_level": 1},
    {"id": "grassland_shared_dust_wraith", "name": "Dust Wraith", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 25, "rarity": "superrare", "base_xp": 560,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (90, 340),
     "basic_attack": "grit murmur", "strong_attack": "sandveil unmaking",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 10, "base_dex": 14, "base_con": 12, "base_int": 20, "base_hp": 170, "base_ap": 13,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 4},

    # ?? Lv 30 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_plains_brute", "name": "Plains Brute", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 30, "rarity": "common", "base_xp": 280,
     "common_drop": "herb_med", "rare_drop": "stimulant_large", "money_range": (40, 160),
     "basic_attack": "maul swing", "strong_attack": "crushing overhead",
     "player_abilities": [],
     "base_str": 18, "base_dex": 9, "base_con": 16, "base_int": 4, "base_hp": 190, "base_ap": 8,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
    {"id": "grassland_shared_wild_stallion_beast", "name": "Wild Stallion Beast", "hostile_type": "creature", "role": "damage", "min_spawn_level": 30, "rarity": "uncommon", "base_xp": 340,
     "common_drop": "herb_major", "rare_drop": "stimulant_large", "money_range": (50, 180),
     "basic_attack": "trampling kick", "strong_attack": "stampede rush",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 18, "base_dex": 17, "base_con": 15, "base_int": 5, "base_hp": 185, "base_ap": 10,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "grassland_shared_arcane_nomad_mage", "name": "Arcane Nomad Mage", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 30, "rarity": "rare", "base_xp": 460,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (70, 260),
     "basic_attack": "arc bolt", "strong_attack": "wind-spiral hex",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 12, "base_dex": 16, "base_con": 16, "base_int": 24, "base_hp": 200, "base_ap": 14,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 4},
    {"id": "grassland_shared_thunderhead_horror", "name": "Thunderhead Horror", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 30, "rarity": "superrare", "base_xp": 700,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (110, 400),
     "basic_attack": "storm-fang bite", "strong_attack": "thunderhead collapse",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 22, "base_dex": 20, "base_con": 20, "base_int": 18, "base_hp": 230, "base_ap": 14,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 3},

    # ?? Lv 35 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_horde_reaver", "name": "Horde Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 35, "rarity": "common", "base_xp": 360,
     "common_drop": "herb_major", "rare_drop": "stimulant_large", "money_range": (50, 200),
     "basic_attack": "cleaving axe", "strong_attack": "reaver charge",
     "player_abilities": [],
     "base_str": 22, "base_dex": 13, "base_con": 18, "base_int": 5, "base_hp": 230, "base_ap": 9,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},
    {"id": "grassland_shared_razorgrass_stalker", "name": "Razorgrass Stalker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 35, "rarity": "uncommon", "base_xp": 440,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (60, 230),
     "basic_attack": "razor lunge", "strong_attack": "ambush shred",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 22, "base_dex": 20, "base_con": 18, "base_int": 6, "base_hp": 250, "base_ap": 10,
     "str_per_level": 4, "dex_per_level": 4, "con_per_level": 3, "int_per_level": 0},
    {"id": "grassland_shared_squall_conjurer", "name": "Squall Conjurer", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 35, "rarity": "rare", "base_xp": 560,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (80, 300),
     "basic_attack": "squall bolt", "strong_attack": "tempest hex",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 14, "base_dex": 22, "base_con": 16, "base_int": 26, "base_hp": 230, "base_ap": 14,
     "str_per_level": 2, "dex_per_level": 4, "con_per_level": 2, "int_per_level": 5},
    {"id": "grassland_shared_ancestral_gale_wraith", "name": "Ancestral Gale Wraith", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 35, "rarity": "superrare", "base_xp": 900,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (140, 520),
     "basic_attack": "grave gust", "strong_attack": "ancestral squall",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 14, "base_dex": 18, "base_con": 16, "base_int": 30, "base_hp": 240, "base_ap": 16,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 5},

    # ?? Lv 40 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_monolith_juggernaut", "name": "Monolith Juggernaut", "hostile_type": "construct", "role": "damage", "min_spawn_level": 40, "rarity": "common", "base_xp": 480,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 70),
     "basic_attack": "monolith smash", "strong_attack": "standing-stone quake",
     "player_abilities": [],
     "base_str": 26, "base_dex": 8, "base_con": 24, "base_int": 5, "base_hp": 300, "base_ap": 9,
     "str_per_level": 4, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "grassland_shared_cavalry_captain", "name": "Cavalry Captain", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 40, "rarity": "uncommon", "base_xp": 600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (80, 300),
     "basic_attack": "cavalry saber", "strong_attack": "captain's charge",
     "player_abilities": ["fire_technique_lv1_scorch_slash"],
     "base_str": 26, "base_dex": 20, "base_con": 22, "base_int": 8, "base_hp": 290, "base_ap": 11,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 1},
    {"id": "grassland_shared_stormcaller_prophet", "name": "Stormcaller Prophet", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 40, "rarity": "rare", "base_xp": 760,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (100, 380),
     "basic_attack": "arc lash", "strong_attack": "chain-storm invocation",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "fire_earth_magic_lv2_magma_javelin"],
     "base_str": 14, "base_dex": 20, "base_con": 20, "base_int": 30, "base_hp": 280, "base_ap": 16,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 5},
    {"id": "grassland_shared_skyfather_spawn", "name": "Skyfather Spawn", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 40, "rarity": "superrare", "base_xp": 1200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (200, 720),
     "basic_attack": "sky-talon rend", "strong_attack": "tempest cataclysm",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 30, "base_dex": 24, "base_con": 26, "base_int": 24, "base_hp": 340, "base_ap": 18,
     "str_per_level": 5, "dex_per_level": 4, "con_per_level": 4, "int_per_level": 4},
]
