# Grassland shared hostiles - rarity-coverage fill, Lv 41-60.
#
# Reusable across all grassland city sizes and the grassland wilderness. One
# seed of every rarity at each 5-level mark (Lv 45, 50, 55, 60) guarantees full
# sliding-window coverage for any zone. Ability ids reused from loaded band files.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 45 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_frontier_marauder", "name": "Frontier Marauder", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 45, "rarity": "common", "base_xp": 620,
     "common_drop": "herb_major", "rare_drop": "stimulant_large", "money_range": (70, 260),
     "basic_attack": "cleaving raid", "strong_attack": "warband rush",
     "player_abilities": [],
     "base_str": 28, "base_dex": 16, "base_con": 24, "base_int": 6, "base_hp": 320, "base_ap": 10,
     "str_per_level": 4, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 0},
    {"id": "grassland_shared_dire_plains_lion", "name": "Dire Plains Lion", "hostile_type": "creature", "role": "damage", "min_spawn_level": 45, "rarity": "uncommon", "base_xp": 780,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (90, 340),
     "basic_attack": "mauling bite", "strong_attack": "savage pounce",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 30, "base_dex": 22, "base_con": 26, "base_int": 8, "base_hp": 330, "base_ap": 11,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 1},
    {"id": "grassland_shared_cyclone_weaver", "name": "Cyclone Weaver", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 45, "rarity": "rare", "base_xp": 1000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (120, 440),
     "basic_attack": "wind whip", "strong_attack": "vortex snare",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 20, "base_dex": 26, "base_con": 22, "base_int": 32, "base_hp": 340, "base_ap": 15,
     "str_per_level": 3, "dex_per_level": 4, "con_per_level": 3, "int_per_level": 6},
    {"id": "grassland_shared_stormfront_terror", "name": "Stormfront Terror", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 45, "rarity": "superrare", "base_xp": 1600,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (240, 820),
     "basic_attack": "static hex", "strong_attack": "stormfront devour",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 22, "base_dex": 28, "base_con": 24, "base_int": 42, "base_hp": 360, "base_ap": 20,
     "str_per_level": 3, "dex_per_level": 4, "con_per_level": 3, "int_per_level": 7},

    # ?? Lv 50 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_ironhoof_enforcer", "name": "Ironhoof Enforcer", "hostile_type": "construct", "role": "damage", "min_spawn_level": 50, "rarity": "common", "base_xp": 900,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 90),
     "basic_attack": "ironhoof stomp", "strong_attack": "quaking charge",
     "player_abilities": [],
     "base_str": 32, "base_dex": 12, "base_con": 28, "base_int": 5, "base_hp": 430, "base_ap": 11,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},
    {"id": "grassland_shared_grass_viper_matron", "name": "Grass Viper Matron", "hostile_type": "creature", "role": "damage", "min_spawn_level": 50, "rarity": "uncommon", "base_xp": 1100,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (120, 440),
     "basic_attack": "venom coil", "strong_attack": "crushing constriction",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 30, "base_dex": 28, "base_con": 26, "base_int": 8, "base_hp": 420, "base_ap": 12,
     "str_per_level": 5, "dex_per_level": 4, "con_per_level": 4, "int_per_level": 1},
    {"id": "grassland_shared_windrite_archon", "name": "Windrite Archon", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 50, "rarity": "rare", "base_xp": 1400,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (160, 580),
     "basic_attack": "gale burst", "strong_attack": "tempest surge",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "fire_earth_magic_lv2_magma_javelin"],
     "base_str": 24, "base_dex": 28, "base_con": 28, "base_int": 34, "base_hp": 440, "base_ap": 15,
     "str_per_level": 4, "dex_per_level": 4, "con_per_level": 4, "int_per_level": 6},
    {"id": "grassland_shared_skyplain_god", "name": "Skyplain God", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 50, "rarity": "superrare", "base_xp": 2200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (360, 1200),
     "basic_attack": "sky maul", "strong_attack": "open-sky apocalypse",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 38, "base_dex": 28, "base_con": 34, "base_int": 28, "base_hp": 500, "base_ap": 20,
     "str_per_level": 6, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 4},

    # ?? Lv 55 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_warband_reaver", "name": "Warband Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 55, "rarity": "common", "base_xp": 1300,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (110, 400),
     "basic_attack": "warblade slash", "strong_attack": "reaver frenzy",
     "player_abilities": [],
     "base_str": 34, "base_dex": 18, "base_con": 30, "base_int": 6, "base_hp": 520, "base_ap": 12,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 0},
    {"id": "grassland_shared_thunder_aurochs", "name": "Thunder Aurochs", "hostile_type": "creature", "role": "damage", "min_spawn_level": 55, "rarity": "uncommon", "base_xp": 1500,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (140, 520),
     "basic_attack": "goring charge", "strong_attack": "thunder stampede",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 38, "base_dex": 18, "base_con": 34, "base_int": 6, "base_hp": 560, "base_ap": 12,
     "str_per_level": 6, "dex_per_level": 2, "con_per_level": 5, "int_per_level": 0},
    {"id": "grassland_shared_galestorm_conjurer", "name": "Galestorm Conjurer", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 55, "rarity": "rare", "base_xp": 2000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (200, 720),
     "basic_attack": "gale lattice", "strong_attack": "galestorm barrage",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 20, "base_dex": 28, "base_con": 26, "base_int": 40, "base_hp": 520, "base_ap": 16,
     "str_per_level": 3, "dex_per_level": 4, "con_per_level": 4, "int_per_level": 7},
    {"id": "grassland_shared_eclipse_stormlord", "name": "Eclipse Stormlord", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 55, "rarity": "superrare", "base_xp": 3000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (400, 1400),
     "basic_attack": "eclipse gale", "strong_attack": "umbral tempest",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 44, "base_dex": 30, "base_con": 40, "base_int": 30, "base_hp": 620, "base_ap": 20,
     "str_per_level": 7, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 4},

    # ?? Lv 60 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_bloodgrass_brute", "name": "Bloodgrass Brute", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 60, "rarity": "common", "base_xp": 1800,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (140, 520),
     "basic_attack": "heavy maul", "strong_attack": "goring rampage",
     "player_abilities": [],
     "base_str": 40, "base_dex": 18, "base_con": 34, "base_int": 6, "base_hp": 620, "base_ap": 12,
     "str_per_level": 6, "dex_per_level": 3, "con_per_level": 5, "int_per_level": 0},
    {"id": "grassland_shared_windmane_alpha", "name": "Windmane Alpha", "hostile_type": "creature", "role": "damage", "min_spawn_level": 60, "rarity": "uncommon", "base_xp": 2200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (180, 640),
     "basic_attack": "windmane kick", "strong_attack": "gale stampede",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 40, "base_dex": 26, "base_con": 34, "base_int": 10, "base_hp": 640, "base_ap": 13,
     "str_per_level": 6, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 1},
    {"id": "grassland_shared_stormspire_warden", "name": "Stormspire Warden", "hostile_type": "construct", "role": "hazard", "min_spawn_level": 60, "rarity": "rare", "base_xp": 2800,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (240, 820),
     "basic_attack": "spire arc", "strong_attack": "warden bulwark",
     "player_abilities": ["level_1_hostile_ability_reinforce_frame", "air_skill_lv1_smoke_bomb"],
     "base_str": 34, "base_dex": 22, "base_con": 38, "base_int": 40, "base_hp": 700, "base_ap": 16,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 6, "int_per_level": 6},
    {"id": "grassland_shared_ancient_sky_titan", "name": "Ancient Sky Titan", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 60, "rarity": "superrare", "base_xp": 4200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (600, 2000),
     "basic_attack": "titan gale", "strong_attack": "sky-splitting descent",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 50, "base_dex": 32, "base_con": 44, "base_int": 26, "base_hp": 780, "base_ap": 20,
     "str_per_level": 8, "dex_per_level": 4, "con_per_level": 7, "int_per_level": 3},
]
