# Grassland shared hostiles - rarity-coverage fill, Lv 61-80.
#
# Reusable across all grassland city sizes and the grassland wilderness. One
# seed of every rarity at each 5-level mark (Lv 65, 70, 75, 80) guarantees full
# sliding-window coverage for any zone. Ability ids reused from loaded band files.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 65 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_warhost_champion", "name": "Warhost Champion", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 65, "rarity": "common", "base_xp": 2600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (180, 640),
     "basic_attack": "champion cleave", "strong_attack": "warhost onslaught",
     "player_abilities": [],
     "base_str": 46, "base_dex": 22, "base_con": 40, "base_int": 8, "base_hp": 720, "base_ap": 13,
     "str_per_level": 7, "dex_per_level": 3, "con_per_level": 6, "int_per_level": 0},
    {"id": "grassland_shared_pride_alpha_lion", "name": "Pride Alpha Lion", "hostile_type": "creature", "role": "damage", "min_spawn_level": 65, "rarity": "uncommon", "base_xp": 3000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (220, 780),
     "basic_attack": "alpha maul", "strong_attack": "pride takedown",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 48, "base_dex": 30, "base_con": 42, "base_int": 10, "base_hp": 740, "base_ap": 14,
     "str_per_level": 7, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 1},
    {"id": "grassland_shared_tempest_hierophant", "name": "Tempest Hierophant", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 65, "rarity": "rare", "base_xp": 3800,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (300, 1000),
     "basic_attack": "storm sigil", "strong_attack": "tempest litany",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 28, "base_dex": 34, "base_con": 34, "base_int": 52, "base_hp": 760, "base_ap": 18,
     "str_per_level": 4, "dex_per_level": 5, "con_per_level": 5, "int_per_level": 9},
    {"id": "grassland_shared_skyrend_horror", "name": "Skyrend Horror", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 65, "rarity": "superrare", "base_xp": 5600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (760, 2600),
     "basic_attack": "skyrend talon", "strong_attack": "firmament collapse",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 56, "base_dex": 38, "base_con": 48, "base_int": 34, "base_hp": 880, "base_ap": 22,
     "str_per_level": 9, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 4},

    # ?? Lv 70 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_bastion_golem", "name": "Bastion Golem", "hostile_type": "construct", "role": "damage", "min_spawn_level": 70, "rarity": "common", "base_xp": 3400,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 110),
     "basic_attack": "bastion slam", "strong_attack": "rampart quake",
     "player_abilities": [],
     "base_str": 54, "base_dex": 16, "base_con": 50, "base_int": 6, "base_hp": 900, "base_ap": 14,
     "str_per_level": 8, "dex_per_level": 2, "con_per_level": 8, "int_per_level": 0},
    {"id": "grassland_shared_thunder_bison", "name": "Thunder Bison", "hostile_type": "creature", "role": "damage", "min_spawn_level": 70, "rarity": "uncommon", "base_xp": 3900,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (260, 900),
     "basic_attack": "goring charge", "strong_attack": "thunder herd rush",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 56, "base_dex": 24, "base_con": 50, "base_int": 8, "base_hp": 940, "base_ap": 14,
     "str_per_level": 9, "dex_per_level": 3, "con_per_level": 7, "int_per_level": 0},
    {"id": "grassland_shared_cyclone_archmage", "name": "Cyclone Archmage", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 70, "rarity": "rare", "base_xp": 4900,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (360, 1200),
     "basic_attack": "cyclone bolt", "strong_attack": "maelstrom convergence",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 30, "base_dex": 38, "base_con": 38, "base_int": 58, "base_hp": 900, "base_ap": 19,
     "str_per_level": 4, "dex_per_level": 5, "con_per_level": 5, "int_per_level": 10},
    {"id": "grassland_shared_stormvault_terror", "name": "Stormvault Terror", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 70, "rarity": "superrare", "base_xp": 7200,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (900, 3000),
     "basic_attack": "vault static", "strong_attack": "storm-heart devour",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 44, "base_dex": 42, "base_con": 46, "base_int": 60, "base_hp": 1000, "base_ap": 24,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 6, "int_per_level": 11},

    # ?? Lv 75 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_horde_warlord", "name": "Horde Warlord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 75, "rarity": "common", "base_xp": 4600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (260, 900),
     "basic_attack": "warlord axe", "strong_attack": "horde devastation",
     "player_abilities": [],
     "base_str": 60, "base_dex": 26, "base_con": 54, "base_int": 8, "base_hp": 1100, "base_ap": 15,
     "str_per_level": 9, "dex_per_level": 3, "con_per_level": 7, "int_per_level": 0},
    {"id": "grassland_shared_savanna_dire_beast", "name": "Savanna Dire Beast", "hostile_type": "creature", "role": "damage", "min_spawn_level": 75, "rarity": "uncommon", "base_xp": 5200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (300, 1050),
     "basic_attack": "dire rend", "strong_attack": "savage evisceration",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 62, "base_dex": 40, "base_con": 54, "base_int": 12, "base_hp": 1120, "base_ap": 16,
     "str_per_level": 9, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 1},
    {"id": "grassland_shared_windshrine_oracle", "name": "Windshrine Oracle", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 75, "rarity": "rare", "base_xp": 6400,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (440, 1500),
     "basic_attack": "oracle gale", "strong_attack": "prophetic tempest",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 32, "base_dex": 42, "base_con": 42, "base_int": 64, "base_hp": 1080, "base_ap": 20,
     "str_per_level": 4, "dex_per_level": 6, "con_per_level": 6, "int_per_level": 11},
    {"id": "grassland_shared_ancestral_storm_god", "name": "Ancestral Storm God", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 75, "rarity": "superrare", "base_xp": 9200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (1200, 4000),
     "basic_attack": "ancestral gale", "strong_attack": "world-storm descent",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 66, "base_dex": 44, "base_con": 56, "base_int": 40, "base_hp": 1300, "base_ap": 24,
     "str_per_level": 10, "dex_per_level": 5, "con_per_level": 8, "int_per_level": 4},

    # ?? Lv 80 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_ironclad_colossus", "name": "Ironclad Colossus", "hostile_type": "construct", "role": "damage", "min_spawn_level": 80, "rarity": "common", "base_xp": 6000,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 120),
     "basic_attack": "colossus smash", "strong_attack": "iron quake",
     "player_abilities": [],
     "base_str": 70, "base_dex": 16, "base_con": 64, "base_int": 8, "base_hp": 1450, "base_ap": 16,
     "str_per_level": 10, "dex_per_level": 2, "con_per_level": 9, "int_per_level": 0},
    {"id": "grassland_shared_plainsking_beast", "name": "Plainsking Beast", "hostile_type": "creature", "role": "damage", "min_spawn_level": 80, "rarity": "uncommon", "base_xp": 6800,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (360, 1250),
     "basic_attack": "plainsking gore", "strong_attack": "monarch stampede",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 68, "base_dex": 38, "base_con": 60, "base_int": 12, "base_hp": 1480, "base_ap": 17,
     "str_per_level": 10, "dex_per_level": 5, "con_per_level": 8, "int_per_level": 1},
    {"id": "grassland_shared_stormcrown_lich", "name": "Stormcrown Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 80, "rarity": "rare", "base_xp": 8400,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (520, 1800),
     "basic_attack": "storm hex", "strong_attack": "crown-of-gales apocalypse",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 40, "base_dex": 42, "base_con": 50, "base_int": 68, "base_hp": 1500, "base_ap": 22,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 12},
    {"id": "grassland_shared_endless_sky_horror", "name": "Endless Sky Horror", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 80, "rarity": "superrare", "base_xp": 13000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (1800, 6000),
     "basic_attack": "endless gale", "strong_attack": "horizon annihilation",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 74, "base_dex": 46, "base_con": 64, "base_int": 46, "base_hp": 1700, "base_ap": 26,
     "str_per_level": 11, "dex_per_level": 6, "con_per_level": 9, "int_per_level": 5},
]
