# Grassland shared hostiles - rarity-coverage fill, Lv 81-100.
#
# Reusable across all grassland city sizes and the grassland wilderness. One
# seed of every rarity at each 5-level mark (Lv 85, 90, 95, 100) guarantees full
# sliding-window coverage for any zone. Ability ids reused from loaded band
# files. Theme: apex storm-gods, world-titans, and sky-devouring horrors.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 85 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_ancient_warhost_lord", "name": "Ancient Warhost Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 85, "rarity": "common", "base_xp": 8400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (360, 1200),
     "basic_attack": "warlord cleave", "strong_attack": "ancestral onslaught",
     "player_abilities": [],
     "base_str": 68, "base_dex": 32, "base_con": 60, "base_int": 10, "base_hp": 1750, "base_ap": 18,
     "str_per_level": 10, "dex_per_level": 4, "con_per_level": 8, "int_per_level": 0},
    {"id": "grassland_shared_plains_dire_matriarch", "name": "Plains Dire Matriarch", "hostile_type": "creature", "role": "damage", "min_spawn_level": 85, "rarity": "uncommon", "base_xp": 9400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (460, 1600),
     "basic_attack": "matriarch maul", "strong_attack": "primal stampede",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 70, "base_dex": 40, "base_con": 62, "base_int": 12, "base_hp": 1850, "base_ap": 19,
     "str_per_level": 10, "dex_per_level": 5, "con_per_level": 9, "int_per_level": 1},
    {"id": "grassland_shared_stormheart_lich", "name": "Stormheart Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 85, "rarity": "rare", "base_xp": 11500,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (600, 2000),
     "basic_attack": "storm bolt", "strong_attack": "galeheart apocalypse",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 44, "base_dex": 40, "base_con": 52, "base_int": 70, "base_hp": 1900, "base_ap": 22,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 12},
    {"id": "grassland_shared_open_sky_god", "name": "Open Sky God", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 85, "rarity": "superrare", "base_xp": 40000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (10000, 34000),
     "basic_attack": "open sky wrath", "strong_attack": "horizon-end cataclysm",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 80, "base_dex": 46, "base_con": 72, "base_int": 60, "base_hp": 24000, "base_ap": 70,
     "str_per_level": 14, "dex_per_level": 6, "con_per_level": 12, "int_per_level": 10},

    # ?? Lv 90 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_plainsbreaker_titan", "name": "Plainsbreaker Titan", "hostile_type": "construct", "role": "damage", "min_spawn_level": 90, "rarity": "common", "base_xp": 12000,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 130),
     "basic_attack": "titan slam", "strong_attack": "plainsbreak quake",
     "player_abilities": [],
     "base_str": 86, "base_dex": 16, "base_con": 78, "base_int": 8, "base_hp": 2400, "base_ap": 16,
     "str_per_level": 12, "dex_per_level": 2, "con_per_level": 11, "int_per_level": 0},
    {"id": "grassland_shared_apex_gale_stalker", "name": "Apex Gale Stalker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 90, "rarity": "uncommon", "base_xp": 13500,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (560, 1900),
     "basic_attack": "apex pounce", "strong_attack": "gale evisceration",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 84, "base_dex": 56, "base_con": 74, "base_int": 16, "base_hp": 2200, "base_ap": 21,
     "str_per_level": 10, "dex_per_level": 7, "con_per_level": 9, "int_per_level": 1},
    {"id": "grassland_shared_skyfather_warden", "name": "Skyfather Warden", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 90, "rarity": "rare", "base_xp": 16000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (700, 2500),
     "basic_attack": "skyfather lash", "strong_attack": "firmament bulwark",
     "player_abilities": ["dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 60, "base_dex": 44, "base_con": 66, "base_int": 80, "base_hp": 2300, "base_ap": 24,
     "str_per_level": 8, "dex_per_level": 5, "con_per_level": 9, "int_per_level": 14},
    {"id": "grassland_shared_devouring_tempest", "name": "Devouring Tempest", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 90, "rarity": "superrare", "base_xp": 46000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (12000, 40000),
     "basic_attack": "devour gale", "strong_attack": "world-end maelstrom",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 88, "base_dex": 52, "base_con": 78, "base_int": 66, "base_hp": 27000, "base_ap": 76,
     "str_per_level": 15, "dex_per_level": 7, "con_per_level": 13, "int_per_level": 11},

    # ?? Lv 95 ??????????????????????????????????????????????????????????????
    {"id": "grassland_shared_primal_steppe_lord", "name": "Primal Steppe Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 95, "rarity": "common", "base_xp": 16000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (600, 2000),
     "basic_attack": "steppe cleave", "strong_attack": "primal rampage",
     "player_abilities": [],
     "base_str": 92, "base_dex": 40, "base_con": 82, "base_int": 12, "base_hp": 2500, "base_ap": 20,
     "str_per_level": 13, "dex_per_level": 5, "con_per_level": 11, "int_per_level": 1},
    {"id": "grassland_shared_thunderking_behemoth", "name": "Thunderking Behemoth", "hostile_type": "creature", "role": "damage", "min_spawn_level": 95, "rarity": "uncommon", "base_xp": 18000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (700, 2400),
     "basic_attack": "behemoth goring", "strong_attack": "thunderking rampage",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 96, "base_dex": 34, "base_con": 88, "base_int": 12, "base_hp": 2700, "base_ap": 20,
     "str_per_level": 14, "dex_per_level": 4, "con_per_level": 12, "int_per_level": 1},
    {"id": "grassland_shared_worldstorm_archon", "name": "Worldstorm Archon", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 95, "rarity": "rare", "base_xp": 22000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (900, 3000),
     "basic_attack": "worldstorm arc", "strong_attack": "primeval maelstrom",
     "player_abilities": ["dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 66, "base_dex": 50, "base_con": 72, "base_int": 92, "base_hp": 2600, "base_ap": 26,
     "str_per_level": 9, "dex_per_level": 6, "con_per_level": 10, "int_per_level": 15},
    {"id": "grassland_shared_end_of_horizons", "name": "End of Horizons", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 95, "rarity": "superrare", "base_xp": 54000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (14000, 46000),
     "basic_attack": "horizon rend", "strong_attack": "unmaking of the plains",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 96, "base_dex": 56, "base_con": 84, "base_int": 72, "base_hp": 30000, "base_ap": 82,
     "str_per_level": 16, "dex_per_level": 7, "con_per_level": 14, "int_per_level": 12},

    # ?? Lv 100 ?????????????????????????????????????????????????????????????
    {"id": "grassland_shared_eternal_warhost_king", "name": "Eternal Warhost King", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 100, "rarity": "common", "base_xp": 22000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (800, 2600),
     "basic_attack": "eternal cleave", "strong_attack": "warhost apocalypse",
     "player_abilities": [],
     "base_str": 100, "base_dex": 44, "base_con": 90, "base_int": 14, "base_hp": 2800, "base_ap": 22,
     "str_per_level": 14, "dex_per_level": 5, "con_per_level": 12, "int_per_level": 1},
    {"id": "grassland_shared_titan_aurochs_god", "name": "Titan Aurochs God", "hostile_type": "creature", "role": "damage", "min_spawn_level": 100, "rarity": "uncommon", "base_xp": 25000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (900, 3000),
     "basic_attack": "titan goring", "strong_attack": "divine stampede",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 104, "base_dex": 38, "base_con": 94, "base_int": 14, "base_hp": 3000, "base_ap": 22,
     "str_per_level": 15, "dex_per_level": 4, "con_per_level": 13, "int_per_level": 1},
    {"id": "grassland_shared_stormsovereign_lich", "name": "Stormsovereign Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 100, "rarity": "rare", "base_xp": 30000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (1200, 4000),
     "basic_attack": "sovereign hex", "strong_attack": "eternal storm requiem",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 60, "base_dex": 52, "base_con": 70, "base_int": 100, "base_hp": 2900, "base_ap": 28,
     "str_per_level": 8, "dex_per_level": 6, "con_per_level": 10, "int_per_level": 16},
    {"id": "grassland_shared_the_boundless_sky", "name": "The Boundless Sky", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 68000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (18000, 60000),
     "basic_attack": "boundless gale", "strong_attack": "the sky descends",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "air_skill_lv1_smoke_bomb"],
     "base_str": 108, "base_dex": 62, "base_con": 94, "base_int": 82, "base_hp": 34000, "base_ap": 90,
     "str_per_level": 18, "dex_per_level": 8, "con_per_level": 15, "int_per_level": 13},
]
