# Grassland Mid City (Highsteeple Crossing) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "crossing_thug", "name": "Crossing Thug", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 240,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (50, 180),
  "basic_attack": "cobble punch", "strong_attack": "street rush",
  "player_abilities": [], "base_str": 12, "base_dex": 8, "base_con": 10, "base_int": 4, "base_hp": 280, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "prairie_shade", "name": "Prairie Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 21, "rarity": "uncommon", "base_xp": 300,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (20, 80),
  "basic_attack": "shade touch", "strong_attack": "plains wail",
  "player_abilities": ["level_1_hostile_ability_night_whisper"],
  "base_str": 4, "base_dex": 12, "base_con": 6, "base_int": 14, "base_hp": 260, "base_ap": 14,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 3},
 {"id": "cathedral_cultist", "name": "Cathedral Cultist", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 25, "rarity": "uncommon", "base_xp": 360,
  "common_drop": "tome_int", "rare_drop": None, "money_range": (80, 280),
  "basic_attack": "ritual blade", "strong_attack": "dark blessing",
  "player_abilities": ["dark_faith_lv1_shade_whisper"],
  "base_str": 8, "base_dex": 8, "base_con": 8, "base_int": 14, "base_hp": 280, "base_ap": 14,
  "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "steeple_berserker", "name": "Steeple Berserker", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 29, "rarity": "common", "base_xp": 320,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (100, 340),
  "basic_attack": "spire slash", "strong_attack": "steeple fury",
  "player_abilities": [], "base_str": 16, "base_dex": 8, "base_con": 14, "base_int": 3, "base_hp": 380, "base_ap": 8,
  "str_per_level": 4, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
 {"id": "crossing_lord", "name": "Crossing Crime Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 35, "rarity": "rare", "base_xp": 700,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (240, 800),
  "basic_attack": "lord's blade", "strong_attack": "highsteeple decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 22, "base_dex": 12, "base_con": 20, "base_int": 8, "base_hp": 560, "base_ap": 12,
  "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 1},
 {"id": "storm_shade_mid_grass", "name": "Storm Shade", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 42, "rarity": "uncommon", "base_xp": 800,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (60, 220),
  "basic_attack": "storm lash", "strong_attack": "tempest surge",
  "player_abilities": ["electric_magic_lv1_fireball", "electric_fire_magic_lv2_arclance"],
  "base_str": 14, "base_dex": 18, "base_con": 14, "base_int": 22, "base_hp": 520, "base_ap": 20,
  "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 5},
 {"id": "plains_lich_mid", "name": "Plains Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 55, "rarity": "superrare", "base_xp": 5000,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (1000, 3500),
  "basic_attack": "death bolt", "strong_attack": "lich storm",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
  "base_str": 8, "base_dex": 10, "base_con": 10, "base_int": 48, "base_hp": 1600, "base_ap": 40,
  "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 10},
 {"id": "steeple_titan", "name": "Steeple Titan", "hostile_type": "construct", "role": "damage", "min_spawn_level": 70, "rarity": "superrare", "base_xp": 14000,
  "common_drop": None, "rare_drop": "herb_major", "money_range": (4000, 14000),
  "basic_attack": "titan slam", "strong_attack": "spire collapse",
  "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
  "base_str": 74, "base_dex": 8, "base_con": 70, "base_int": 10, "base_hp": 16000, "base_ap": 12,
  "str_per_level": 15, "dex_per_level": 1, "con_per_level": 14, "int_per_level": 2},
 {"id": "crossing_world_god", "name": "The Crossing World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 100000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (40000, 130000),
  "basic_attack": "world storm", "strong_attack": "highsteeple apocalypse",
  "player_abilities": ["electric_electric_electric_magic_lv3_thunderstorm"],
  "base_str": 26, "base_dex": 34, "base_con": 26, "base_int": 148, "base_hp": 80000, "base_ap": 118,
  "str_per_level": 5, "dex_per_level": 7, "con_per_level": 5, "int_per_level": 29},
]
