"""Uul’thar’s Abyssal Maw Dungeon Seed Configuration"""

from typing import Dict, Any

# Tile constants for dungeon rendering and builder decisions
OPEN_AREA_TILE = "░"
IMPASSABLE_TILE = "¤"
IMPASSABLE_CHANCE = 0.05   # slightly higher due to coral walls + trenches

FLOOR_HOSTILES = {
    1: [
        'abyssal_eel',
        'tide_horror',
        'coral_sentinel',
        'drowned_mariner',
        'void_jelly',
        'current_stalker',
        'abyssal_ray'
    ]
}

HOSTILE_SEEDS = [  # all level 8–10, ~10 hostiles total
    # Floor 1 - Abyssal Maw (eldritch sea creatures, drowned spirits, coral constructs)
    {
        'id': 'abyssal_eel',
        'name': 'Abyssal Eel',
        'hostile_type': 'creature',
        'min_spawn_level': 17,
        'role': 'damage',
        'rarity': 'common',
        'base_xp': 20,
        'common_drop': 'herb_minor',
        'rare_drop': None,
        'money_range': (2, 12),
        'basic_attack': 'snap bite',
        'strong_attack': 'electric surge',
        'player_abilities': [],
        'base_str': 4,
        'base_dex': 6,
        'base_con': 3,
        'base_int': 2,
        'base_hp': 24,
        'base_ap': 0,
        'str_per_level': 1,
        'dex_per_level': 2,
        'con_per_level': 1,
        'int_per_level': 0,
        'resistances': ['water'],
        'immunities': [],
        'weaknesses': ['electric']
    },
    {
        'id': 'tide_horror',
        'name': 'Tide Horror',
        'hostile_type': 'spirit',
        'min_spawn_level': 22,
        'role': 'hazard',
        'rarity': 'common',
        'base_xp': 36,
        'common_drop': 'stimulant_small',
        'rare_drop': 'stimulant_large',
        'money_range': (6, 30),
        'basic_attack': 'drowning grasp',
        'strong_attack': 'undertow scream',
        'player_abilities': ['water_dark_tech_lv2_shadow_cannon'],
        'base_str': 3,
        'base_dex': 4,
        'base_con': 4,
        'base_int': 5,
        'base_hp': 34,
        'base_ap': 14,
        'str_per_level': 1,
        'dex_per_level': 1,
        'con_per_level': 1,
        'int_per_level': 2,
        'resistances': ['water'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['light']
    },
    {
        'id': 'coral_sentinel',
        'name': 'Coral Sentinel',
        'hostile_type': 'construct',
        'min_spawn_level': 18,
        'role': 'damage',
        'rarity': 'uncommon',
        'base_xp': 60,
        'common_drop': 'herb_med',
        'rare_drop': 'herb_major',
        'money_range': (10, 50),
        'basic_attack': 'reef slam',
        'strong_attack': 'coral spike burst',
        'player_abilities': [],
        'base_str': 6,
        'base_dex': 3,
        'base_con': 8,
        'base_int': 2,
        'base_hp': 80,
        'base_ap': 0,
        'str_per_level': 2,
        'dex_per_level': 0,
        'con_per_level': 2,
        'int_per_level': 0,
        'resistances': ['water', 'earth'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['electric']
    },
    {
        'id': 'drowned_mariner',
        'name': 'Drowned Mariner',
        'hostile_type': 'undead',
        'min_spawn_level': 21,
        'role': 'hazard',
        'rarity': 'uncommon',
        'base_xp': 120,
        'common_drop': 'herb_minor',
        'rare_drop': 'herb_major',
        'money_range': (20, 90),
        'basic_attack': 'rusted cutlass',
        'strong_attack': 'drowning curse',
        'player_abilities': ['water_dark_skill_lv2_abyssal_mire', 'water_tech_lv1_tide_entangler'],
        'base_str': 5,
        'base_dex': 4,
        'base_con': 6,
        'base_int': 3,
        'base_hp': 140,
        'base_ap': 60,
        'str_per_level': 2,
        'dex_per_level': 1,
        'con_per_level': 2,
        'int_per_level': 1,
        'resistances': ['water'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['fire']
    },
    {
        'id': 'void_jelly',
        'name': 'Void Jelly',
        'hostile_type': 'creature',
        'min_spawn_level': 21,
        'role': 'support',
        'rarity': 'rare',
        'base_xp': 200,
        'common_drop': 'herb_minor',
        'rare_drop': 'ointment',
        'money_range': (30, 120),
        'basic_attack': 'void sting',
        'strong_attack': 'gravity pulse',
        'player_abilities': ['electric_tech_lv1_taze_charge', 'electric_dark_tech_lv2_void_shocker'],
        'base_str': 3,
        'base_dex': 5,
        'base_con': 5,
        'base_int': 6,
        'base_hp': 60,
        'base_ap': 20,
        'str_per_level': 1,
        'dex_per_level': 2,
        'con_per_level': 1,
        'int_per_level': 2,
        'resistances': ['water', 'electric'],
        'immunities': ['continuous_damage'],
        'weaknesses': []
    },
    {
        'id': 'current_stalker',
        'name': 'Current Stalker',
        'hostile_type': 'creature',
        'min_spawn_level': 18,
        'role': 'damage',
        'rarity': 'common',
        'base_xp': 24,
        'common_drop': 'stimulant_small',
        'rare_drop': None,
        'money_range': (4, 16),
        'basic_attack': 'fin slash',
        'strong_attack': 'riptide dash',
        'player_abilities': ['water_technique_lv1_slick_manuever'],
        'base_str': 6,
        'base_dex': 4,
        'base_con': 4,
        'base_int': 2,
        'base_hp': 30,
        'base_ap': 10,
        'str_per_level': 1,
        'dex_per_level': 2,
        'con_per_level': 1,
        'int_per_level': 0,
        'resistances': ['water'],
        'immunities': [],
        'weaknesses': ['electric']
    },
    {
        'id': 'abyssal_ray',
        'name': 'Abyssal Ray',
        'hostile_type': 'creature',
        'min_spawn_level': 22,
        'role': 'damage',
        'rarity': 'superrare',
        'base_xp': 300,
        'common_drop': 'herb_major',
        'rare_drop': 'tome_faith_superrare',
        'money_range': (50, 200),
        'basic_attack': 'void beam',
        'strong_attack': 'abyssal wave',
        'player_abilities': ['water_dark_technique_lv2_abyssal_rip', 'water_water_technique_lv2_torrent_tech'],
        'base_str': 8,
        'base_dex': 8,
        'base_con': 8,
        'base_int': 6,
        'base_hp': 380,
        'base_ap': 100,
        'str_per_level': 2,
        'dex_per_level': 2,
        'con_per_level': 2,
        'int_per_level': 1,
        'resistances': ['water'],
        'immunities': ['ice'],
        'weaknesses': ['electric']
    }
]

DUNGEON_NPCS = [ {'id': 'uulthar','location': 'final_chamber'} ]
DUNGEON_ITEMS = [ {'id': 'herb_major', 'location': 'treasure_room'} ]

BOSS_MOB = { 'id': 'uulthar_1',
             'name': 'Uul’thar the Tide‑Wakened',
             'hostiles': [
                'tide_fragment',
                'tide_fragment',
                'uulthar_1']
            }

BOSS_HOSTILES = [
    {
        "id": "tide_fragment", "name": "Tide Fragment", "hostile_type": "magic", "role": "hazard",
        "min_spawn_level": 25, "rarity": "superrare", "base_xp": 480,
        "common_drop": "herb_major", "rare_drop": "tome_faith", "money_range": (45,180),
        "basic_attack": "tidal lash", "strong_attack": "gravity swell",
        "player_abilities": ["water_tech_lv1_tide_entangler", "dark_magic_lv1_shadow_tendril"],
        "base_str": 6, "base_dex": 8, "base_con": 10, "base_int": 14,
        "base_hp": 320, "base_ap": 90,
        "str_per_level": 1, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 3
    },
    {
        "id": "uulthar_1", "name": "Uul’thar the Tide‑Wakened", "hostile_type": "magic", "role": "boss",
        "min_spawn_level": 30, "rarity": "notfound", "base_xp": 1200,
        "common_drop": "herb_major", "rare_drop": "tome_faith", "money_range": (100,300),
        "basic_attack": "abyssal pull", "strong_attack": "void tide",
        "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "water_dark_magic_lv2_abyssal_tide", "dark_faith_lv1_shade_whisper"],
        "base_str": 10, "base_dex": 10, "base_con": 14, "base_int": 18,
        "base_hp": 2000, "base_ap": 100,
        "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 3
    }
]

DUNGEON_SETTINGS: Dict[str, Any] = {
    "dungeon_id": "uulthar_lair",
    "seed": abs(hash("uulthar_lair")),
    "floor_count": 1,
    "room_size_min_max": (81, 120),  # a 9x9 area is 81
    "rooms_per_floor": 10,
    "max_neighbors_per_room": 3,
    "additional_connection_chance": 0.0,
    "min_max_distance_between_rooms": (3,6),
    "min_max_corridor_width": (3,4),
    "display_name": "Uul’thar’s Abyssal Maw",
    "open_area_tile": OPEN_AREA_TILE,
    "impassable_tile": IMPASSABLE_TILE,
    "impassable_chance": IMPASSABLE_CHANCE,
    "floor_hostiles": FLOOR_HOSTILES,
    "hostile_seeds": HOSTILE_SEEDS,
    "npcs": DUNGEON_NPCS,
	"items": DUNGEON_ITEMS,
    "boss_mob": BOSS_MOB,
    "boss_hostiles": BOSS_HOSTILES,
    "visible_distance": 5
}
