# Snow Mid City (Hailward Hold) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "hold_raider", "name": "Hold Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 230,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (50, 180),
  "basic_attack": "ice axe", "strong_attack": "hold raid",
  "player_abilities": [], "base_str": 14, "base_dex": 8, "base_con": 12, "base_int": 3, "base_hp": 300, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "hailward_shade", "name": "Hailward Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 300,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (15, 60),
  "basic_attack": "hail touch", "strong_attack": "hold wail",
  "player_abilities": ["ice_magic_lv1_frostbolt"],
  "base_str": 3, "base_dex": 10, "base_con": 5, "base_int": 12, "base_hp": 240, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "hold_berserker", "name": "Hold Berserker", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 27, "rarity": "common", "base_xp": 320,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (90, 320),
  "basic_attack": "frost cleave", "strong_attack": "hold fury",
  "player_abilities": [], "base_str": 16, "base_dex": 8, "base_con": 14, "base_int": 2, "base_hp": 380, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
 {"id": "hold_sorcerer", "name": "Hold Sorcerer", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 34, "rarity": "uncommon", "base_xp": 520,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (100, 360),
  "basic_attack": "frost bolt", "strong_attack": "hailward curse",
  "player_abilities": ["ice_magic_lv1_frostbolt", "ice_water_magic_lv2_glacier_spike"],
  "base_str": 4, "base_dex": 8, "base_con": 6, "base_int": 20, "base_hp": 300, "base_ap": 18,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 5},
 {"id": "hold_crime_lord", "name": "Hold Crime Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 42, "rarity": "rare", "base_xp": 900,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (340, 1100),
  "basic_attack": "lord's frost blade", "strong_attack": "hailward decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 28, "base_dex": 10, "base_con": 26, "base_int": 8, "base_hp": 760, "base_ap": 10,
  "str_per_level": 5, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 1},
 {"id": "hold_frost_lich", "name": "Hold Frost Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 62, "rarity": "superrare", "base_xp": 9000,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (2000, 7000),
  "basic_attack": "frost death bolt", "strong_attack": "lich hold storm",
  "player_abilities": ["ice_magic_lv1_frostbolt", "ice_ice_magic_lv2_glacier_burst"],
  "base_str": 8, "base_dex": 10, "base_con": 10, "base_int": 58, "base_hp": 2800, "base_ap": 48,
  "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 12},
 {"id": "hailward_titan", "name": "Hailward Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 82, "rarity": "superrare", "base_xp": 25000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (8000, 28000),
  "basic_attack": "hail titan slam", "strong_attack": "hold annihilation",
  "player_abilities": ["ice_ice_ice_magic_lv3_hailstorm"],
  "base_str": 92, "base_dex": 10, "base_con": 86, "base_int": 12, "base_hp": 28000, "base_ap": 14,
  "str_per_level": 18, "dex_per_level": 1, "con_per_level": 17, "int_per_level": 2},
 {"id": "hailward_world_god", "name": "The Hailward World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 100000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (40000, 130000),
  "basic_attack": "world hail decree", "strong_attack": "hailward apocalypse",
  "player_abilities": ["ice_ice_ice_magic_lv3_hailstorm"],
  "base_str": 24, "base_dex": 26, "base_con": 24, "base_int": 138, "base_hp": 80000, "base_ap": 114,
  "str_per_level": 5, "dex_per_level": 5, "con_per_level": 5, "int_per_level": 28},
]
