"""Serene's Whispering Maze Dungeon Seed Configuration"""

from typing import Dict, Any

# Tile constants for dungeon rendering and builder decisions
OPEN_AREA_TILE = "░"       # tall grass paths
IMPASSABLE_TILE = "♠"      # dense thicket walls
IMPASSABLE_CHANCE = 0.03   # shifting grass walls

FLOOR_HOSTILES = {
    1: [
        'windling',
        'echo_sparrow',
        'grass_stalker',
        'praerie_shade',
        'windswept_golem',
        'nomad_blade_dancer',
        'tempest_fox'
    ]
}

HOSTILE_SEEDS = [  # all level 8–10, ~10 hostiles total
    # Floor 1 - Whispering Maze (wind spirits, echo creatures, nomads)
    {
        'id': 'windling',
        'name': 'Windling',
        'hostile_type': 'spirit',
        'min_spawn_level': 18,
        'role': 'damage',
        'rarity': 'common',
        'base_xp': 20,
        'common_drop': 'herb_minor',
        'rare_drop': None,
        'money_range': (2, 12),
        'basic_attack': 'gust jab',
        'strong_attack': 'spiral burst',
        'player_abilities': ['air_faith_lv1_zephyr_bless'],
        'base_str': 3,
        'base_dex': 4,
        'base_con': 3,
        'base_int': 5,
        'base_hp': 22,
        'base_ap': 3,
        'str_per_level': 1,
        'dex_per_level': 2,
        'con_per_level': 1,
        'int_per_level': 1,
        'resistances': ['air'],
        'immunities': [],
        'weaknesses': ['earth']
    },
    {
        'id': 'echo_sparrow',
        'name': 'Echo Sparrow',
        'hostile_type': 'creature',
        'min_spawn_level': 19,
        'role': 'hazard',
        'rarity': 'common',
        'base_xp': 36,
        'common_drop': 'stimulant_small',
        'rare_drop': 'stimulant_large',
        'money_range': (6, 30),
        'basic_attack': 'echo peck',
        'strong_attack': 'voice mimic',
        'player_abilities': ['air_technique_lv1_sonic_strike'],
        'base_str': 2,
        'base_dex': 7,
        'base_con': 3,
        'base_int': 4,
        'base_hp': 30,
        'base_ap': 4,
        'str_per_level': 1,
        'dex_per_level': 3,
        'con_per_level': 1,
        'int_per_level': 1,
        'resistances': ['air'],
        'immunities': ['silence'],
        'weaknesses': ['ice']
    },
    {
        'id': 'grass_stalker',
        'name': 'Grass Stalker',
        'hostile_type': 'creature',
        'min_spawn_level': 20,
        'role': 'damage',
        'rarity': 'uncommon',
        'base_xp': 60,
        'common_drop': 'herb_med',
        'rare_drop': 'herb_major',
        'money_range': (10, 50),
        'basic_attack': 'bladegrass slash',
        'strong_attack': 'ambush pounce',
        'player_abilities': [],
        'base_str': 8,
        'base_dex': 5,
        'base_con': 1,
        'base_int': 1,
        'base_hp': 60,
        'base_ap': 4,
        'str_per_level': 4,
        'dex_per_level': 2,
        'con_per_level': 0,
        'int_per_level': 0,
        'resistances': [],
        'immunities': [],
        'weaknesses': ['fire']
    },
    {
        'id': 'praerie_shade',
        'name': 'Praerie Shade',
        'hostile_type': 'spirit',
        'min_spawn_level': 20,
        'role': 'support',
        'rarity': 'uncommon',
        'base_xp': 120,
        'common_drop': 'herb_minor',
        'rare_drop': 'herb_major',
        'money_range': (20, 90),
        'basic_attack': 'hushed strike',
        'strong_attack': 'silence veil',
        'player_abilities': ['air_dark_magic_lv2_night_wind'],
        'base_str': 3,
        'base_dex': 5,
        'base_con': 5,
        'base_int': 7,
        'base_hp': 140,
        'base_ap': 6,
        'str_per_level': 1,
        'dex_per_level': 1,
        'con_per_level': 2,
        'int_per_level': 3,
        'resistances': ['air'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['fire']
    },
    {
        'id': 'windswept_golem',
        'name': 'Windswept Golem',
        'hostile_type': 'construct',
        'min_spawn_level': 22,
        'role': 'hazard',
        'rarity': 'rare',
        'base_xp': 200,
        'common_drop': 'herb_minor',
        'rare_drop': 'tome_dex',
        'money_range': (30, 120),
        'basic_attack': 'time lash',
        'strong_attack': 'echo trap',
        'player_abilities': ['earth_air_technique_lv2_crosswind_hammerblow'],
        'base_str': 8,
        'base_dex': 2,
        'base_con': 6,
        'base_int': 2,
        'base_hp': 80,
        'base_ap': 5,
        'str_per_level': 1,
        'dex_per_level': 2,
        'con_per_level': 2,
        'int_per_level': 2,
        'resistances': ['air'],
        'immunities': ['stun'],
        'weaknesses': ['earth']
    },
    {
        'id': 'nomad_blade_dancer',
        'name': 'Nomad Blade-Dancer',
        'hostile_type': 'humanoid',
        'min_spawn_level': 18,
        'role': 'damage',
        'rarity': 'common',
        'base_xp': 24,
        'common_drop': 'stimulant_small',
        'rare_drop': None,
        'money_range': (4, 16),
        'basic_attack': 'windcut slash',
        'strong_attack': 'dancing flurry',
        'player_abilities': ['air_technique_lv1_sonic_strike'],
        'base_str': 4,
        'base_dex': 6,
        'base_con': 4,
        'base_int': 2,
        'base_hp': 28,
        'base_ap': 3,
        'str_per_level': 1,
        'dex_per_level': 2,
        'con_per_level': 1,
        'int_per_level': 0,
        'resistances': [],
        'immunities': [],
        'weaknesses': ['earth']
    },
    {
        'id': 'tempest_fox',
        'name': 'Tempest Fox',
        'hostile_type': 'creature',
        'min_spawn_level': 24,
        'role': 'damage',
        'rarity': 'superrare',
        'base_xp': 300,
        'common_drop': 'herb_major',
        'rare_drop': 'tome_dex_superrare',
        'money_range': (50, 200),
        'basic_attack': 'wind fang',
        'strong_attack': 'tempest pounce',
        'player_abilities': ['air_air_skill_lv2_gust_blitz'],
        'base_str': 7,
        'base_dex': 10,
        'base_con': 7,
        'base_int': 4,
        'base_hp': 360,
        'base_ap': 6,
        'str_per_level': 2,
        'dex_per_level': 3,
        'con_per_level': 2,
        'int_per_level': 1,
        'resistances': ['air'],
        'immunities': ['silence'],
        'weaknesses': ['earth']
    }
]

DUNGEON_NPCS = [ {'id': 'serene','location': 'final_chamber'} ]
DUNGEON_ITEMS = [ {'id': 'herb_major', 'location': 'treasure_room'} ]

BOSS_MOB = { 'id': 'serene_1',
             'name': 'Serene the Whisper-Thief',
             'hostiles': [
                'serene_echo',
                'serene_echo',
                'serene_1']
            }

BOSS_HOSTILES = [
    {
        "id": "serene_echo", "name": "Echo Fragment", "hostile_type": "magic", "role": "hazard",
        "min_spawn_level": 23, "rarity": "superrare", "base_xp": 480,
        "common_drop": "herb_major", "rare_drop": "tome_dex", "money_range": (45,180),
        "basic_attack": "whisper slash", "strong_attack": "future echo burst",
        "player_abilities": ["wind_magic_lv1_gust", "air_light_magic_lv2_starbreeze"],
        "base_str": 6, "base_dex": 10, "base_con": 8, "base_int": 12,
        "base_hp": 1500, "base_ap": 10,
        "str_per_level": 1, "dex_per_level": 3, "con_per_level": 1, "int_per_level": 2
    },
    {
        "id": "serene_1", "name": "Serene the Whisper-Thief", "hostile_type": "magic", "role": "damage",
        "min_spawn_level": 30, "rarity": "notfound", "base_xp": 1200,
        "common_drop": "herb_major", "rare_drop": "tome_dex", "money_range": (100,300),
        "basic_attack": "voice snatch", "strong_attack": "stolen tomorrow",
        "player_abilities": ["air_dark_skill_lv2_gale_of_doubt", "air_air_air_skill_lv3_gale_slash","air_electric_fire_skill_lv3_silencing_gale"],
        "base_str": 8, "base_dex": 16, "base_con": 10, "base_int": 14,
        "base_hp": 2100, "base_ap": 12,
        "str_per_level": 1, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 2
    }
]

DUNGEON_SETTINGS: Dict[str, Any] = {
    "dungeon_id": "serene_lair",
    "seed": abs(hash("serene_lair")),
    "floor_count": 1,
    "room_size_min_max": (81, 120),  # a 9x9 area is 81
    "rooms_per_floor": 12,
    "max_neighbors_per_room": 4,
    "additional_connection_chance": 0.0,
    "min_max_distance_between_rooms": (3,6),
    "min_max_corridor_width": (4,7),
    "display_name": "Serene's Whispering Maze",
    "open_area_tile": OPEN_AREA_TILE,
    "impassable_tile": IMPASSABLE_TILE,
    "impassable_chance": IMPASSABLE_CHANCE,
    "floor_hostiles": FLOOR_HOSTILES,
    "hostile_seeds": HOSTILE_SEEDS,
    "npcs": DUNGEON_NPCS,
	"items": DUNGEON_ITEMS,
    "boss_mob": BOSS_MOB,
    "boss_hostiles": BOSS_HOSTILES,
    "visible_distance": 9
}