# Simple in-bar drinks menu. Effects are immediate and don't create inventory items.
DRINK_MENU = [
 {"id": "ale", "name": "Ale", "value":10, "hp_fraction":0.10, "ap_fraction":0.0, "min_level":1},
 {"id": "stout", "name": "Stout", "value":25, "hp_fraction":0.20, "ap_fraction":0.0, "min_level":2},
 {"id": "cocktail", "name": "Cocktail", "value":50, "hp_fraction":0.30, "ap_fraction":0.0, "min_level":3},
 {"id": "porter", "name": "Porter", "value":65, "hp_fraction":0.40, "ap_fraction":0.0, "min_level":4},
 {"id": "rum", "name": "Rum", "value":80, "hp_fraction":0.50, "ap_fraction":0.0, "min_level":5},
 {"id": "brandy", "name": "Brandy", "value":110, "hp_fraction":0.60, "ap_fraction":0.0, "min_level":6},
 {"id": "whiskey", "name": "Whiskey", "value":120, "hp_fraction":0.70, "ap_fraction":0.0, "min_level":7},
 {"id": "cognac", "name": "Cognac", "value":130, "hp_fraction":0.80, "ap_fraction":0.0, "min_level":8},
 {"id": "absinthe", "name": "Absinthe", "value":140, "hp_fraction":0.90, "ap_fraction":0.0, "min_level":9},
 {"id": "elixir", "name": "Elixir", "value":200, "hp_fraction":1.00, "ap_fraction":0.3, "min_level":10},
]

BUILDINGS = [
	{ "name": "bar", "display_name": "Dead n' Gone", "type": "bar", "char": "µ", "seed_range":60, "threshold":0.03, "hostile_prob":0.35, "can_buy": True, "can_sell": False, "image": "/assets/tiles/bar.svg", "color": "#6b8b5a"},
]

# Internal sublocations per subtype
SUBLOC_MAP = {
 "bar": ["bottle rack", "jukebox", "backroom locker", "lantern hook", "moldy crate"],
 "alley": ["vehicle", "trash pile", "shack", "broken drone", "boardwalk gap"],
 "street": ["vehicle", "old signpost", "stilt bridge", "market stall", "faded kiosk"],
 "open_area": ["bog pool", "buried crate", "mossy log", "reed bed", "sunken canoe", "watcher's shrine", "rusted pump", "glass beads patch", "luminous fungus", "beacon post"],
}

# Swamp / marsh / fen searchables (with neo-noir cyber-fantasy flavor)
SUBLOCATION_DEFS = {
 "bottle rack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A damp rack of bottles behind the bar; some labels glow faintly and small things are tucked between crates.",
 "money_range": (0,16),
 },
 "jukebox": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "An old jukebox playing an eerie synth blues; the coin slot sometimes hides datapaks or coins.",
 "money_range": (0,20),
 },
 "backroom locker": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A rust-streaked locker with muddy boots inside; someone may have stashed a wrapped pouch.",
 "money_range": (5,60),
 },
 "lantern hook": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A bent hook where lanterns hang; a scrap of paper or a coin could be jammed in the wood.",
 "money_range": (0,8),
 },
 "moldy crate": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A mold-covered crate stacked in a corner; tarps sometimes hide small valuables.",
 "money_range": (0,20),
 },

 "vehicle": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.14,
 "prompt": "A half-submerged vehicle in the marsh; gloveboxes and underseats hide oddments and salvage.",
 "money_range": (1,10),
 },
 "trash pile": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.18,
 "prompt": "A greasy mound of refuse with woven plastic and neon wrappers; scavengers sometimes miss small components.",
 "money_range": (0,6),
 },
 "shack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.12,
 "prompt": "A ramshackle shack on stilts with a sagging floor; crates and floorboards may conceal items.",
 "money_range": (0,40),
 },
 "broken drone": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A smashed delivery drone tangled in reeds - pry open the casing for salvage and maybe a credit chip.",
 "money_range": (0,50),
 },
 "boardwalk gap": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A missing plank in a raised boardwalk; the cavity below can hide small packages.",
 "money_range": (0,12),
 },

 "old signpost": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A sodden signpost plastered with faded notices; a tin box may be stapled behind it.",
 "money_range": (0,10),
 },
 "stilt bridge": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A rickety bridge on stilts over black water; lost coins and the occasional datapad tangle beneath the planks.",
 "money_range": (0,18),
 },
 "market stall": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A damp market stall selling dried goods and illicit trinkets; check under crates and cloth covers.",
 "money_range": (0,30),
 },
 "faded kiosk": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A weather-beaten kiosk with a sticky register; a folded note could be hidden inside.",
 "money_range": (0,12),
 },

 "bog pool": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.10,
 "prompt": "A black, still pool where objects slowly surface; careful probing might find coins or sealed pouches.",
 "money_range": (0,15),
 },
 "buried crate": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A sodden wooden crate half-swallowed by peat; its contents may survive if the lock held.",
 "money_range": (5,60),
 },
 "mossy log": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A fallen log carpeted in moss; someone could have slipped an item into a knot or hollow.",
 "money_range": (0,12),
 },
 "reed bed": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A tangle of reeds and willow roots; old bottles and bits of tech can snag among the stems.",
 "money_range": (0,10),
 },
 "sunken canoe": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A half-sunk canoe with a waterlogged chest; if you're brave enough you might find something dry inside.",
 "money_range": (0,40),
 },
 "watcher's shrine": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.02,
 "prompt": "A small shrine of painted shells and glass beads - locals leave offerings and sometimes coins.",
 "money_range": (0,20),
 },
 "rusted pump": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "An old water pump with a rusted maintenance box; pry it open for tools or notes.",
 "money_range": (0,15),
 },
 "glass beads patch": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A scattering of polished glass beads along a bank; trinkets and a wrapped token could be hidden nearby.",
 "money_range": (0,10),
 },
 "luminous fungus": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "Patches of bioluminescent fungus on old stumps; sometimes someone hides a small vial or charm beneath the caps.",
 "money_range": (0,12),
 },
 "beacon post": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.02,
 "prompt": "A tall post with a cracked beacon light; a sealed maintenance box might contain spare parts or notes.",
 "money_range": (0,25),
 },
}