# Simple in-bar drinks menu. Effects are immediate and don't create inventory items.
DRINK_MENU = [
 {"id": "ale", "name": "Ale", "value":10, "hp_fraction":0.10, "ap_fraction":0.0, "min_level":1},
 {"id": "stout", "name": "Stout", "value":25, "hp_fraction":0.20, "ap_fraction":0.0, "min_level":2},
 {"id": "cocktail", "name": "Cocktail", "value":50, "hp_fraction":0.30, "ap_fraction":0.0, "min_level":3},
 {"id": "porter", "name": "Porter", "value":65, "hp_fraction":0.40, "ap_fraction":0.0, "min_level":4},
 {"id": "rum", "name": "Rum", "value":80, "hp_fraction":0.50, "ap_fraction":0.0, "min_level":5},
 {"id": "brandy", "name": "Brandy", "value":110, "hp_fraction":0.60, "ap_fraction":0.0, "min_level":6},
 {"id": "whiskey", "name": "Whiskey", "value":120, "hp_fraction":0.70, "ap_fraction":0.0, "min_level":7},
 {"id": "cognac", "name": "Cognac", "value":130, "hp_fraction":0.80, "ap_fraction":0.0, "min_level":8},
 {"id": "absinthe", "name": "Absinthe", "value":140, "hp_fraction":0.90, "ap_fraction":0.0, "min_level":9},
 {"id": "elixir", "name": "Elixir", "value":200, "hp_fraction":1.00, "ap_fraction":0.3, "min_level":10},
]

BUILDINGS = [
	{ "name": "bar", "display_name": "The Good n' Homely", "type": "bar", "char": "µ", "seed_range":60, "threshold":0.03, "hostile_prob":0.2, "can_buy": True, "can_sell": False, "image": "/assets/tiles/bar.svg", "color": "#8b3e3e"},
]

# Internal sublocations per subtype
SUBLOC_MAP = {
 "bar": ["coat rack", "barrel stash", "jukebox", "backroom safe", "dartboard"],
 "alley": ["vehicle", "haystack", "fence post", "abandoned cart", "field gate"],
 "street": ["vehicle", "mile marker", "rest kiosk", "old signpost", "roadside shrine"],
 "open_area": ["hay bale", "stone cairn", "dry pond", "hedgerow", "buried crate", "wildflower patch", "sheep trough", "ant hill", "old well", "abandoned wagon"],
}

# Grassland / meadow searchables
SUBLOCATION_DEFS = {
 "coat rack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A coat rack near the bar entrance with a few crusted pockets and a lost coin.",
 "money_range": (0,8),
 },
 "barrel stash": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.10,
 "prompt": "A stack of wooden barrels behind the counter; one looks recently moved.",
 "money_range": (0,25),
 },
 "jukebox": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "An old jukebox with a loose coin slot; a small compartment might hold something.",
 "money_range": (0,20),
 },
 "backroom safe": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A locked backroom safe behind crates; the combination may be guessed with time.",
 "money_range": (10,100),
 },
 "dartboard": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A dartboard on the wall - players sometimes wedge notes or coins behind it.",
 "money_range": (0,12),
 },

 "vehicle": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.16,
 "prompt": "An abandoned vehicle at the roadside; glove compartments often contain oddments.",
 "money_range": (1,6),
 },
 "haystack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.12,
 "prompt": "A pile of loose hay; people hide packages here occasionally.",
 "money_range": (0,10),
 },
 "fence post": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A weathered fence post with nails and maybe a small tin box nailed to the side.",
 "money_range": (0,8),
 },
 "abandoned cart": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.11,
 "prompt": "A toppled cart with crates; a forgotten satchel can be tucked underneath.",
 "money_range": (0,20),
 },
 "field gate": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A hinged gate between pastures; a small box may be mounted on a post nearby.",
 "money_range": (0,12),
 },

 "mile marker": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A faded mile marker by the road; someone once hid a note in a crack.",
 "money_range": (0,6),
 },
 "rest kiosk": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A simple roadside kiosk with brochures and a loose cashbox.",
 "money_range": (0,30),
 },
 "old signpost": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "An old signpost with a tin box behind one plank.",
 "money_range": (0,12),
 },
 "roadside shrine": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.02,
 "prompt": "A small roadside shrine-visitors sometimes leave coins or notes.",
 "money_range": (0,20),
 },

 "hay bale": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.10,
 "prompt": "A round hay bale with a loose center; farmers sometimes stash small items there.",
 "money_range": (0,12),
 },
 "stone cairn": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A small stack of stones that marks a path; a tin may be hidden beneath the top rock.",
 "money_range": (0,10),
 },
 "dry pond": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A shallow dry pond where things collect when the water recedes.",
 "money_range": (0,15),
 },
 "hedgerow": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A dense hedgerow at a field edge; small cavities can hide items.",
 "money_range": (0,8),
 },
 "buried crate": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A half-buried wooden crate; the lock may be corroded open.",
 "money_range": (5,60),
 },
 "wildflower patch": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A blooming patch of wildflowers; there's sometimes a small tin hidden nearby.",
 "money_range": (0,8),
 },
 "sheep trough": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A stone trough used by livestock; someone may have left coins tucked in a corner.",
 "money_range": (0,10),
 },
 "ant hill": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A large anthill; careful searching might reveal small beads or metal bits.",
 "money_range": (0,6),
 },
 "old well": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A stone well long out of use; a bucket may contain hidden items.",
 "money_range": (0,25),
 },
 "abandoned wagon": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "An old wagon left to rot; crates inside might still hold something.",
 "money_range": (1,40),
 },
}