# Simple in-bar drinks menu. Effects are immediate and don't create inventory items.
DRINK_MENU = [
 {"id": "ale", "name": "Ale", "value":10, "hp_fraction":0.10, "ap_fraction":0.0, "min_level":1},
 {"id": "stout", "name": "Stout", "value":25, "hp_fraction":0.20, "ap_fraction":0.0, "min_level":2},
 {"id": "cocktail", "name": "Cocktail", "value":50, "hp_fraction":0.30, "ap_fraction":0.0, "min_level":3},
 {"id": "porter", "name": "Porter", "value":65, "hp_fraction":0.40, "ap_fraction":0.0, "min_level":4},
 {"id": "rum", "name": "Rum", "value":80, "hp_fraction":0.50, "ap_fraction":0.0, "min_level":5},
 {"id": "brandy", "name": "Brandy", "value":110, "hp_fraction":0.60, "ap_fraction":0.0, "min_level":6},
 {"id": "whiskey", "name": "Whiskey", "value":120, "hp_fraction":0.70, "ap_fraction":0.0, "min_level":7},
 {"id": "cognac", "name": "Cognac", "value":130, "hp_fraction":0.80, "ap_fraction":0.0, "min_level":8},
 {"id": "absinthe", "name": "Absinthe", "value":140, "hp_fraction":0.90, "ap_fraction":0.0, "min_level":9},
 {"id": "elixir", "name": "Elixir", "value":200, "hp_fraction":1.00, "ap_fraction":0.3, "min_level":10},
]

BUILDINGS = [
	{ "name": "bar", "display_name": "Grogg's Mead", "type": "bar", "char": "µ", "seed_range":60, "threshold":0.03, "hostile_prob":0.3, "can_buy": True, "can_sell": False, "image": "/assets/tiles/bar.svg", "color": "#8b3e3e"},
]

# Internal sublocations per subtype
SUBLOC_MAP = {
 "bar": ["coat rack", "stone fireplace", "map rack", "backroom locker", "keg stash"],
 "alley": ["vehicle", "fallen tree", "rope coil", "trail marker", "boot prints"],
 "street": ["vehicle", "lookout point", "old signpost", "bridge", "switchback marker"],
 "open_area": ["scree field", "cairn", "mountain spring", "rock crevice", "buried crate", "mineshaft mouth", "snow drift", "eagle perch", "herbal patch", "ranger cache"],
}

# Mountain-themed searchables
SUBLOCATION_DEFS = {
 "coat rack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A coat rack by the door with a few patched pockets and a forgotten coin.",
 "money_range": (0,8),
 },
 "stone fireplace": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A cold stone fireplace; ashes hide small objects and sometimes a wrapped parcel.",
 "money_range": (0,20),
 },
 "map rack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A rack of tattered maps; a note or a hidden ticket may be tucked in a fold.",
 "money_range": (0,12),
 },
 "backroom locker": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A metal locker in the backroom; gear and small valuables can be hidden inside.",
 "money_range": (5,60),
 },
 "keg stash": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A storage area of kegs; someone might have slipped money or a note into a barrel.",
 "money_range": (0,30),
 },

 "vehicle": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.15,
 "prompt": "An abandoned mountain vehicle; toolboxes and glove compartments may hold something.",
 "money_range": (1,8),
 },
 "fallen tree": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A large fallen trunk with hollowed sections; small items are sometimes stashed there.",
 "money_range": (0,10),
 },
 "rope coil": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A coiled rope left by climbers; a small pouch might be tied into the strands.",
 "money_range": (0,12),
 },
 "trail marker": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A painted trail marker; someone once hid a tin box behind it.",
 "money_range": (0,6),
 },
 "boot prints": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.02,
 "prompt": "A cluster of fresh boot prints in soft earth-follow them or examine nearby disturbed soil.",
 "money_range": (0,6),
 },

 "lookout point": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A rocky outcrop with a commanding view; visitors sometimes leave notes or small offerings.",
 "money_range": (0,18),
 },
 "old signpost": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A weathered signpost nailed to a post; a small pocket behind a plank may hide something.",
 "money_range": (0,10),
 },
 "bridge": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A narrow bridge over a chasm; under the planks, lost coins and trinkets sometimes settle.",
 "money_range": (0,12),
 },
 "switchback marker": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A painted switchback marker; in a crevice you might find a hidden note.",
 "money_range": (0,6),
 },

 "scree field": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A field of loose stones where things tumble and collect in hollows.",
 "money_range": (0,12),
 },
 "cairn": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A small pile of rocks marking a route; people occasionally tuck messages or coins beneath the top stone.",
 "money_range": (0,10),
 },
 "mountain spring": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A clear spring bubbling from the rock; small containers or pouches can be hidden nearby.",
 "money_range": (0,15),
 },
 "rock crevice": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A narrow crevice in a boulder that might hide a small cache or note.",
 "money_range": (0,12),
 },
 "buried crate": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A half-buried wooden crate that has been covered by time and scree.",
 "money_range": (5,60),
 },
 "mineshaft mouth": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "The weathered entrance to an old mine; timbers and discarded gear may hide small finds.",
 "money_range": (0,40),
 },
 "snow drift": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A drift of snow that occasionally covers lost items; careful digging can reveal them.",
 "money_range": (0,8),
 },
 "eagle perch": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": False,
 "loot_chance":0.02,
 "prompt": "A tall crag used by birds of prey; you might spot shiny objects caught in the nest but approach with care.",
 "money_range": (0,6),
 },
 "herbal patch": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A patch of high-altitude herbs valued by healers; small roots and bulbs may be gathered.",
 "money_range": (0,12),
 },
 "ranger cache": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A small cache maintained by rangers: emergency supplies or a wrapped note could be found.",
 "money_range": (0,30),
 },
}