# Simple in-bar drinks menu. Effects are immediate and don't create inventory items.
DRINK_MENU = [
 {"id": "ale", "name": "Ale", "value":10, "hp_fraction":0.10, "ap_fraction":0.0, "min_level":1},
 {"id": "stout", "name": "Stout", "value":25, "hp_fraction":0.20, "ap_fraction":0.0, "min_level":2},
 {"id": "cocktail", "name": "Cocktail", "value":50, "hp_fraction":0.30, "ap_fraction":0.0, "min_level":3},
 {"id": "porter", "name": "Porter", "value":65, "hp_fraction":0.40, "ap_fraction":0.0, "min_level":4},
 {"id": "rum", "name": "Rum", "value":80, "hp_fraction":0.50, "ap_fraction":0.0, "min_level":5},
 {"id": "brandy", "name": "Brandy", "value":110, "hp_fraction":0.60, "ap_fraction":0.0, "min_level":6},
 {"id": "whiskey", "name": "Whiskey", "value":120, "hp_fraction":0.70, "ap_fraction":0.0, "min_level":7},
 {"id": "cognac", "name": "Cognac", "value":130, "hp_fraction":0.80, "ap_fraction":0.0, "min_level":8},
 {"id": "absinthe", "name": "Absinthe", "value":140, "hp_fraction":0.90, "ap_fraction":0.0, "min_level":9},
 {"id": "elixir", "name": "Elixir", "value":200, "hp_fraction":1.00, "ap_fraction":0.3, "min_level":10},
]

BUILDINGS = [
	{ "name": "bar", "display_name": "Wet Yer' Whistle", "type": "bar", "char": "µ", "seed_range":60, "threshold":0.03, "hostile_prob":0.25, "can_buy": True, "can_sell": False, "image": "/assets/tiles/bar.svg", "color": "#8b3e3e"},
]

# Internal sublocations per subtype
SUBLOC_MAP = {
 "bar": ["bottle rack", "jukebox", "backroom locker", "neon sign", "rusted ice chest"],
 "alley": ["vehicle", "trash pile", "drift shack", "broken drone", "fisher net"],
 "street": ["vehicle", "pier kiosk", "old signpost", "collapsed pier", "market stall"],
 "open_area": ["tide pool", "buried crate", "shipwreck", "kelp mat", "data buoy", "salvage pile", "oyster bed", "rusted anchor", "beacon", "glass beach"],
}

# Shallows / coastal / cyber-fantasy searchables
SUBLOCATION_DEFS = {
 "bottle rack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.10,
 "prompt": "A leaning rack of bottles; some labels glow faintly and someone may have slipped a coin or a chip inside.",
 "money_range": (0,18),
 },
 "jukebox": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A beat-up jukebox playing a muted synth track; the coin slot sometimes hides small items or datapaks.",
 "money_range": (0,20),
 },
 "backroom locker": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A damp backroom locker with salty gear; a wrapped package might rattle inside.",
 "money_range": (5,60),
 },
 "neon sign": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A flickering neon sign. The metal housing has a small cavity where someone could stash a note.",
 "money_range": (0,12),
 },
 "rusted ice chest": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "An old ice chest stained with brine; packages and loose change sometimes hide between crates.",
 "money_range": (0,25),
 },

 "vehicle": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.15,
 "prompt": "A beached or abandoned vehicle; dashboards and underseats hide oddments.",
 "money_range": (1,8),
 },
 "trash pile": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.20,
 "prompt": "A greasy pile of refuse with neon wrappers; scavengers sometimes miss useful components.",
 "money_range": (0,6),
 },
 "drift shack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.12,
 "prompt": "A ramshackle shack made from driftwood and metal; pockets and loose floorboards may contain goods.",
 "money_range": (0,30),
 },
 "broken drone": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A smashed delivery drone with exposed circuits-salvageable chips and credits can be pried loose.",
 "money_range": (0,40),
 },
 "fisher net": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A tangled fisher net on the rocks; trapped tins, coins, or a small sealed pouch might lurk within.",
 "money_range": (0,10),
 },

 "pier kiosk": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.10,
 "prompt": "A battered kiosk selling snacks and data maps; the register or a back drawer could contain loose change.",
 "money_range": (0,30),
 },
 "old signpost": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A salt-bleached signpost with stickers and a duct-taped envelope tucked behind it.",
 "money_range": (0,10),
 },
 "collapsed pier": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "Rotted planks and exposed beams; cavities hide coins and the occasional washed-up package.",
 "money_range": (1,25),
 },
 "market stall": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A half-closed stall with salted goods and illegal trinkets; check under crates and cloth covers.",
 "money_range": (0,35),
 },

 "tide pool": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.12,
 "prompt": "A neon-lit tide pool where bio-luminescent algae and biotech detritus collect; shiny things sometimes cling to the rocks.",
 "money_range": (0,12),
 },
 "buried crate": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A crate half-buried in sand and silt; its contents may still be intact if the lock survived.",
 "money_range": (5,80),
 },
 "shipwreck": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "Ribbed hull and twisted metal of a small wreck; pockets and compartments hide salvage and old credits.",
 "money_range": (2,100),
 },
 "kelp mat": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A tangled mat of kelp where plastics and tech can collect; careful sorting finds items.",
 "money_range": (0,12),
 },
 "data buoy": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A bobbing data buoy with a damaged casing; flickering LEDs suggest stored telemetry or a cached datapad.",
 "money_range": (0,50),
 },
 "salvage pile": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.11,
 "prompt": "A heap of washed-up salvage: glass, metal, and odd modules - some are still valuable.",
 "money_range": (0,40),
 },
 "oyster bed": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A spread of shell beds; pearls are rare but something shiny could be pried loose.",
 "money_range": (0,25),
 },
 "rusted anchor": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A massive rusted anchor chained to a buried crate; pry points may reveal hidden compartments.",
 "money_range": (0,30),
 },
 "beacon": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.02,
 "prompt": "A battered navigation beacon with a sealed maintenance box that sometimes contains parts or notes.",
 "money_range": (0,20),
 },
 "glass beach": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A stretch of beach strewn with reef-polished glass and tech shards; someone might have hidden a trinket beneath.",
 "money_range": (0,15),
 },
}