# Simple in-bar drinks menu. Effects are immediate and don't create inventory items.
DRINK_MENU = [
 {"id": "ale", "name": "Ale", "value":10, "hp_fraction":0.10, "ap_fraction":0.0, "min_level":1},
 {"id": "stout", "name": "Stout", "value":25, "hp_fraction":0.20, "ap_fraction":0.0, "min_level":2},
 {"id": "cocktail", "name": "Cocktail", "value":50, "hp_fraction":0.30, "ap_fraction":0.0, "min_level":3},
 {"id": "porter", "name": "Porter", "value":65, "hp_fraction":0.40, "ap_fraction":0.0, "min_level":4},
 {"id": "rum", "name": "Rum", "value":80, "hp_fraction":0.50, "ap_fraction":0.0, "min_level":5},
 {"id": "brandy", "name": "Brandy", "value":110, "hp_fraction":0.60, "ap_fraction":0.0, "min_level":6},
 {"id": "whiskey", "name": "Whiskey", "value":120, "hp_fraction":0.70, "ap_fraction":0.0, "min_level":7},
 {"id": "cognac", "name": "Cognac", "value":130, "hp_fraction":0.80, "ap_fraction":0.0, "min_level":8},
 {"id": "absinthe", "name": "Absinthe", "value":140, "hp_fraction":0.90, "ap_fraction":0.0, "min_level":9},
 {"id": "elixir", "name": "Elixir", "value":200, "hp_fraction":1.00, "ap_fraction":0.3, "min_level":10},
]

BUILDINGS = [
	{ "name": "bar", "display_name": "The Frothy Hearthe", "type": "bar", "char": "µ", "seed_range":60, "threshold":0.03, "hostile_prob":0.3, "can_buy": True, "can_sell": False, "image": "/assets/tiles/bar.svg", "color": "#8b3e3e"},
]

# Internal sublocations per subtype
SUBLOC_MAP = {
 "bar": ["coat rack", "stone hearth", "boot dryer", "keg locker", "frosted window"],
 "alley": ["vehicle", "footprints", "ice drift", "collapsed sign", "supply crate"],
 "street": ["vehicle", "mile marker", "phone kiosk", "snowplow pile", "overpass"],
 "open_area": ["snow mound", "frozen pond", "ice crevice", "buried crate", "icicle cluster", "sled debris", "radio antenna", "siren post", "ranger cache", "cairn"],
}

# Snow / alpine / cold-region searchables
SUBLOCATION_DEFS = {
 "coat rack": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A rack of heavy coats near the bar door; pockets may hold gloves, coins or a scrap of data.",
 "money_range": (0,8),
 },
 "stone hearth": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A cold stone hearth with ashes; small wrapped items can be tucked between the stones.",
 "money_range": (0,20),
 },
 "boot dryer": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A communal boot dryer with forgotten socks and a taped envelope behind the machine.",
 "money_range": (0,12),
 },
 "keg locker": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "A locked locker used for spare kegs; someone might stash cash or contraband inside.",
 "money_range": (5,60),
 },
 "frosted window": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A frosted pane with smudged messages; a small note or token might be taped to the frame.",
 "money_range": (0,10),
 },

 "vehicle": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.14,
 "prompt": "An abandoned vehicle half-buried in snow; gloveboxes and consoles hide sundries.",
 "money_range": (1,8),
 },
 "footprints": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.02,
 "prompt": "Fresh footprints lead into deeper snow-search the disturbed snow for dropped items.",
 "money_range": (0,6),
 },
 "ice drift": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "A drift of windblown ice and debris where tin cans and small packages gather.",
 "money_range": (0,12),
 },
 "collapsed sign": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A bent road sign ripped loose by the storm; a tin box may be wedged behind it.",
 "money_range": (0,10),
 },
 "supply crate": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.11,
 "prompt": "A damp supply crate with tarps; rations, tools or a stamped envelope could be inside.",
 "money_range": (0,30),
 },

 "mile marker": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A frost-coated mile marker; someone once hid a note in a crack when the wind picked up.",
 "money_range": (0,6),
 },
 "phone kiosk": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A battered phone kiosk with icicles; the coin return sometimes holds something unexpected.",
 "money_range": (0,12),
 },
 "snowplow pile": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.06,
 "prompt": "Piles of plowed snow mixed with debris; items get buried at the edges.",
 "money_range": (0,15),
 },
 "overpass": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "The underside of an overpass where wind deposits forgotten gear and papers.",
 "money_range": (0,20),
 },

 "snow mound": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.10,
 "prompt": "A lumpy mound of settled snow; careful probing can reveal hidden objects beneath the crust.",
 "money_range": (0,12),
 },
 "frozen pond": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.08,
 "prompt": "A clear sheet of ice over a shallow pond; items sometimes sink into slushy gaps at the edge.",
 "money_range": (0,20),
 },
 "ice crevice": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A narrow crevice between ice and rock where small caches can be slipped and forgotten.",
 "money_range": (0,12),
 },
 "buried crate": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.07,
 "prompt": "A crate half-buried in snow and ice; it may contain preserved supplies if the seal held.",
 "money_range": (5,60),
 },
 "icicle cluster": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A dangling cluster of icicles on a ledge; a small wrapped item could be frozen in the ice.",
 "money_range": (0,8),
 },
 "sled debris": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.09,
 "prompt": "Broken sled parts and scattered packs; a pouch might remain among the wreckage.",
 "money_range": (0,30),
 },
 "radio antenna": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.04,
 "prompt": "A leaning radio antenna with a sealed maintenance box; it sometimes stores notes or spare parts.",
 "money_range": (0,25),
 },
 "siren post": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.02,
 "prompt": "A faded emergency siren on a pole; a small locked box at the base might hide supplies.",
 "money_range": (0,20),
 },
 "ranger cache": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.05,
 "prompt": "A camouflaged cache of ranger supplies: wrapped rations and a sealed pouch could be here.",
 "money_range": (0,40),
 },
 "cairn": {
 "mode": "searchable",
 "level_delta":0,
 "searchable": True,
 "loot_chance":0.03,
 "prompt": "A small cairn of stones that marks a trail; people sometimes tuck messages or trinkets under the topstone.",
 "money_range": (0,10),
 },
}