# Shallows Small City (Tidekin Cove) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "cove_thief", "name": "Cove Thief", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 200,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (40, 150),
  "basic_attack": "cove shiv", "strong_attack": "tidal ambush",
  "player_abilities": [], "base_str": 10, "base_dex": 12, "base_con": 8, "base_int": 3, "base_hp": 240, "base_ap": 10,
  "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
 {"id": "tidekin_shade", "name": "Tidekin Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 23, "rarity": "uncommon", "base_xp": 280,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (15, 60),
  "basic_attack": "tide touch", "strong_attack": "cove wail",
  "player_abilities": ["level_1_hostile_ability_streamlet"],
  "base_str": 3, "base_dex": 12, "base_con": 5, "base_int": 12, "base_hp": 220, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 3},
 {"id": "cove_raider", "name": "Cove Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 28, "rarity": "common", "base_xp": 300,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (80, 280),
  "basic_attack": "raider slash", "strong_attack": "cove fury",
  "player_abilities": [], "base_str": 14, "base_dex": 12, "base_con": 12, "base_int": 2, "base_hp": 340, "base_ap": 10,
  "str_per_level": 3, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
 {"id": "cove_sea_witch", "name": "Cove Sea Witch", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 36, "rarity": "uncommon", "base_xp": 500,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (80, 300),
  "basic_attack": "cove hex", "strong_attack": "tidal curse",
  "player_abilities": ["water_magic_lv1_spray_shard", "ice_water_magic_lv2_glacier_spike"],
  "base_str": 3, "base_dex": 10, "base_con": 5, "base_int": 20, "base_hp": 280, "base_ap": 18,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 4},
 {"id": "cove_bandit_lord", "name": "Cove Bandit Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 46, "rarity": "superrare", "base_xp": 2800,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (600, 2000),
  "basic_attack": "lord's blade", "strong_attack": "tidekin decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 36, "base_dex": 18, "base_con": 32, "base_int": 10, "base_hp": 2000, "base_ap": 12,
  "str_per_level": 7, "dex_per_level": 3, "con_per_level": 6, "int_per_level": 2},
 {"id": "cove_sea_titan", "name": "Cove Sea Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 72, "rarity": "superrare", "base_xp": 16000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (4500, 15000),
  "basic_attack": "titan tide slam", "strong_attack": "cove annihilation",
  "player_abilities": ["water_water_water_magic_lv3_tsunami_burst"],
  "base_str": 82, "base_dex": 12, "base_con": 76, "base_int": 12, "base_hp": 20000, "base_ap": 14,
  "str_per_level": 16, "dex_per_level": 2, "con_per_level": 15, "int_per_level": 2},
 {"id": "tidekin_world_god", "name": "The Tidekin World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 90000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (30000, 100000),
  "basic_attack": "world tide mandate", "strong_attack": "tidekin apocalypse",
  "player_abilities": ["water_water_water_magic_lv3_tsunami_burst"],
  "base_str": 22, "base_dex": 28, "base_con": 22, "base_int": 128, "base_hp": 70000, "base_ap": 108,
  "str_per_level": 4, "dex_per_level": 5, "con_per_level": 4, "int_per_level": 26},
]
