"""Miregloom's Rot-Catacomb Dungeon Seed Configuration"""

from typing import Dict, Any

# Tile constants for dungeon rendering and builder decisions
OPEN_AREA_TILE   = "░"
IMPASSABLE_TILE  = "¤"
IMPASSABLE_CHANCE = 0.04
OPEN_AREA_COLOR  = "#5a6838"
IMPASSABLE_COLOR = "#1e2410"
BORDER_TILE      = "·"
BORDER_COLOR     = "#3a4820"

FLOOR_HOSTILES = {
    1: [
        'bog_crawler',
        'rotling',
        'mire_witch',
        'swamp_shambler',
        'curse_leech',
        'bog_bonewalker',
        'swamp_hydra_whelp'
    ]
}

HOSTILE_SEEDS = [  # all level 8–10, ~10 hostiles total
    # Floor 1 - Rot-Catacomb (undead, rot-beasts, cursed creatures)
    {
        'id': 'bog_crawler',
        'name': 'Bog Crawler',
        'hostile_type': 'creature',
        'min_spawn_level': 18,
        'role': 'damage',
        'rarity': 'common',
        'base_xp': 20,
        'common_drop': 'herb_minor',
        'rare_drop': None,
        'money_range': (2, 12),
        'basic_attack': 'muck bite',
        'strong_attack': 'swamp drag',
        'player_abilities': [],
        'base_str': 3,
        'base_dex': 4,
        'base_con': 4,
        'base_int': 1,
        'base_hp': 26,
        'base_ap': 3,
        'str_per_level': 1,
        'dex_per_level': 2,
        'con_per_level': 1,
        'int_per_level': 0,
        'resistances': ['dark'],
        'immunities': [],
        'weaknesses': ['fire']
    },
    {
        'id': 'rotling',
        'name': 'Rotling',
        'hostile_type': 'undead',
        'min_spawn_level': 19,
        'role': 'hazard',
        'rarity': 'common',
        'base_xp': 36,
        'common_drop': 'stimulant_small',
        'rare_drop': 'stimulant_large',
        'money_range': (6, 30),
        'basic_attack': 'rot swipe',
        'strong_attack': 'decay burst',
        'player_abilities': ['dark_technique_lv1_night_claw'],
        'base_str': 4,
        'base_dex': 3,
        'base_con': 5,
        'base_int': 2,
        'base_hp': 38,
        'base_ap': 4,
        'str_per_level': 1,
        'dex_per_level': 1,
        'con_per_level': 2,
        'int_per_level': 0,
        'resistances': ['dark'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['fire', 'light']
    },
    {
        'id': 'mire_witch',
        'name': 'Mire Witch',
        'hostile_type': 'humanoid',
        'min_spawn_level': 20,
        'role': 'support',
        'rarity': 'uncommon',
        'base_xp': 60,
        'common_drop': 'herb_med',
        'rare_drop': 'herb_major',
        'money_range': (10, 50),
        'basic_attack': 'hex spit',
        'strong_attack': 'curse mire',
        'player_abilities': ['dark_dark_magic_lv2_umbra_storm'],
        'base_str': 3,
        'base_dex': 4,
        'base_con': 5,
        'base_int': 7,
        'base_hp': 70,
        'base_ap': 5,
        'str_per_level': 1,
        'dex_per_level': 1,
        'con_per_level': 1,
        'int_per_level': 3,
        'resistances': ['continuous_damage'],
        'immunities': [],
        'weaknesses': ['light']
    },
    {
        'id': 'swamp_shambler',
        'name': 'Swamp Shambler',
        'hostile_type': 'undead',
        'min_spawn_level': 19,
        'role': 'damage',
        'rarity': 'uncommon',
        'base_xp': 120,
        'common_drop': 'herb_minor',
        'rare_drop': 'herb_major',
        'money_range': (20, 90),
        'basic_attack': 'mire slam',
        'strong_attack': 'bog crush',
        'player_abilities': ['earth_dark_technique_lv2_dark_impact'],
        'base_str': 6,
        'base_dex': 2,
        'base_con': 10,
        'base_int': 1,
        'base_hp': 160,
        'base_ap': 6,
        'str_per_level': 2,
        'dex_per_level': 0,
        'con_per_level': 3,
        'int_per_level': 0,
        'resistances': ['dark'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['fire']
    },
    {
        'id': 'curse_leech',
        'name': 'Curse Leech',
        'hostile_type': 'creature',
        'min_spawn_level': 22,
        'role': 'hazard',
        'rarity': 'rare',
        'base_xp': 200,
        'common_drop': 'herb_minor',
        'rare_drop': 'ointment',
        'money_range': (30, 120),
        'basic_attack': 'curse drain',
        'strong_attack': 'memory siphon',
        'player_abilities': ['light_dark_skill_lv2_twilight_bleed'],
        'base_str': 3,
        'base_dex': 6,
        'base_con': 4,
        'base_int': 5,
        'base_hp': 50,
        'base_ap': 4,
        'str_per_level': 1,
        'dex_per_level': 2,
        'con_per_level': 1,
        'int_per_level': 2,
        'resistances': ['continuous_damage'],
        'immunities': [],
        'weaknesses': ['fire']
    },
    {
        'id': 'bog_bonewalker',
        'name': 'Bog Bonewalker',
        'hostile_type': 'undead',
        'min_spawn_level': 18,
        'role': 'damage',
        'rarity': 'common',
        'base_xp': 24,
        'common_drop': 'stimulant_small',
        'rare_drop': None,
        'money_range': (4, 16),
        'basic_attack': 'bone rake',
        'strong_attack': 'marsh cleave',
        'player_abilities': [],
        'base_str': 5,
        'base_dex': 3,
        'base_con': 4,
        'base_int': 1,
        'base_hp': 30,
        'base_ap': 3,
        'str_per_level': 2,
        'dex_per_level': 1,
        'con_per_level': 1,
        'int_per_level': 0,
        'resistances': ['dark'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['light']
    },
    {
        'id': 'swamp_hydra_whelp',
        'name': 'Swamp Hydra Whelp',
        'hostile_type': 'creature',
        'min_spawn_level': 24,
        'role': 'damage',
        'rarity': 'superrare',
        'base_xp': 300,
        'common_drop': 'herb_major',
        'rare_drop': 'tome_con_superrare',
        'money_range': (50, 200),
        'basic_attack': 'toxic bite',
        'strong_attack': 'hydra lash',
        'player_abilities': ['water_dark_technique_lv2_abyssal_rip'],
        'base_str': 9,
        'base_dex': 7,
        'base_con': 9,
        'base_int': 3,
        'base_hp': 380,
        'base_ap': 6,
        'str_per_level': 3,
        'dex_per_level': 2,
        'con_per_level': 2,
        'int_per_level': 0,
        'resistances': ['water'],
        'immunities': ['dark'],
        'weaknesses': ['fire']
    }
]

DUNGEON_NPCS = [ {'id': 'miregloom','location': 'final_chamber'} ]
DUNGEON_ITEMS = [ {'id': 'herb_major', 'location': 'treasure_room'} ]

BOSS_MOB = { 'id': 'miregloom_1',
             'name': 'Lich‑King Miregloom',
             'hostiles': [
                'mire_thrall',
                'mire_thrall',
                'miregloom_1']
            }

BOSS_HOSTILES = [
    {
        "id": "mire_thrall", "name": "Mire Thrall", "hostile_type": "magic", "role": "hazard",
        "min_spawn_level": 25, "rarity": "superrare", "base_xp": 480,
        "common_drop": "herb_major", "rare_drop": "tome_dex", "money_range": (45,180),
        "basic_attack": "rot swipe", "strong_attack": "bog burst",
        "player_abilities": ["light_dark_tech_lv2_contrast_burst", 'dark_spirit_lv1_shade_whisper'],
        "base_str": 8, "base_dex": 6, "base_con": 12, "base_int": 10,
        "base_hp": 1700, "base_ap": 10,
        "str_per_level": 2, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 2,
        'resistances': ['dark'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['light']
    },
    {
        "id": "miregloom_1", "name": "Lich‑King Miregloom", "hostile_type": "magic", "role": "boss",
        "min_spawn_level": 30, "rarity": "notfound", "base_xp": 1200,
        "common_drop": "herb_major", "rare_drop": "tome_dex", "money_range": (100,300),
        "basic_attack": "necrotic lash", "strong_attack": "swampfire surge",
        "player_abilities": ["air_dark_magic_lv2_gloom_vortex", "dark_dark_magic_lv2_umbra_storm", 'dark_dark_dark_magic_lv3_shadow_blast'],
        "base_str": 12, "base_dex": 8, "base_con": 16, "base_int": 18,
        "base_hp": 2700, "base_ap": 12,
        "str_per_level": 2, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 3,
        'resistances': [],
        'immunities': ['continuous_damage', 'dark', 'silence', 'stun', 'confuse', 'petrify', 'sleep'],
        'weaknesses': ['light']
    }
]

DUNGEON_SETTINGS: Dict[str, Any] = {
    "dungeon_id": "miregloom_lair",
    "seed": abs(hash("miregloom_lair")),
    "floor_count": 1,
    "room_size_min_max": (81, 120),  # a 9x9 area is 81
    "rooms_per_floor": 10,
    "max_neighbors_per_room": 3,
    "additional_connection_chance": 0.0,
    "min_max_distance_between_rooms": (5,12),
    "min_max_corridor_width": (3,6),
    "display_name": "Miregloom's Rot-Catacomb",
    "open_area_tile": OPEN_AREA_TILE,
    "impassable_tile": IMPASSABLE_TILE,
    "open_area_color":  OPEN_AREA_COLOR,
	"impassable_color": IMPASSABLE_COLOR,
	"border_tile":      BORDER_TILE,
	"border_color":     BORDER_COLOR,
    "impassable_chance": IMPASSABLE_CHANCE,
    "floor_hostiles": FLOOR_HOSTILES,
    "hostile_seeds": HOSTILE_SEEDS,
    "npcs": DUNGEON_NPCS,
	"items": DUNGEON_ITEMS,
    "boss_mob": BOSS_MOB,
    "boss_hostiles": BOSS_HOSTILES,
    "visible_distance": 5
}
