# Shallows shared hostiles - rarity-coverage fill, Lv 1-20.
# Uniform multiple-of-5 ladder per rarity (seed at N covers window starts N-4..N).
# Safe drops (no city reports a gap): uncommon Lv 5/10, superrare Lv 10.
RANDOM_HOSTILE_SEEDS = [
    {"id": "shallows_shared_dock_rat", "name": "Dock Rat", "hostile_type": "creature", "role": "damage", "min_spawn_level": 5, "rarity": "common", "base_xp": 40,
     "common_drop": "herb_minor", "rare_drop": None, "money_range": (5, 30),
     "basic_attack": "gnawing bite", "strong_attack": "scurrying swarm",
     "player_abilities": [],
     "base_str": 5, "base_dex": 6, "base_con": 5, "base_int": 2, "base_hp": 42, "base_ap": 5,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 0},
    {"id": "shallows_shared_gull_scavenger", "name": "Gull Scavenger", "hostile_type": "creature", "role": "damage", "min_spawn_level": 10, "rarity": "common", "base_xp": 90,
     "common_drop": "herb_minor", "rare_drop": None, "money_range": (8, 44),
     "basic_attack": "pecking dive", "strong_attack": "screech swarm",
     "player_abilities": [],
     "base_str": 7, "base_dex": 9, "base_con": 6, "base_int": 3, "base_hp": 90, "base_ap": 7,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 0},
    {"id": "shallows_shared_wharf_cutpurse", "name": "Wharf Cutpurse", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 15, "rarity": "common", "base_xp": 140,
     "common_drop": "herb_minor", "rare_drop": "stimulant_small", "money_range": (14, 68),
     "basic_attack": "quick shiv", "strong_attack": "gutter slash",
     "player_abilities": [],
     "base_str": 9, "base_dex": 11, "base_con": 8, "base_int": 4, "base_hp": 120, "base_ap": 8,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 0},
    {"id": "shallows_shared_mudflat_lurker", "name": "Mudflat Lurker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 20, "rarity": "common", "base_xp": 260,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (20, 96),
     "basic_attack": "raking claw", "strong_attack": "mire lunge",
     "player_abilities": [],
     "base_str": 13, "base_dex": 13, "base_con": 12, "base_int": 4, "base_hp": 200, "base_ap": 10,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "shallows_shared_reef_stalker", "name": "Reef Stalker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 15, "rarity": "uncommon", "base_xp": 170,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (18, 88),
     "basic_attack": "raking claw", "strong_attack": "shallows ambush",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 11, "base_dex": 13, "base_con": 10, "base_int": 5, "base_hp": 130, "base_ap": 9,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "shallows_shared_tidepool_serpent", "name": "Tidepool Serpent", "hostile_type": "creature", "role": "damage", "min_spawn_level": 20, "rarity": "uncommon", "base_xp": 300,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (24, 110),
     "basic_attack": "lunging bite", "strong_attack": "coil constriction",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 14, "base_dex": 16, "base_con": 12, "base_int": 5, "base_hp": 200, "base_ap": 10,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "shallows_shared_tidepool_lurker", "name": "Tidepool Lurker", "hostile_type": "creature", "role": "hazard", "min_spawn_level": 5, "rarity": "rare", "base_xp": 75,
     "common_drop": "herb_minor", "rare_drop": "herb_med", "money_range": (10, 48),
     "basic_attack": "tentacle snare", "strong_attack": "undertow drag",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 5, "base_dex": 8, "base_con": 5, "base_int": 7, "base_hp": 48, "base_ap": 7,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 1},
    {"id": "shallows_shared_coral_naga", "name": "Coral Naga", "hostile_type": "creature", "role": "hazard", "min_spawn_level": 10, "rarity": "rare", "base_xp": 150,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (14, 66),
     "basic_attack": "venom spit", "strong_attack": "reef coil",
     "player_abilities": ["level_1_hostile_ability_poison_dart", "air_skill_lv1_smoke_bomb"],
     "base_str": 8, "base_dex": 11, "base_con": 8, "base_int": 10, "base_hp": 92, "base_ap": 8,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 2},
    {"id": "shallows_shared_brine_conjurer", "name": "Brine Conjurer", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 15, "rarity": "rare", "base_xp": 210,
     "common_drop": "tome_int", "rare_drop": "stimulant_small", "money_range": (20, 90),
     "basic_attack": "salt hex", "strong_attack": "riptide surge",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 8, "base_dex": 12, "base_con": 10, "base_int": 16, "base_hp": 150, "base_ap": 11,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 3},
    {"id": "shallows_shared_sunken_warden", "name": "Sunken Warden", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 20, "rarity": "rare", "base_xp": 320,
     "common_drop": "tome_int", "rare_drop": "stimulant_small", "money_range": (28, 120),
     "basic_attack": "grave brine", "strong_attack": "drowned grasp",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor"],
     "base_str": 14, "base_dex": 14, "base_con": 16, "base_int": 18, "base_hp": 210, "base_ap": 12,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 3},
    {"id": "shallows_shared_drowned_wisp", "name": "Drowned Wisp", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 5, "rarity": "superrare", "base_xp": 90,
     "common_drop": "herb_minor", "rare_drop": "stimulant_med", "money_range": (20, 90),
     "basic_attack": "cold whisper", "strong_attack": "drowning dread",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 5, "base_dex": 8, "base_con": 5, "base_int": 9, "base_hp": 52, "base_ap": 7,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 1},
    {"id": "shallows_shared_sunken_phantom", "name": "Sunken Phantom", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 15, "rarity": "superrare", "base_xp": 300,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (40, 160),
     "basic_attack": "abyssal murmur", "strong_attack": "deep-water madness",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 10, "base_dex": 13, "base_con": 10, "base_int": 14, "base_hp": 160, "base_ap": 10,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 2},
    {"id": "shallows_shared_leviathan_hatchling", "name": "Leviathan Hatchling", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 20, "rarity": "superrare", "base_xp": 520,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (60, 220),
     "basic_attack": "brine lash", "strong_attack": "tidal devour",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 16, "base_dex": 16, "base_con": 16, "base_int": 18, "base_hp": 260, "base_ap": 12,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 2},
]
