# Shallows shared hostiles - rarity-coverage fill, Lv 21-40.
# Uniform multiple-of-5 ladder per rarity at Lv 25, 30, 35, 40 (all gapped).
RANDOM_HOSTILE_SEEDS = [
    # -- common --
    {"id": "shallows_shared_pier_gnawer", "name": "Pier Gnawer", "hostile_type": "creature", "role": "damage", "min_spawn_level": 25, "rarity": "common", "base_xp": 430,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (22, 105),
     "basic_attack": "gnashing bite", "strong_attack": "swarming rush",
     "player_abilities": [],
     "base_str": 17, "base_dex": 15, "base_con": 14, "base_int": 4, "base_hp": 270, "base_ap": 11,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "shallows_shared_smuggler_thug", "name": "Smuggler Thug", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 30, "rarity": "common", "base_xp": 540,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (34, 145),
     "basic_attack": "cudgel swing", "strong_attack": "dockside ambush",
     "player_abilities": [],
     "base_str": 21, "base_dex": 18, "base_con": 18, "base_int": 6, "base_hp": 330, "base_ap": 12,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},
    {"id": "shallows_shared_shore_crab_brute", "name": "Shore Crab Brute", "hostile_type": "creature", "role": "damage", "min_spawn_level": 35, "rarity": "common", "base_xp": 660,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (40, 168),
     "basic_attack": "claw snap", "strong_attack": "shell charge",
     "player_abilities": [],
     "base_str": 25, "base_dex": 16, "base_con": 24, "base_int": 5, "base_hp": 410, "base_ap": 12,
     "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},
    {"id": "shallows_shared_dune_wader", "name": "Dune Wader", "hostile_type": "creature", "role": "damage", "min_spawn_level": 40, "rarity": "common", "base_xp": 820,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (50, 200),
     "basic_attack": "beak jab", "strong_attack": "tidal stomp",
     "player_abilities": [],
     "base_str": 28, "base_dex": 20, "base_con": 26, "base_int": 5, "base_hp": 500, "base_ap": 13,
     "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},

    # -- uncommon --
    {"id": "shallows_shared_gull_harrier", "name": "Gull Harrier", "hostile_type": "creature", "role": "damage", "min_spawn_level": 25, "rarity": "uncommon", "base_xp": 460,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (30, 130),
     "basic_attack": "diving peck", "strong_attack": "screeching dive",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 18, "base_dex": 22, "base_con": 15, "base_int": 6, "base_hp": 280, "base_ap": 12,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "shallows_shared_eel_stalker", "name": "Eel Stalker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 30, "rarity": "uncommon", "base_xp": 600,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (36, 155),
     "basic_attack": "slithering bite", "strong_attack": "coil constriction",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 20, "base_dex": 24, "base_con": 18, "base_int": 6, "base_hp": 330, "base_ap": 13,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "shallows_shared_tidecaller_acolyte", "name": "Tidecaller Acolyte", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 35, "rarity": "uncommon", "base_xp": 720,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (46, 190),
     "basic_attack": "brine bolt", "strong_attack": "surging tide",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 18, "base_dex": 22, "base_con": 22, "base_int": 34, "base_hp": 400, "base_ap": 16,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 5},
    {"id": "shallows_shared_barnacle_raptor", "name": "Barnacle Raptor", "hostile_type": "creature", "role": "damage", "min_spawn_level": 40, "rarity": "uncommon", "base_xp": 880,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (56, 220),
     "basic_attack": "raking talon", "strong_attack": "reef dive",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 28, "base_dex": 30, "base_con": 22, "base_int": 7, "base_hp": 500, "base_ap": 14,
     "str_per_level": 4, "dex_per_level": 4, "con_per_level": 3, "int_per_level": 0},

    # -- rare --
    {"id": "shallows_shared_reef_golem", "name": "Reef Golem", "hostile_type": "construct", "role": "hazard", "min_spawn_level": 25, "rarity": "rare", "base_xp": 500,
     "common_drop": None, "rare_drop": "tome_con", "money_range": (0, 80),
     "basic_attack": "coral fist", "strong_attack": "tidal slam",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 24, "base_dex": 10, "base_con": 26, "base_int": 4, "base_hp": 360, "base_ap": 11,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "shallows_shared_saltmarsh_shaman", "name": "Saltmarsh Shaman", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 30, "rarity": "rare", "base_xp": 640,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (48, 200),
     "basic_attack": "marsh hex", "strong_attack": "drowning ritual",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "level_1_hostile_ability_poison_dart"],
     "base_str": 16, "base_dex": 18, "base_con": 18, "base_int": 30, "base_hp": 360, "base_ap": 15,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 5},
    {"id": "shallows_shared_deepwater_ogre", "name": "Deepwater Ogre", "hostile_type": "creature", "role": "damage", "min_spawn_level": 35, "rarity": "rare", "base_xp": 820,
     "common_drop": "herb_med", "rare_drop": "tome_str", "money_range": (58, 230),
     "basic_attack": "fist smash", "strong_attack": "tidal haymaker",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 32, "base_dex": 14, "base_con": 28, "base_int": 5, "base_hp": 500, "base_ap": 13,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "shallows_shared_wraithtide_warden", "name": "Wraithtide Warden", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 40, "rarity": "rare", "base_xp": 980,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (70, 280),
     "basic_attack": "grave brine", "strong_attack": "sunken curse",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 24, "base_dex": 20, "base_con": 26, "base_int": 30, "base_hp": 520, "base_ap": 16,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 5},

    # -- superrare --
    {"id": "shallows_shared_kraken_spawn", "name": "Kraken Spawn", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 25, "rarity": "superrare", "base_xp": 900,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (120, 420),
     "basic_attack": "tentacle flurry", "strong_attack": "abyssal grasp",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 22, "base_dex": 24, "base_con": 24, "base_int": 26, "base_hp": 440, "base_ap": 16,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 3},
    {"id": "shallows_shared_tidemaw_terror", "name": "Tidemaw Terror", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 30, "rarity": "superrare", "base_xp": 1100,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (150, 520),
     "basic_attack": "maw snap", "strong_attack": "devouring whirlpool",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 24, "base_dex": 24, "base_con": 24, "base_int": 32, "base_hp": 480, "base_ap": 18,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 5},
    {"id": "shallows_shared_drowned_leviathan", "name": "Drowned Leviathan", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 35, "rarity": "superrare", "base_xp": 1400,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (200, 700),
     "basic_attack": "leviathan lash", "strong_attack": "tidal annihilation",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 30, "base_dex": 26, "base_con": 28, "base_int": 30, "base_hp": 560, "base_ap": 19,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 4},
    {"id": "shallows_shared_abyssal_siren", "name": "Abyssal Siren", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 40, "rarity": "superrare", "base_xp": 1750,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (260, 880),
     "basic_attack": "siren wail", "strong_attack": "maddening chorus",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 32, "base_dex": 30, "base_con": 30, "base_int": 34, "base_hp": 640, "base_ap": 20,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 5},
]
