# Shallows shared hostiles - rarity-coverage fill, Lv 41-60.
# Uniform multiple-of-5 ladder per rarity at Lv 45, 50, 55, 60 (all gapped).
RANDOM_HOSTILE_SEEDS = [
    # -- common --
    {"id": "shallows_shared_corsair_raider", "name": "Corsair Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 45, "rarity": "common", "base_xp": 1100,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (76, 300),
     "basic_attack": "cutlass slash", "strong_attack": "boarding onslaught",
     "player_abilities": [],
     "base_str": 32, "base_dex": 24, "base_con": 28, "base_int": 6, "base_hp": 560, "base_ap": 14,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "shallows_shared_reef_troll", "name": "Reef Troll", "hostile_type": "creature", "role": "damage", "min_spawn_level": 50, "rarity": "common", "base_xp": 1300,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (88, 330),
     "basic_attack": "club smash", "strong_attack": "coral hurl",
     "player_abilities": [],
     "base_str": 36, "base_dex": 18, "base_con": 34, "base_int": 5, "base_hp": 680, "base_ap": 14,
     "str_per_level": 5, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 0},
    {"id": "shallows_shared_brineblood_marauder", "name": "Brineblood Marauder", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 55, "rarity": "common", "base_xp": 1500,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (96, 360),
     "basic_attack": "boarding axe", "strong_attack": "pillage charge",
     "player_abilities": [],
     "base_str": 40, "base_dex": 24, "base_con": 34, "base_int": 6, "base_hp": 760, "base_ap": 15,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 0},
    {"id": "shallows_shared_deepshell_hulk", "name": "Deepshell Hulk", "hostile_type": "creature", "role": "damage", "min_spawn_level": 60, "rarity": "common", "base_xp": 1720,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (104, 380),
     "basic_attack": "shell bash", "strong_attack": "tidal crush",
     "player_abilities": [],
     "base_str": 44, "base_dex": 20, "base_con": 42, "base_int": 6, "base_hp": 880, "base_ap": 15,
     "str_per_level": 6, "dex_per_level": 2, "con_per_level": 5, "int_per_level": 0},

    # -- uncommon --
    {"id": "shallows_shared_storm_harrier", "name": "Storm Harrier", "hostile_type": "creature", "role": "damage", "min_spawn_level": 45, "rarity": "uncommon", "base_xp": 1160,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (78, 300),
     "basic_attack": "diving rake", "strong_attack": "squall dive",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 28, "base_dex": 34, "base_con": 24, "base_int": 8, "base_hp": 580, "base_ap": 15,
     "str_per_level": 4, "dex_per_level": 5, "con_per_level": 3, "int_per_level": 0},
    {"id": "shallows_shared_bilge_brute", "name": "Bilge Brute", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 50, "rarity": "uncommon", "base_xp": 1360,
     "common_drop": "herb_med", "rare_drop": "tome_str", "money_range": (88, 330),
     "basic_attack": "anchor swing", "strong_attack": "crushing haymaker",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 40, "base_dex": 22, "base_con": 34, "base_int": 7, "base_hp": 700, "base_ap": 15,
     "str_per_level": 5, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 0},
    {"id": "shallows_shared_maelstrom_mystic", "name": "Maelstrom Mystic", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 55, "rarity": "uncommon", "base_xp": 1560,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (100, 360),
     "basic_attack": "whirl bolt", "strong_attack": "vortex nova",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_magic_lv1_shadow_tendril"],
     "base_str": 24, "base_dex": 28, "base_con": 28, "base_int": 42, "base_hp": 680, "base_ap": 18,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 6},
    {"id": "shallows_shared_serpent_stalker", "name": "Serpent Stalker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 60, "rarity": "uncommon", "base_xp": 1780,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (112, 384),
     "basic_attack": "lunging bite", "strong_attack": "constricting coil",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 44, "base_dex": 38, "base_con": 36, "base_int": 8, "base_hp": 880, "base_ap": 16,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 4, "int_per_level": 0},

    # -- rare --
    {"id": "shallows_shared_coralforge_golem", "name": "Coralforge Golem", "hostile_type": "construct", "role": "hazard", "min_spawn_level": 45, "rarity": "rare", "base_xp": 1300,
     "common_drop": None, "rare_drop": "tome_con", "money_range": (0, 120),
     "basic_attack": "coral fist", "strong_attack": "reef quake",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 40, "base_dex": 14, "base_con": 42, "base_int": 10, "base_hp": 760, "base_ap": 14,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 1},
    {"id": "shallows_shared_tempest_oracle", "name": "Tempest Oracle", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 50, "rarity": "rare", "base_xp": 1500,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (100, 360),
     "basic_attack": "storm hex", "strong_attack": "typhoon ritual",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_magic_lv1_shadow_tendril"],
     "base_str": 28, "base_dex": 26, "base_con": 30, "base_int": 44, "base_hp": 700, "base_ap": 18,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 6},
    {"id": "shallows_shared_leviathan_drake", "name": "Leviathan Drake", "hostile_type": "creature", "role": "damage", "min_spawn_level": 55, "rarity": "rare", "base_xp": 1720,
     "common_drop": "herb_med", "rare_drop": "tome_str", "money_range": (130, 460),
     "basic_attack": "fin buffet", "strong_attack": "tidal divebomb",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 44, "base_dex": 34, "base_con": 38, "base_int": 16, "base_hp": 820, "base_ap": 18,
     "str_per_level": 6, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 1},
    {"id": "shallows_shared_sunken_lich", "name": "Sunken Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 60, "rarity": "rare", "base_xp": 1980,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (150, 520),
     "basic_attack": "soul brine", "strong_attack": "drowning requiem",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 32, "base_dex": 30, "base_con": 36, "base_int": 50, "base_hp": 880, "base_ap": 20,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 7},

    # -- superrare --
    {"id": "shallows_shared_maelstrom_colossus", "name": "Maelstrom Colossus", "hostile_type": "construct", "role": "damage", "min_spawn_level": 45, "rarity": "superrare", "base_xp": 2300,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (320, 1050),
     "basic_attack": "tidal hammer", "strong_attack": "maelstrom eruption",
     "player_abilities": ["earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb", "dark_magic_lv1_shadow_tendril"],
     "base_str": 46, "base_dex": 22, "base_con": 46, "base_int": 24, "base_hp": 940, "base_ap": 20,
     "str_per_level": 6, "dex_per_level": 2, "con_per_level": 6, "int_per_level": 3},
    {"id": "shallows_shared_abyss_devourer", "name": "Abyss Devourer", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 50, "rarity": "superrare", "base_xp": 2700,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (360, 1200),
     "basic_attack": "abyss gnaw", "strong_attack": "hunger of the deep",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 42, "base_dex": 32, "base_con": 40, "base_int": 46, "base_hp": 1000, "base_ap": 22,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 5, "int_per_level": 7},
    {"id": "shallows_shared_tempest_titan", "name": "Tempest Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 55, "rarity": "superrare", "base_xp": 3200,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (420, 1400),
     "basic_attack": "thunder fist", "strong_attack": "typhoon descent",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 52, "base_dex": 34, "base_con": 48, "base_int": 30, "base_hp": 1150, "base_ap": 24,
     "str_per_level": 7, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 3},
    {"id": "shallows_shared_abyssal_tide_god", "name": "Abyssal Tide God", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 60, "rarity": "superrare", "base_xp": 4000,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (520, 1700),
     "basic_attack": "abyssal wrath", "strong_attack": "tide-of-madness rend",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 56, "base_dex": 38, "base_con": 50, "base_int": 46, "base_hp": 1300, "base_ap": 26,
     "str_per_level": 7, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 6},
]
