# Shallows shared hostiles - rarity-coverage fill, Lv 61-80.
# Uniform multiple-of-5 ladder per rarity at Lv 65, 70, 75, 80.
# Safe drop (no city reports a gap): superrare Lv 65.
RANDOM_HOSTILE_SEEDS = [
    # -- common --
    {"id": "shallows_shared_harborlord_reaver", "name": "Harborlord Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 65, "rarity": "common", "base_xp": 2200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (150, 540),
     "basic_attack": "reaver cleave", "strong_attack": "harbor onslaught",
     "player_abilities": [],
     "base_str": 48, "base_dex": 26, "base_con": 42, "base_int": 8, "base_hp": 920, "base_ap": 16,
     "str_per_level": 7, "dex_per_level": 3, "con_per_level": 5, "int_per_level": 0},
    {"id": "shallows_shared_barnacle_ogre", "name": "Barnacle Ogre", "hostile_type": "creature", "role": "damage", "min_spawn_level": 70, "rarity": "common", "base_xp": 2500,
     "common_drop": "herb_major", "rare_drop": None, "money_range": (0, 130),
     "basic_attack": "shell swing", "strong_attack": "tidal stomp",
     "player_abilities": [],
     "base_str": 54, "base_dex": 22, "base_con": 50, "base_int": 6, "base_hp": 1080, "base_ap": 16,
     "str_per_level": 8, "dex_per_level": 2, "con_per_level": 6, "int_per_level": 0},
    {"id": "shallows_shared_tideguard_veteran", "name": "Tideguard Veteran", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 75, "rarity": "common", "base_xp": 2900,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (190, 660),
     "basic_attack": "trident sweep", "strong_attack": "veteran's execution",
     "player_abilities": [],
     "base_str": 58, "base_dex": 30, "base_con": 50, "base_int": 8, "base_hp": 1180, "base_ap": 17,
     "str_per_level": 8, "dex_per_level": 3, "con_per_level": 6, "int_per_level": 0},
    {"id": "shallows_shared_riptide_brute", "name": "Riptide Brute", "hostile_type": "creature", "role": "damage", "min_spawn_level": 80, "rarity": "common", "base_xp": 3400,
     "common_drop": "herb_major", "rare_drop": None, "money_range": (0, 140),
     "basic_attack": "crushing slam", "strong_attack": "undertow barrage",
     "player_abilities": [],
     "base_str": 64, "base_dex": 26, "base_con": 56, "base_int": 8, "base_hp": 1340, "base_ap": 17,
     "str_per_level": 9, "dex_per_level": 3, "con_per_level": 7, "int_per_level": 0},

    # -- uncommon --
    {"id": "shallows_shared_gale_wyvern", "name": "Gale Wyvern", "hostile_type": "creature", "role": "damage", "min_spawn_level": 65, "rarity": "uncommon", "base_xp": 2400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (160, 560),
     "basic_attack": "talon rake", "strong_attack": "screeching dive",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 46, "base_dex": 44, "base_con": 38, "base_int": 10, "base_hp": 920, "base_ap": 17,
     "str_per_level": 7, "dex_per_level": 5, "con_per_level": 4, "int_per_level": 0},
    {"id": "shallows_shared_saltforge_zealot", "name": "Saltforge Zealot", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 70, "rarity": "uncommon", "base_xp": 2700,
     "common_drop": "herb_major", "rare_drop": "tome_str", "money_range": (180, 620),
     "basic_attack": "brine maul", "strong_attack": "tidefire smite",
     "player_abilities": ["earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril"],
     "base_str": 52, "base_dex": 28, "base_con": 44, "base_int": 12, "base_hp": 1080, "base_ap": 17,
     "str_per_level": 8, "dex_per_level": 3, "con_per_level": 5, "int_per_level": 1},
    {"id": "shallows_shared_seafang_alpha", "name": "Seafang Alpha", "hostile_type": "creature", "role": "damage", "min_spawn_level": 75, "rarity": "uncommon", "base_xp": 3100,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (200, 700),
     "basic_attack": "seafang bite", "strong_attack": "pack takedown",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 56, "base_dex": 44, "base_con": 46, "base_int": 10, "base_hp": 1180, "base_ap": 17,
     "str_per_level": 8, "dex_per_level": 5, "con_per_level": 5, "int_per_level": 0},
    {"id": "shallows_shared_squall_shaman", "name": "Squall Shaman", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 80, "rarity": "uncommon", "base_xp": 3500,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (220, 760),
     "basic_attack": "squall bolt", "strong_attack": "cyclone hex",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_magic_lv1_shadow_tendril"],
     "base_str": 36, "base_dex": 42, "base_con": 44, "base_int": 58, "base_hp": 1180, "base_ap": 20,
     "str_per_level": 4, "dex_per_level": 5, "con_per_level": 5, "int_per_level": 9},

    # -- rare --
    {"id": "shallows_shared_tideforge_golem", "name": "Tideforge Golem", "hostile_type": "construct", "role": "hazard", "min_spawn_level": 65, "rarity": "rare", "base_xp": 2700,
     "common_drop": None, "rare_drop": "tome_con", "money_range": (0, 160),
     "basic_attack": "tide fist", "strong_attack": "surge devastation",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 56, "base_dex": 18, "base_con": 58, "base_int": 12, "base_hp": 1300, "base_ap": 16,
     "str_per_level": 8, "dex_per_level": 2, "con_per_level": 7, "int_per_level": 1},
    {"id": "shallows_shared_brinescale_wyrm", "name": "Brinescale Wyrm", "hostile_type": "creature", "role": "damage", "min_spawn_level": 70, "rarity": "rare", "base_xp": 3100,
     "common_drop": "herb_major", "rare_drop": "tome_str", "money_range": (240, 820),
     "basic_attack": "brine breath", "strong_attack": "coil crush",
     "player_abilities": ["earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 58, "base_dex": 36, "base_con": 50, "base_int": 20, "base_hp": 1300, "base_ap": 20,
     "str_per_level": 8, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 2},
    {"id": "shallows_shared_drowned_archlich", "name": "Drowned Archlich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 75, "rarity": "rare", "base_xp": 3600,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (280, 950),
     "basic_attack": "grave brine", "strong_attack": "abyssal requiem",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 38, "base_dex": 36, "base_con": 44, "base_int": 60, "base_hp": 1300, "base_ap": 22,
     "str_per_level": 5, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 9},
    {"id": "shallows_shared_maelstrom_archon", "name": "Maelstrom Archon", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 80, "rarity": "rare", "base_xp": 4100,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (320, 1100),
     "basic_attack": "vortex arc", "strong_attack": "chain maelstrom",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 44, "base_dex": 44, "base_con": 50, "base_int": 64, "base_hp": 1400, "base_ap": 23,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 6, "int_per_level": 10},

    # -- superrare (Lv 65 dropped: no city reports superrare gap at Lv 61-65) --
    {"id": "shallows_shared_deepwater_god", "name": "Deepwater God", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 70, "rarity": "superrare", "base_xp": 5200,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (760, 2500),
     "basic_attack": "deepwater wrath", "strong_attack": "abyssal cataclysm",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "earth_magic_lv1_tremor"],
     "base_str": 62, "base_dex": 40, "base_con": 56, "base_int": 44, "base_hp": 1650, "base_ap": 28,
     "str_per_level": 9, "dex_per_level": 4, "con_per_level": 7, "int_per_level": 5},
    {"id": "shallows_shared_void_tide_horror", "name": "Void Tide Horror", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 75, "rarity": "superrare", "base_xp": 6200,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (900, 3000),
     "basic_attack": "void rend", "strong_attack": "tide-devouring collapse",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 56, "base_dex": 46, "base_con": 54, "base_int": 58, "base_hp": 1750, "base_ap": 28,
     "str_per_level": 8, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 9},
    {"id": "shallows_shared_ascendant_tide_god", "name": "Ascendant Tide God", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 80, "rarity": "superrare", "base_xp": 7400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (1100, 3600),
     "basic_attack": "ascendant surge", "strong_attack": "world-tide descent",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field"],
     "base_str": 66, "base_dex": 48, "base_con": 58, "base_int": 52, "base_hp": 1900, "base_ap": 30,
     "str_per_level": 10, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 6},
]
