# Shallows shared hostiles - rarity-coverage fill, Lv 81-100.
# Uniform multiple-of-5 ladder per rarity at Lv 85, 90, 95, 100 (all gapped).
# Theme: apex tide-gods, drowned leviathans, void-touched abyss horrors.
RANDOM_HOSTILE_SEEDS = [
    # -- common --
    {"id": "shallows_shared_wartide_marauder", "name": "Wartide Marauder", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 85, "rarity": "common", "base_xp": 6600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (300, 1050),
     "basic_attack": "greataxe cleave", "strong_attack": "tide onslaught",
     "player_abilities": [],
     "base_str": 66, "base_dex": 30, "base_con": 58, "base_int": 10, "base_hp": 1500, "base_ap": 18,
     "str_per_level": 10, "dex_per_level": 3, "con_per_level": 7, "int_per_level": 0},
    {"id": "shallows_shared_reefshell_behemoth", "name": "Reefshell Behemoth", "hostile_type": "creature", "role": "damage", "min_spawn_level": 90, "rarity": "common", "base_xp": 8000,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 130),
     "basic_attack": "shell smash", "strong_attack": "tidal quake",
     "player_abilities": [],
     "base_str": 74, "base_dex": 24, "base_con": 66, "base_int": 8, "base_hp": 1750, "base_ap": 18,
     "str_per_level": 11, "dex_per_level": 2, "con_per_level": 8, "int_per_level": 0},
    {"id": "shallows_shared_harbor_champion", "name": "Harbor Champion", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 95, "rarity": "common", "base_xp": 10000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (400, 1400),
     "basic_attack": "champion maul", "strong_attack": "tidebreaker execution",
     "player_abilities": [],
     "base_str": 82, "base_dex": 34, "base_con": 72, "base_int": 10, "base_hp": 2100, "base_ap": 19,
     "str_per_level": 12, "dex_per_level": 4, "con_per_level": 9, "int_per_level": 0},
    {"id": "shallows_shared_titan_hulk", "name": "Titan Hulk", "hostile_type": "creature", "role": "damage", "min_spawn_level": 100, "rarity": "common", "base_xp": 14000,
     "common_drop": "herb_major", "rare_drop": None, "money_range": (0, 150),
     "basic_attack": "colossal swipe", "strong_attack": "abyssal avalanche",
     "player_abilities": [],
     "base_str": 92, "base_dex": 30, "base_con": 84, "base_int": 10, "base_hp": 2600, "base_ap": 20,
     "str_per_level": 13, "dex_per_level": 3, "con_per_level": 11, "int_per_level": 0},

    # -- uncommon --
    {"id": "shallows_shared_skyfin_wyvern", "name": "Skyfin Wyvern", "hostile_type": "creature", "role": "damage", "min_spawn_level": 85, "rarity": "uncommon", "base_xp": 7200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (360, 1250),
     "basic_attack": "skyfin rake", "strong_attack": "apex divebomb",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 66, "base_dex": 54, "base_con": 56, "base_int": 14, "base_hp": 1550, "base_ap": 19,
     "str_per_level": 10, "dex_per_level": 6, "con_per_level": 7, "int_per_level": 1},
    {"id": "shallows_shared_tideforge_warlord", "name": "Tideforge Warlord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 90, "rarity": "uncommon", "base_xp": 8800,
     "common_drop": "herb_major", "rare_drop": "tome_str", "money_range": (420, 1450),
     "basic_attack": "brine cleave", "strong_attack": "tidefire devastation",
     "player_abilities": ["earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril"],
     "base_str": 76, "base_dex": 36, "base_con": 66, "base_int": 16, "base_hp": 1800, "base_ap": 19,
     "str_per_level": 11, "dex_per_level": 4, "con_per_level": 8, "int_per_level": 1},
    {"id": "shallows_shared_abyss_alpha", "name": "Abyss Alpha", "hostile_type": "creature", "role": "damage", "min_spawn_level": 95, "rarity": "uncommon", "base_xp": 11000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (480, 1650),
     "basic_attack": "abyss bite", "strong_attack": "deep takedown",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 82, "base_dex": 52, "base_con": 72, "base_int": 14, "base_hp": 2100, "base_ap": 20,
     "str_per_level": 12, "dex_per_level": 6, "con_per_level": 8, "int_per_level": 0},
    {"id": "shallows_shared_tempest_hierophant", "name": "Tempest Hierophant", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 100, "rarity": "uncommon", "base_xp": 15000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (560, 1900),
     "basic_attack": "storm sigil", "strong_attack": "tempest litany",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 46, "base_dex": 52, "base_con": 60, "base_int": 86, "base_hp": 2300, "base_ap": 24,
     "str_per_level": 6, "dex_per_level": 6, "con_per_level": 8, "int_per_level": 13},

    # -- rare --
    {"id": "shallows_shared_worldtide_golem", "name": "Worldtide Golem", "hostile_type": "construct", "role": "hazard", "min_spawn_level": 85, "rarity": "rare", "base_xp": 8000,
     "common_drop": None, "rare_drop": "tome_con", "money_range": (0, 200),
     "basic_attack": "worldtide fist", "strong_attack": "cataclysmic surge",
     "player_abilities": ["earth_magic_lv1_tremor", "earth_earth_magic_lv2_quake_field"],
     "base_str": 78, "base_dex": 22, "base_con": 80, "base_int": 14, "base_hp": 2000, "base_ap": 18,
     "str_per_level": 11, "dex_per_level": 2, "con_per_level": 10, "int_per_level": 1},
    {"id": "shallows_shared_abyssal_wyrm", "name": "Abyssal Wyrm", "hostile_type": "creature", "role": "damage", "min_spawn_level": 90, "rarity": "rare", "base_xp": 9600,
     "common_drop": "herb_major", "rare_drop": "tome_str", "money_range": (500, 1700),
     "basic_attack": "abyssal breath", "strong_attack": "coil devastation",
     "player_abilities": ["earth_earth_magic_lv2_quake_field", "air_skill_lv1_smoke_bomb"],
     "base_str": 78, "base_dex": 44, "base_con": 68, "base_int": 28, "base_hp": 2000, "base_ap": 22,
     "str_per_level": 11, "dex_per_level": 5, "con_per_level": 8, "int_per_level": 2},
    {"id": "shallows_shared_tide_archlich", "name": "Tide Archlich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 95, "rarity": "rare", "base_xp": 12000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (620, 2100),
     "basic_attack": "soul brine", "strong_attack": "eternal drowning requiem",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 48, "base_dex": 46, "base_con": 58, "base_int": 82, "base_hp": 2100, "base_ap": 24,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 13},
    {"id": "shallows_shared_maelstrom_sovereign", "name": "Maelstrom Sovereign", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "rare", "base_xp": 16000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (760, 2600),
     "basic_attack": "sovereign arc", "strong_attack": "apex chain maelstrom",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field"],
     "base_str": 56, "base_dex": 54, "base_con": 66, "base_int": 90, "base_hp": 2300, "base_ap": 26,
     "str_per_level": 7, "dex_per_level": 6, "con_per_level": 8, "int_per_level": 14},

    # -- superrare --
    {"id": "shallows_shared_worldtide_god", "name": "Worldtide God", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 85, "rarity": "superrare", "base_xp": 40000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (10000, 34000),
     "basic_attack": "worldtide wrath", "strong_attack": "ocean-end cataclysm",
     "player_abilities": ["earth_earth_magic_lv2_quake_field", "dark_dark_dark_magic_lv3_shadow_blast", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 80, "base_dex": 46, "base_con": 72, "base_int": 60, "base_hp": 24000, "base_ap": 70,
     "str_per_level": 14, "dex_per_level": 6, "con_per_level": 12, "int_per_level": 10},
    {"id": "shallows_shared_the_abyss_maw", "name": "The Abyss Maw", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 90, "rarity": "superrare", "base_xp": 48000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (12000, 40000),
     "basic_attack": "devouring dark", "strong_attack": "unmaking of the deep",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 88, "base_dex": 54, "base_con": 80, "base_int": 76, "base_hp": 27000, "base_ap": 76,
     "str_per_level": 16, "dex_per_level": 7, "con_per_level": 14, "int_per_level": 12},
    {"id": "shallows_shared_leviathan_of_the_deep", "name": "Leviathan of the Deep", "hostile_type": "creature", "role": "damage", "min_spawn_level": 95, "rarity": "superrare", "base_xp": 56000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (14000, 46000),
     "basic_attack": "leviathan maw", "strong_attack": "ocean-splitter dive",
     "player_abilities": ["earth_earth_magic_lv2_quake_field", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 96, "base_dex": 56, "base_con": 84, "base_int": 60, "base_hp": 30000, "base_ap": 82,
     "str_per_level": 16, "dex_per_level": 7, "con_per_level": 14, "int_per_level": 10},
    {"id": "shallows_shared_the_endless_tide", "name": "The Endless Tide", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 68000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (18000, 60000),
     "basic_attack": "endless surge", "strong_attack": "the ocean rises",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_earth_magic_lv2_quake_field", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 100, "base_dex": 60, "base_con": 90, "base_int": 80, "base_hp": 34000, "base_ap": 90,
     "str_per_level": 18, "dex_per_level": 8, "con_per_level": 15, "int_per_level": 13},
]
