# Mountains shared hostiles - rarity-coverage fill, Lv 41-60.
#
# EFFICIENT fill: seeds placed at the union of gap marks from the mountain
# small/mid/large reports for this band:
#   common    -> Lv 41, 46, 51, 56
#   uncommon  -> Lv 43, 48, 53, 58
#   rare      -> Lv 41, 46, 51, 57
#   superrare -> Lv 41, 46, 51, 60
#
# Ability ids reused from loaded band files (known-valid vs PLAYER_ABILITY_SEEDS).

RANDOM_HOSTILE_SEEDS = [

    # ?? common ?????????????????????????????????????????????????????????????
    {"id": "mountain_shared_deepdrift_raider", "name": "Deepdrift Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 41, "rarity": "common", "base_xp": 1000,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (70, 280),
     "basic_attack": "cleaving swing", "strong_attack": "raider onslaught",
     "player_abilities": [],
     "base_str": 30, "base_dex": 22, "base_con": 26, "base_int": 6, "base_hp": 520, "base_ap": 14,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "mountain_shared_crag_troll", "name": "Crag Troll", "hostile_type": "creature", "role": "damage", "min_spawn_level": 46, "rarity": "common", "base_xp": 1150,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (80, 300),
     "basic_attack": "club smash", "strong_attack": "boulder hurl",
     "player_abilities": [],
     "base_str": 34, "base_dex": 18, "base_con": 32, "base_int": 5, "base_hp": 620, "base_ap": 14,
     "str_per_level": 5, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 0},
    {"id": "mountain_shared_summit_marauder", "name": "Summit Marauder", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 51, "rarity": "common", "base_xp": 1350,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (90, 340),
     "basic_attack": "axe chop", "strong_attack": "highland charge",
     "player_abilities": [],
     "base_str": 38, "base_dex": 24, "base_con": 32, "base_int": 6, "base_hp": 700, "base_ap": 15,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 0},
    {"id": "mountain_shared_frostpeak_yeti", "name": "Frostpeak Yeti", "hostile_type": "creature", "role": "damage", "min_spawn_level": 56, "rarity": "common", "base_xp": 1550,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (100, 360),
     "basic_attack": "frozen swipe", "strong_attack": "avalanche pounce",
     "player_abilities": [],
     "base_str": 42, "base_dex": 22, "base_con": 38, "base_int": 6, "base_hp": 800, "base_ap": 15,
     "str_per_level": 6, "dex_per_level": 2, "con_per_level": 5, "int_per_level": 0},

    # ?? uncommon ???????????????????????????????????????????????????????????
    {"id": "mountain_shared_cliff_harrier", "name": "Cliff Harrier", "hostile_type": "creature", "role": "damage", "min_spawn_level": 43, "rarity": "uncommon", "base_xp": 1120,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (78, 300),
     "basic_attack": "diving rake", "strong_attack": "gale dive",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 30, "base_dex": 34, "base_con": 24, "base_int": 8, "base_hp": 560, "base_ap": 15,
     "str_per_level": 4, "dex_per_level": 5, "con_per_level": 3, "int_per_level": 0},
    {"id": "mountain_shared_ironhide_brute", "name": "Ironhide Brute", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 48, "rarity": "uncommon", "base_xp": 1300,
     "common_drop": "herb_med", "rare_drop": "tome_str", "money_range": (86, 320),
     "basic_attack": "iron gauntlet", "strong_attack": "crushing haymaker",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 40, "base_dex": 22, "base_con": 34, "base_int": 7, "base_hp": 700, "base_ap": 15,
     "str_per_level": 5, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 0},
    {"id": "mountain_shared_ashsoot_conjurer", "name": "Ashsoot Conjurer", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 53, "rarity": "uncommon", "base_xp": 1500,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (100, 360),
     "basic_attack": "cinder bolt", "strong_attack": "ashen nova",
     "player_abilities": ["fire_technique_lv1_scorch_slash", "dark_magic_lv1_shadow_tendril"],
     "base_str": 24, "base_dex": 28, "base_con": 28, "base_int": 40, "base_hp": 660, "base_ap": 18,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 6},
    {"id": "mountain_shared_glacier_stalker", "name": "Glacier Stalker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 58, "rarity": "uncommon", "base_xp": 1700,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (110, 380),
     "basic_attack": "frost pounce", "strong_attack": "icy evisceration",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 42, "base_dex": 36, "base_con": 34, "base_int": 8, "base_hp": 820, "base_ap": 16,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 4, "int_per_level": 0},

    # ?? rare ???????????????????????????????????????????????????????????????
    {"id": "mountain_shared_runeforge_golem", "name": "Runeforge Golem", "hostile_type": "construct", "role": "hazard", "min_spawn_level": 41, "rarity": "rare", "base_xp": 1200,
     "common_drop": None, "rare_drop": "tome_con", "money_range": (0, 120),
     "basic_attack": "rune fist", "strong_attack": "seismic stomp",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 38, "base_dex": 14, "base_con": 40, "base_int": 10, "base_hp": 720, "base_ap": 14,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 1},
    {"id": "mountain_shared_bloodpeak_shaman", "name": "Bloodpeak Shaman", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 46, "rarity": "rare", "base_xp": 1380,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (100, 360),
     "basic_attack": "blood hex", "strong_attack": "peak-fury ritual",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "fire_technique_lv1_scorch_slash"],
     "base_str": 28, "base_dex": 26, "base_con": 30, "base_int": 42, "base_hp": 700, "base_ap": 18,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 6},
    {"id": "mountain_shared_stormcrag_drake", "name": "Stormcrag Drake", "hostile_type": "creature", "role": "damage", "min_spawn_level": 51, "rarity": "rare", "base_xp": 1600,
     "common_drop": "herb_med", "rare_drop": "tome_str", "money_range": (130, 460),
     "basic_attack": "wing buffet", "strong_attack": "thunderous divebomb",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 44, "base_dex": 34, "base_con": 38, "base_int": 16, "base_hp": 820, "base_ap": 18,
     "str_per_level": 6, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 1},
    {"id": "mountain_shared_hollow_lich", "name": "Hollow Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 57, "rarity": "rare", "base_xp": 1900,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (150, 520),
     "basic_attack": "soul chill", "strong_attack": "hollowing curse",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 30, "base_dex": 30, "base_con": 34, "base_int": 48, "base_hp": 860, "base_ap": 20,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 7},

    # ?? superrare ??????????????????????????????????????????????????????????
    {"id": "mountain_shared_pyreheart_colossus", "name": "Pyreheart Colossus", "hostile_type": "construct", "role": "damage", "min_spawn_level": 41, "rarity": "superrare", "base_xp": 2100,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (300, 1000),
     "basic_attack": "molten hammer", "strong_attack": "pyreheart eruption",
     "player_abilities": ["fire_technique_lv1_scorch_slash", "earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril"],
     "base_str": 44, "base_dex": 22, "base_con": 44, "base_int": 24, "base_hp": 900, "base_ap": 20,
     "str_per_level": 6, "dex_per_level": 2, "con_per_level": 6, "int_per_level": 3},
    {"id": "mountain_shared_voidmine_devourer", "name": "Voidmine Devourer", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 46, "rarity": "superrare", "base_xp": 2500,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (360, 1200),
     "basic_attack": "void gnaw", "strong_attack": "hunger of the deep",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 40, "base_dex": 32, "base_con": 38, "base_int": 44, "base_hp": 940, "base_ap": 22,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 5, "int_per_level": 7},
    {"id": "mountain_shared_stormbound_titan", "name": "Stormbound Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 51, "rarity": "superrare", "base_xp": 3000,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (420, 1400),
     "basic_attack": "thunder fist", "strong_attack": "tempest descent",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 50, "base_dex": 34, "base_con": 46, "base_int": 30, "base_hp": 1100, "base_ap": 24,
     "str_per_level": 7, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 3},
    {"id": "mountain_shared_abyssal_peak_god", "name": "Abyssal Peak God", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 60, "rarity": "superrare", "base_xp": 3800,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (520, 1700),
     "basic_attack": "abyssal wrath", "strong_attack": "peak-of-madness rend",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 54, "base_dex": 38, "base_con": 48, "base_int": 46, "base_hp": 1250, "base_ap": 26,
     "str_per_level": 7, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 6},
]
