# Mountains shared hostiles - rarity-coverage fill, Lv 61-80.
#
# EFFICIENT fill: seeds placed at the union of gap marks from the mountain
# small/mid/large reports for this band:
#   common    -> Lv 61, 66, 71, 76
#   uncommon  -> Lv 61, 66, 71, 76
#   rare      -> Lv 62, 67, 72, 77
#   superrare -> Lv 61, 67, 72, 77
#
# Ability ids reused from loaded band files (known-valid vs PLAYER_ABILITY_SEEDS).

RANDOM_HOSTILE_SEEDS = [

    # ?? common ?????????????????????????????????????????????????????????????
    {"id": "mountain_shared_ridgeline_reaver", "name": "Ridgeline Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 61, "rarity": "common", "base_xp": 2000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (140, 520),
     "basic_attack": "reaver cleave", "strong_attack": "ridge onslaught",
     "player_abilities": [],
     "base_str": 46, "base_dex": 26, "base_con": 40, "base_int": 8, "base_hp": 900, "base_ap": 16,
     "str_per_level": 7, "dex_per_level": 3, "con_per_level": 5, "int_per_level": 0},
    {"id": "mountain_shared_boulder_ogre", "name": "Boulder Ogre", "hostile_type": "creature", "role": "damage", "min_spawn_level": 66, "rarity": "common", "base_xp": 2300,
     "common_drop": "herb_major", "rare_drop": None, "money_range": (0, 130),
     "basic_attack": "boulder swing", "strong_attack": "quake stomp",
     "player_abilities": [],
     "base_str": 52, "base_dex": 22, "base_con": 48, "base_int": 6, "base_hp": 1050, "base_ap": 16,
     "str_per_level": 8, "dex_per_level": 2, "con_per_level": 6, "int_per_level": 0},
    {"id": "mountain_shared_peakguard_veteran", "name": "Peakguard Veteran", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 71, "rarity": "common", "base_xp": 2700,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (180, 640),
     "basic_attack": "halberd sweep", "strong_attack": "veteran's execution",
     "player_abilities": [],
     "base_str": 56, "base_dex": 30, "base_con": 48, "base_int": 8, "base_hp": 1150, "base_ap": 17,
     "str_per_level": 8, "dex_per_level": 3, "con_per_level": 6, "int_per_level": 0},
    {"id": "mountain_shared_avalanche_brute", "name": "Avalanche Brute", "hostile_type": "creature", "role": "damage", "min_spawn_level": 76, "rarity": "common", "base_xp": 3200,
     "common_drop": "herb_major", "rare_drop": None, "money_range": (0, 140),
     "basic_attack": "crushing slam", "strong_attack": "snowfall barrage",
     "player_abilities": [],
     "base_str": 62, "base_dex": 26, "base_con": 54, "base_int": 8, "base_hp": 1300, "base_ap": 17,
     "str_per_level": 9, "dex_per_level": 3, "con_per_level": 7, "int_per_level": 0},

    # ?? uncommon ???????????????????????????????????????????????????????????
    {"id": "mountain_shared_talon_wyvern", "name": "Talon Wyvern", "hostile_type": "creature", "role": "damage", "min_spawn_level": 61, "rarity": "uncommon", "base_xp": 2200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (160, 560),
     "basic_attack": "talon rake", "strong_attack": "screeching dive",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 46, "base_dex": 42, "base_con": 38, "base_int": 10, "base_hp": 900, "base_ap": 17,
     "str_per_level": 7, "dex_per_level": 5, "con_per_level": 4, "int_per_level": 0},
    {"id": "mountain_shared_emberforge_zealot", "name": "Emberforge Zealot", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 66, "rarity": "uncommon", "base_xp": 2500,
     "common_drop": "herb_major", "rare_drop": "tome_str", "money_range": (180, 620),
     "basic_attack": "molten maul", "strong_attack": "forgefire smite",
     "player_abilities": ["fire_technique_lv1_scorch_slash", "earth_magic_lv1_tremor"],
     "base_str": 52, "base_dex": 28, "base_con": 44, "base_int": 12, "base_hp": 1050, "base_ap": 17,
     "str_per_level": 8, "dex_per_level": 3, "con_per_level": 5, "int_per_level": 1},
    {"id": "mountain_shared_frostfang_alpha", "name": "Frostfang Alpha", "hostile_type": "creature", "role": "damage", "min_spawn_level": 71, "rarity": "uncommon", "base_xp": 2900,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (200, 700),
     "basic_attack": "frost bite", "strong_attack": "pack takedown",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 56, "base_dex": 44, "base_con": 46, "base_int": 10, "base_hp": 1150, "base_ap": 17,
     "str_per_level": 8, "dex_per_level": 5, "con_per_level": 5, "int_per_level": 0},
    {"id": "mountain_shared_gale_shaman", "name": "Gale Shaman", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 76, "rarity": "uncommon", "base_xp": 3300,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (220, 760),
     "basic_attack": "gale bolt", "strong_attack": "cyclone hex",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_magic_lv1_shadow_tendril"],
     "base_str": 34, "base_dex": 40, "base_con": 42, "base_int": 56, "base_hp": 1150, "base_ap": 20,
     "str_per_level": 4, "dex_per_level": 5, "con_per_level": 5, "int_per_level": 9},

    # ?? rare ???????????????????????????????????????????????????????????????
    {"id": "mountain_shared_titanforge_golem", "name": "Titanforge Golem", "hostile_type": "construct", "role": "hazard", "min_spawn_level": 62, "rarity": "rare", "base_xp": 2600,
     "common_drop": None, "rare_drop": "tome_con", "money_range": (0, 160),
     "basic_attack": "titan fist", "strong_attack": "seismic devastation",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 56, "base_dex": 18, "base_con": 58, "base_int": 12, "base_hp": 1300, "base_ap": 16,
     "str_per_level": 8, "dex_per_level": 2, "con_per_level": 7, "int_per_level": 1},
    {"id": "mountain_shared_cinderpeak_wyrm", "name": "Cinderpeak Wyrm", "hostile_type": "creature", "role": "damage", "min_spawn_level": 67, "rarity": "rare", "base_xp": 3000,
     "common_drop": "herb_major", "rare_drop": "tome_str", "money_range": (240, 820),
     "basic_attack": "flame breath", "strong_attack": "molten coil crush",
     "player_abilities": ["fire_technique_lv1_scorch_slash", "earth_magic_lv1_tremor"],
     "base_str": 58, "base_dex": 36, "base_con": 50, "base_int": 20, "base_hp": 1300, "base_ap": 20,
     "str_per_level": 8, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 2},
    {"id": "mountain_shared_wraithpeak_lich", "name": "Wraithpeak Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 72, "rarity": "rare", "base_xp": 3500,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (280, 950),
     "basic_attack": "grave frost", "strong_attack": "summit requiem",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 38, "base_dex": 36, "base_con": 44, "base_int": 60, "base_hp": 1300, "base_ap": 22,
     "str_per_level": 5, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 9},
    {"id": "mountain_shared_stormcaller_archon", "name": "Stormcaller Archon", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 77, "rarity": "rare", "base_xp": 4000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (320, 1100),
     "basic_attack": "storm arc", "strong_attack": "chain tempest",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 44, "base_dex": 44, "base_con": 50, "base_int": 64, "base_hp": 1400, "base_ap": 23,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 6, "int_per_level": 10},

    # ?? superrare ??????????????????????????????????????????????????????????
    {"id": "mountain_shared_worldpeak_leviathan", "name": "Worldpeak Leviathan", "hostile_type": "creature", "role": "damage", "min_spawn_level": 61, "rarity": "superrare", "base_xp": 4400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (620, 2100),
     "basic_attack": "leviathan maw", "strong_attack": "mountain-splitter dive",
     "player_abilities": ["earth_magic_lv1_tremor", "dark_dark_magic_lv2_umbra_storm", "air_skill_lv1_smoke_bomb"],
     "base_str": 58, "base_dex": 40, "base_con": 52, "base_int": 36, "base_hp": 1500, "base_ap": 26,
     "str_per_level": 9, "dex_per_level": 4, "con_per_level": 7, "int_per_level": 4},
    {"id": "mountain_shared_infernal_forgemaster", "name": "Infernal Forgemaster", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 67, "rarity": "superrare", "base_xp": 5200,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (760, 2500),
     "basic_attack": "hellforge hammer", "strong_attack": "molten cataclysm",
     "player_abilities": ["fire_technique_lv1_scorch_slash", "dark_dark_magic_lv2_umbra_storm", "earth_magic_lv1_tremor"],
     "base_str": 62, "base_dex": 40, "base_con": 56, "base_int": 44, "base_hp": 1650, "base_ap": 28,
     "str_per_level": 9, "dex_per_level": 4, "con_per_level": 7, "int_per_level": 5},
    {"id": "mountain_shared_void_summit_horror", "name": "Void Summit Horror", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 72, "rarity": "superrare", "base_xp": 6200,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (900, 3000),
     "basic_attack": "void rend", "strong_attack": "peak-devouring collapse",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 56, "base_dex": 46, "base_con": 54, "base_int": 58, "base_hp": 1750, "base_ap": 28,
     "str_per_level": 8, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 9},
    {"id": "mountain_shared_ascendant_storm_god", "name": "Ascendant Storm God", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 77, "rarity": "superrare", "base_xp": 7400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (1100, 3600),
     "basic_attack": "ascendant gale", "strong_attack": "world-storm descent",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field"],
     "base_str": 66, "base_dex": 48, "base_con": 58, "base_int": 52, "base_hp": 1900, "base_ap": 30,
     "str_per_level": 10, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 6},
]
