# Mountains Small City (Hollerforge Hollow) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "hollow_miner", "name": "Hollow Miner", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 220,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (50, 180),
  "basic_attack": "pickaxe strike", "strong_attack": "miner's fury",
  "player_abilities": [], "base_str": 14, "base_dex": 6, "base_con": 12, "base_int": 2, "base_hp": 300, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 0, "con_per_level": 3, "int_per_level": 0},
 {"id": "forge_shade_sm", "name": "Forge Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 23, "rarity": "uncommon", "base_xp": 280,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (15, 60),
  "basic_attack": "ash touch", "strong_attack": "forge haunt",
  "player_abilities": ["level_1_hostile_ability_night_whisper"],
  "base_str": 3, "base_dex": 8, "base_con": 5, "base_int": 12, "base_hp": 220, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "hollow_forgemaster", "name": "Hollow Forgemaster", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 30, "rarity": "rare", "base_xp": 600,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (200, 700),
  "basic_attack": "forge hammer", "strong_attack": "master's decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 22, "base_dex": 8, "base_con": 20, "base_int": 6, "base_hp": 560, "base_ap": 10,
  "str_per_level": 4, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 1},
 {"id": "stone_construct_hollow", "name": "Stone Construct", "hostile_type": "construct", "role": "damage", "min_spawn_level": 38, "rarity": "uncommon", "base_xp": 700,
  "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 30),
  "basic_attack": "stone fist", "strong_attack": "crush and grind",
  "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
  "base_str": 26, "base_dex": 2, "base_con": 24, "base_int": 4, "base_hp": 800, "base_ap": 6,
  "str_per_level": 5, "dex_per_level": 0, "con_per_level": 5, "int_per_level": 0},
 {"id": "hollow_frost_drake", "name": "Hollow Frost Drake", "hostile_type": "creature", "role": "damage", "min_spawn_level": 50, "rarity": "superrare", "base_xp": 4000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (800, 2800),
  "basic_attack": "frost claw", "strong_attack": "freeze breath",
  "player_abilities": ["ice_magic_lv1_frostbolt", "ice_ice_magic_lv2_glacier_burst"],
  "base_str": 44, "base_dex": 12, "base_con": 40, "base_int": 10, "base_hp": 3000, "base_ap": 12,
  "str_per_level": 9, "dex_per_level": 2, "con_per_level": 8, "int_per_level": 2},
 {"id": "hollerforge_god", "name": "The Hollerforge God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 90000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (30000, 100000),
  "basic_attack": "forge mandate", "strong_attack": "hollow world end",
  "player_abilities": ["earth_earth_earth_magic_lv3_earthshaker", "fire_fire_fire_magic_lv3_inferno_wave"],
  "base_str": 22, "base_dex": 20, "base_con": 24, "base_int": 128, "base_hp": 70000, "base_ap": 108,
  "str_per_level": 4, "dex_per_level": 4, "con_per_level": 4, "int_per_level": 26},
]
