# LEVEL5+ ability seeds
# Extracted from constants_other.py — abilities with level >=5
LEVEL_5_PLAYER_ABILITY_SEEDS = [
 {"id": "dark_magic_lv5_abyssal_shadow", "name": "Abyssal Shadow", "description": "Call upon dark energies.", "ability_type": "magic", "level":5, "elements": ["dark", "air", "fire", "water", "earth"], "base_power":95, "ap_cost":6, "effect": "damage", "can_aoe": False},
 # -- Level5 dedicated light healing/rescue seeds --
 {"id": "light_light_light_light_light_faith_lv5_apotheosis", "name": "Apotheosis", "description": "An overwhelming beam of pure light that fully mends a single ally.", "ability_type": "faith", "level":5, "elements": ["light", "light", "light", "light", "light"], "base_power":180, "ap_cost":10, "effect": "heal", "can_aoe": False},
 {"id": "light_light_light_air_water_faith_lv5_prismatic_cascade", "name": "Prismatic Cascade", "description": "A vast cascade of light, air and water that restores many allies.", "ability_type": "faith", "level":5, "elements": ["light", "light", "light", "air", "water"], "base_power":120, "ap_cost":8, "effect": "heal", "can_aoe": True},
 {"id": "light_light_light_dark_dark_faith_lv5_resurrection_rite", "name": "Resurrection Rite", "description": "A solemn rite that fully restores life to a fallen ally (percentage-based revive).", "ability_type": "faith", "level":5, "elements": ["light", "light", "light", "dark", "dark"], "base_power":100, "ap_cost":10, "effect": "revive", "can_aoe": False},
 {"id": "light_faith_lv5_ardent_inspire", "name": "Ardent Inspire", "description": "Rousing light that sharpens ally blows.", "ability_type": "faith", "level":5, "elements": ["light", "fire", "water", "earth", "air"], "base_power":0, "ap_cost":3, "effect": "status", "status_keys": ["attack_buff"], "can_aoe": True},
 {"id": "light_water_faith_lv5_halo_coat", "name": "Halo Coat", "description": "A soft shining coat that soothes and deflects.", "ability_type": "faith", "level":5, "elements": ["light", "water", "earth", "air", "fire"], "base_power":0, "ap_cost":3, "effect": "status", "status_keys": ["defense_buff"], "can_aoe": True},
 {"id": "water_earth_skill_lv5_sap_overgrowth", "name": "Sap Overgrowth", "description": "A sticky bloom that weakens plating and hide.", "ability_type": "skill", "level":5, "elements": ["water", "earth", "fire", "air", "light"], "base_power":0, "ap_cost":3, "effect": "status", "status_keys": ["defense_debuff"], "can_aoe": True},
 {"id": "water_earth_magic_lv5_tide_shield", "name": "Tide Shield", "description": "Water wards that absorb incoming force.", "ability_type": "magic", "level":5, "elements": ["water", "earth", "air", "fire", "light"], "base_power":0, "ap_cost":3, "effect": "status", "status_keys": ["elemental_defense_buff"], "can_aoe": True},
 {"id": "water_faith_lv5_stream_savant", "name": "Stream Savant", "description": "A flowing clarity of mind drawn from water's patience.", "ability_type": "faith", "level":5, "elements": ["water", "fire", "earth", "air", "light"], "base_power":0, "ap_cost":3, "effect": "status", "status_keys": ["intelligence_buff"], "can_aoe": True},
 {"id": "water_dark_magic_lv5_gloom_Tsunami", "name": "Gloom Tsunami", "description": "A rolling tide of confusion that dulls thought.", "ability_type": "magic", "level":5, "elements": ["water", "dark", "fire", "air", "earth"], "base_power":0, "ap_cost":3, "effect": "status", "status_keys": ["intelligence_debuff"], "can_aoe": True},
 {"id": "earth_dark_skill_lv5_venom_trace", "name": "Venom Trace", "description": "A lingering toxin that deals ongoing harm.", "ability_type": "skill", "level":5, "elements": ["earth", "dark", "fire", "water", "air"], "base_power":28, "ap_cost":3, "effect": "status", "status_keys": ["continuous_damage"], "can_aoe": True},
 {"id": "water_dark_magic_lv5_frostbite_net_dup", "name": "Frostbite Net (dup)", "description": "Icy chains that wrench elemental balance. (duplicate)", "ability_type": "magic", "level":5, "elements": ["water", "dark", "fire", "earth", "air"], "base_power":0, "ap_cost":4, "effect": "status", "status_keys": ["elemental_debuff"], "can_aoe": True},

 {"id": "earth_air_dark_magic_lv5_sand_rot", "name": "Sand Rot", "description": "A gritty curse that weakens elemental cohesion.", "ability_type": "magic", "level":5, "elements": ["earth", "air", "dark", "fire", "water"], "base_power":0, "ap_cost":6, "effect": "status", "status_keys": ["elemental_debuff"], "can_aoe": True},
 {"id": "air_earth_tech_lv5_reinforce_frame", "name": "Reinforce Frame", "description": "Mechanical overclock to harden armor and body.", "ability_type": "tech", "level":5, "elements": ["air", "earth", "fire", "water", "light"], "base_power":0, "ap_cost":5, "effect": "status", "status_keys": ["defense_buff"], "can_aoe": True},
 {"id": "dark_earth_magic_lv5_shadow_erode", "name": "Shadow Erode", "description": "Insidious darkness that reduces resilience.", "ability_type": "magic", "level":5, "elements": ["dark", "earth", "air", "fire", "water"], "base_power":0, "ap_cost":5, "effect": "status", "status_keys": ["defense_debuff"], "can_aoe": True},
 {"id": "light_air_magic_lv5_arcane_focus", "name": "Arcane Focus", "description": "A concentrated arcane snap that heightens mental acuity.", "ability_type": "magic", "level":5, "elements": ["light", "air", "fire", "water", "earth"], "base_power":0, "ap_cost":4, "effect": "status", "status_keys": ["intelligence_buff"], "can_aoe": True},
 {"id": "water_air_magic_lv5_frost_lash", "name": "Frost Lash", "description": "Biting cold that gnaws health over time.", "ability_type": "magic", "level":5, "elements": ["water", "air", "dark", "fire", "earth"], "base_power":72, "ap_cost":5, "effect": "status", "status_keys": ["continuous_damage"], "can_aoe": False},

 # --- Additional level-5+ abilities (added18 entries across ability types) ---
 {"id": "light_magic_lv5_solar_cataclysm", "name": "Solar Cataclysm", "description": "A blinding eruption of solar energy.", "ability_type": "magic", "level":5, "elements": ["light", "fire", "air", "earth", "water"], "base_power":88, "ap_cost":7, "effect": "damage", "can_aoe": False},
 {"id": "light_faith_lv5_echoing_prayer", "name": "Echoing Prayer", "description": "A radiant hymn that bolsters allies' resolve.", "ability_type": "faith", "level":5, "elements": ["light", "water", "light", "air", "earth"], "base_power":0, "ap_cost":5, "effect": "status", "status_keys": ["attack_buff"], "can_aoe": True},
 {"id": "air_tech_lv5_ionic_overload", "name": "Ionic Overload", "description": "Overcharge that arcs between constructs and flesh.", "ability_type": "tech", "level":5, "elements": ["air", "light", "electric", "fire", "dark"], "base_power":70, "ap_cost":6, "effect": "damage", "can_aoe": False},
 {"id": "earth_technique_lv5_seismic_wave", "name": "Seismic Wave", "description": "A concussive wall of earth.", "ability_type": "technique", "level":5, "elements": ["earth", "earth", "air", "dark", "fire"], "base_power":55, "ap_cost":6, "effect": "damage", "can_aoe": False},
 {"id": "water_skill_lv5_riptide_chain", "name": "Riptide Chain", "description": "A linked rip that catches multiple foes.", "ability_type": "skill", "level":5, "elements": ["water", "water", "air", "light", "earth"], "base_power":42, "ap_cost":4, "effect": "damage", "can_aoe": True},
 {"id": "fire_magic_lv5_cinder_shower", "name": "Cinder Shower", "description": "A falling rain of hot embers.", "ability_type": "magic", "level":5, "elements": ["fire", "air", "light", "dark", "earth"], "base_power":48, "ap_cost":5, "effect": "damage", "can_aoe": True},
 {"id": "dark_tech_lv5_spectral_bind", "name": "Spectral Bind", "description": "Ethereal chains that pin foes in place.", "ability_type": "tech", "level":5, "elements": ["dark", "air", "water", "earth", "light"], "base_power":0, "ap_cost":5, "effect": "status", "status_keys": ["defense_debuff"], "can_aoe": True},
 {"id": "light_tech_lv5_prism_barrage", "name": "Prism Barrage", "description": "Concentrated light shards fired in a cone.", "ability_type": "tech", "level":5, "elements": ["light", "light", "air", "fire", "earth"], "base_power":52, "ap_cost":6, "effect": "damage", "can_aoe": False},
 {"id": "tech_lv5_mechanized_salvo", "name": "Mechanized Salvo", "description": "A barrage of mechanized munitions.", "ability_type": "tech", "level":5, "elements": ["air", "earth", "fire", "water", "dark"], "base_power":65, "ap_cost":7, "effect": "damage", "can_aoe": False},
 {"id": "faith_lv5_guardian_oath", "name": "Guardian Oath", "description": "An oath that grants nearby allies temporary fortitude.", "ability_type": "faith", "level":5, "elements": ["light", "earth", "water", "air", "fire"], "base_power":0, "ap_cost":4, "effect": "status", "status_keys": ["defense_buff"], "can_aoe": True},
 {"id": "water_tech_lv5_maelstrom_field", "name": "Maelstrom Field", "description": "A spinning field of pressurized water.", "ability_type": "tech", "level":5, "elements": ["water", "air", "dark", "earth", "light"], "base_power":60, "ap_cost":7, "effect": "damage", "can_aoe": False},
 {"id": "dark_magic_lv5_void_corridor", "name": "Void Corridor", "description": "Open a rift that siphons life through the void.", "ability_type": "magic", "level":5, "elements": ["dark", "dark", "air", "earth", "water"], "base_power":85, "ap_cost":8, "effect": "damage", "can_aoe": False},
 {"id": "air_magic_lv5_gale_cascade", "name": "Gale Cascade", "description": "A cascading wind that tosses foes.", "ability_type": "magic", "level":5, "elements": ["air", "air", "water", "light", "earth"], "base_power":46, "ap_cost":5, "effect": "damage", "can_aoe": True},
 {"id": "fire_skill_lv5_ember_wake", "name": "Ember Wake", "description": "A wake of embers follows your strike.", "ability_type": "skill", "level":5, "elements": ["fire", "earth", "air", "light", "dark"], "base_power":38, "ap_cost":4, "effect": "damage", "can_aoe": True},
 {"id": "light_tech_lv5_luminous_shieldwall", "name": "Luminous Shieldwall", "description": "A wall of light that blocks and reflects.", "ability_type": "tech", "level":5, "elements": ["light", "earth", "air", "water", "fire"], "base_power":0, "ap_cost":5, "effect": "status", "status_keys": ["elemental_defense_buff"], "can_aoe": True},
 {"id": "technique_lv5_ravaging_strike", "name": "Ravaging Strike", "description": "A devastating single-target brutal strike.", "ability_type": "technique", "level":5, "elements": ["earth", "fire", "dark", "air", "light"], "base_power":75, "ap_cost":8, "effect": "damage", "can_aoe": False},
 {"id": "tech_lv5_plasma_spike", "name": "Plasma Spike", "description": "A concentrated plasma impalement.", "ability_type": "tech", "level":5, "elements": ["fire", "light", "air", "earth", "water"], "base_power":54, "ap_cost":6, "effect": "damage", "can_aoe": False},
 {"id": "water_faith_lv5_soothing_tide", "name": "Soothing Tide", "description": "A flowing ward that steadies and protects allies.", "ability_type": "faith", "level":5, "elements": ["water", "light", "earth", "air", "fire"], "base_power":0, "ap_cost":6, "effect": "status", "status_keys": ["defense_buff"], "can_aoe": True},
]
