# Snow shared rarity-fill band Lv 61-80.
# Full multiple-of-5 ladder per rarity (seed at N covers window starts N-4..N).
RANDOM_HOSTILE_SEEDS = [
    # --- common ---
    {"id": "snow_shared_tundra_warlord", "name": "Tundra Warlord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 65, "rarity": "common", "base_xp": 1420,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (64, 280),
     "basic_attack": "greataxe cleave", "strong_attack": "warcry rush",
     "player_abilities": [],
     "base_str": 32, "base_dex": 22, "base_con": 26, "base_int": 7, "base_hp": 640, "base_ap": 16,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},
    {"id": "snow_shared_ice_troll", "name": "Ice Troll", "hostile_type": "creature", "role": "tank", "min_spawn_level": 70, "rarity": "common", "base_xp": 1600,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (70, 300),
     "basic_attack": "boulder throw", "strong_attack": "regenerating slam",
     "player_abilities": [],
     "base_str": 34, "base_dex": 16, "base_con": 34, "base_int": 6, "base_hp": 760, "base_ap": 16,
     "str_per_level": 4, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "snow_shared_frostpeak_reaver", "name": "Frostpeak Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 75, "rarity": "common", "base_xp": 1780,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (74, 320),
     "basic_attack": "twin axe rend", "strong_attack": "berserk flurry",
     "player_abilities": [],
     "base_str": 33, "base_dex": 26, "base_con": 26, "base_int": 7, "base_hp": 680, "base_ap": 17,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "snow_shared_glacier_behemoth", "name": "Glacier Behemoth", "hostile_type": "creature", "role": "tank", "min_spawn_level": 80, "rarity": "common", "base_xp": 2000,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (80, 340),
     "basic_attack": "quaking stomp", "strong_attack": "glacier crush",
     "player_abilities": [],
     "base_str": 38, "base_dex": 16, "base_con": 38, "base_int": 6, "base_hp": 880, "base_ap": 17,
     "str_per_level": 4, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},

    # --- uncommon ---
    {"id": "snow_shared_blizzard_champion", "name": "Blizzard Champion", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 65, "rarity": "uncommon", "base_xp": 1500,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (66, 290),
     "basic_attack": "frostbrand slash", "strong_attack": "storm of blades",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 30, "base_dex": 28, "base_con": 24, "base_int": 9, "base_hp": 620, "base_ap": 16,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "snow_shared_permafrost_juggernaut", "name": "Permafrost Juggernaut", "hostile_type": "creature", "role": "tank", "min_spawn_level": 70, "rarity": "uncommon", "base_xp": 1680,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (72, 310),
     "basic_attack": "crushing charge", "strong_attack": "unstoppable roll",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 36, "base_dex": 18, "base_con": 36, "base_int": 8, "base_hp": 800, "base_ap": 17,
     "str_per_level": 4, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "snow_shared_rimewild_hunter", "name": "Rimewild Hunter", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 75, "rarity": "uncommon", "base_xp": 1860,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (76, 330),
     "basic_attack": "harpoon strike", "strong_attack": "frostbite volley",
     "player_abilities": ["level_1_hostile_ability_poison_dart", "air_skill_lv1_smoke_bomb"],
     "base_str": 30, "base_dex": 32, "base_con": 24, "base_int": 9, "base_hp": 700, "base_ap": 17,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "snow_shared_icecrag_sentinel", "name": "Icecrag Sentinel", "hostile_type": "humanoid", "role": "tank", "min_spawn_level": 80, "rarity": "uncommon", "base_xp": 2080,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (82, 350),
     "basic_attack": "tower shield bash", "strong_attack": "frozen bulwark",
     "player_abilities": ["earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 36, "base_dex": 20, "base_con": 38, "base_int": 9, "base_hp": 840, "base_ap": 17,
     "str_per_level": 4, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},

    # --- rare ---
    {"id": "snow_shared_frost_necromancer", "name": "Frost Necromancer", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 65, "rarity": "rare", "base_xp": 1520,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (66, 295),
     "basic_attack": "chill bolt", "strong_attack": "raise frozen dead",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor"],
     "base_str": 20, "base_dex": 24, "base_con": 26, "base_int": 34, "base_hp": 600, "base_ap": 17,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 5},
    {"id": "snow_shared_glacier_seer", "name": "Glacier Seer", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 70, "rarity": "rare", "base_xp": 1700,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (72, 315),
     "basic_attack": "frozen eye", "strong_attack": "glimpse of the void",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 20, "base_dex": 26, "base_con": 26, "base_int": 36, "base_hp": 620, "base_ap": 17,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 5},
    {"id": "snow_shared_frostbound_archmage", "name": "Frostbound Archmage", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 75, "rarity": "rare", "base_xp": 1880,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (76, 335),
     "basic_attack": "glacial spike", "strong_attack": "cataclysmic frost",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 20, "base_dex": 26, "base_con": 26, "base_int": 38, "base_hp": 640, "base_ap": 18,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 5},
    {"id": "snow_shared_permafrost_dreadlord", "name": "Permafrost Dreadlord", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 80, "rarity": "rare", "base_xp": 2100,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (82, 355),
     "basic_attack": "soulfrost grip", "strong_attack": "frozen dominion",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 24, "base_dex": 26, "base_con": 30, "base_int": 38, "base_hp": 700, "base_ap": 18,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 5},

    # --- superrare ---
    {"id": "snow_shared_boreal_dragon", "name": "Boreal Dragon", "hostile_type": "creature", "role": "damage", "min_spawn_level": 65, "rarity": "superrare", "base_xp": 1900,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (130, 460),
     "basic_attack": "frost breath", "strong_attack": "arctic firestorm",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril"],
     "base_str": 34, "base_dex": 26, "base_con": 30, "base_int": 26, "base_hp": 720, "base_ap": 18,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 3},
    {"id": "snow_shared_frost_titan_lord", "name": "Frost Titan Lord", "hostile_type": "eldritch", "role": "tank", "min_spawn_level": 70, "rarity": "superrare", "base_xp": 2100,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (140, 490),
     "basic_attack": "colossal slam", "strong_attack": "world-ending frost",
     "player_abilities": ["earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril"],
     "base_str": 40, "base_dex": 20, "base_con": 40, "base_int": 24, "base_hp": 900, "base_ap": 18,
     "str_per_level": 4, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 2},
    {"id": "snow_shared_aurora_seraph", "name": "Aurora Seraph", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 75, "rarity": "superrare", "base_xp": 2300,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (150, 520),
     "basic_attack": "radiant frost", "strong_attack": "aurora cataclysm",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 26, "base_dex": 28, "base_con": 30, "base_int": 38, "base_hp": 760, "base_ap": 18,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 4},
    {"id": "snow_shared_eternal_wendigo", "name": "Eternal Wendigo", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 80, "rarity": "superrare", "base_xp": 2560,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (160, 560),
     "basic_attack": "famished rend", "strong_attack": "endless hunger",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 36, "base_dex": 30, "base_con": 32, "base_int": 30, "base_hp": 820, "base_ap": 19,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 3},
]
