# Snow shared rarity-fill band Lv 81-100.
# Full multiple-of-5 ladder per rarity (seed at N covers window starts N-4..N).
RANDOM_HOSTILE_SEEDS = [
    # --- common ---
    {"id": "snow_shared_frost_warbringer", "name": "Frost Warbringer", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 85, "rarity": "common", "base_xp": 2200,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (84, 360),
     "basic_attack": "warmaul crush", "strong_attack": "conqueror's charge",
     "player_abilities": [],
     "base_str": 40, "base_dex": 26, "base_con": 32, "base_int": 8, "base_hp": 820, "base_ap": 18,
     "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},
    {"id": "snow_shared_glacier_tyrant", "name": "Glacier Tyrant", "hostile_type": "creature", "role": "tank", "min_spawn_level": 90, "rarity": "common", "base_xp": 2440,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (90, 380),
     "basic_attack": "mountain slam", "strong_attack": "cataclysm stomp",
     "player_abilities": [],
     "base_str": 44, "base_dex": 18, "base_con": 44, "base_int": 7, "base_hp": 980, "base_ap": 18,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},
    {"id": "snow_shared_permafrost_reaver", "name": "Permafrost Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 95, "rarity": "common", "base_xp": 2680,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (94, 400),
     "basic_attack": "frozen greatsword", "strong_attack": "reaving whirlwind",
     "player_abilities": [],
     "base_str": 42, "base_dex": 30, "base_con": 32, "base_int": 8, "base_hp": 880, "base_ap": 19,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "snow_shared_icecrown_colossus", "name": "Icecrown Colossus", "hostile_type": "creature", "role": "tank", "min_spawn_level": 100, "rarity": "common", "base_xp": 3000,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (100, 420),
     "basic_attack": "world hammer", "strong_attack": "apocalypse quake",
     "player_abilities": [],
     "base_str": 48, "base_dex": 18, "base_con": 48, "base_int": 7, "base_hp": 1100, "base_ap": 19,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},

    # --- uncommon ---
    {"id": "snow_shared_blizzard_overlord", "name": "Blizzard Overlord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 85, "rarity": "uncommon", "base_xp": 2280,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (86, 370),
     "basic_attack": "stormblade cleave", "strong_attack": "eye of the storm",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 38, "base_dex": 34, "base_con": 30, "base_int": 10, "base_hp": 800, "base_ap": 18,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "snow_shared_permafrost_warmaster", "name": "Permafrost Warmaster", "hostile_type": "creature", "role": "tank", "min_spawn_level": 90, "rarity": "uncommon", "base_xp": 2520,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (92, 390),
     "basic_attack": "avalanche charge", "strong_attack": "unbreakable siege",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 44, "base_dex": 22, "base_con": 44, "base_int": 9, "base_hp": 980, "base_ap": 19,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},
    {"id": "snow_shared_rimewild_alpha", "name": "Rimewild Alpha", "hostile_type": "creature", "role": "damage", "min_spawn_level": 95, "rarity": "uncommon", "base_xp": 2760,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (96, 410),
     "basic_attack": "primal maul", "strong_attack": "apex frenzy",
     "player_abilities": ["level_1_hostile_ability_poison_dart", "air_skill_lv1_smoke_bomb"],
     "base_str": 42, "base_dex": 38, "base_con": 32, "base_int": 10, "base_hp": 900, "base_ap": 19,
     "str_per_level": 4, "dex_per_level": 4, "con_per_level": 3, "int_per_level": 0},
    {"id": "snow_shared_glacier_praetorian", "name": "Glacier Praetorian", "hostile_type": "humanoid", "role": "tank", "min_spawn_level": 100, "rarity": "uncommon", "base_xp": 3080,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (100, 430),
     "basic_attack": "aegis smash", "strong_attack": "immortal bastion",
     "player_abilities": ["earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 44, "base_dex": 24, "base_con": 48, "base_int": 10, "base_hp": 1050, "base_ap": 19,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},

    # --- rare ---
    {"id": "snow_shared_frost_lichlord", "name": "Frost Lichlord", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 85, "rarity": "rare", "base_xp": 2320,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (86, 375),
     "basic_attack": "soulfrost bolt", "strong_attack": "legion of the frozen",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor"],
     "base_str": 24, "base_dex": 28, "base_con": 32, "base_int": 42, "base_hp": 760, "base_ap": 19,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 6},
    {"id": "snow_shared_glacier_archon", "name": "Glacier Archon", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 90, "rarity": "rare", "base_xp": 2560,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (92, 395),
     "basic_attack": "prism frost", "strong_attack": "shattering resonance",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 24, "base_dex": 30, "base_con": 32, "base_int": 44, "base_hp": 780, "base_ap": 19,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 6},
    {"id": "snow_shared_permafrost_oracle", "name": "Permafrost Oracle", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 95, "rarity": "rare", "base_xp": 2800,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (96, 415),
     "basic_attack": "frozen prophecy", "strong_attack": "the long winter",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 24, "base_dex": 30, "base_con": 34, "base_int": 46, "base_hp": 820, "base_ap": 20,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 6},
    {"id": "snow_shared_absolute_zero_lich", "name": "Absolute Zero Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 100, "rarity": "rare", "base_xp": 3120,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (100, 435),
     "basic_attack": "entropy frost", "strong_attack": "heat death",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 26, "base_dex": 30, "base_con": 36, "base_int": 48, "base_hp": 880, "base_ap": 20,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 6},

    # --- superrare ---
    {"id": "snow_shared_ancient_frost_wyrm", "name": "Ancient Frost Wyrm", "hostile_type": "creature", "role": "damage", "min_spawn_level": 85, "rarity": "superrare", "base_xp": 2900,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (170, 600),
     "basic_attack": "glacial breath", "strong_attack": "extinction frost",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril"],
     "base_str": 42, "base_dex": 30, "base_con": 36, "base_int": 34, "base_hp": 960, "base_ap": 20,
     "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 3},
    {"id": "snow_shared_god_of_winter", "name": "Herald of Endless Winter", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 90, "rarity": "superrare", "base_xp": 3200,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (185, 640),
     "basic_attack": "primordial frost", "strong_attack": "the frozen end",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 34, "base_dex": 32, "base_con": 38, "base_int": 46, "base_hp": 1000, "base_ap": 20,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 5},
    {"id": "snow_shared_frost_leviathan_prime", "name": "Frost Leviathan Prime", "hostile_type": "eldritch", "role": "tank", "min_spawn_level": 95, "rarity": "superrare", "base_xp": 3500,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (200, 700),
     "basic_attack": "abyssal freeze", "strong_attack": "glacier maw",
     "player_abilities": ["earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 46, "base_dex": 26, "base_con": 46, "base_int": 36, "base_hp": 1150, "base_ap": 21,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 3},
    {"id": "snow_shared_avatar_of_frost", "name": "Avatar of Absolute Frost", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 4000,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (220, 780),
     "basic_attack": "annihilating frost", "strong_attack": "the final winter",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 48, "base_dex": 34, "base_con": 44, "base_int": 44, "base_hp": 1250, "base_ap": 21,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 4},
]
