CITY_BITMAPS = [
    [
    " tt   tt ",
    "tttt tttt",
    "ttttttttt",
    " ttttttt ",
    "  ttttt  ",
    "   ttt   ",
    "    t    ",
    ],
    [
    "   tttttt   ",
    "  tttttttt  ",
    " tttttttttt ",
    " tttttttttt ",
    " tttt tt ttt",
    " tttttttttt ",
    "   tttttt   ",
    ],
    [
    "  tttt  ",
    " tttttt ",
    "ttt tt t",
    "ttt tt t",
    "tttttttt",
    "tt ttt t",
    "t      t",
    ],
    [
    "    tt          tt    ",
    "    tttttt  tttttt    ",
    "  tttttt      tttttt  ",
    " tttttt   tt   tttttt ",
    " ttt      tt      ttt ",
    " tt t    tttt    t tt ",
    " t t t  tttttt  t t t ",
    "  tt tttttttttttt tt  ",
    "    tttttt  tttttt    ",
    ],
    [
    "  tttt  ",
    " tttttt ",
    "ttt  ttt",
    "ttt  ttt",
    " tttttt ",
    "  tttt  ",
    ],
    [
    " ttttt ",
    "t tt tt",
    "t  t  t",
    "ttttttt",
    " ttttt ",
    " t t t ",
    ],
    [
    "ttt       ttt",
    "  tt t t tt  ",
    "   ttttttt   ",
    "    t t t    ",
    ],
    [
    "    t   t    ",
    "     t t  t  ",
    "   t  tt   t ",
    "    tt  t    ",
    " t t t t  t  ",
    "  t  ttttt   ",
    "tt  t t t t t",
    " tt  t t  ttt",
    "  tt t tttt  ",
    "   ttttttt   ",
    "    ttttt    ",
    ],
    [
    "    ttttt    ",
    "   t      t  ",
    "  t   tttt t ",
    " t   ttt  t t",
    "tt  tt tt  tt",
    "tt   tttttt t",
    "tt    ttt   t",
    " tt       ttt",
    "  tttttttttt ",
    "    tttttt   ",
    ]
    ,
    [
    "      tt      ",
    "     t tt     ",
    "     t tt     ",
    "     t tt     ",
    "   ttt ttt tt ",
    " ttt t tt tttt",
    "tttt  t  t ttt",
    " tttttt    ttt",
    "  ttttttttttt ",
    "    tttttttt  ",
    ]
]