"""Zaruun's Lair Dungeon Seed Configuration"""

from typing import Dict, Any

# Tile constants for dungeon rendering and builder decisions
OPEN_AREA_TILE = "░"
IMPASSABLE_TILE = "¤"
IMPASSABLE_CHANCE =0.02

FLOOR_HOSTILES = {
	1: ['sand_serpent', 'dust_whistler', 'antlion', 'oasis_nymph', 'sand_basilisk', 'desert_bandit', 'scorpion_stinger']
}

HOSTILE_SEEDS = [ # all should be level 8 to 10... only araound 10 hostiles total
    # Floor 1 - Zaruun's Lair (commons + uncommons + rares + occasional superrare) - non-undead
	{
		'id': 'sand_serpent',
		'name': 'Sand Serpent',
		'hostile_type': 'creature',
		'min_spawn_level': 18,
		'role': 'damage',
		'rarity': 'common',
		'base_xp': 20,
		'common_drop': 'herb_minor',
		'rare_drop': None,
		'money_range': (2, 12),
		'basic_attack': 'coil bite',
		'strong_attack': 'burrowing crush',
		'player_abilities': ['earth_skill_lv1_soporific_veil'],
		'base_str': 3,
		'base_dex': 5,
		'base_con': 3,
		'base_int': 2,
		'base_hp': 22,
		'base_ap': 3,
		'str_per_level': 1,
		'dex_per_level': 2,
		'con_per_level': 1,
		'int_per_level': 0,
		'resistances': ['earth'],
		'immunities': [],
		'weaknesses': ['water']
	},
	{
		'id': 'dust_whistler',
		'name': 'Dust Whistler',
		'hostile_type': 'humanoid',
		'min_spawn_level': 17,
		'role': 'hazard',
		'rarity': 'common',
		'base_xp': 36,
		'common_drop': 'stimulant_small',
		'rare_drop': 'stimulant_large',
		'money_range': (6, 30),
		'basic_attack': 'whistle jab',
		'strong_attack': 'sonic clap',
		'player_abilities': ['dark_skill_lv1_tranq_dart'],
		'base_str': 3,
		'base_dex': 4,
		'base_con': 3,
		'base_int': 3,
		'base_hp': 34,
		'base_ap': 4,
		'str_per_level': 1,
		'dex_per_level': 1,
		'con_per_level': 1,
		'int_per_level': 1,
		'resistances': [],
		'immunities': [],
		'weaknesses': []
	},
	{
		'id': 'antlion',
		'name': 'Antlion',
		'hostile_type': 'creature',
		'min_spawn_level': 22,
		'role': 'damage',
		'rarity': 'uncommon',
		'base_xp': 60,
		'common_drop': 'herb_med',
		'rare_drop': 'herb_major',
		'money_range': (10, 50),
		'basic_attack': 'mandible snap',
		'strong_attack': 'acid spit',
		'player_abilities': ['dark_skill_lv1_creeping_strike', 'earth_earth_technique_lv2_terra_slam'],
		'base_str': 5,
		'base_dex': 6,
		'base_con': 5,
		'base_int': 1,
		'base_hp': 60,
		'base_ap': 4,
		'str_per_level': 2,
		'dex_per_level': 2,
		'con_per_level': 1,
		'int_per_level': 0,
		'resistances': [],
		'immunities': ['earth'],
		'weaknesses': ['fire']
	},
	{
		'id': 'oasis_nymph',
		'name': 'Oasis Nymph',
		'hostile_type': 'spirit',
		'min_spawn_level': 21,
		'role': 'support',
		'rarity': 'uncommon',
		'base_xp': 120,
		'common_drop': 'herb_minor',
		'rare_drop': 'herb_major',
		'money_range': (20, 90),
		'basic_attack': 'soothing touch',
		'strong_attack': 'mirage bind',
		'player_abilities': ['air_light_faith_lv2_serene_breath', 'earth_faith_lv1_earthen_blessing'],
		'base_str': 4,
		'base_dex': 4,
		'base_con': 6,
		'base_int': 6,
		'base_hp': 140,
		'base_ap': 6,
		'str_per_level': 1,
		'dex_per_level': 1,
		'con_per_level': 2,
		'int_per_level': 2,
		'resistances': [],
		'immunities': ['continuous_damage'],
		'weaknesses': ['fire']
	},
	{
		'id': 'sand_basilisk',
		'name': 'Sand Basilisk',
		'hostile_type': 'creature',
		'min_spawn_level': 22,
		'role': 'damage',
		'rarity': 'rare',
		'base_xp': 200,
		'common_drop': 'herb_minor',
		'rare_drop': 'herb_major',
		'money_range': (30, 120),
		'basic_attack': 'petrifying gaze',
		'strong_attack': 'stone spike',
		'player_abilities': ['earth_dark_skill_lv2_petrify_dart',  'earth_technique_lv1_armor_up'],
		'base_str': 5,
		'base_dex': 7,
		'base_con': 4,
		'base_int': 4,
		'base_hp': 180,
		'base_ap': 5,
		'str_per_level': 1,
		'dex_per_level': 2,
		'con_per_level': 2,
		'int_per_level': 1,
		'resistances': ['earth'],
		'immunities': ['petrify'],
		'weaknesses': ['water']
	},
	{
		'id': 'desert_bandit',
		'name': 'Desert Bandit',
		'hostile_type': 'humanoid',
		'min_spawn_level': 17,
		'role': 'hazard',
		'rarity': 'common',
		'base_xp': 24,
		'common_drop': 'stimulant_small',
		'rare_drop': None,
		'money_range': (4, 16),
		'basic_attack': 'slash',
		'strong_attack': 'brutal strike',
		'player_abilities': [],
		'base_str': 4,
		'base_dex': 5,
		'base_con': 4,
		'base_int': 2,
		'base_hp': 28,
		'base_ap': 3,
		'str_per_level': 1,
		'dex_per_level': 2,
		'con_per_level': 1,
		'int_per_level': 0,
		'resistances': [],
		'immunities': [],
		'weaknesses': []
	},
	{
		'id': 'scorpion_stinger',
		'name': 'Scorpion Stinger',
		'hostile_type': 'creature',
		'min_spawn_level': 19,
		'role': 'damage',
		'rarity': 'uncommon',
		'base_xp': 40,
		'common_drop': 'herb_minor',
		'rare_drop': 'ointment',
		'money_range': (8, 24),
		'basic_attack': 'sting jab',
		'strong_attack': 'venomous strike',
		'player_abilities': ['earth_air_skill_lv2_sandstream'],
		'base_str': 4,
		'base_dex': 6,
		'base_con': 4,
		'base_int': 1,
		'base_hp': 32,
		'base_ap': 3,
		'str_per_level': 1,
		'dex_per_level': 2,
		'con_per_level': 1,
		'int_per_level': 0,
		'resistances': [],
		'immunities': ['continuous_damage'],
		'weaknesses': ['ice']
	},
	{
		'id': 'crystal_sand_dragon',
		'name': 'Crystal Sand Dragon',
		'hostile_type': 'dragon',
		'min_spawn_level': 24,
		'role': 'damage',
		'rarity': 'superrare',
		'base_xp': 300,
		'common_drop': 'herb_major',
		'rare_drop': 'tome_con_superrare',
		'money_range': (50, 200),
		'basic_attack': 'crystal breath',
		'strong_attack': 'shard storm',
		'player_abilities': ['earth_earth_technique_lv2_terra_slam', 'earth_technique_lv1_armor_up'],
		'base_str': 10,
		'base_dex': 8,
		'base_con': 10,
		'base_int': 6,
		'base_hp': 400,
		'base_ap': 6,
		'str_per_level': 3,
		'dex_per_level': 2,
		'con_per_level': 2,
		'int_per_level': 1,
		'resistances': [],
		'immunities': ['earth'],
		'weaknesses': ['water']
	}
]


DUNGEON_NPCS = [ {'id': 'zaruun','location': 'final_chamber'} ]
DUNGEON_ITEMS = [ {'id': 'herb_major', 'location': 'treasure_room'} ]

BOSS_MOB = { 'id': 'zaruun_1', 
			'name': 'Zaruun the Sand-Sunderer',
			'hostiles': [
				'zaruuns_apprentice',
				'zaruuns_apprentice',
				'zaruun_1']
			}

BOSS_HOSTILES = [
	{
		"id": "zaruuns_apprentice", "name": "Zaruuns Apprentice", "hostile_type": "magic", "role": "hazard", "min_spawn_level":23, "rarity": "superrare", 
		"base_xp":480, "common_drop": "herb_major", "rare_drop": "tome_int", "money_range": (45,180),
		"basic_attack": "mirage touch", "strong_attack": "illusive burst", 
		"player_abilities": ["earth_tech_lv1_fault_inhibitor", "earth_air_magic_lv2_sandstream"], 
		"base_str":6, "base_dex":8, "base_con":6, "base_int":14, 
		"base_hp":1320, "base_ap":10, 
		"str_per_level":1, "dex_per_level":2, "con_per_level":1, "int_per_level":3,
		'resistances': [],
		'immunities': ['earth'],
		'weaknesses': ['water']
	},
	{
		"id": "zaruun_1", "name": "Zaruun the Sand-Sunderer", "hostile_type": "magic", "role": "damage", "min_spawn_level":30, "rarity": "notfound", 
		"base_xp":1200, "common_drop": "herb_major", "rare_drop": "tome_int", "money_range": (100,300),
		"basic_attack": "sand shatter", "strong_attack": "desert quake", 
		"player_abilities": ["earth_earth_earth_magic_lv3_earthshaker", "earth_dark_magic_lv2_sinkhole", 'earth_magic_lv1_tremor'], 
		"base_str":10, "base_dex":8, "base_con":12, "base_int":16, 
		"base_hp":2200, "base_ap":12, 
		"str_per_level":2, "dex_per_level":1, "con_per_level":2, "int_per_level":3,
		'resistances': [],
		'immunities': ['earth'],
		'weaknesses': ['water']
	}
]

DUNGEON_SETTINGS: Dict[str, Any] = {
    "dungeon_id": "zaruun_lair",
    "seed": abs(hash("zaruun_lair")),
    "floor_count": 1,
    "room_size_min_max": (61, 80),  # a 9x9 area is 81
    "rooms_per_floor": 12,
    "max_neighbors_per_room": 3,
    "additional_connection_chance": 0.0,
    "min_max_distance_between_rooms": (5,12),
    "min_max_corridor_width": (3,6),
    "display_name": "Zaruun's Lair",
	"open_area_tile": OPEN_AREA_TILE,
	"impassable_tile": IMPASSABLE_TILE,
	"impassable_chance": IMPASSABLE_CHANCE,
	"floor_hostiles": FLOOR_HOSTILES,
	"hostile_seeds": HOSTILE_SEEDS,
    "npcs": DUNGEON_NPCS,
	"items": DUNGEON_ITEMS,
	"boss_mob": BOSS_MOB,
	"boss_hostiles": BOSS_HOSTILES,
    "visible_distance": 8
}