# Mountains Large City (Ironveil Foundry) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "foundry_enforcer", "name": "Foundry Enforcer", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 260,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (60, 200),
  "basic_attack": "iron pipe", "strong_attack": "enforcer beatdown",
  "player_abilities": [], "base_str": 14, "base_dex": 8, "base_con": 12, "base_int": 3, "base_hp": 320, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "forge_wraith", "name": "Forge Wraith", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 340,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (20, 80),
  "basic_attack": "ash touch", "strong_attack": "forge wail",
  "player_abilities": ["level_1_hostile_ability_night_whisper"],
  "base_str": 4, "base_dex": 10, "base_con": 6, "base_int": 14, "base_hp": 280, "base_ap": 14,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "mountain_berserker_lg", "name": "Mountain Berserker", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 26, "rarity": "common", "base_xp": 360,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (100, 340),
  "basic_attack": "pick axe swing", "strong_attack": "mountain fury",
  "player_abilities": [], "base_str": 18, "base_dex": 6, "base_con": 16, "base_int": 2, "base_hp": 440, "base_ap": 8,
  "str_per_level": 4, "dex_per_level": 0, "con_per_level": 3, "int_per_level": 0},
 {"id": "iron_golem_foundry", "name": "Iron Golem", "hostile_type": "construct", "role": "damage", "min_spawn_level": 30, "rarity": "uncommon", "base_xp": 500,
  "common_drop": None, "rare_drop": "kevlar_vest", "money_range": (0, 20),
  "basic_attack": "iron fist", "strong_attack": "forge crush",
  "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
  "base_str": 22, "base_dex": 2, "base_con": 20, "base_int": 4, "base_hp": 640, "base_ap": 6,
  "str_per_level": 5, "dex_per_level": 0, "con_per_level": 4, "int_per_level": 0},
 {"id": "foundry_crime_lord", "name": "Foundry Crime Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 36, "rarity": "rare", "base_xp": 800,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (300, 1000),
  "basic_attack": "lord's hammer", "strong_attack": "iron decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 26, "base_dex": 10, "base_con": 24, "base_int": 8, "base_hp": 720, "base_ap": 10,
  "str_per_level": 5, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 1},
 {"id": "forge_dragon", "name": "Forge Dragon", "hostile_type": "creature", "role": "damage", "min_spawn_level": 46, "rarity": "superrare", "base_xp": 3200,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (600, 2000),
  "basic_attack": "fire claw", "strong_attack": "foundry breath",
  "player_abilities": ["fire_magic_lv1_fireball", "fire_earth_magic_lv2_magma_javelin"],
  "base_str": 40, "base_dex": 12, "base_con": 36, "base_int": 10, "base_hp": 2800, "base_ap": 12,
  "str_per_level": 8, "dex_per_level": 2, "con_per_level": 7, "int_per_level": 2},
 {"id": "foundry_lich", "name": "Foundry Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 60, "rarity": "superrare", "base_xp": 8000,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (2000, 7000),
  "basic_attack": "forge death bolt", "strong_attack": "lich industrial storm",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
  "base_str": 10, "base_dex": 12, "base_con": 12, "base_int": 58, "base_hp": 3000, "base_ap": 48,
  "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 12},
 {"id": "iron_titan", "name": "Iron Titan", "hostile_type": "construct", "role": "damage", "min_spawn_level": 78, "rarity": "superrare", "base_xp": 24000,
  "common_drop": None, "rare_drop": "herb_major", "money_range": (8000, 26000),
  "basic_attack": "iron titan slam", "strong_attack": "foundry annihilation",
  "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
  "base_str": 96, "base_dex": 8, "base_con": 90, "base_int": 10, "base_hp": 30000, "base_ap": 12,
  "str_per_level": 19, "dex_per_level": 1, "con_per_level": 18, "int_per_level": 2},
 {"id": "ironveil_world_god", "name": "The Ironveil World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 120000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (50000, 160000),
  "basic_attack": "world forge decree", "strong_attack": "foundry world end",
  "player_abilities": ["earth_earth_earth_magic_lv3_earthshaker", "fire_fire_fire_magic_lv3_inferno_wave"],
  "base_str": 140, "base_dex": 24, "base_con": 132, "base_int": 28, "base_hp": 100000, "base_ap": 22,
  "str_per_level": 28, "dex_per_level": 4, "con_per_level": 26, "int_per_level": 5},
]
