# Mountains Large City (Ironveil Foundry) — hostile seeds levels 21–30.

RANDOM_HOSTILE_SEEDS = [
 {"id": "foundry_enforcer", "name": "Foundry Enforcer", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 260,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (60, 200),
  "basic_attack": "iron pipe", "strong_attack": "enforcer beatdown",
  "player_abilities": [], "base_str": 14, "base_dex": 8, "base_con": 12, "base_int": 3, "base_hp": 320, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "forge_wraith", "name": "Forge Wraith", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 340,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (20, 80),
  "basic_attack": "ash touch", "strong_attack": "forge wail",
  "player_abilities": ["level_1_hostile_ability_night_whisper"],
  "base_str": 4, "base_dex": 10, "base_con": 6, "base_int": 14, "base_hp": 280, "base_ap": 14,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "mountain_berserker_lg", "name": "Mountain Berserker", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 26, "rarity": "common", "base_xp": 360,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (100, 340),
  "basic_attack": "pick axe swing", "strong_attack": "mountain fury",
  "player_abilities": [], "base_str": 18, "base_dex": 6, "base_con": 16, "base_int": 2, "base_hp": 440, "base_ap": 8,
  "str_per_level": 4, "dex_per_level": 0, "con_per_level": 3, "int_per_level": 0},
 {"id": "iron_golem_foundry", "name": "Iron Golem", "hostile_type": "construct", "role": "damage", "min_spawn_level": 30, "rarity": "uncommon", "base_xp": 500,
  "common_drop": None, "rare_drop": "kevlar_vest", "money_range": (0, 20),
  "basic_attack": "iron fist", "strong_attack": "forge crush",
  "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
  "base_str": 22, "base_dex": 2, "base_con": 20, "base_int": 4, "base_hp": 640, "base_ap": 6,
  "str_per_level": 5, "dex_per_level": 0, "con_per_level": 4, "int_per_level": 0},
]
