# Grassland Small City (Quantford Hollow) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "hollow_thief", "name": "Hollow Thief", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 200,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (40, 150),
  "basic_attack": "pocket knife", "strong_attack": "hollow ambush",
  "player_abilities": [], "base_str": 10, "base_dex": 12, "base_con": 8, "base_int": 3, "base_hp": 240, "base_ap": 10,
  "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
 {"id": "meadow_wraith", "name": "Meadow Wraith", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 280,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (15, 60),
  "basic_attack": "meadow touch", "strong_attack": "prairie wail",
  "player_abilities": ["level_1_hostile_ability_night_whisper"],
  "base_str": 3, "base_dex": 10, "base_con": 5, "base_int": 12, "base_hp": 220, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 3},
 {"id": "hollow_raider", "name": "Hollow Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 26, "rarity": "common", "base_xp": 300,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (70, 240),
  "basic_attack": "raider slash", "strong_attack": "hollow fury",
  "player_abilities": [], "base_str": 14, "base_dex": 10, "base_con": 12, "base_int": 2, "base_hp": 340, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "quant_golem", "name": "Quant Golem", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 32, "rarity": "uncommon", "base_xp": 440,
  "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 20),
  "basic_attack": "earth fist", "strong_attack": "hollow stomp",
  "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
  "base_str": 18, "base_dex": 2, "base_con": 16, "base_int": 4, "base_hp": 480, "base_ap": 6,
  "str_per_level": 4, "dex_per_level": 0, "con_per_level": 3, "int_per_level": 0},
 {"id": "hollow_bandit_lord", "name": "Hollow Bandit Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 42, "rarity": "superrare", "base_xp": 2200,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (400, 1400),
  "basic_attack": "lord's slash", "strong_attack": "bandit decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 30, "base_dex": 16, "base_con": 28, "base_int": 8, "base_hp": 1400, "base_ap": 12,
  "str_per_level": 6, "dex_per_level": 2, "con_per_level": 5, "int_per_level": 1},
 {"id": "prairie_titan_small", "name": "Prairie Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 65, "rarity": "superrare", "base_xp": 12000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (3000, 10000),
  "basic_attack": "titan stomp", "strong_attack": "prairie earthquake",
  "player_abilities": ["earth_magic_lv1_tremor", "earth_earth_magic_lv2_quake_field"],
  "base_str": 70, "base_dex": 8, "base_con": 66, "base_int": 10, "base_hp": 14000, "base_ap": 12,
  "str_per_level": 14, "dex_per_level": 1, "con_per_level": 13, "int_per_level": 2},
 {"id": "hollow_world_god", "name": "The Hollow World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 90000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (30000, 100000),
  "basic_attack": "hollow mandate", "strong_attack": "quantford apocalypse",
  "player_abilities": ["earth_earth_earth_magic_lv3_earthshaker"],
  "base_str": 22, "base_dex": 26, "base_con": 24, "base_int": 128, "base_hp": 70000, "base_ap": 108,
  "str_per_level": 4, "dex_per_level": 5, "con_per_level": 4, "int_per_level": 26},
]
