# Faith abilities for level 4
LEVEL_4_FAITH_ABILITY_SEEDS = [

    #### NON PLAYER ABILITIES
    {"id": "radiant_lie", "name": "Radiant Lie", "description": "A dazzling veil of warmth and acceptance that warps the minds of all who behold it, turning allies against one another while dulling their resolve.", "ability_type": "spirit", "level": 4, "elements": ["light", "light", "dark", "air"], "base_power": 10, "ap_cost": 120, "effect": "status", "status_keys": ["confuse", "attack_debuff", "intelligence_debuff"], "can_aoe": True, "non_player_ability": True},
    {"id": "collapse_of_joy", "name": "Collapse of Joy", "description": "Revelry inverts the frequency of celebration itself — what felt like ecstasy curdles into panic, leaving all caught in its wave confused, disoriented, and drained of the strength to press on.", "ability_type": "spirit", "level": 4, "elements": ["light", "air", "dark", "air"], "base_power": 10, "ap_cost": 115, "effect": "status", "status_keys": ["confuse", "dexterity_debuff", "attack_debuff"], "can_aoe": True, "non_player_ability": True},
    {"id": "endless_tragedy", "name": "Endless Tragedy", "description": "Lament extends grief across the entire battlefield as a smothering field of pure despair — those caught within begin to erode from the inside out, their bodies and spirits failing together.", "ability_type": "spirit", "level": 4, "elements": ["dark", "ice", "dark", "water"], "base_power": 10, "ap_cost": 124, "effect": "status", "status_keys": ["continuous_damage", "constitution_debuff", "defense_debuff"], "can_aoe": True, "non_player_ability": True},
    # stigma — support role: continuous_damage field; identity-devouring aura
    {"id": "the_darkness_consuming", "name": "The Darkness Consuming", "description": "Stigma breathes out a living darkness that hungers for identity — it settles on all nearby and slowly devours whatever sense of self remains, sapping both will and clarity as it feeds.", "ability_type": "spirit", "level": 4, "elements": ["dark", "dark", "air", "light"], "base_power": 10, "ap_cost": 124, "effect": "status", "status_keys": ["continuous_damage", "intelligence_debuff", "attack_debuff"], "can_aoe": True, "non_player_ability": True},
    # pageant — hazard role: social coercion as status weapons
    {"id": "mask_of_expectation", "name": "Mask of Expectation", "description": "Pageant forces a single target to wear the mask of absolute social expectation — the weight of every standard they've failed pins them helplessly in place, silencing their voice and crushing their nerve.", "ability_type": "spirit", "level": 4, "elements": ["light", "air", "light", "dark"], "base_power": 10, "ap_cost": 116, "effect": "status", "status_keys": ["sleep", "silence", "attack_debuff"], "can_aoe": False, "non_player_ability": True},
    {"id": "crushing_reputation", "name": "Crushing Reputation", "description": "The verdict of the audience descends on all — Pageant broadcasts every failure, every flaw, every deviation, until the will to fight is buried under collective judgment and no one can raise their guard.", "ability_type": "spirit", "level": 4, "elements": ["light", "dark", "air", "light"], "base_power": 10, "ap_cost": 120, "effect": "status", "status_keys": ["attack_debuff", "defense_debuff", "dexterity_debuff"], "can_aoe": True, "non_player_ability": True},
    # paradox — hazard: identity-shattering revelations as AoE confuse
    {"id": "infuriating_revelation", "name": "Infuriating Revelation", "description": "Paradox delivers the most maddening truth imaginable: that the rules holding reality together were always arbitrary. The revelation hits every target like a psychic detonation, scattering thought and stilling the tongue.", "ability_type": "spirit", "level": 4, "elements": ["dark", "air", "electric", "light"], "base_power": 10, "ap_cost": 126, "effect": "status", "status_keys": ["confuse", "silence", "intelligence_debuff"], "can_aoe": True, "non_player_ability": True},
    {"id": "they_arent_who_you_are", "name": "They Aren't Who You Are", "description": "Paradox reaches into a target's sense of identity and swaps it with a contradictory self — the victim fights for Paradox's cause, confused about which side they were ever on and no longer able to trust their own instincts.", "ability_type": "spirit", "level": 4, "elements": ["dark", "light", "dark", "air"], "base_power": 17, "ap_cost": 128, "effect": "status", "status_keys": ["confuse", "attack_debuff", "intelligence_debuff"], "can_aoe": False, "non_player_ability": True},
    # cataclysm — damage: relentless constitution drain; entropy made manifest
    {"id": "eternal_nerve", "name": "Eternal Nerve", "description": "Cataclysm does not rage — it endures. An ancient, grinding force settles over all in range, slowly eroding the physical resilience of every living thing until collapse is inevitable, wearing down body and guard alike.", "ability_type": "spirit", "level": 4, "elements": ["dark", "earth", "fire", "dark"], "base_power": 5, "ap_cost": 122, "effect": "status", "status_keys": ["constitution_debuff", "continuous_damage", "defense_debuff"], "can_aoe": True, "non_player_ability": True},
]