# Magic abilities for level 4
LEVEL_4_MAGIC_ABILITY_SEEDS = [

    #### NON PLAYER ABILITIES
    {"id": "beauty_as_weapon", "name": "Beauty as Weapon", "description": "Glamour compresses overwhelming radiance into a focused lance of light and shadow that obliterates a single target.", "ability_type": "magic", "level": 4, "elements": ["light", "air", "dark", "light"], "base_power": 112, "ap_cost": 100, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    {"id": "manic_freedom", "name": "Manic Freedom", "description": "Revelry detonates ecstatic energy outward in every direction — a chaotic storm of air, electricity and fire that scorches all caught in its radius.", "ability_type": "magic", "level": 4, "elements": ["air", "electric", "air", "fire"], "base_power": 105, "ap_cost": 98, "effect": "damage", "can_aoe": True, "non_player_ability": True},
    {"id": "distortion_of_reality", "name": "Distortion of Reality", "description": "Garbage inverts the meaning of existence itself — the target's reality warps and rots around them until only ruin remains.", "ability_type": "magic", "level": 4, "elements": ["dark", "earth", "dark", "ice"], "base_power": 120, "ap_cost": 106, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    {"id": "collapse_of_self", "name": "Collapse of Self", "description": "Identity itself implodes. Lament draws grief to a singular point of impossible density and releases it — a black implosion that annihilates a target from within.", "ability_type": "magic", "level": 4, "elements": ["dark", "dark", "ice", "water"], "base_power": 124, "ap_cost": 110, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # stigma
    {"id": "void_refraction", "name": "Void Refraction", "description": "Stigma bends the light of identity through the void — the target's sense of self is refracted into unreality and consumed in a single, annihilating pulse.", "ability_type": "magic", "level": 4, "elements": ["dark", "air", "light", "dark"], "base_power": 120, "ap_cost": 104, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    {"id": "identity_collapse", "name": "Identity Collapse", "description": "Every mask, every persona, every borrowed self — Stigma detonates them all simultaneously, leaving all caught in the blast unable to remember who they are, how to speak, or how to fight.", "ability_type": "magic", "level": 4, "elements": ["dark", "dark", "light", "air"], "base_power": 0, "ap_cost": 106, "effect": "status", "status_keys": ["confuse", "silence", "attack_debuff"], "can_aoe": True, "non_player_ability": True},
    # edict
    {"id": "inescapable_edict", "name": "Inescapable Edict", "description": "Edict issues a ruling that existence itself must obey — the target is frozen in place by a decree that neither mind nor body can disobey.", "ability_type": "magic", "level": 4, "elements": ["dark", "earth", "dark", "light"], "base_power": 0, "ap_cost": 102, "effect": "status", "status_keys": ["petrify"], "can_aoe": False, "non_player_ability": True},
    # pageant
    {"id": "curtain_call_offensive", "name": "Curtain Call", "description": "Pageant's final performance — a blinding crescendo of light and air that obliterates the audience that dared to stop watching.", "ability_type": "magic", "level": 4, "elements": ["light", "dark", "air", "light"], "base_power": 120, "ap_cost": 104, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # crux — hazard/damage: spawns mutually exclusive realities simultaneously, AoE logic erasure
    {"id": "impossibility_storm", "name": "Impossibility Storm", "description": "Crux floods the field with cascading contradictions — every target is struck by something that cannot exist and cannot be blocked, because blocking it is also impossible.", "ability_type": "magic", "level": 4, "elements": ["dark", "electric", "air", "dark"], "base_power": 115, "ap_cost": 108, "effect": "damage", "can_aoe": True, "non_player_ability": True},
    # paradox — hazard: a burst of impossible inverted fury
    {"id": "demonic_fury", "name": "Demonic Fury", "description": "Paradox collapses two mutually exclusive states of rage into a single annihilating pulse — the very contradiction of its existence tears outward as pure destructive force.", "ability_type": "magic", "level": 4, "elements": ["dark", "fire", "electric", "dark"], "base_power": 122, "ap_cost": 110, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # crux boss — damage role: brutal structural collapse
    {"id": "structural_paradox", "name": "Structural Paradox", "description": "Crux drives a wedge of pure logical contradiction through the target's physical form — matter that simultaneously exists and does not exist tears itself apart.", "ability_type": "magic", "level": 4, "elements": ["dark", "ice", "electric", "dark"], "base_power": 128, "ap_cost": 112, "effect": "damage", "can_aoe": False, "non_player_ability": True},
]