# Skill abilities for level4
LEVEL_4_SKILL_ABILITY_SEEDS = [
 {"id": "fire_air_light_earth_skill_lv4_blazing_feint", "name": "Blazing Feint", "description": "A deceptive strike followed by a flare of heat.", "ability_type": "skill", "level":4, "elements": ["fire","air","light","earth"], "base_power":72, "ap_cost":75, "effect": "damage", "can_aoe": True},
 {"id": "water_air_earth_light_skill_lv4_torrent_step", "name": "Torrent Step", "description": "A fluid movement that eases follow-up attacks.", "ability_type": "skill", "level":4, "elements": ["water","air","earth","light"], "base_power":60, "ap_cost":70, "effect": "damage", "can_aoe": True},
 {"id": "earth_fire_water_air_skill_lv4_quake_stride", "name": "Quake Stride", "description": "A heavy step that destabilizes foes' footing, cracking their guard and slowing their advance.", "ability_type": "skill", "level":4, "elements": ["earth","fire","water","air"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["defense_debuff", "dexterity_debuff", "attack_debuff"], "can_aoe": True},
 {"id": "air_fire_light_water_skill_lv4_gale_dash", "name": "Gale Dash", "description": "A rapid dash that lets you close or evade, sharpening your strikes and quickening your step.", "ability_type": "skill", "level":4, "elements": ["air","fire","light","water"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["attack_buff", "dexterity_buff", "dexterity_buff"], "can_aoe": True},
 {"id": "light_air_earth_fire_skill_lv4_flash_counter", "name": "Flash Counter", "description": "A bright parry that opens targets for strikes.", "ability_type": "skill", "level":4, "elements": ["light","air","earth","fire"], "base_power":48, "ap_cost":72, "effect": "damage", "can_aoe": True},
 {"id": "dark_air_earth_water_skill_lv4_shadow_slip", "name": "Shadow Slip", "description": "A stealthy step that confuses the enemy line, dulling their aim and their footing alike.", "ability_type": "skill", "level":4, "elements": ["dark","air","earth","water"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["attack_debuff", "continuous_damage", "dexterity_debuff"], "can_aoe": True},

 {"id": "fire_water_air_earth_skill_lv4_steam_scroll", "name": "Steam Scroll", "description": "A trick move amid scalding steam to misdirect.", "ability_type": "skill", "level":4, "elements": ["fire","water","air","earth"], "base_power":68, "ap_cost":72, "effect": "damage", "can_aoe": True},
 {"id": "fire_earth_light_dark_skill_lv4_ember_clutch", "name": "Ember Clutch", "description": "A close strike that leaves embers burning.", "ability_type": "skill", "level":4, "elements": ["fire","earth","light","dark"], "base_power":76, "ap_cost":78, "effect": "damage", "can_aoe": True},
 {"id": "fire_air_light_dark_skill_lv4_scorch_waltz", "name": "Scorch Waltz", "description": "A swirling advance that scorches and disorients.", "ability_type": "skill", "level":4, "elements": ["fire","air","light","dark"], "base_power":72, "ap_cost":75, "effect": "damage", "can_aoe": True},
 {"id": "fire_light_air_water_skill_lv4_ember_glint", "name": "Ember Glint", "description": "A quick flourish that dazzles briefly, steeling your offense and quickening your reflexes.", "ability_type": "skill", "level":4, "elements": ["fire","light","air","water"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["attack_buff", "dexterity_buff", "constitution_buff"], "can_aoe": True},
 {"id": "fire_dark_earth_air_skill_lv4_nightflare", "name": "Nightflare", "description": "A sinister strike veiled in smoke and flame.", "ability_type": "skill", "level":4, "elements": ["fire","dark","earth","air"], "base_power":80, "ap_cost":80, "effect": "damage", "can_aoe": True},

 {"id": "water_earth_dark_air_skill_lv4_mudturn", "name": "Mudturn", "description": "A slippery feint leaving foes off-balance, mired and slow to recover their guard.", "ability_type": "skill", "level":4, "elements": ["water","earth","dark","air"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["defense_debuff", "strength_debuff", "dexterity_debuff"], "can_aoe": True},
 {"id": "water_air_light_dark_skill_lv4_raincloak", "name": "Raincloak", "description": "A misty step that hides the next strike, sharpening your aim and hardening your guard behind the veil.", "ability_type": "skill", "level":4, "elements": ["water","air","light","dark"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["attack_buff", "defense_buff", "dexterity_buff"], "can_aoe": True},
 {"id": "water_light_air_earth_skill_lv4_moonlit_rip", "name": "Moonlit Rip", "description": "A delicate strike carried on moonlit spray.", "ability_type": "skill", "level":4, "elements": ["water","light","air","earth"], "base_power":64, "ap_cost":70, "effect": "damage", "can_aoe": True},
 {"id": "water_dark_light_earth_skill_lv4_ebb_slash", "name": "Ebb Slash", "description": "A draining strike that saps clarity.", "ability_type": "skill", "level":4, "elements": ["water","dark","light","earth"], "base_power":60, "ap_cost":70, "effect": "damage", "can_aoe": True},

 {"id": "earth_air_fire_water_skill_lv4_dust_pivot", "name": "Dust Pivot", "description": "A pivoting strike that disrupts footing, blinding the foe with grit and sapping their strength.", "ability_type": "skill", "level":4, "elements": ["earth","air","fire","water"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["attack_debuff", "dexterity_debuff", "constitution_debuff"], "can_aoe": True},
 {"id": "earth_light_air_dark_skill_lv4_seismic_glow", "name": "Seismic Glow", "description": "A glowing stomp that steadies allies, bolstering their guard and their resolve to endure.", "ability_type": "skill", "level":4, "elements": ["earth","light","air","dark"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["defense_buff", "constitution_buff", "attack_buff"], "can_aoe": True},
 {"id": "earth_dark_fire_light_skill_lv4_grave_jab", "name": "Grave Jab", "description": "A corrosive jab that frays resolve.", "ability_type": "skill", "level":4, "elements": ["earth","dark","fire","light"], "base_power":68, "ap_cost":70, "effect": "damage", "can_aoe": True},

 {"id": "air_light_fire_earth_skill_lv4_brisk_beam", "name": "Brisk Beam", "description": "A brisk strike accompanied by a flash.", "ability_type": "skill", "level":4, "elements": ["air","light","fire","earth"], "base_power":56, "ap_cost":70, "effect": "damage", "can_aoe": True},
 {"id": "air_dark_water_light_skill_lv4_void_breeze", "name": "Void Breeze", "description": "A chilling step that unsettles targets, numbing their strikes and slowing their pursuit.", "ability_type": "skill", "level":4, "elements": ["air","dark","water","light"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["attack_debuff", "continuous_damage", "dexterity_debuff"], "can_aoe": True},

 {"id": "light_dark_air_water_skill_lv4_dusk_shimmer", "name": "Dusk Shimmer", "description": "A shimmering feint that blurs intent, clouding the mind and dulling the enemy's aim.", "ability_type": "skill", "level":4, "elements": ["light","dark","air","water"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["intelligence_debuff", "attack_debuff", "dexterity_debuff"], "can_aoe": True},

 {"id": "fire_water_earth_air_skill_lv4_boil_burrow", "name": "Boil Burrow", "description": "A press-and-pull strike of steam and soil.", "ability_type": "skill", "level":4, "elements": ["fire","water","earth","air"], "base_power":76, "ap_cost":78, "effect": "damage", "can_aoe": True},
 {"id": "fire_air_light_earth_skill_lv4_phoenix_step", "name": "Phoenix Step", "description": "A luminous leap that empowers follow-ups, kindling strength, speed, and unshakable footing.", "ability_type": "skill", "level":4, "elements": ["fire","air","light","earth"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["attack_buff", "dexterity_buff", "defense_buff"], "can_aoe": True},
 {"id": "water_earth_air_light_skill_lv4_swirl_trap", "name": "Swirl Trap", "description": "A twining movement that traps and trips, breaking the foe's guard and stalling their steps.", "ability_type": "skill", "level":4, "elements": ["water","earth","air","light"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["defense_debuff", "stun", "dexterity_debuff"], "can_aoe": True},
 {"id": "earth_light_dark_fire_skill_lv4_shadow_plateau", "name": "Shadow Plateau", "description": "A heavy step that weakens mental focus, fraying concentration and dulling the foe's blows.", "ability_type": "skill", "level":4, "elements": ["earth","light","dark","fire"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["intelligence_debuff", "attack_debuff", "defense_debuff"], "can_aoe": True},

 {"id": "air_water_light_earth_skill_lv4_glisten_rip", "name": "Glisten Rip", "description": "A quick strike that leaves lingering brilliance.", "ability_type": "skill", "level":4, "elements": ["air","water","light","earth"], "base_power":64, "ap_cost":70, "effect": "damage", "can_aoe": True},
 {"id": "fire_light_dark_earth_skill_lv4_cinder_shade", "name": "Cinder Shade", "description": "A short flurry that saps and sears.", "ability_type": "skill", "level":4, "elements": ["fire","light","dark","earth"], "base_power":72, "ap_cost":75, "effect": "damage", "can_aoe": True},

 {"id": "fire_water_air_light_skill_lv4_tempest_waltz", "name": "Tempest Waltz", "description": "A complex movement mixing elements in a single flourish.", "ability_type": "skill", "level":4, "elements": ["fire","water","air","light"], "base_power":88, "ap_cost":88, "effect": "damage", "can_aoe": False},
 {"id": "earth_air_water_dark_skill_lv4_mire_blast", "name": "Mire Blast", "description": "A muddy feint ending in a hard strike.", "ability_type": "skill", "level":4, "elements": ["earth","air","water","dark"], "base_power":84, "ap_cost":84, "effect": "damage", "can_aoe": False},

 {"id": "light_air_earth_water_skill_lv4_serene_cadence", "name": "Serene Cadence", "description": "A graceful sequence that steadies allies, fortifying their guard and calming their minds for the fight ahead.", "ability_type": "skill", "level":4, "elements": ["light","air","earth","water"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["defense_buff", "intelligence_buff", "constitution_buff"], "can_aoe": True},
 {"id": "dark_fire_earth_air_skill_lv4_abyssal_stride", "name": "Abyssal Stride", "description": "A harsh, rhythmical assault that unnerves.", "ability_type": "skill", "level":4, "elements": ["dark","fire","earth","air"], "base_power":92, "ap_cost":92, "effect": "damage", "can_aoe": False},

 {"id": "light_dark_fire_water_skill_lv4_twilight_ambush", "name": "Twilight Ambush", "description": "A sudden strike that mixes light and shadow.", "ability_type": "skill", "level":4, "elements": ["light","dark","fire","water"], "base_power":80, "ap_cost":80, "effect": "damage", "can_aoe": True},
 {"id": "air_light_dark_earth_skill_lv4_whispered_tango", "name": "Whispered Tango", "description": "A delicate but disorienting duo-step that opens the foe, unbalancing their guard and slowing their reply.", "ability_type": "skill", "level":4, "elements": ["air","light","dark","earth"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["attack_debuff", "defense_debuff", "dexterity_debuff"], "can_aoe": True},

 {"id": "fire_earth_light_dark_skill_lv4_prismatic_inferno", "name": "Prismatic Inferno", "description": "A prismatic burst layered over searing flame.", "ability_type": "skill", "level":4, "elements": ["fire","earth","light","dark"], "base_power":96, "ap_cost":96, "effect": "damage", "can_aoe": False},
 {"id": "water_air_dark_light_skill_lv4_gloaming_flow", "name": "Gloaming Flow", "description": "A flowing sequence that muddles senses, clouding thought and blunting the enemy's strikes.", "ability_type": "skill", "level":4, "elements": ["water","air","dark","light"], "base_power":0, "ap_cost":80, "effect": "status", "status_keys": ["intelligence_debuff", "attack_debuff", "dexterity_debuff"], "can_aoe": True},

  #### NON PLAYER ABILITIES
  #scalpel
 {"id": "perfect_cut", "name": "Perfect Cut", "description": "An impossibly precise slash that threads through every gap in the target's guard in a single, silent motion.", "ability_type": "skill", "level": 4, "elements": ["air", "ice", "dark", "electric"], "base_power": 96, "ap_cost": 85, "effect": "damage", "can_aoe": False, "non_player_ability": True},
 {"id": "thrill_of_ruin", "name": "Thrill of Ruin", "description": "A predatory burst of speed and force — Rapture pinpoints every weakness and strikes them all in one savage, exhilarating sequence.", "ability_type": "skill", "level": 4, "elements": ["dark", "fire", "air", "electric"], "base_power": 104, "ap_cost": 92, "effect": "damage", "can_aoe": False, "non_player_ability": True},


]
