# Snow Large City (Frostgate Spire) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "spire_frost_guard", "name": "Spire Frost Guard", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 250,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (60, 200),
  "basic_attack": "frost blade", "strong_attack": "spire guard rush",
  "player_abilities": [], "base_str": 14, "base_dex": 8, "base_con": 12, "base_int": 3, "base_hp": 320, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "frost_shade_lg", "name": "Frost Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 320,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (20, 80),
  "basic_attack": "frost touch", "strong_attack": "spire wail",
  "player_abilities": ["ice_magic_lv1_frostbolt"],
  "base_str": 4, "base_dex": 10, "base_con": 6, "base_int": 14, "base_hp": 280, "base_ap": 14,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "frostgate_raider", "name": "Frostgate Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 26, "rarity": "common", "base_xp": 340,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (100, 340),
  "basic_attack": "ice axe", "strong_attack": "tundra fury",
  "player_abilities": [], "base_str": 16, "base_dex": 8, "base_con": 14, "base_int": 2, "base_hp": 400, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
 {"id": "frost_sorcerer_lg", "name": "Frost Sorcerer", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 31, "rarity": "uncommon", "base_xp": 520,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (100, 360),
  "basic_attack": "frost bolt", "strong_attack": "blizzard curse",
  "player_abilities": ["ice_magic_lv1_frostbolt", "ice_ice_magic_lv2_glacier_burst"],
  "base_str": 4, "base_dex": 8, "base_con": 6, "base_int": 22, "base_hp": 320, "base_ap": 20,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 5},
 {"id": "frostgate_crime_lord", "name": "Frostgate Crime Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 38, "rarity": "rare", "base_xp": 900,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (360, 1200),
  "basic_attack": "lord's ice blade", "strong_attack": "frost decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 26, "base_dex": 12, "base_con": 24, "base_int": 8, "base_hp": 780, "base_ap": 10,
  "str_per_level": 5, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 1},
 {"id": "spire_ice_dragon", "name": "Spire Ice Dragon", "hostile_type": "creature", "role": "damage", "min_spawn_level": 50, "rarity": "superrare", "base_xp": 5500,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (1200, 4000),
  "basic_attack": "ice claw", "strong_attack": "absolute zero breath",
  "player_abilities": ["ice_magic_lv1_frostbolt", "ice_ice_magic_lv2_glacier_burst"],
  "base_str": 50, "base_dex": 14, "base_con": 46, "base_int": 12, "base_hp": 4600, "base_ap": 12,
  "str_per_level": 10, "dex_per_level": 2, "con_per_level": 9, "int_per_level": 2},
 {"id": "frost_lich_lg", "name": "Frost Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 65, "rarity": "superrare", "base_xp": 11000,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (3000, 10000),
  "basic_attack": "frost death bolt", "strong_attack": "lich ice storm",
  "player_abilities": ["ice_magic_lv1_frostbolt", "ice_ice_magic_lv2_glacier_burst", "ice_ice_ice_magic_lv3_hailstorm"],
  "base_str": 8, "base_dex": 12, "base_con": 10, "base_int": 62, "base_hp": 3600, "base_ap": 52,
  "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 13},
 {"id": "spire_glacier_titan", "name": "Spire Glacier Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 82, "rarity": "superrare", "base_xp": 28000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (10000, 34000),
  "basic_attack": "glacier titan slam", "strong_attack": "spire annihilation",
  "player_abilities": ["ice_ice_ice_magic_lv3_hailstorm"],
  "base_str": 100, "base_dex": 12, "base_con": 94, "base_int": 14, "base_hp": 34000, "base_ap": 14,
  "str_per_level": 20, "dex_per_level": 2, "con_per_level": 19, "int_per_level": 2},
 {"id": "frostgate_world_god", "name": "The Frostgate World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 120000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (50000, 160000),
  "basic_attack": "world frost decree", "strong_attack": "frostgate world end",
  "player_abilities": ["ice_ice_ice_magic_lv3_hailstorm"],
  "base_str": 140, "base_dex": 24, "base_con": 132, "base_int": 28, "base_hp": 100000, "base_ap": 22,
  "str_per_level": 28, "dex_per_level": 4, "con_per_level": 26, "int_per_level": 5},
]
