# Weapons for levels21-35
WEAPONS_LV21_35 = [
    {
     "id": "glacial_spear",
     "name": "Glacial Spear",
     "description": "A spear of frozen death.",
     "damage": 36,
     "damage_type": "piercing",
     "ap_cost": 3,
     "range": 2,
     "critical_chance": 14.0,
     "value": 3400,
     "min_spawn_level": 30,
     "rarity": "notfound",
     "durability": 140,
     "max_durability": 140,
     "strength": 20,
     "dexterity": 16,
     "intelligence": 22,
     "elements": ["ice"]
    },
    { "id": "sandglass_staff", "name": "Sandglass Staff", "description": "A staff containing a suspended hourglass of living sand. Its spells distort heat, time, and terrain.", "damage": 28, "damage_type": "energy", "ap_cost": 3, "range": 3, "critical_chance": 14.0, "value": 5200, "min_spawn_level": 30, "rarity": "notfound", "durability": 150, "max_durability": 150, "strength": 4, "dexterity": 12, "intelligence": 32, "constitution": 20, "elements": ["earth", "light", "air"] },
    { "id": "wildroot_fangblade", "name": "Wildroot Fangblade", "description": "A curved blade grown from a root touched by darkness, honed into a brutal edge.", "damage": 40, "damage_type": "slashing", "ap_cost": 3, "range": 1, "critical_chance": 14.0, "value": 5200, "min_spawn_level": 30, "rarity": "notfound", "durability": 150, "max_durability": 150, "strength": 30, "dexterity": 12, "intelligence": 2, "constitution": 18, "elements": ["earth", "dark"] },
    { "id": "whisperwind_blades", "name": "Whisperwind Blades", "description": "Twin blades so light they sing through the air, crackling with stolen echoes.", "damage": 34, "damage_type": "slashing", "ap_cost": 2, "range": 1, "critical_chance": 20.0, "value": 5200, "min_spawn_level": 30, "rarity": "notfound", "durability": 140, "max_durability": 140, "strength": 6, "dexterity": 36, "intelligence": 12, "constitution": 10, "elements": ["air", "electric"] },
    { "id": "corebreaker_hammer", "name": "Core‑Breaker Hammer", "description": "A seismic hammer powered by forge‑heat coils and electric drivers.", "damage": 38, "damage_type": "bludgeoning", "ap_cost": 3, "range": 1, "critical_chance": 12.0, "value": 5200, "min_spawn_level": 30, "rarity": "notfound", "durability": 160, "max_durability": 160, "strength": 12, "dexterity": 22, "intelligence": 34, "constitution": 10, "elements": ["earth", "fire", "electric"] },
    { "id": "moontide_staff", "name": "Moon‑Tide Staff", "description": "A staff crowned with a drifting orb of tidal light, shadowed by the deep's whisper.", "damage": 30, "damage_type": "energy", "ap_cost": 3, "range": 3, "critical_chance": 12.0, "value": 5200, "min_spawn_level": 30, "rarity": "notfound", "durability": 150, "max_durability": 150, "strength": 2, "dexterity": 10, "intelligence": 38, "constitution": 18, "elements": ["water", "light", "dark"] },
    { "id": "cursespark_engine_rod", "name": "Cursespark Engine‑Rod", "description": "A humming rod of cursed circuitry, frost‑bitten coils, and swamp‑fire capacitors.", "damage": 36, "damage_type": "energy", "ap_cost": 3, "range": 3, "critical_chance": 14.0, "value": 5200, "min_spawn_level": 30, "rarity": "notfound", "durability": 150, "max_durability": 150, "strength": 4, "dexterity": 22, "intelligence": 36, "constitution": 10, "elements": ["dark", "electric", "ice"] },
    # ── World-drop weapons ────────────────────────────────────────────────────
    # common / technique — lv22
    {
        "id": "iron_shortsword",
        "name": "Iron Shortsword",
        "description": "A single-handed shortsword with a plain crossguard and a grip that has been rewrapped more than once. It has no distinguishing features. It works.",
        "damage": 22,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 14.0,
        "value": 1200,
        "min_spawn_level": 22,
        "rarity": "common",
        "durability": 118,
        "max_durability": 118,
        "strength": 12,
        "dexterity": 8,
        "intelligence": 2,
        "constitution": 6,
        "elements": ["earth"]
    },
    # uncommon / magic — lv28
    {
        "id": "runic_wand",
        "name": "Runic Wand",
        "description": "A short casting wand inscribed with layered runic notation from two separate traditions that probably shouldn't coexist. They do, mostly.",
        "damage": 26,
        "damage_type": "energy",
        "ap_cost": 2,
        "range": 3,
        "critical_chance": 13.0,
        "value": 2800,
        "min_spawn_level": 28,
        "rarity": "uncommon",
        "durability": 130,
        "max_durability": 130,
        "strength": 3,
        "dexterity": 8,
        "intelligence": 30,
        "constitution": 14,
        "elements": ["fire", "air"]
    },
    # rare / spirit — lv33
    {
        "id": "blessed_scepter",
        "name": "Blessed Scepter",
        "description": "A scepter consecrated through a three-day rite that the temple no longer performs. The blessing held. The temple did not.",
        "damage": 32,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 12.0,
        "value": 5200,
        "min_spawn_level": 33,
        "rarity": "rare",
        "durability": 148,
        "max_durability": 148,
        "strength": 4,
        "dexterity": 6,
        "intelligence": 38,
        "constitution": 26,
        "elements": ["light", "water"]
    },
]