# Weapons for levels 36-50
# Covers endgame attainable characters: Lyren Vale (35), Marshal Vek Drast (45), Warden Hale Brimholt (50)
# Extended characters: Veyr Ashcant (40), Regent Sylvara (40), Spark Maddox (40),
#                      Commander Drax (40), Ghost (40), Eldon Dawnseer (40), Voss Caldera (50)
WEAPONS_LV36_50 = [
    # --- Lyren Vale (level 35) — Water/Light/Air Spirit healer ---
    {
        "id": "gentlecurrent_staff",
    "name": "Gentlecurrent Staff",
        "description": "A staff carved from river-smoothed heartwood, crowned with a softly glowing water-light orb. Spells flow from it like a quiet stream.",
        "damage": 34,
        "damage_type": "energy",
  "ap_cost": 3,
        "range": 3,
        "critical_chance": 13.0,
        "value": 7200,
        "min_spawn_level": 35,
        "rarity": "notfound",
        "durability": 160,
        "max_durability": 160,
        "strength": 4,
     "dexterity": 16,
        "intelligence": 42,
        "constitution": 28,
        "elements": ["water", "light", "air"]
    },
    # --- Marshal Vek Drast (level 45) — Fire/Earth Technique STR/CON tank ---
 {
        "id": "dominion_halberd",
        "name": "Dominion Halberd",
        "description": "A heavy war halberd forged under Edict's regime — its blade etched with command sigils and tempered in volcanic heat.",
        "damage": 52,
        "damage_type": "slashing",
        "ap_cost": 3,
        "range": 2,
    "critical_chance": 12.0,
     "value": 11000,
        "min_spawn_level": 45,
    "rarity": "notfound",
        "durability": 190,
     "max_durability": 190,
        "strength": 46,
        "dexterity": 12,
        "intelligence": 16,
        "constitution": 26,
        "elements": ["fire", "earth"]
    },
    # --- Warden Hale Brimholt (level 50) — Water/Light Spirit INT/CON healer-tank ---
    {
        "id": "ledgerbrand_mace",
        "name": "Ledgerbrand Mace",
        "description": "A ceremonial mace whose head is inscribed with an unbroken list of names — every soul the Warden swore to protect.",
   "damage": 58,
        "damage_type": "bludgeoning",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 11.0,
        "value": 13000,
  "min_spawn_level": 50,
        "rarity": "notfound",
      "durability": 200,
        "max_durability": 200,
        "strength": 16,
        "dexterity": 10,
    "intelligence": 52,
     "constitution": 40,
        "elements": ["water", "light"]
    },
    # --- Veyr Ashcant (level 40) — Fire/Dark/Electric caster ---
    {
        "id": "flameheart_staff",
        "name": "Flameheart Staff",
        "description": "A staff whose core is a preserved ember from a fire that has never gone out. Spells cast through it carry a residual emotional charge.",
        "damage": 44,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 15.0,
        "value": 8600,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 170,
        "max_durability": 170,
        "strength": 6,
        "dexterity": 8,
        "intelligence": 70,
        "constitution": 34,
        "elements": ["fire", "dark", "electric"]
    },
    {
        "id": "blazeheart_staff",
        "name": "Blazeheart Staff",
        "description": "A twin-core variant of the Flameheart — two preserved embers wound together, their competing heat creating an unstable surge that Veyr has learned to channel.",
        "damage": 44,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 15.0,
        "value": 8600,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 170,
        "max_durability": 170,
        "strength": 6,
        "dexterity": 8,
        "intelligence": 70,
        "constitution": 34,
        "elements": ["fire", "dark", "electric"]
    },
    # --- Regent Sylvara (level 40) — Dark/Electric/Air caster ---
    {
        "id": "regency_rod",
        "name": "Regency Rod",
        "description": "A slender obsidian rod tipped with a compressed storm-crystal. It looks decorative. It is not.",
        "damage": 44,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 15.0,
        "value": 8600,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 170,
        "max_durability": 170,
        "strength": 4,
        "dexterity": 6,
        "intelligence": 72,
        "constitution": 30,
        "elements": ["dark", "electric", "air"]
    },
    {
        "id": "scepter_of_dominion",
        "name": "Scepter of Dominion",
        "description": "A ceremonial scepter whose grip is wrapped in compressed void-thread. It was never meant to be carried openly — Sylvara carries it openly.",
        "damage": 44,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 15.0,
        "value": 8600,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 170,
        "max_durability": 170,
        "strength": 4,
        "dexterity": 6,
        "intelligence": 72,
        "constitution": 30,
        "elements": ["dark", "electric", "air"]
    },
    # --- Spark Maddox (level 40) — Electric/Air agile ---
    {
        "id": "voltage_wrench",
        "name": "Voltage Wrench",
        "description": "An oversized wrench rebuilt with conductive plating and a charge accumulator in the handle. It was originally a repair tool. Maddox improved it.",
        "damage": 44,
        "damage_type": "bludgeoning",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 17.0,
        "value": 8400,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 180,
        "max_durability": 180,
        "strength": 10,
        "dexterity": 66,
        "intelligence": 34,
        "constitution": 8,
        "elements": ["electric", "air"]
    },
    {
        "id": "shockdart_launcher",
        "name": "Shockdart Launcher",
        "description": "A wrist-mounted launcher Maddox built from salvage — fires compressed-charge darts at range. He lost the safety toggle on the third iteration. He doesn't miss it.",
        "damage": 44,
        "damage_type": "energy",
        "ap_cost": 2,
        "range": 4,
        "critical_chance": 17.0,
        "value": 8400,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 180,
        "max_durability": 180,
        "strength": 10,
        "dexterity": 66,
        "intelligence": 34,
        "constitution": 8,
        "elements": ["electric", "air"]
    },
    # --- Commander Drax (level 40) — Earth/Light/Electric/Ice brawler ---
    {
        "id": "command_greataxe",
        "name": "Command Greataxe",
        "description": "A two-handed greataxe forged in a forward operating base under active siege. The haft is wrapped in field-stripped uniform cord — his soldiers', not his own.",
        "damage": 46,
        "damage_type": "slashing",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 11.0,
        "value": 8800,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 185,
        "max_durability": 185,
        "strength": 76,
        "dexterity": 4,
        "intelligence": 6,
        "constitution": 36,
        "elements": ["earth", "light", "electric"]
    },
    {
        "id": "wardens_claymore",
        "name": "Warden's Claymore",
        "description": "A claymore bearing the warden crest — commissioned for Drax when he was promoted. He's outgrown the rank the sword represents. He still carries it.",
        "damage": 46,
        "damage_type": "slashing",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 11.0,
        "value": 8800,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 185,
        "max_durability": 185,
        "strength": 76,
        "dexterity": 4,
        "intelligence": 6,
        "constitution": 36,
        "elements": ["earth", "light", "electric"]
    },
    # --- Ghost (level 40) — Dark/Air/Electric balanced ---
    {
        "id": "phantom_blade",
        "name": "Phantom Blade",
        "description": "A blade treated with shadow-dampening oil so it produces no reflection, no glint, and no sound. You only know it was there after.",
        "damage": 44,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 14.0,
        "value": 8600,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 175,
        "max_durability": 175,
        "strength": 56,
        "dexterity": 40,
        "intelligence": 14,
        "constitution": 14,
        "elements": ["dark", "air", "electric"]
    },
    {
        "id": "phantom_edge",
        "name": "Phantom Edge",
        "description": "A single-edge variant of the Phantom Blade — thinner profile, silent draw. Ghost had the spine shaved down. Nobody else can hold it at the right angle.",
        "damage": 44,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 14.0,
        "value": 8600,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 175,
        "max_durability": 175,
        "strength": 56,
        "dexterity": 40,
        "intelligence": 14,
        "constitution": 14,
        "elements": ["dark", "air", "electric"]
    },
    # --- Eldon Dawnseer (level 40) — Light/Dark/Earth caster ---
    {
        "id": "omen_staff",
        "name": "Omen Staff",
        "description": "A gnarled staff grown from a tree struck by lightning at the exact moment of a fracture event. Every vision Eldon has had since has passed through it first.",
        "damage": 44,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 15.0,
        "value": 8600,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 170,
        "max_durability": 170,
        "strength": 4,
        "dexterity": 8,
        "intelligence": 70,
        "constitution": 32,
        "elements": ["light", "dark", "earth"]
    },
    {
        "id": "seer_focus_wand",
        "name": "Seer's Focus Wand",
        "description": "A short wand carved from vision-bone — a material that softens at the moment of prophecy and hardens again when the vision resolves. Eldon keeps it in constant contact with her palm.",
        "damage": 44,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 15.0,
        "value": 8600,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 170,
        "max_durability": 170,
        "strength": 4,
        "dexterity": 8,
        "intelligence": 70,
        "constitution": 32,
        "elements": ["light", "dark", "earth"]
    },
    # --- Voss Caldera (level 50) — Light/Fire/Electric brawler ---
    {
        "id": "takeover_blade",
        "name": "Takeover Blade",
        "description": "A custom-commissioned longsword engraved with a non-compete clause on one side and a severance notice on the other. Both are legally binding.",
        "damage": 60,
        "damage_type": "slashing",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 11.0,
        "value": 13200,
        "min_spawn_level": 50,
        "rarity": "notfound",
        "durability": 200,
        "max_durability": 200,
        "strength": 94,
        "dexterity": 4,
        "intelligence": 8,
        "constitution": 44,
        "elements": ["light", "fire", "electric"]
    },
    {
        "id": "leverage_maul",
        "name": "Leverage Maul",
        "description": "A heavy maul commissioned from the same foundry that cast Voss's first corporate seal. Its head is shaped like a gavel. This was intentional.",
        "damage": 60,
        "damage_type": "bludgeoning",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 10.0,
        "value": 13200,
        "min_spawn_level": 50,
        "rarity": "notfound",
        "durability": 200,
        "max_durability": 200,
        "strength": 94,
        "dexterity": 4,
        "intelligence": 8,
        "constitution": 44,
        "elements": ["light", "fire", "electric"]
    },
    # ── Mythic Chain Weapons (D-chain rewards) ──────────────────────────────
    {
        "id": "mythic_desert_large_dune_resonance_blade",
        "name": "Dune Resonance Blade",
        "description": "A blade forged from compressed dune-glass at the exact frequency the desert resonates after a rift event. It hums in a dry wind and sings in a storm.",
        "damage": 62,
        "damage_type": "slashing",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 14.0,
        "value": 28000,
        "min_spawn_level": 40,
        "rarity": "notfound",
        "durability": 200,
        "max_durability": 200,
        "strength": 40,
        "dexterity": 30,
        "intelligence": 20,
        "constitution": 22,
        "elements": ["earth", "fire"]
    },
    {
        "id": "mythic_desert_small_scrapwrights_edge",
        "name": "Scrapwright's Edge",
        "description": "A blade assembled entirely from salvage — no original parts remain from its first forging. The balance is perfect despite having no reason to be.",
        "damage": 56,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 16.0,
        "value": 22000,
        "min_spawn_level": 36,
        "rarity": "notfound",
        "durability": 195,
        "max_durability": 195,
        "strength": 30,
        "dexterity": 40,
        "intelligence": 16,
        "constitution": 18,
        "elements": ["earth", "air"]
    },
    {
        "id": "mythic_shallows_large_tidecleaver",
        "name": "Tidecleaver",
        "description": "A heavy cleaver forged from tidal-iron harvested at low tide during a rift surge. It carries the weight of every wave that shaped the coast it came from.",
        "damage": 60,
        "damage_type": "slashing",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 12.0,
        "value": 25000,
        "min_spawn_level": 38,
        "rarity": "notfound",
        "durability": 198,
        "max_durability": 198,
        "strength": 44,
        "dexterity": 20,
        "intelligence": 18,
        "constitution": 26,
        "elements": ["water", "earth"]
    },
    {
        "id": "mythic_shallows_small_tidecaller_edge",
        "name": "Tidecaller's Edge",
        "description": "A narrow blade etched with tidekin calling-script — worn smooth by the tides and still perfectly sharp.",
        "damage": 54,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 15.0,
        "value": 20000,
        "min_spawn_level": 36,
        "rarity": "notfound",
        "durability": 192,
        "max_durability": 192,
        "strength": 28,
        "dexterity": 38,
        "intelligence": 20,
        "constitution": 16,
        "elements": ["water", "air"]
    },
    {
        "id": "mythic_swamp_large_bonedrown_reliquary",
        "name": "Bonedrown Reliquary",
        "description": "A mace-reliquary fused from bone and swamp-iron — each sealed compartment in the head holds something the Necropolis refused to let go of.",
        "damage": 58,
        "damage_type": "bludgeoning",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 11.0,
        "value": 24000,
        "min_spawn_level": 38,
        "rarity": "notfound",
        "durability": 196,
        "max_durability": 196,
        "strength": 40,
        "dexterity": 14,
        "intelligence": 28,
        "constitution": 26,
        "elements": ["dark", "earth"]
    },
    {
        "id": "mythic_swamp_small_rotfen_dredge_blade",
        "name": "Rotfen Dredge Blade",
        "description": "A broad dredging blade recovered from the swamp floor — its edge was honed by decades of sediment and whatever else the bayou buried down there.",
        "damage": 54,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 13.0,
        "value": 20000,
        "min_spawn_level": 36,
        "rarity": "notfound",
        "durability": 192,
        "max_durability": 192,
        "strength": 34,
        "dexterity": 24,
        "intelligence": 20,
        "constitution": 20,
        "elements": ["dark", "water"]
    },
    {
        "id": "mythic_mountains_small_dominion_edge",
        "name": "Dominion Edge",
        "description": "A blade forged from the ore of a collapsed mine shaft — every vein in its metal is a record of what was taken from the mountain and never returned.",
        "damage": 58,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 14.0,
        "value": 22000,
        "min_spawn_level": 38,
        "rarity": "notfound",
        "durability": 196,
        "max_durability": 196,
        "strength": 36,
        "dexterity": 28,
        "intelligence": 18,
        "constitution": 22,
        "elements": ["earth", "fire"]
    },
    # ── World-drop weapons ────────────────────────────────────────────────────
    # common / skill — lv37
    {
        "id": "fieldwork_blade",
        "name": "Fieldwork Blade",
        "description": "A standard-issue work blade carried by regional surveyors and scouts. Its edge is maintained to a serviceable standard by people who rely on it daily.",
        "damage": 40,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 13.0,
        "value": 2600,
        "min_spawn_level": 37,
        "rarity": "common",
        "durability": 160,
        "max_durability": 160,
        "strength": 20,
        "dexterity": 20,
        "intelligence": 10,
        "constitution": 14,
        "elements": ["earth"]
    },
    # uncommon / tech — lv43
    {
        "id": "arc_pistol",
        "name": "Arc Pistol",
        "description": "A compact sidearm built around a compressed charge cell. The trigger pull is lighter than regulation. The previous owner filed it down — an improvement, generally.",
        "damage": 46,
        "damage_type": "energy",
        "ap_cost": 2,
        "range": 4,
        "critical_chance": 16.0,
        "value": 4800,
        "min_spawn_level": 43,
        "rarity": "uncommon",
        "durability": 168,
        "max_durability": 168,
        "strength": 6,
        "dexterity": 50,
        "intelligence": 28,
        "constitution": 6,
        "elements": ["electric", "air"]
    },
    # superrare / technique — lv49
    {
        "id": "bloodbound_cleaver",
        "name": "Bloodbound Cleaver",
        "description": "A cleaver forged with a temper that responds to sustained combat — the edge sharpens with continued use, which is a problem for anyone standing opposite it.",
        "damage": 62,
        "damage_type": "slashing",
        "ap_cost": 3,
        "range": 1,
        "critical_chance": 13.0,
        "value": 12400,
        "min_spawn_level": 49,
        "rarity": "superrare",
        "durability": 202,
        "max_durability": 202,
        "strength": 88,
        "dexterity": 18,
        "intelligence": 6,
        "constitution": 42,
        "elements": ["fire", "dark"]
    },
]
