# Weapons for levels 51-65
# Covers endgame attainable character: Seraphine Dawnwell (level 60) — Ice/Air/Light Magic INT/DEX
# Extended characters: Dare (55), Rynn (60), Anita (65)
WEAPONS_LV51_65 = [
    # --- Seraphine Dawnwell (level 60) ---
    {
        "id": "aurora_staff",
        "name": "Aurora Staff",
    "description": "A crystalline staff that refracts light into shifting auroras. Each spell cast through it warps time slightly around the target.",
        "damage": 72,
   "damage_type": "energy",
        "ap_cost": 3,
   "range": 4,
        "critical_chance": 18.0,
    "value": 22000,
        "min_spawn_level": 60,
        "rarity": "notfound",
     "durability": 210,
        "max_durability": 210,
        "strength": 6,
      "dexterity": 30,
      "intelligence": 74,
   "constitution": 20,
        "elements": ["light", "ice", "air"]
    },
    # --- Dare (level 55) — Water/Air/Fire agile ---
    {
        "id": "hurricane_blade",
        "name": "Hurricane Blade",
        "description": "A curved short-sword weighted for one-handed throws and regrips. The edge is seasoned with brine corrosion — it holds a better bite than a standard grind.",
        "damage": 65,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 18.0,
        "value": 17200,
        "min_spawn_level": 55,
        "rarity": "notfound",
        "durability": 215,
        "max_durability": 215,
        "strength": 50,
        "dexterity": 96,
        "intelligence": 8,
        "constitution": 8,
        "elements": ["water", "air", "fire"]
    },
    {
        "id": "tiderunner_blades",
        "name": "Tiderunner Blades",
        "description": "A matched pair of short blades balanced for dual-wield at speed. The off-hand blade is weighted heavier — Dare claims it evens out the spin. He is correct.",
        "damage": 65,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 18.0,
        "value": 17200,
        "min_spawn_level": 55,
        "rarity": "notfound",
        "durability": 215,
        "max_durability": 215,
        "strength": 50,
        "dexterity": 96,
        "intelligence": 8,
        "constitution": 8,
        "elements": ["water", "air", "fire"]
    },
    # --- Rynn (level 60) — Light/Water/Earth/Air caster ---
    {
        "id": "mending_staff",
        "name": "Mending Staff",
        "description": "A staff grown from a single branch of a living tree that has never stopped healing itself. Rynn keeps it wrapped in bandages between use — old habit.",
        "damage": 72,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 15.0,
        "value": 22000,
        "min_spawn_level": 60,
        "rarity": "notfound",
        "durability": 210,
        "max_durability": 210,
        "strength": 6,
        "dexterity": 10,
        "intelligence": 100,
        "constitution": 54,
        "elements": ["light", "water", "earth", "air"]
    },
    {
        "id": "mending_scepter",
        "name": "Mending Scepter",
        "description": "A shorter scepter variant of the Mending Staff — easier to manage in tight field conditions. The head is shaped to double as a splinting post. Rynn has used it that way.",
        "damage": 72,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 15.0,
        "value": 22000,
        "min_spawn_level": 60,
        "rarity": "notfound",
        "durability": 210,
        "max_durability": 210,
        "strength": 6,
        "dexterity": 10,
        "intelligence": 100,
        "constitution": 54,
        "elements": ["light", "water", "earth", "air"]
    },
    # --- Anita (level 65) — Dark/Light/Earth balanced ---
    {
        "id": "cryptseal_blade",
        "name": "Cryptseal Blade",
        "description": "A short broad-blade etched with classified registry marks — some of them hers, most of them not. Each mark is a file she never returned.",
        "damage": 80,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 14.0,
        "value": 26400,
        "min_spawn_level": 65,
        "rarity": "notfound",
        "durability": 225,
        "max_durability": 225,
        "strength": 60,
        "dexterity": 30,
        "intelligence": 60,
        "constitution": 50,
        "elements": ["dark", "light", "earth"]
    },
    {
        "id": "codex_blade",
        "name": "Codex Blade",
        "description": "A blade etched with the index of Anita's personal codex — a document that no longer exists anywhere else. The blade is the only copy.",
        "damage": 80,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 14.0,
        "value": 26400,
        "min_spawn_level": 65,
        "rarity": "notfound",
        "durability": 225,
        "max_durability": 225,
        "strength": 60,
        "dexterity": 30,
        "intelligence": 60,
        "constitution": 50,
        "elements": ["dark", "light", "earth"]
    },
    # ── World-drop weapons ────────────────────────────────────────────────────
    # common / technique — lv52
    {
        "id": "worn_longsword",
        "name": "Worn Longsword",
        "description": "A longsword with a blade that has been re-ground so many times the profile has shifted. It still cuts true. Someone sharpened it for a living.",
        "damage": 60,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 14.0,
        "value": 5800,
        "min_spawn_level": 52,
        "rarity": "common",
        "durability": 196,
        "max_durability": 196,
        "strength": 46,
        "dexterity": 20,
        "intelligence": 4,
        "constitution": 14,
        "elements": ["earth"]
    },
    # uncommon / faith — lv58
    {
        "id": "restoration_crook",
        "name": "Restoration Crook",
        "description": "A shepherd's crook repurposed as a faith-casting focus — a common enough conversion in the lower regions. The original owner's initials are still carved into the base.",
        "damage": 66,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 12.0,
        "value": 9200,
        "min_spawn_level": 58,
        "rarity": "uncommon",
        "durability": 204,
        "max_durability": 204,
        "strength": 4,
        "dexterity": 8,
        "intelligence": 76,
        "constitution": 44,
        "elements": ["light", "water"]
    },
    # rare / magic — lv63
    {
        "id": "convergence_rod",
        "name": "Convergence Rod",
        "description": "A casting rod engineered at the intersection of three elemental disciplines. The theory behind it is sound. The instability is a feature, according to the original design notes.",
        "damage": 76,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 18400,
        "min_spawn_level": 63,
        "rarity": "rare",
        "durability": 218,
        "max_durability": 218,
        "strength": 4,
        "dexterity": 14,
        "intelligence": 90,
        "constitution": 28,
        "elements": ["ice", "electric", "dark"]
    },
]
