# Weapons for levels 66-80
# Extended characters: Andrea Starveil (70), Talon (80)
WEAPONS_LV66_80 = [
    # --- Andrea Starveil (level 70) — Fire/Air/Water agile ---
    {
        "id": "morale_blade",
        "name": "Morale Blade",
        "description": "A single-edged performance saber engraved with the names of every person she's kept moving forward. Both sides. Different lists.",
        "damage": 90,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 19.0,
        "value": 32400,
        "min_spawn_level": 70,
        "rarity": "notfound",
        "durability": 235,
        "max_durability": 235,
        "strength": 60,
        "dexterity": 120,
        "intelligence": 10,
        "constitution": 8,
        "elements": ["fire", "air", "water"]
    },
    {
        "id": "encore_blades",
        "name": "Encore Blades",
        "description": "A matched pair of performance sabers Andrea had commissioned after her first successful tour — one for the show, one for what comes after. She stopped distinguishing between them.",
        "damage": 90,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 19.0,
        "value": 32400,
        "min_spawn_level": 70,
        "rarity": "notfound",
        "durability": 235,
        "max_durability": 235,
        "strength": 60,
        "dexterity": 120,
        "intelligence": 10,
        "constitution": 8,
        "elements": ["fire", "air", "water"]
    },
    # --- Talon (level 80) — Light/Water/Earth/Air caster ---
    {
        "id": "mercy_staff",
        "name": "Mercy Staff",
        "description": "A staff carved from a fallen healer's tree — species unknown, never catalogued. It blooms with pale flowers when near the dying. Talon has stopped being surprised by it.",
        "damage": 106,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 15.0,
        "value": 46400,
        "min_spawn_level": 80,
        "rarity": "notfound",
        "durability": 255,
        "max_durability": 255,
        "strength": 6,
        "dexterity": 12,
        "intelligence": 136,
        "constitution": 74,
        "elements": ["light", "water", "earth", "air"]
    },
    {
        "id": "kindness_staff",
        "name": "Kindness Staff",
        "description": "A staff Talon refuses to have repaired by anyone else — she re-wraps the grip herself at the start of every season. The wood has absorbed so much healing energy it glows faintly on overcast days.",
        "damage": 106,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 15.0,
        "value": 46400,
        "min_spawn_level": 80,
        "rarity": "notfound",
        "durability": 255,
        "max_durability": 255,
        "strength": 6,
        "dexterity": 12,
        "intelligence": 136,
        "constitution": 74,
        "elements": ["light", "water", "earth", "air"]
    },
    # ── World-drop weapons ────────────────────────────────────────────────────
    # uncommon / skill — lv67
    {
        "id": "balanced_rapier",
        "name": "Balanced Rapier",
        "description": "A dueling rapier with a counterweighted hilt — the balance point is exactly where the maker intended it, which is to say better than most people can hold.",
        "damage": 84,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 16.0,
        "value": 16400,
        "min_spawn_level": 67,
        "rarity": "uncommon",
        "durability": 228,
        "max_durability": 228,
        "strength": 44,
        "dexterity": 44,
        "intelligence": 20,
        "constitution": 16,
        "elements": ["air"]
    },
    # rare / tech — lv73
    {
        "id": "pulse_emitter",
        "name": "Pulse Emitter",
        "description": "A long-barreled emitter that fires focused charge pulses at range. The cooling fins were added after the second prototype. Both prior versions still function.",
        "damage": 98,
        "damage_type": "energy",
        "ap_cost": 2,
        "range": 4,
        "critical_chance": 17.0,
        "value": 30400,
        "min_spawn_level": 73,
        "rarity": "rare",
        "durability": 242,
        "max_durability": 242,
        "strength": 8,
        "dexterity": 90,
        "intelligence": 60,
        "constitution": 12,
        "elements": ["electric", "ice"]
    },
    # superrare / faith — lv79
    {
        "id": "covenant_staff",
        "name": "Covenant Staff",
        "description": "A staff that carries the binding weight of a promise made between entities that no longer exist. Whatever they agreed to, it still holds — and so does the staff.",
        "damage": 108,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 14.0,
        "value": 44400,
        "min_spawn_level": 79,
        "rarity": "superrare",
        "durability": 258,
        "max_durability": 258,
        "strength": 4,
        "dexterity": 10,
        "intelligence": 142,
        "constitution": 74,
        "elements": ["light", "earth", "water", "air"]
    },
]