# Weapons for levels 66-80
# Extended characters: Andrea Starveil (70), Talia Softheart (80)
WEAPONS_LV66_80 = [
    # --- Andrea Starveil (level 70) — Fire/Air/Water agile ---
    {
        "id": "morale_blade",
        "name": "Morale Blade",
        "description": "A single-edged performance saber engraved with the names of every person she's kept moving forward. Both sides. Different lists.",
        "damage": 90,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 19.0,
        "value": 32400,
        "min_spawn_level": 70,
        "rarity": "notfound",
        "durability": 235,
        "max_durability": 235,
        "strength": 60,
        "dexterity": 120,
        "intelligence": 10,
        "constitution": 8,
        "elements": ["fire", "air", "water"]
    },
    {
        "id": "encore_blades",
        "name": "Encore Blades",
        "description": "A matched pair of performance sabers Andrea had commissioned after her first successful tour — one for the show, one for what comes after. She stopped distinguishing between them.",
        "damage": 90,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 19.0,
        "value": 32400,
        "min_spawn_level": 70,
        "rarity": "notfound",
        "durability": 235,
        "max_durability": 235,
        "strength": 60,
        "dexterity": 120,
        "intelligence": 10,
        "constitution": 8,
        "elements": ["fire", "air", "water"]
    },
    # --- Talia Softheart (level 80) — Light/Water/Earth/Air caster ---
    {
        "id": "mercy_staff",
        "name": "Mercy Staff",
        "description": "A staff carved from a fallen healer's tree — species unknown, never catalogued. It blooms with pale flowers when near the dying. Talia has stopped being surprised by it.",
        "damage": 106,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 15.0,
        "value": 46400,
        "min_spawn_level": 80,
        "rarity": "notfound",
        "durability": 255,
        "max_durability": 255,
        "strength": 6,
        "dexterity": 12,
        "intelligence": 136,
        "constitution": 74,
        "elements": ["light", "water", "earth", "air"]
    },
    {
        "id": "kindness_staff",
        "name": "Kindness Staff",
        "description": "A staff Talia refuses to have repaired by anyone else — she re-wraps the grip herself at the start of every season. The wood has absorbed so much healing energy it glows faintly on overcast days.",
        "damage": 106,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 15.0,
        "value": 46400,
        "min_spawn_level": 80,
        "rarity": "notfound",
        "durability": 255,
        "max_durability": 255,
        "strength": 6,
        "dexterity": 12,
        "intelligence": 136,
        "constitution": 74,
        "elements": ["light", "water", "earth", "air"]
    },
]