# Weapons for levels 81-105
# Extended characters: Alden Brightvein (85), Lyric (95), Osten Dreamweaver (100), Lira Emberforge (105)
WEAPONS_LV81_105 = [
    # --- Alden Brightvein (level 85) — Light/Electric/Fire/Earth/Air caster ---
    {
        "id": "beacon_staff",
        "name": "Beacon Staff",
        "description": "A staff crowned with a multi-element focal that broadcasts spells in expanding resonant arcs. People have been known to stop fighting when it fires. Not from damage — from the sound.",
        "damage": 114,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 54400,
        "min_spawn_level": 85,
        "rarity": "notfound",
        "durability": 265,
        "max_durability": 265,
        "strength": 6,
        "dexterity": 12,
        "intelligence": 144,
        "constitution": 80,
        "elements": ["light", "electric", "fire", "earth", "air"]
    },
    {
        "id": "voice_of_valor_staff",
        "name": "Voice of Valor Staff",
        "description": "A staff that resonates at the frequency of collective will — when Alden speaks through it, people remember why they started. She has ended more fights with it than she has started.",
        "damage": 114,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 54400,
        "min_spawn_level": 85,
        "rarity": "notfound",
        "durability": 265,
        "max_durability": 265,
        "strength": 6,
        "dexterity": 12,
        "intelligence": 144,
        "constitution": 80,
        "elements": ["light", "electric", "fire", "earth", "air"]
    },
    # --- Lyric (level 95) — Electric/Dark/Air caster ---
    {
        "id": "collapse_staff",
        "name": "Collapse Staff",
        "description": "A staff built from the structural core of an institution that collapsed under its own contradictions. Lyric recovered it from the rubble. He finds the symbolism acceptable.",
        "damage": 128,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 72400,
        "min_spawn_level": 95,
        "rarity": "notfound",
        "durability": 285,
        "max_durability": 285,
        "strength": 10,
        "dexterity": 30,
        "intelligence": 172,
        "constitution": 70,
        "elements": ["electric", "dark", "air"]
    },
    {
        "id": "axiom_focus_rod",
        "name": "Axiom Focus Rod",
        "description": "A rod machined to Lyric's own dimensional specifications — the tolerances are tighter than anything commercially available. He measured the resonance chamber himself. Three times.",
        "damage": 128,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 72400,
        "min_spawn_level": 95,
        "rarity": "notfound",
        "durability": 285,
        "max_durability": 285,
        "strength": 10,
        "dexterity": 30,
        "intelligence": 172,
        "constitution": 70,
        "elements": ["electric", "dark", "air"]
    },
    # --- Osten Dreamweaver (level 100) — Dark/Light/Water caster ---
    {
        "id": "dreamer_staff",
        "name": "Dreamer's Staff",
        "description": "A staff carved from driftwood that floated into Osten's camp one morning with no shore in reach. He's been telling its story ever since. He hasn't finished it.",
        "damage": 136,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 82400,
        "min_spawn_level": 100,
        "rarity": "notfound",
        "durability": 295,
        "max_durability": 295,
        "strength": 14,
        "dexterity": 20,
        "intelligence": 182,
        "constitution": 80,
        "elements": ["dark", "light", "water"]
    },
    {
        "id": "storyteller_staff",
        "name": "Storyteller's Staff",
        "description": "The staff Osten uses when the story needs witnesses. It hums at a frequency that makes people lean in. He doesn't cast when he uses it. He narrates.",
        "damage": 136,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 82400,
        "min_spawn_level": 100,
        "rarity": "notfound",
        "durability": 295,
        "max_durability": 295,
        "strength": 14,
        "dexterity": 20,
        "intelligence": 182,
        "constitution": 80,
        "elements": ["dark", "light", "water"]
    },
    # --- Lira Emberforge (level 105) — Fire/Earth/Electric/Air agile ---
    {
        "id": "masterwork_blade",
        "name": "Masterwork Blade",
        "description": "The blade Lira made when she finally understood what she was doing. She has never explained what changed. Everyone who has held it agrees something did.",
        "damage": 144,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 20.0,
        "value": 94400,
        "min_spawn_level": 105,
        "rarity": "notfound",
        "durability": 305,
        "max_durability": 305,
        "strength": 90,
        "dexterity": 182,
        "intelligence": 16,
        "constitution": 18,
        "elements": ["fire", "earth", "electric", "air"]
    },
    {
        "id": "prima_blade",
        "name": "Prima Blade",
        "description": "The first blade Lira made that she kept. She has made hundreds since. None of them are this one.",
        "damage": 144,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 20.0,
        "value": 94400,
        "min_spawn_level": 105,
        "rarity": "notfound",
        "durability": 305,
        "max_durability": 305,
        "strength": 90,
        "dexterity": 182,
        "intelligence": 16,
        "constitution": 18,
        "elements": ["fire", "earth", "electric", "air"]
    },
    # ── World-drop weapons ────────────────────────────────────────────────────
    # common / technique — lv83
    {
        "id": "standard_warblade",
        "name": "Standard Warblade",
        "description": "A production-forged warblade commissioned in bulk during a conflict that ended before they were all distributed. They were. Eventually.",
        "damage": 110,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 14.0,
        "value": 22400,
        "min_spawn_level": 83,
        "rarity": "common",
        "durability": 258,
        "max_durability": 258,
        "strength": 70,
        "dexterity": 40,
        "intelligence": 8,
        "constitution": 18,
        "elements": ["fire"]
    },
    # rare / spirit — lv92
    {
        "id": "sanctified_staff",
        "name": "Sanctified Staff",
        "description": "A staff passed through seven consecutive rites of sanctification — the seventh performed by someone who no longer believed in the first six. It remains sanctified.",
        "damage": 126,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 13.0,
        "value": 52400,
        "min_spawn_level": 92,
        "rarity": "rare",
        "durability": 278,
        "max_durability": 278,
        "strength": 4,
        "dexterity": 10,
        "intelligence": 154,
        "constitution": 88,
        "elements": ["light", "water", "earth"]
    },
    # ── Trial Voidwalker boss drops (notfound) ────────────────────────────────
    # Crux Trial — damage/hazard tech, electric/dark/air — lv98
    {
        "id": "crux_logic_core",
        "name": "Crux Logic Core",
        "description": "A dense focusing rod assembled from contradictory components that should cancel each other out. They don't. The rod holds its shape by insisting that both truths are simultaneously correct, and reality agrees.",
        "damage": 130,
        "damage_type": "energy",
        "ap_cost": 2,
        "range": 4,
        "critical_chance": 18.0,
        "value": 78400,
        "min_spawn_level": 98,
        "rarity": "notfound",
        "durability": 290,
        "max_durability": 290,
        "strength": 10,
        "dexterity": 148,
        "intelligence": 90,
        "constitution": 24,
        "elements": ["electric", "dark", "air"]
    },
    # Rapture Trial — damage skill, fire/electric/air — lv99
    {
        "id": "rapture_intensity_core",
        "name": "Rapture Intensity Core",
        "description": "A short, heavy baton that pulses with escalating voltage on every swing — each hit a fraction harder than the last. There is no governor. The only limit is the wielder's nerve.",
        "damage": 132,
        "damage_type": "impact",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 22.0,
        "value": 80400,
        "min_spawn_level": 99,
        "rarity": "notfound",
        "durability": 292,
        "max_durability": 292,
        "strength": 120,
        "dexterity": 148,
        "intelligence": 14,
        "constitution": 24,
        "elements": ["fire", "electric", "air"]
    },
    # Scalpel Trial — damage dex, ice/dark/air — lv99
    {
        "id": "scalpel_precision_blade",
        "name": "Scalpel Precision Blade",
        "description": "A blade ground to a geometry that most forges cannot hold. It does not hack. It finds the exact place the cut is supposed to be and goes there without ceremony.",
        "damage": 132,
        "damage_type": "slashing",
        "ap_cost": 1,
        "range": 1,
        "critical_chance": 26.0,
        "value": 80400,
        "min_spawn_level": 99,
        "rarity": "notfound",
        "durability": 292,
        "max_durability": 292,
        "strength": 60,
        "dexterity": 196,
        "intelligence": 18,
        "constitution": 14,
        "elements": ["ice", "dark", "air"]
    },
    # Revelry Trial — damage dex/str, fire/air/electric — lv100
    {
        "id": "revelry_euphoria_crystal",
        "name": "Revelry Euphoria Crystal",
        "description": "A crystal baton that resonates at the frequency of pure exhilaration. It doesn't hurt so much as it overwhelms — the targets are flooded with sensation until there is no room left for resistance.",
        "damage": 136,
        "damage_type": "energy",
        "ap_cost": 2,
        "range": 2,
        "critical_chance": 20.0,
        "value": 84400,
        "min_spawn_level": 100,
        "rarity": "notfound",
        "durability": 295,
        "max_durability": 295,
        "strength": 80,
        "dexterity": 160,
        "intelligence": 30,
        "constitution": 20,
        "elements": ["fire", "air", "electric"]
    },
    # Paradox Trial — hazard balanced, dark/light — lv100
    {
        "id": "paradox_duality_orb",
        "name": "Paradox Duality Orb",
        "description": "An orb that is simultaneously light and dark — each face a different element, neither cancelling the other. Strikes with it land twice: once as each half. Witnesses disagree on what colour it glows.",
        "damage": 136,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 3,
        "critical_chance": 17.0,
        "value": 84400,
        "min_spawn_level": 100,
        "rarity": "notfound",
        "durability": 295,
        "max_durability": 295,
        "strength": 70,
        "dexterity": 70,
        "intelligence": 100,
        "constitution": 50,
        "elements": ["dark", "light", "electric"]
    },
    # Oracle Trial — hazard caster, dark/ice/light — lv101
    {
        "id": "oracle_prophecy_tome",
        "name": "Oracle Prophecy Tome",
        "description": "A tome that writes itself. Every page it opens to shows the next thing that will happen in the combat — not as warning, but as verdict. The text is never wrong. It has never been kind.",
        "damage": 138,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 88400,
        "min_spawn_level": 101,
        "rarity": "notfound",
        "durability": 298,
        "max_durability": 298,
        "strength": 8,
        "dexterity": 22,
        "intelligence": 190,
        "constitution": 60,
        "elements": ["dark", "ice", "light"]
    },
    # Cataclysm Trial — damage str/dex, fire/dark/earth — lv102
    {
        "id": "cataclysm_refinement_core",
        "name": "Cataclysm Refinement Core",
        "description": "A dense, scarred core recovered from a collapse that was not an accident but a process. Swinging it feels like the ending of something structural. That feeling is accurate.",
        "damage": 142,
        "damage_type": "impact",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 19.0,
        "value": 92400,
        "min_spawn_level": 102,
        "rarity": "notfound",
        "durability": 302,
        "max_durability": 302,
        "strength": 160,
        "dexterity": 120,
        "intelligence": 30,
        "constitution": 40,
        "elements": ["fire", "dark", "earth"]
    },
    # superrare / tech — lv103
    {
        "id": "quantum_projector",
        "name": "Quantum Projector",
        "description": "A projector built to specifications that its creator described as 'theoretically impossible to manufacture.' It was manufactured. The creator has not commented.",
        "damage": 142,
        "damage_type": "energy",
        "ap_cost": 2,
        "range": 4,
        "critical_chance": 18.0,
        "value": 90400,
        "min_spawn_level": 103,
        "rarity": "superrare",
        "durability": 306,
        "max_durability": 306,
        "strength": 12,
        "dexterity": 162,
        "intelligence": 112,
        "constitution": 20,
        "elements": ["electric", "dark", "air"]
    },
]