# Weapons for levels 81-105
# Extended characters: Korina Brightvein (85), Lyric (95), Osten Dreamweaver (100), Lira Emberforge (105)
WEAPONS_LV81_105 = [
    # --- Korina Brightvein (level 85) — Light/Electric/Fire/Earth/Air caster ---
    {
        "id": "beacon_staff",
        "name": "Beacon Staff",
        "description": "A staff crowned with a multi-element focal that broadcasts spells in expanding resonant arcs. People have been known to stop fighting when it fires. Not from damage — from the sound.",
        "damage": 114,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 54400,
        "min_spawn_level": 85,
        "rarity": "notfound",
        "durability": 265,
        "max_durability": 265,
        "strength": 6,
        "dexterity": 12,
        "intelligence": 144,
        "constitution": 80,
        "elements": ["light", "electric", "fire", "earth", "air"]
    },
    {
        "id": "voice_of_valor_staff",
        "name": "Voice of Valor Staff",
        "description": "A staff that resonates at the frequency of collective will — when Korina speaks through it, people remember why they started. She has ended more fights with it than she has started.",
        "damage": 114,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 54400,
        "min_spawn_level": 85,
        "rarity": "notfound",
        "durability": 265,
        "max_durability": 265,
        "strength": 6,
        "dexterity": 12,
        "intelligence": 144,
        "constitution": 80,
        "elements": ["light", "electric", "fire", "earth", "air"]
    },
    # --- Lyric (level 95) — Electric/Dark/Air caster ---
    {
        "id": "collapse_staff",
        "name": "Collapse Staff",
        "description": "A staff built from the structural core of an institution that collapsed under its own contradictions. Lyric recovered it from the rubble. He finds the symbolism acceptable.",
        "damage": 128,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 72400,
        "min_spawn_level": 95,
        "rarity": "notfound",
        "durability": 285,
        "max_durability": 285,
        "strength": 10,
        "dexterity": 30,
        "intelligence": 172,
        "constitution": 70,
        "elements": ["electric", "dark", "air"]
    },
    {
        "id": "axiom_focus_rod",
        "name": "Axiom Focus Rod",
        "description": "A rod machined to Lyric's own dimensional specifications — the tolerances are tighter than anything commercially available. He measured the resonance chamber himself. Three times.",
        "damage": 128,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 72400,
        "min_spawn_level": 95,
        "rarity": "notfound",
        "durability": 285,
        "max_durability": 285,
        "strength": 10,
        "dexterity": 30,
        "intelligence": 172,
        "constitution": 70,
        "elements": ["electric", "dark", "air"]
    },
    # --- Osten Dreamweaver (level 100) — Dark/Light/Water caster ---
    {
        "id": "dreamer_staff",
        "name": "Dreamer's Staff",
        "description": "A staff carved from driftwood that floated into Osten's camp one morning with no shore in reach. He's been telling its story ever since. He hasn't finished it.",
        "damage": 136,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 82400,
        "min_spawn_level": 100,
        "rarity": "notfound",
        "durability": 295,
        "max_durability": 295,
        "strength": 14,
        "dexterity": 20,
        "intelligence": 182,
        "constitution": 80,
        "elements": ["dark", "light", "water"]
    },
    {
        "id": "storyteller_staff",
        "name": "Storyteller's Staff",
        "description": "The staff Osten uses when the story needs witnesses. It hums at a frequency that makes people lean in. He doesn't cast when he uses it. He narrates.",
        "damage": 136,
        "damage_type": "energy",
        "ap_cost": 3,
        "range": 4,
        "critical_chance": 16.0,
        "value": 82400,
        "min_spawn_level": 100,
        "rarity": "notfound",
        "durability": 295,
        "max_durability": 295,
        "strength": 14,
        "dexterity": 20,
        "intelligence": 182,
        "constitution": 80,
        "elements": ["dark", "light", "water"]
    },
    # --- Lira Emberforge (level 105) — Fire/Earth/Electric/Air agile ---
    {
        "id": "masterwork_blade",
        "name": "Masterwork Blade",
        "description": "The blade Lira made when she finally understood what she was doing. She has never explained what changed. Everyone who has held it agrees something did.",
        "damage": 144,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 20.0,
        "value": 94400,
        "min_spawn_level": 105,
        "rarity": "notfound",
        "durability": 305,
        "max_durability": 305,
        "strength": 90,
        "dexterity": 182,
        "intelligence": 16,
        "constitution": 18,
        "elements": ["fire", "earth", "electric", "air"]
    },
    {
        "id": "prima_blade",
        "name": "Prima Blade",
        "description": "The first blade Lira made that she kept. She has made hundreds since. None of them are this one.",
        "damage": 144,
        "damage_type": "slashing",
        "ap_cost": 2,
        "range": 1,
        "critical_chance": 20.0,
        "value": 94400,
        "min_spawn_level": 105,
        "rarity": "notfound",
        "durability": 305,
        "max_durability": 305,
        "strength": 90,
        "dexterity": 182,
        "intelligence": 16,
        "constitution": 18,
        "elements": ["fire", "earth", "electric", "air"]
    },
]