# Swamp shared rarity-fill band Lv 21-40.
# Full multiple-of-5 ladder per rarity (seed at N covers window starts N-4..N).
RANDOM_HOSTILE_SEEDS = [
    # --- common ---
    {"id": "swamp_shared_gator_brute", "name": "Gator Brute", "hostile_type": "creature", "role": "damage", "min_spawn_level": 25, "rarity": "common", "base_xp": 360,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (24, 110),
     "basic_attack": "snapping jaws", "strong_attack": "death roll",
     "player_abilities": [],
     "base_str": 15, "base_dex": 15, "base_con": 14, "base_int": 4, "base_hp": 240, "base_ap": 11,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "swamp_shared_bog_boar", "name": "Bog Boar", "hostile_type": "creature", "role": "tank", "min_spawn_level": 30, "rarity": "common", "base_xp": 440,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (28, 130),
     "basic_attack": "goring tusk", "strong_attack": "muck charge",
     "player_abilities": [],
     "base_str": 18, "base_dex": 12, "base_con": 18, "base_int": 4, "base_hp": 320, "base_ap": 12,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
    {"id": "swamp_shared_marsh_scavver", "name": "Marsh Scavver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 35, "rarity": "common", "base_xp": 520,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (32, 150),
     "basic_attack": "hooked jab", "strong_attack": "ambush swing",
     "player_abilities": [],
     "base_str": 17, "base_dex": 17, "base_con": 15, "base_int": 5, "base_hp": 300, "base_ap": 12,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "swamp_shared_mire_troll", "name": "Mire Troll", "hostile_type": "creature", "role": "tank", "min_spawn_level": 40, "rarity": "common", "base_xp": 640,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (40, 180),
     "basic_attack": "crushing swipe", "strong_attack": "bog slam",
     "player_abilities": [],
     "base_str": 22, "base_dex": 13, "base_con": 22, "base_int": 5, "base_hp": 420, "base_ap": 13,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},

    # --- uncommon ---
    {"id": "swamp_shared_swamp_panther", "name": "Swamp Panther", "hostile_type": "creature", "role": "damage", "min_spawn_level": 25, "rarity": "uncommon", "base_xp": 400,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (28, 120),
     "basic_attack": "pouncing claw", "strong_attack": "reed flurry",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 16, "base_dex": 19, "base_con": 14, "base_int": 6, "base_hp": 250, "base_ap": 11,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "swamp_shared_bog_reaver", "name": "Bog Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 30, "rarity": "uncommon", "base_xp": 480,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (32, 140),
     "basic_attack": "cleaving axe", "strong_attack": "mire whirl",
     "player_abilities": ["air_skill_lv1_smoke_bomb"],
     "base_str": 20, "base_dex": 16, "base_con": 16, "base_int": 6, "base_hp": 320, "base_ap": 12,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "swamp_shared_fenshade_rogue", "name": "Fenshade Rogue", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 35, "rarity": "uncommon", "base_xp": 560,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (36, 160),
     "basic_attack": "twin daggers", "strong_attack": "mistveil strike",
     "player_abilities": ["level_1_hostile_ability_poison_dart", "air_skill_lv1_smoke_bomb"],
     "base_str": 18, "base_dex": 21, "base_con": 15, "base_int": 7, "base_hp": 330, "base_ap": 12,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "swamp_shared_muck_brute", "name": "Muck Brute", "hostile_type": "creature", "role": "tank", "min_spawn_level": 40, "rarity": "uncommon", "base_xp": 700,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (44, 190),
     "basic_attack": "boulder fist", "strong_attack": "sludge stomp",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 24, "base_dex": 14, "base_con": 24, "base_int": 6, "base_hp": 460, "base_ap": 13,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},

    # --- rare ---
    {"id": "swamp_shared_voodoo_witch", "name": "Voodoo Witch", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 25, "rarity": "rare", "base_xp": 420,
     "common_drop": "tome_int", "rare_drop": "stimulant_small", "money_range": (30, 130),
     "basic_attack": "curse hex", "strong_attack": "hex nova",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 12, "base_dex": 15, "base_con": 14, "base_int": 22, "base_hp": 260, "base_ap": 13,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 3},
    {"id": "swamp_shared_mire_wraith", "name": "Mire Wraith", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 30, "rarity": "rare", "base_xp": 500,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (34, 150),
     "basic_attack": "chilling touch", "strong_attack": "drowned wail",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor"],
     "base_str": 15, "base_dex": 16, "base_con": 18, "base_int": 20, "base_hp": 320, "base_ap": 13,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 3},
    {"id": "swamp_shared_swamp_druid", "name": "Swamp Druid", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 35, "rarity": "rare", "base_xp": 580,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (38, 165),
     "basic_attack": "thorn bramble", "strong_attack": "creeping vines",
     "player_abilities": ["earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 14, "base_dex": 17, "base_con": 16, "base_int": 23, "base_hp": 340, "base_ap": 13,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 4},
    {"id": "swamp_shared_sunken_lich", "name": "Sunken Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 40, "rarity": "rare", "base_xp": 760,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (46, 200),
     "basic_attack": "rot bolt", "strong_attack": "grave surge",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 14, "base_dex": 16, "base_con": 20, "base_int": 26, "base_hp": 420, "base_ap": 14,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 4},

    # --- superrare ---
    {"id": "swamp_shared_marsh_phantom", "name": "Marsh Phantom", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 25, "rarity": "superrare", "base_xp": 600,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (60, 220),
     "basic_attack": "spectral chill", "strong_attack": "phantom burst",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 14, "base_dex": 17, "base_con": 15, "base_int": 20, "base_hp": 300, "base_ap": 13,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 3},
    {"id": "swamp_shared_bog_colossus", "name": "Bog Colossus", "hostile_type": "creature", "role": "tank", "min_spawn_level": 30, "rarity": "superrare", "base_xp": 720,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (70, 250),
     "basic_attack": "titan slam", "strong_attack": "mire quake",
     "player_abilities": ["earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril"],
     "base_str": 26, "base_dex": 13, "base_con": 26, "base_int": 10, "base_hp": 520, "base_ap": 14,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 1},
    {"id": "swamp_shared_plague_seraph", "name": "Plague Seraph", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 35, "rarity": "superrare", "base_xp": 840,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (80, 280),
     "basic_attack": "rot lance", "strong_attack": "hymn of decay",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 16, "base_dex": 18, "base_con": 18, "base_int": 24, "base_hp": 400, "base_ap": 14,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 3},
    {"id": "swamp_shared_mire_titan", "name": "Mire Titan", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 40, "rarity": "superrare", "base_xp": 1040,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (90, 320),
     "basic_attack": "sludge maul", "strong_attack": "endless bog",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 26, "base_dex": 18, "base_con": 24, "base_int": 22, "base_hp": 520, "base_ap": 15,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 2},
]
