# Swamp shared rarity-fill band Lv 41-60.
# Full multiple-of-5 ladder per rarity (seed at N covers window starts N-4..N).
RANDOM_HOSTILE_SEEDS = [
    # --- common ---
    {"id": "swamp_shared_bog_mammoth", "name": "Bog Mammoth", "hostile_type": "creature", "role": "tank", "min_spawn_level": 45, "rarity": "common", "base_xp": 820,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (46, 200),
     "basic_attack": "tusk sweep", "strong_attack": "trampling stampede",
     "player_abilities": [],
     "base_str": 26, "base_dex": 13, "base_con": 26, "base_int": 5, "base_hp": 520, "base_ap": 14,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "swamp_shared_fenclad_raider", "name": "Fenclad Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 50, "rarity": "common", "base_xp": 940,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (50, 220),
     "basic_attack": "rusted blade", "strong_attack": "reaving charge",
     "player_abilities": [],
     "base_str": 24, "base_dex": 20, "base_con": 20, "base_int": 6, "base_hp": 480, "base_ap": 14,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "swamp_shared_marsh_ogre", "name": "Marsh Ogre", "hostile_type": "creature", "role": "tank", "min_spawn_level": 55, "rarity": "common", "base_xp": 1080,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (54, 240),
     "basic_attack": "club smash", "strong_attack": "bog bellow",
     "player_abilities": [],
     "base_str": 30, "base_dex": 14, "base_con": 30, "base_int": 5, "base_hp": 620, "base_ap": 15,
     "str_per_level": 4, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "swamp_shared_mire_marauder", "name": "Mire Marauder", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 60, "rarity": "common", "base_xp": 1240,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (60, 260),
     "basic_attack": "hooked spear", "strong_attack": "raider's fury",
     "player_abilities": [],
     "base_str": 28, "base_dex": 22, "base_con": 22, "base_int": 6, "base_hp": 560, "base_ap": 15,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},

    # --- uncommon ---
    {"id": "swamp_shared_quagmire_beast", "name": "Quagmire Beast", "hostile_type": "creature", "role": "tank", "min_spawn_level": 45, "rarity": "uncommon", "base_xp": 880,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (50, 210),
     "basic_attack": "muck swipe", "strong_attack": "burying surge",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 28, "base_dex": 15, "base_con": 26, "base_int": 7, "base_hp": 540, "base_ap": 14,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "swamp_shared_reed_archer", "name": "Reed Archer", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 50, "rarity": "uncommon", "base_xp": 1000,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (54, 230),
     "basic_attack": "poison arrow", "strong_attack": "reed volley",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 20, "base_dex": 26, "base_con": 18, "base_int": 8, "base_hp": 460, "base_ap": 14,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "swamp_shared_gatorfang_alpha", "name": "Gatorfang Alpha", "hostile_type": "creature", "role": "damage", "min_spawn_level": 55, "rarity": "uncommon", "base_xp": 1140,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (58, 250),
     "basic_attack": "alpha maul", "strong_attack": "thrashing pack",
     "player_abilities": ["level_1_hostile_ability_poison_dart", "air_skill_lv1_smoke_bomb"],
     "base_str": 27, "base_dex": 24, "base_con": 22, "base_int": 8, "base_hp": 540, "base_ap": 15,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "swamp_shared_bog_knight", "name": "Bog Knight", "hostile_type": "humanoid", "role": "tank", "min_spawn_level": 60, "rarity": "uncommon", "base_xp": 1320,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (62, 270),
     "basic_attack": "rusted bash", "strong_attack": "mire phalanx",
     "player_abilities": ["earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 30, "base_dex": 18, "base_con": 30, "base_int": 8, "base_hp": 640, "base_ap": 15,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},

    # --- rare ---
    {"id": "swamp_shared_plague_mage", "name": "Plague Mage", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 45, "rarity": "rare", "base_xp": 900,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (50, 215),
     "basic_attack": "rot shard", "strong_attack": "miasma storm",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 16, "base_dex": 20, "base_con": 20, "base_int": 28, "base_hp": 440, "base_ap": 15,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 4},
    {"id": "swamp_shared_drowned_lich", "name": "Drowned Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 50, "rarity": "rare", "base_xp": 1020,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (54, 235),
     "basic_attack": "necrotic mire", "strong_attack": "grave deluge",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor"],
     "base_str": 18, "base_dex": 20, "base_con": 24, "base_int": 30, "base_hp": 500, "base_ap": 15,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 4},
    {"id": "swamp_shared_mire_oracle", "name": "Mire Oracle", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 55, "rarity": "rare", "base_xp": 1160,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (58, 255),
     "basic_attack": "murky gaze", "strong_attack": "prophecy of rot",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 18, "base_dex": 22, "base_con": 22, "base_int": 30, "base_hp": 520, "base_ap": 16,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 4},
    {"id": "swamp_shared_bog_warlock", "name": "Bog Warlock", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 60, "rarity": "rare", "base_xp": 1340,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (64, 275),
     "basic_attack": "void rot", "strong_attack": "eternal decay pact",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 18, "base_dex": 22, "base_con": 24, "base_int": 32, "base_hp": 560, "base_ap": 16,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 5},

    # --- superrare ---
    {"id": "swamp_shared_fen_leviathan", "name": "Fen Leviathan", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 45, "rarity": "superrare", "base_xp": 1180,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (95, 340),
     "basic_attack": "muck maw", "strong_attack": "bog devour",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 28, "base_dex": 20, "base_con": 26, "base_int": 24, "base_hp": 560, "base_ap": 16,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 3},
    {"id": "swamp_shared_rot_archon", "name": "Rot Archon", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 50, "rarity": "superrare", "base_xp": 1320,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (100, 360),
     "basic_attack": "blight edict", "strong_attack": "absolute decay",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 22, "base_dex": 22, "base_con": 24, "base_int": 30, "base_hp": 560, "base_ap": 16,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 4},
    {"id": "swamp_shared_bog_wyrm", "name": "Bog Wyrm", "hostile_type": "creature", "role": "damage", "min_spawn_level": 55, "rarity": "superrare", "base_xp": 1480,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (110, 390),
     "basic_attack": "toxic breath", "strong_attack": "mire dive",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 30, "base_dex": 24, "base_con": 28, "base_int": 20, "base_hp": 640, "base_ap": 16,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 2},
    {"id": "swamp_shared_marsh_godspawn", "name": "Marsh Godspawn", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 60, "rarity": "superrare", "base_xp": 1680,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (120, 420),
     "basic_attack": "divine rot", "strong_attack": "world in mire",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 26, "base_dex": 24, "base_con": 28, "base_int": 32, "base_hp": 680, "base_ap": 17,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 4},
]
