# Swamp shared rarity-fill band Lv 81-100.
# Full multiple-of-5 ladder per rarity (seed at N covers window starts N-4..N).
RANDOM_HOSTILE_SEEDS = [
    # --- common ---
    {"id": "swamp_shared_mire_warbringer", "name": "Mire Warbringer", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 85, "rarity": "common", "base_xp": 2200,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (84, 360),
     "basic_attack": "warmaul crush", "strong_attack": "conqueror's charge",
     "player_abilities": [],
     "base_str": 40, "base_dex": 26, "base_con": 32, "base_int": 8, "base_hp": 820, "base_ap": 18,
     "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},
    {"id": "swamp_shared_bog_tyrant", "name": "Bog Tyrant", "hostile_type": "creature", "role": "tank", "min_spawn_level": 90, "rarity": "common", "base_xp": 2440,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (90, 380),
     "basic_attack": "mountain slam", "strong_attack": "cataclysm stomp",
     "player_abilities": [],
     "base_str": 44, "base_dex": 18, "base_con": 44, "base_int": 7, "base_hp": 980, "base_ap": 18,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},
    {"id": "swamp_shared_mire_reaver", "name": "Mire Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 95, "rarity": "common", "base_xp": 2680,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (94, 400),
     "basic_attack": "rotted greatsword", "strong_attack": "reaving whirlwind",
     "player_abilities": [],
     "base_str": 42, "base_dex": 30, "base_con": 32, "base_int": 8, "base_hp": 880, "base_ap": 19,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "swamp_shared_marsh_colossus", "name": "Marsh Colossus", "hostile_type": "creature", "role": "tank", "min_spawn_level": 100, "rarity": "common", "base_xp": 3000,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (100, 420),
     "basic_attack": "world hammer", "strong_attack": "apocalypse quake",
     "player_abilities": [],
     "base_str": 48, "base_dex": 18, "base_con": 48, "base_int": 7, "base_hp": 1100, "base_ap": 19,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},

    # --- uncommon ---
    {"id": "swamp_shared_swamp_overlord", "name": "Swamp Overlord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 85, "rarity": "uncommon", "base_xp": 2280,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (86, 370),
     "basic_attack": "venomblade cleave", "strong_attack": "eye of the storm",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "level_1_hostile_ability_poison_dart"],
     "base_str": 38, "base_dex": 34, "base_con": 30, "base_int": 10, "base_hp": 800, "base_ap": 18,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "swamp_shared_muck_warmaster", "name": "Muck Warmaster", "hostile_type": "creature", "role": "tank", "min_spawn_level": 90, "rarity": "uncommon", "base_xp": 2520,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (92, 390),
     "basic_attack": "sludge charge", "strong_attack": "unbreakable siege",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 44, "base_dex": 22, "base_con": 44, "base_int": 9, "base_hp": 980, "base_ap": 19,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},
    {"id": "swamp_shared_gatorfang_apex", "name": "Gatorfang Apex", "hostile_type": "creature", "role": "damage", "min_spawn_level": 95, "rarity": "uncommon", "base_xp": 2760,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (96, 410),
     "basic_attack": "primal maul", "strong_attack": "apex frenzy",
     "player_abilities": ["level_1_hostile_ability_poison_dart", "air_skill_lv1_smoke_bomb"],
     "base_str": 42, "base_dex": 38, "base_con": 32, "base_int": 10, "base_hp": 900, "base_ap": 19,
     "str_per_level": 4, "dex_per_level": 4, "con_per_level": 3, "int_per_level": 0},
    {"id": "swamp_shared_mire_praetorian", "name": "Mire Praetorian", "hostile_type": "humanoid", "role": "tank", "min_spawn_level": 100, "rarity": "uncommon", "base_xp": 3080,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (100, 430),
     "basic_attack": "aegis smash", "strong_attack": "immortal bastion",
     "player_abilities": ["earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 44, "base_dex": 24, "base_con": 48, "base_int": 10, "base_hp": 1050, "base_ap": 19,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 0},

    # --- rare ---
    {"id": "swamp_shared_rot_lichlord", "name": "Rot Lichlord", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 85, "rarity": "rare", "base_xp": 2320,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (86, 375),
     "basic_attack": "soulrot bolt", "strong_attack": "legion of the drowned",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor"],
     "base_str": 24, "base_dex": 28, "base_con": 32, "base_int": 42, "base_hp": 760, "base_ap": 19,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 6},
    {"id": "swamp_shared_mire_archon", "name": "Mire Archon", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 90, "rarity": "rare", "base_xp": 2560,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (92, 395),
     "basic_attack": "blight prism", "strong_attack": "shattering rot",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor"],
     "base_str": 24, "base_dex": 30, "base_con": 32, "base_int": 44, "base_hp": 780, "base_ap": 19,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 6},
    {"id": "swamp_shared_bog_oracle", "name": "Bog Oracle", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 95, "rarity": "rare", "base_xp": 2800,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (96, 415),
     "basic_attack": "murky prophecy", "strong_attack": "the long rot",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 24, "base_dex": 30, "base_con": 34, "base_int": 46, "base_hp": 820, "base_ap": 20,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 6},
    {"id": "swamp_shared_blight_lich", "name": "Blight Prime Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 100, "rarity": "rare", "base_xp": 3120,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (100, 435),
     "basic_attack": "entropy rot", "strong_attack": "total decay",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 26, "base_dex": 30, "base_con": 36, "base_int": 48, "base_hp": 880, "base_ap": 20,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 6},

    # --- superrare ---
    {"id": "swamp_shared_ancient_bog_wyrm", "name": "Ancient Bog Wyrm", "hostile_type": "creature", "role": "damage", "min_spawn_level": 85, "rarity": "superrare", "base_xp": 2900,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (170, 600),
     "basic_attack": "miasmic breath", "strong_attack": "extinction rot",
     "player_abilities": ["air_skill_lv1_smoke_bomb", "earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril"],
     "base_str": 42, "base_dex": 30, "base_con": 36, "base_int": 34, "base_hp": 960, "base_ap": 20,
     "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 3},
    {"id": "swamp_shared_herald_of_rot", "name": "Herald of Endless Rot", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 90, "rarity": "superrare", "base_xp": 3200,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (185, 640),
     "basic_attack": "primordial blight", "strong_attack": "the drowned end",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 34, "base_dex": 32, "base_con": 38, "base_int": 46, "base_hp": 1000, "base_ap": 20,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 5},
    {"id": "swamp_shared_bog_leviathan_prime", "name": "Bog Leviathan Prime", "hostile_type": "eldritch", "role": "tank", "min_spawn_level": 95, "rarity": "superrare", "base_xp": 3500,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (200, 700),
     "basic_attack": "abyssal mire", "strong_attack": "swamp maw",
     "player_abilities": ["earth_magic_lv1_tremor", "dark_magic_lv1_shadow_tendril", "air_skill_lv1_smoke_bomb"],
     "base_str": 46, "base_dex": 26, "base_con": 46, "base_int": 36, "base_hp": 1150, "base_ap": 21,
     "str_per_level": 5, "dex_per_level": 1, "con_per_level": 5, "int_per_level": 3},
    {"id": "swamp_shared_avatar_of_rot", "name": "Avatar of the Endless Bog", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 4000,
     "common_drop": "tome_int", "rare_drop": "stimulant_med", "money_range": (220, 780),
     "basic_attack": "annihilating rot", "strong_attack": "the final drowning",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "earth_magic_lv1_tremor", "air_skill_lv1_smoke_bomb"],
     "base_str": 48, "base_dex": 34, "base_con": 44, "base_int": 44, "base_hp": 1250, "base_ap": 21,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 4},
]
