# Forest shared hostiles - rarity-coverage fill, Lv 1-20.
#
# Reusable across all forest city sizes (large / mid / small) and the forest
# wilderness. To be self-sufficient for ANY zone (even the sparse small city),
# this roster places one seed of EVERY rarity at each 5-level mark
# (Lv 5, 10, 15, 20). A seed at level N covers the validator's sliding windows
# starting N-4..N, so multiples of 5 guarantee full REGION_HOSTILE_RARITY_GAP
# coverage regardless of what a zone already defines.
#
# Ability ids are reused from existing loaded band files, so they are
# known-valid against PLAYER_ABILITY_SEEDS.
# Theme: feral beasts, poacher gangs, corrupted dryads, root golems.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 5 ???????????????????????????????????????????????????????????????
    {"id": "forest_shared_thicket_stray", "name": "Thicket Stray", "hostile_type": "creature", "role": "damage", "min_spawn_level": 5, "rarity": "common", "base_xp": 40,
     "common_drop": "herb_minor", "rare_drop": None, "money_range": (5, 30),
     "basic_attack": "clawing swipe", "strong_attack": "lunging bite",
     "player_abilities": [],
     "base_str": 5, "base_dex": 5, "base_con": 5, "base_int": 2, "base_hp": 42, "base_ap": 5,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 0},
    {"id": "forest_shared_snare_poacher", "name": "Snare Poacher", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 5, "rarity": "uncommon", "base_xp": 55,
     "common_drop": "herb_minor", "rare_drop": "stimulant_small", "money_range": (10, 45),
     "basic_attack": "net toss", "strong_attack": "snare yank",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 5, "base_dex": 6, "base_con": 5, "base_int": 4, "base_hp": 46, "base_ap": 6,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 1},
    {"id": "forest_shared_sapling_dryad", "name": "Sapling Dryad", "hostile_type": "elemental", "role": "support", "min_spawn_level": 5, "rarity": "rare", "base_xp": 75,
     "common_drop": "herb_minor", "rare_drop": "herb_med", "money_range": (12, 55),
     "basic_attack": "thorn flick", "strong_attack": "binding root",
     "player_abilities": ["earth_magic_lv1_tremor", "light_faith_lv1_minor_heal"],
     "base_str": 4, "base_dex": 6, "base_con": 6, "base_int": 8, "base_hp": 50, "base_ap": 7,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 1},
    {"id": "forest_shared_gloomling_horror", "name": "Gloomling Horror", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 5, "rarity": "superrare", "base_xp": 90,
     "common_drop": "herb_minor", "rare_drop": "stimulant_med", "money_range": (20, 90),
     "basic_attack": "whispering touch", "strong_attack": "dread bloom",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "fire_magic_lv1_fireball", "level_1_hostile_ability_poison_dart"],
     "base_str": 5, "base_dex": 7, "base_con": 5, "base_int": 9, "base_hp": 52, "base_ap": 7,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 1},

    # ?? Lv 10 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_bramble_hound", "name": "Bramble Hound", "hostile_type": "creature", "role": "damage", "min_spawn_level": 10, "rarity": "common", "base_xp": 80,
     "common_drop": "herb_minor", "rare_drop": None, "money_range": (10, 50),
     "basic_attack": "snapping bite", "strong_attack": "pack lunge",
     "player_abilities": [],
     "base_str": 8, "base_dex": 8, "base_con": 7, "base_int": 3, "base_hp": 70, "base_ap": 6,
     "str_per_level": 1, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 0},
    {"id": "forest_shared_bark_bandit", "name": "Bark Bandit", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 10, "rarity": "uncommon", "base_xp": 105,
     "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (18, 70),
     "basic_attack": "hatchet chop", "strong_attack": "ambush cleave",
     "player_abilities": ["fire_technique_lv1_scorch_slash"],
     "base_str": 10, "base_dex": 8, "base_con": 8, "base_int": 3, "base_hp": 78, "base_ap": 7,
     "str_per_level": 2, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 0},
    {"id": "forest_shared_thorn_warden", "name": "Thorn Warden", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 10, "rarity": "rare", "base_xp": 150,
     "common_drop": "herb_med", "rare_drop": "herb_med", "money_range": (24, 90),
     "basic_attack": "thorn volley", "strong_attack": "root snare",
     "player_abilities": ["earth_magic_lv1_tremor", "level_1_hostile_ability_poison_dart"],
     "base_str": 8, "base_dex": 9, "base_con": 9, "base_int": 12, "base_hp": 84, "base_ap": 9,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 2},
    {"id": "forest_shared_moonlit_devourer", "name": "Moonlit Devourer", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 10, "rarity": "superrare", "base_xp": 190,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (30, 120),
     "basic_attack": "moon-fang bite", "strong_attack": "lunar rend",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "level_1_hostile_ability_poison_dart"],
     "base_str": 12, "base_dex": 12, "base_con": 10, "base_int": 10, "base_hp": 92, "base_ap": 9,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 2},

    # ?? Lv 15 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_fen_lurker", "name": "Fen Lurker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 15, "rarity": "common", "base_xp": 120,
     "common_drop": "herb_med", "rare_drop": None, "money_range": (16, 70),
     "basic_attack": "raking claw", "strong_attack": "mud-burst charge",
     "player_abilities": [],
     "base_str": 11, "base_dex": 9, "base_con": 10, "base_int": 3, "base_hp": 100, "base_ap": 7,
     "str_per_level": 2, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
    {"id": "forest_shared_poacher_ranger", "name": "Poacher Ranger", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 15, "rarity": "uncommon", "base_xp": 150,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (24, 95),
     "basic_attack": "hunting shot", "strong_attack": "piercing volley",
     "player_abilities": ["fire_technique_lv1_scorch_slash"],
     "base_str": 11, "base_dex": 13, "base_con": 9, "base_int": 4, "base_hp": 105, "base_ap": 8,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 1, "int_per_level": 0},
    {"id": "forest_shared_grove_hexer", "name": "Grove Hexer", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 15, "rarity": "rare", "base_xp": 220,
     "common_drop": "tome_int", "rare_drop": "herb_med", "money_range": (30, 120),
     "basic_attack": "hex bolt", "strong_attack": "witherwood curse",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "level_1_hostile_ability_poison_dart"],
     "base_str": 7, "base_dex": 10, "base_con": 9, "base_int": 16, "base_hp": 100, "base_ap": 11,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 3},
    {"id": "forest_shared_wraithwood_shade", "name": "Wraithwood Shade", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 15, "rarity": "superrare", "base_xp": 280,
     "common_drop": "tome_int", "rare_drop": "stimulant_large", "money_range": (40, 160),
     "basic_attack": "spectral clutch", "strong_attack": "hollow scream",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "level_1_hostile_ability_poison_dart"],
     "base_str": 9, "base_dex": 12, "base_con": 10, "base_int": 18, "base_hp": 118, "base_ap": 12,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 3},

    # ?? Lv 20 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_root_golem", "name": "Root Golem", "hostile_type": "construct", "role": "damage", "min_spawn_level": 20, "rarity": "common", "base_xp": 160,
     "common_drop": None, "rare_drop": "herb_med", "money_range": (0, 40),
     "basic_attack": "timber slam", "strong_attack": "root crush",
     "player_abilities": [],
     "base_str": 14, "base_dex": 5, "base_con": 14, "base_int": 3, "base_hp": 150, "base_ap": 7,
     "str_per_level": 2, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
    {"id": "forest_shared_greenfang_stalker", "name": "Greenfang Stalker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 20, "rarity": "uncommon", "base_xp": 200,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (28, 110),
     "basic_attack": "pouncing rake", "strong_attack": "throat lunge",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 13, "base_dex": 15, "base_con": 11, "base_int": 4, "base_hp": 130, "base_ap": 9,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 2, "int_per_level": 0},
    {"id": "forest_shared_blight_druid", "name": "Blight Druid", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 20, "rarity": "rare", "base_xp": 300,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (40, 150),
     "basic_attack": "rotting touch", "strong_attack": "blight bloom",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "level_1_hostile_ability_poison_dart"],
     "base_str": 8, "base_dex": 11, "base_con": 12, "base_int": 18, "base_hp": 140, "base_ap": 12,
     "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 3},
    {"id": "forest_shared_verdant_terror", "name": "Verdant Terror", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 20, "rarity": "superrare", "base_xp": 400,
     "common_drop": "herb_major", "rare_drop": "stimulant_large", "money_range": (60, 220),
     "basic_attack": "thrashing vines", "strong_attack": "devouring canopy",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "earth_magic_lv1_tremor"],
     "base_str": 16, "base_dex": 14, "base_con": 15, "base_int": 16, "base_hp": 170, "base_ap": 12,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 2},
]
