# Forest shared hostiles - rarity-coverage fill, Lv 21-40.
#
# Reusable across all forest city sizes and the forest wilderness. One seed of
# every rarity at each 5-level mark (Lv 25, 30, 35, 40) guarantees full sliding-
# window coverage for any zone. Ability ids reused from loaded band files.
# Theme (mid): moonhunters, blight wolves, arcane wardens, shade raptors.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 25 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_briar_raider", "name": "Briar Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 25, "rarity": "common", "base_xp": 220,
     "common_drop": "herb_med", "rare_drop": "stimulant_med", "money_range": (30, 130),
     "basic_attack": "brier cleaver", "strong_attack": "thicket ambush",
     "player_abilities": [],
     "base_str": 14, "base_dex": 10, "base_con": 12, "base_int": 4, "base_hp": 160, "base_ap": 8,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
    {"id": "forest_shared_shade_raptor", "name": "Shade Raptor", "hostile_type": "creature", "role": "damage", "min_spawn_level": 25, "rarity": "uncommon", "base_xp": 280,
     "common_drop": "herb_med", "rare_drop": "stimulant_large", "money_range": (40, 150),
     "basic_attack": "talon rake", "strong_attack": "diving strike",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 15, "base_dex": 18, "base_con": 12, "base_int": 5, "base_hp": 155, "base_ap": 9,
     "str_per_level": 3, "dex_per_level": 4, "con_per_level": 2, "int_per_level": 0},
    {"id": "forest_shared_moonhunter", "name": "Moonhunter", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 25, "rarity": "rare", "base_xp": 380,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (60, 220),
     "basic_attack": "silver arrow", "strong_attack": "moonlit volley",
     "player_abilities": ["fire_technique_lv1_scorch_slash", "level_1_hostile_ability_poison_dart"],
     "base_str": 16, "base_dex": 18, "base_con": 13, "base_int": 6, "base_hp": 175, "base_ap": 10,
     "str_per_level": 3, "dex_per_level": 4, "con_per_level": 2, "int_per_level": 0},
    {"id": "forest_shared_hollow_dread", "name": "Hollow Dread", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 25, "rarity": "superrare", "base_xp": 560,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (90, 340),
     "basic_attack": "void murmur", "strong_attack": "hollow unmaking",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "level_1_hostile_ability_poison_dart"],
     "base_str": 10, "base_dex": 12, "base_con": 12, "base_int": 20, "base_hp": 170, "base_ap": 13,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 4},

    # ?? Lv 30 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_timber_brute", "name": "Timber Brute", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 30, "rarity": "common", "base_xp": 280,
     "common_drop": "herb_med", "rare_drop": "stimulant_large", "money_range": (40, 160),
     "basic_attack": "log swing", "strong_attack": "crushing overhead",
     "player_abilities": [],
     "base_str": 18, "base_dex": 8, "base_con": 16, "base_int": 4, "base_hp": 190, "base_ap": 8,
     "str_per_level": 3, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 0},
    {"id": "forest_shared_blight_wolf", "name": "Blight Wolf", "hostile_type": "creature", "role": "damage", "min_spawn_level": 30, "rarity": "uncommon", "base_xp": 340,
     "common_drop": "herb_major", "rare_drop": "stimulant_large", "money_range": (50, 180),
     "basic_attack": "festering bite", "strong_attack": "plague howl",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 18, "base_dex": 16, "base_con": 15, "base_int": 6, "base_hp": 185, "base_ap": 10,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 0},
    {"id": "forest_shared_arcane_warden", "name": "Arcane Warden", "hostile_type": "construct", "role": "hazard", "min_spawn_level": 30, "rarity": "rare", "base_xp": 460,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (70, 260),
     "basic_attack": "rune bolt", "strong_attack": "warding pulse",
     "player_abilities": ["level_1_hostile_ability_reinforce_frame", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 16, "base_dex": 12, "base_con": 18, "base_int": 22, "base_hp": 210, "base_ap": 13,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 4},
    {"id": "forest_shared_night_canopy_horror", "name": "Night Canopy Horror", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 30, "rarity": "superrare", "base_xp": 700,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (110, 400),
     "basic_attack": "grasping bough", "strong_attack": "canopy collapse",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "earth_magic_lv1_tremor"],
     "base_str": 22, "base_dex": 18, "base_con": 20, "base_int": 18, "base_hp": 230, "base_ap": 14,
     "str_per_level": 3, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 3},

    # ?? Lv 35 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_hollow_reaver", "name": "Hollow Reaver", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 35, "rarity": "common", "base_xp": 360,
     "common_drop": "herb_major", "rare_drop": "stimulant_large", "money_range": (50, 200),
     "basic_attack": "cleaving axe", "strong_attack": "reaver charge",
     "player_abilities": [],
     "base_str": 22, "base_dex": 12, "base_con": 18, "base_int": 5, "base_hp": 230, "base_ap": 9,
     "str_per_level": 3, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},
    {"id": "forest_shared_thornmail_beast", "name": "Thornmail Beast", "hostile_type": "creature", "role": "damage", "min_spawn_level": 35, "rarity": "uncommon", "base_xp": 440,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (60, 230),
     "basic_attack": "gore charge", "strong_attack": "spine barrage",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 24, "base_dex": 14, "base_con": 20, "base_int": 6, "base_hp": 250, "base_ap": 10,
     "str_per_level": 4, "dex_per_level": 2, "con_per_level": 3, "int_per_level": 0},
    {"id": "forest_shared_fae_trickster", "name": "Fae Trickster", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 35, "rarity": "rare", "base_xp": 560,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (80, 300),
     "basic_attack": "glamour bolt", "strong_attack": "bewildering hex",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 12, "base_dex": 22, "base_con": 14, "base_int": 26, "base_hp": 220, "base_ap": 14,
     "str_per_level": 2, "dex_per_level": 4, "con_per_level": 2, "int_per_level": 5},
    {"id": "forest_shared_elderwood_wraith", "name": "Elderwood Wraith", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 35, "rarity": "superrare", "base_xp": 900,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (140, 520),
     "basic_attack": "grave root", "strong_attack": "elder curse",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 14, "base_dex": 16, "base_con": 16, "base_int": 30, "base_hp": 240, "base_ap": 16,
     "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 5},

    # ?? Lv 40 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_bramble_juggernaut", "name": "Bramble Juggernaut", "hostile_type": "construct", "role": "damage", "min_spawn_level": 40, "rarity": "common", "base_xp": 480,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 70),
     "basic_attack": "bramble smash", "strong_attack": "thicket quake",
     "player_abilities": [],
     "base_str": 26, "base_dex": 8, "base_con": 24, "base_int": 5, "base_hp": 300, "base_ap": 9,
     "str_per_level": 4, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 0},
    {"id": "forest_shared_pack_alpha", "name": "Pack Alpha", "hostile_type": "creature", "role": "damage", "min_spawn_level": 40, "rarity": "uncommon", "base_xp": 600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (80, 300),
     "basic_attack": "alpha bite", "strong_attack": "rally howl",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 26, "base_dex": 20, "base_con": 22, "base_int": 8, "base_hp": 290, "base_ap": 11,
     "str_per_level": 4, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 1},
    {"id": "forest_shared_grovekeeper_apostate", "name": "Grovekeeper Apostate", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 40, "rarity": "rare", "base_xp": 760,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (100, 380),
     "basic_attack": "corrupt bloom", "strong_attack": "withering grasp",
     "player_abilities": ["dark_magic_lv1_shadow_tendril", "fire_earth_magic_lv2_magma_javelin"],
     "base_str": 14, "base_dex": 18, "base_con": 20, "base_int": 30, "base_hp": 280, "base_ap": 16,
     "str_per_level": 2, "dex_per_level": 3, "con_per_level": 3, "int_per_level": 5},
    {"id": "forest_shared_verdant_god_spawn", "name": "Verdant God-Spawn", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 40, "rarity": "superrare", "base_xp": 1200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (200, 720),
     "basic_attack": "primal lash", "strong_attack": "overgrowth cataclysm",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "earth_magic_lv1_tremor"],
     "base_str": 30, "base_dex": 22, "base_con": 28, "base_int": 24, "base_hp": 340, "base_ap": 18,
     "str_per_level": 5, "dex_per_level": 3, "con_per_level": 4, "int_per_level": 4},
]
