# Forest shared hostiles - rarity-coverage fill, Lv 61-80.
#
# Reusable across all forest city sizes and the forest wilderness. One seed of
# every rarity at each 5-level mark (Lv 65, 70, 75, 80) guarantees full sliding-
# window coverage for any zone. Ability ids reused from loaded band files.
# Theme (late): ancient forest spirits, void-touched predators, tree wraiths.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 65 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_deep_grove_raider", "name": "Deep Grove Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 65, "rarity": "common", "base_xp": 2600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (160, 560),
     "basic_attack": "greataxe cleave", "strong_attack": "raiding charge",
     "player_abilities": [],
     "base_str": 44, "base_dex": 22, "base_con": 38, "base_int": 8, "base_hp": 760, "base_ap": 13,
     "str_per_level": 7, "dex_per_level": 3, "con_per_level": 6, "int_per_level": 0},
    {"id": "forest_shared_shadewood_panther", "name": "Shadewood Panther", "hostile_type": "creature", "role": "damage", "min_spawn_level": 65, "rarity": "uncommon", "base_xp": 3000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (220, 760),
     "basic_attack": "shadow pounce", "strong_attack": "throat-render leap",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm"],
     "base_str": 44, "base_dex": 32, "base_con": 38, "base_int": 12, "base_hp": 800, "base_ap": 14,
     "str_per_level": 7, "dex_per_level": 5, "con_per_level": 6, "int_per_level": 1},
    {"id": "forest_shared_verdant_shaman", "name": "Verdant Shaman", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level": 65, "rarity": "rare", "base_xp": 3800,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (300, 1000),
     "basic_attack": "spore hex", "strong_attack": "rotstorm",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 28, "base_dex": 30, "base_con": 34, "base_int": 46, "base_hp": 820, "base_ap": 16,
     "str_per_level": 4, "dex_per_level": 4, "con_per_level": 5, "int_per_level": 8},
    {"id": "forest_shared_void_touched_lynx", "name": "Void-Touched Lynx", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 65, "rarity": "superrare", "base_xp": 5600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (800, 2800),
     "basic_attack": "void claw", "strong_attack": "reality pounce",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "level_1_hostile_ability_poison_dart"],
     "base_str": 52, "base_dex": 40, "base_con": 44, "base_int": 30, "base_hp": 900, "base_ap": 22,
     "str_per_level": 8, "dex_per_level": 6, "con_per_level": 7, "int_per_level": 4},

    # ?? Lv 70 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_titan_root_golem", "name": "Titan Root Golem", "hostile_type": "construct", "role": "damage", "min_spawn_level": 70, "rarity": "common", "base_xp": 3600,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 110),
     "basic_attack": "titan root slam", "strong_attack": "grove-shaking quake",
     "player_abilities": [],
     "base_str": 52, "base_dex": 12, "base_con": 48, "base_int": 6, "base_hp": 1000, "base_ap": 13,
     "str_per_level": 8, "dex_per_level": 1, "con_per_level": 8, "int_per_level": 0},
    {"id": "forest_shared_bloodmoon_hunter", "name": "Bloodmoon Hunter", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 70, "rarity": "uncommon", "base_xp": 4200,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (280, 900),
     "basic_attack": "bloodmoon shot", "strong_attack": "crimson volley",
     "player_abilities": ["fire_technique_lv1_scorch_slash"],
     "base_str": 48, "base_dex": 36, "base_con": 42, "base_int": 12, "base_hp": 960, "base_ap": 15,
     "str_per_level": 7, "dex_per_level": 5, "con_per_level": 6, "int_per_level": 1},
    {"id": "forest_shared_colossal_tree_wraith", "name": "Colossal Tree Wraith", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 70, "rarity": "rare", "base_xp": 5200,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (360, 1200),
     "basic_attack": "haunting bough", "strong_attack": "wraithwood knell",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 40, "base_dex": 30, "base_con": 42, "base_int": 52, "base_hp": 1100, "base_ap": 18,
     "str_per_level": 6, "dex_per_level": 4, "con_per_level": 6, "int_per_level": 9},
    {"id": "forest_shared_ancient_forest_spirit", "name": "Ancient Forest Spirit", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 70, "rarity": "superrare", "base_xp": 7800,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (1200, 4000),
     "basic_attack": "primeval wrath", "strong_attack": "forest cataclysm",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field"],
     "base_str": 60, "base_dex": 34, "base_con": 54, "base_int": 40, "base_hp": 1300, "base_ap": 22,
     "str_per_level": 10, "dex_per_level": 5, "con_per_level": 9, "int_per_level": 6},

    # ?? Lv 75 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_wildwood_berserker", "name": "Wildwood Berserker", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 75, "rarity": "common", "base_xp": 4800,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (220, 760),
     "basic_attack": "frenzied cleave", "strong_attack": "bloodwood rampage",
     "player_abilities": [],
     "base_str": 56, "base_dex": 26, "base_con": 48, "base_int": 8, "base_hp": 1200, "base_ap": 15,
     "str_per_level": 9, "dex_per_level": 3, "con_per_level": 7, "int_per_level": 0},
    {"id": "forest_shared_dire_grove_serpent", "name": "Dire Grove Serpent", "hostile_type": "creature", "role": "damage", "min_spawn_level": 75, "rarity": "uncommon", "base_xp": 5400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (300, 1000),
     "basic_attack": "venomous coil", "strong_attack": "crushing constriction",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 56, "base_dex": 34, "base_con": 50, "base_int": 10, "base_hp": 1280, "base_ap": 16,
     "str_per_level": 8, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 1},
    {"id": "forest_shared_umbral_dryad_queen", "name": "Umbral Dryad Queen", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 75, "rarity": "rare", "base_xp": 6600,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (400, 1400),
     "basic_attack": "umbral bloom", "strong_attack": "queen's withering",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 40, "base_dex": 40, "base_con": 46, "base_int": 58, "base_hp": 1300, "base_ap": 18,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 6, "int_per_level": 10},
    {"id": "forest_shared_heart_of_the_wild", "name": "Heart of the Wild", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 75, "rarity": "superrare", "base_xp": 9600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (1600, 5000),
     "basic_attack": "primal surge", "strong_attack": "verdant annihilation",
     "player_abilities": ["dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field", "fire_earth_magic_lv2_magma_javelin"],
     "base_str": 64, "base_dex": 38, "base_con": 58, "base_int": 42, "base_hp": 1500, "base_ap": 22,
     "str_per_level": 10, "dex_per_level": 5, "con_per_level": 9, "int_per_level": 6},

    # ?? Lv 80 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_grovelord_champion", "name": "Grovelord Champion", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 80, "rarity": "common", "base_xp": 6000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (280, 900),
     "basic_attack": "champion cleave", "strong_attack": "grovelord onslaught",
     "player_abilities": [],
     "base_str": 62, "base_dex": 28, "base_con": 54, "base_int": 8, "base_hp": 1500, "base_ap": 16,
     "str_per_level": 10, "dex_per_level": 3, "con_per_level": 8, "int_per_level": 0},
    {"id": "forest_shared_nightbloom_horror", "name": "Nightbloom Horror", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 80, "rarity": "uncommon", "base_xp": 6800,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (360, 1200),
     "basic_attack": "nightbloom spores", "strong_attack": "toxic full bloom",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm"],
     "base_str": 40, "base_dex": 40, "base_con": 48, "base_int": 56, "base_hp": 1520, "base_ap": 19,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 9},
    {"id": "forest_shared_voidwood_devourer", "name": "Voidwood Devourer", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 80, "rarity": "rare", "base_xp": 8600,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (520, 1800),
     "basic_attack": "void bough rend", "strong_attack": "consuming thicket",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 60, "base_dex": 42, "base_con": 54, "base_int": 34, "base_hp": 1700, "base_ap": 20,
     "str_per_level": 9, "dex_per_level": 6, "con_per_level": 8, "int_per_level": 4},
    {"id": "forest_shared_worldtree_colossus", "name": "Worldtree Colossus", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 80, "rarity": "superrare", "base_xp": 14000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (2200, 7000),
     "basic_attack": "worldtree slam", "strong_attack": "canopy apocalypse",
     "player_abilities": ["dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field", "fire_earth_magic_lv2_magma_javelin"],
     "base_str": 74, "base_dex": 32, "base_con": 68, "base_int": 40, "base_hp": 2000, "base_ap": 22,
     "str_per_level": 12, "dex_per_level": 4, "con_per_level": 11, "int_per_level": 6},
]
