# Forest shared hostiles - rarity-coverage fill, Lv 81-100.
#
# Reusable across all forest city sizes and the forest wilderness. One seed of
# every rarity at each 5-level mark (Lv 85, 90, 95, 100) guarantees full
# sliding-window coverage for any zone. Ability ids reused from loaded band
# files. Theme: apex void-touched forest gods and colossal tree wraiths.

RANDOM_HOSTILE_SEEDS = [

    # ?? Lv 85 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_ancient_warband_lord", "name": "Ancient Warband Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 85, "rarity": "common", "base_xp": 8400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (360, 1200),
     "basic_attack": "warlord cleave", "strong_attack": "ancestral onslaught",
     "player_abilities": [],
     "base_str": 68, "base_dex": 32, "base_con": 60, "base_int": 10, "base_hp": 1750, "base_ap": 18,
     "str_per_level": 10, "dex_per_level": 4, "con_per_level": 8, "int_per_level": 0},
    {"id": "forest_shared_direwood_matriarch", "name": "Direwood Matriarch", "hostile_type": "creature", "role": "damage", "min_spawn_level": 85, "rarity": "uncommon", "base_xp": 9400,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (460, 1600),
     "basic_attack": "matriarch maul", "strong_attack": "primal rampage",
     "player_abilities": ["earth_magic_lv1_tremor"],
     "base_str": 70, "base_dex": 40, "base_con": 62, "base_int": 12, "base_hp": 1850, "base_ap": 19,
     "str_per_level": 10, "dex_per_level": 5, "con_per_level": 9, "int_per_level": 1},
    {"id": "forest_shared_blightheart_lich", "name": "Blightheart Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 85, "rarity": "rare", "base_xp": 11500,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (600, 2000),
     "basic_attack": "blight bolt", "strong_attack": "rotheart apocalypse",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 44, "base_dex": 40, "base_con": 52, "base_int": 70, "base_hp": 1900, "base_ap": 22,
     "str_per_level": 6, "dex_per_level": 5, "con_per_level": 7, "int_per_level": 12},
    {"id": "forest_shared_void_grove_god", "name": "Void Grove God", "hostile_type": "eldritch", "role": "damage", "min_spawn_level": 85, "rarity": "superrare", "base_xp": 40000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (10000, 34000),
     "basic_attack": "void grove wrath", "strong_attack": "grove-end cataclysm",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field"],
     "base_str": 80, "base_dex": 46, "base_con": 72, "base_int": 60, "base_hp": 24000, "base_ap": 70,
     "str_per_level": 14, "dex_per_level": 6, "con_per_level": 12, "int_per_level": 10},

    # ?? Lv 90 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_grovebreaker_titan", "name": "Grovebreaker Titan", "hostile_type": "construct", "role": "damage", "min_spawn_level": 90, "rarity": "common", "base_xp": 12000,
     "common_drop": None, "rare_drop": "herb_major", "money_range": (0, 130),
     "basic_attack": "titan bough smash", "strong_attack": "grovebreak quake",
     "player_abilities": [],
     "base_str": 86, "base_dex": 16, "base_con": 78, "base_int": 8, "base_hp": 2400, "base_ap": 16,
     "str_per_level": 12, "dex_per_level": 2, "con_per_level": 11, "int_per_level": 0},
    {"id": "forest_shared_apex_shadow_stalker", "name": "Apex Shadow Stalker", "hostile_type": "creature", "role": "damage", "min_spawn_level": 90, "rarity": "uncommon", "base_xp": 13500,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (560, 1900),
     "basic_attack": "apex pounce", "strong_attack": "shadow evisceration",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm"],
     "base_str": 84, "base_dex": 56, "base_con": 74, "base_int": 16, "base_hp": 2200, "base_ap": 21,
     "str_per_level": 10, "dex_per_level": 7, "con_per_level": 9, "int_per_level": 1},
    {"id": "forest_shared_worldroot_warden", "name": "Worldroot Warden", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 90, "rarity": "rare", "base_xp": 16000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (700, 2500),
     "basic_attack": "worldroot lash", "strong_attack": "primeval bulwark",
     "player_abilities": ["dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field"],
     "base_str": 60, "base_dex": 44, "base_con": 66, "base_int": 80, "base_hp": 2300, "base_ap": 24,
     "str_per_level": 8, "dex_per_level": 5, "con_per_level": 9, "int_per_level": 14},

    # ?? Lv 95 ??????????????????????????????????????????????????????????????
    {"id": "forest_shared_primal_wildlord", "name": "Primal Wildlord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 95, "rarity": "common", "base_xp": 16000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (600, 2000),
     "basic_attack": "wildlord cleave", "strong_attack": "primal rampage",
     "player_abilities": [],
     "base_str": 92, "base_dex": 40, "base_con": 82, "base_int": 12, "base_hp": 2500, "base_ap": 20,
     "str_per_level": 12, "dex_per_level": 5, "con_per_level": 10, "int_per_level": 0},
    {"id": "forest_shared_eclipsewood_beast", "name": "Eclipsewood Beast", "hostile_type": "creature", "role": "damage", "min_spawn_level": 95, "rarity": "uncommon", "base_xp": 17500,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (700, 2400),
     "basic_attack": "eclipse maw", "strong_attack": "umbral devour",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm"],
     "base_str": 94, "base_dex": 58, "base_con": 84, "base_int": 18, "base_hp": 2600, "base_ap": 22,
     "str_per_level": 12, "dex_per_level": 7, "con_per_level": 10, "int_per_level": 1},
    {"id": "forest_shared_wraithcanopy_sovereign", "name": "Wraithcanopy Sovereign", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 95, "rarity": "rare", "base_xp": 21000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (900, 3200),
     "basic_attack": "sovereign hex", "strong_attack": "canopy of the dead",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 50, "base_dex": 56, "base_con": 64, "base_int": 96, "base_hp": 2400, "base_ap": 26,
     "str_per_level": 6, "dex_per_level": 7, "con_per_level": 8, "int_per_level": 14},

    # ?? Lv 100 ?????????????????????????????????????????????????????????????
    {"id": "forest_shared_worldheart_behemoth", "name": "Worldheart Behemoth", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 100, "rarity": "common", "base_xp": 22000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (800, 2600),
     "basic_attack": "worldheart smash", "strong_attack": "forest-quake finality",
     "player_abilities": [],
     "base_str": 100, "base_dex": 44, "base_con": 92, "base_int": 14, "base_hp": 2900, "base_ap": 22,
     "str_per_level": 13, "dex_per_level": 5, "con_per_level": 11, "int_per_level": 0},
    {"id": "forest_shared_verdant_apex_predator", "name": "Verdant Apex Predator", "hostile_type": "creature", "role": "damage", "min_spawn_level": 100, "rarity": "uncommon", "base_xp": 24000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (900, 3000),
     "basic_attack": "apex evisceration", "strong_attack": "verdant slaughter",
     "player_abilities": ["level_1_hostile_ability_poison_dart"],
     "base_str": 102, "base_dex": 66, "base_con": 92, "base_int": 18, "base_hp": 3000, "base_ap": 23,
     "str_per_level": 13, "dex_per_level": 8, "con_per_level": 11, "int_per_level": 1},
    {"id": "forest_shared_god_of_the_endless_grove", "name": "God of the Endless Grove", "hostile_type": "eldritch", "role": "hazard", "min_spawn_level": 100, "rarity": "rare", "base_xp": 30000,
     "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (1200, 4000),
     "basic_attack": "endless bloom", "strong_attack": "grove without end",
     "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
     "base_str": 60, "base_dex": 60, "base_con": 72, "base_int": 110, "base_hp": 2900, "base_ap": 28,
     "str_per_level": 8, "dex_per_level": 8, "con_per_level": 9, "int_per_level": 16},
    {"id": "forest_shared_worldtree_god", "name": "The Worldtree God", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 120000,
     "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (40000, 120000),
     "basic_attack": "world-branch descent", "strong_attack": "the endless overgrowth",
     "player_abilities": ["dark_dark_dark_magic_lv3_shadow_blast", "earth_earth_magic_lv2_quake_field", "fire_earth_magic_lv2_magma_javelin", "dark_dark_magic_lv2_umbra_storm"],
     "base_str": 130, "base_dex": 52, "base_con": 120, "base_int": 60, "base_hp": 90000, "base_ap": 26,
     "str_per_level": 26, "dex_per_level": 6, "con_per_level": 24, "int_per_level": 8},
]
