# Magic abilities for level 5
LEVEL_5_MAGIC_ABILITY_SEEDS = [
    {"id": "dark_earth_magic_lv5_shadow_erode", "name": "Shadow Erode", "description": "Insidious darkness that reduces resilience.", "ability_type": "magic", "level":5, "elements": ["dark", "earth", "air", "fire", "water"], "base_power":0, "ap_cost":160, "effect": "status", "status_keys": ["defense_debuff", "continuous_damage", "elemental_debuff"], "can_aoe": True},
    {"id": "light_air_magic_lv5_arcane_focus", "name": "Arcane Focus", "description": "A concentrated arcane snap that heightens mental acuity.", "ability_type": "magic", "level":5, "elements": ["light", "air", "fire", "water", "earth"], "base_power":0, "ap_cost":170, "effect": "status", "status_keys": ["intelligence_buff","intelligence_buff","intelligence_buff", "dexterity_buff", "constitution_buff", "constitution_buff"], "can_aoe": True},
    {"id": "water_air_magic_lv5_frost_lash", "name": "Frost Lash", "description": "Biting cold that gnaws health over time.", "ability_type": "magic", "level":5, "elements": ["water", "air", "dark", "fire", "earth"], "base_power":72, "ap_cost":100, "effect": "status", "status_keys": ["continuous_damage"], "can_aoe": False},
    {"id": "earth_air_dark_magic_lv5_sand_rot", "name": "Sand Rot", "description": "A gritty curse that weakens elemental cohesion.", "ability_type": "magic", "level":5, "elements": ["earth", "air", "dark", "fire", "water"], "base_power":0, "ap_cost":160, "effect": "status", "status_keys": ["elemental_debuff", "elemental_debuff", "continuous_damage"], "can_aoe": True},
    {"id": "water_dark_magic_lv5_frostbite_net", "name": "Frostbite Net", "description": "Icy chains that wrench elemental balance. (duplicate)", "ability_type": "magic", "level":5, "elements": ["water", "dark", "fire", "earth", "air"], "base_power":0, "ap_cost":160, "effect": "status", "status_keys": ["elemental_debuff", "continuous_damage", "stun"], "can_aoe": True},
    {"id": "water_earth_magic_lv5_tide_shield", "name": "Tide Shield", "description": "Water wards that absorb incoming force.", "ability_type": "magic", "level":5, "elements": ["water", "earth", "air", "fire", "light"], "base_power":25, "ap_cost":160, "effect": "status", "status_keys": ["elemental_defense_buff", "regen", "defense_buff"], "can_aoe": True},
    {"id": "water_dark_magic_lv5_gloom_Tsunami", "name": "Gloom Tsunami", "description": "A rolling tide of confusion that dulls thought.", "ability_type": "magic", "level":5, "elements": ["water", "dark", "fire", "air", "earth"], "base_power":0, "ap_cost":185, "effect": "status", "status_keys": ["intelligence_debuff", "continuous_damage", "confuse"], "can_aoe": True},
    {"id": "dark_magic_lv5_abyssal_shadow", "name": "Abyssal Shadow", "description": "Call upon dark energies.", "ability_type": "magic", "level":5, "elements": ["dark", "air", "fire", "water", "earth"], "base_power":195, "ap_cost":176, "effect": "damage", "can_aoe": False},
    {"id": "light_magic_lv5_solar_cataclysm", "name": "Solar Cataclysm", "description": "A blinding eruption of solar energy.", "ability_type": "magic", "level":5, "elements": ["light", "fire", "air", "earth", "water"], "base_power":208, "ap_cost":190, "effect": "damage", "can_aoe": False},
    {"id": "fire_magic_lv5_cinder_shower", "name": "Cinder Shower", "description": "A falling rain of hot embers.", "ability_type": "magic", "level":5, "elements": ["fire", "air", "light", "dark", "earth"], "base_power":165, "ap_cost":170, "effect": "damage", "can_aoe": True},
    {"id": "dark_magic_lv5_void_corridor", "name": "Void Corridor", "description": "Open a rift that siphons life through the void.", "ability_type": "magic", "level":5, "elements": ["dark", "dark", "air", "earth", "water"], "base_power":215, "ap_cost":198, "effect": "damage", "can_aoe": False},
    {"id": "air_magic_lv5_gale_cascade", "name": "Gale Cascade", "description": "A cascading wind that tosses foes.", "ability_type": "magic", "level":5, "elements": ["air", "air", "water", "light", "earth"], "base_power":165, "ap_cost":170, "effect": "damage", "can_aoe": True},

    #### NON PLAYER ABILITIES
    # cataclysm — damage: singular focused catastrophe, a world ending in one precise moment
    {"id": "calamity", "name": "Calamity", "description": "Cataclysm compresses the entropy of an entire collapsing world into a single point and releases it at one target — a catastrophe delivered with the calm certainty of inevitability.", "ability_type": "magic", "level": 5, "elements": ["dark", "fire", "earth", "dark", "fire"], "base_power": 210, "ap_cost": 178, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # oracle — hazard: the vision that unmakes you
    {"id": "vision_of_ruin", "name": "Vision of Ruin", "description": "Oracle forces a precise, unavoidable vision of the target's destruction directly into their mind — not a metaphor, not a warning, but the real thing arriving early, burning through reality to become true.", "ability_type": "magic", "level": 5, "elements": ["dark", "fire", "light", "dark", "air"], "base_power": 195, "ap_cost": 168, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # reliquary — hazard: memory weaponised as pain
    {"id": "memory_of_suffering", "name": "Memory of Suffering", "description": "Reliquary retrieves the target's most precise memory of pain from its archive and replays it at full fidelity — not as recollection but as re-experience, stripping away the will to fight and the strength to endure.", "ability_type": "magic", "level": 5, "elements": ["dark", "water", "ice", "dark", "earth"], "base_power": 20, "ap_cost": 190, "effect": "status", "status_keys": ["attack_debuff", "constitution_debuff", "defense_debuff", "continuous_damage"], "can_aoe": True, "non_player_ability": True},
    # lament_trial — hazard: the weight of grief
    {"id": "crushing_despair", "name": "Crushing Despair", "description": "Lament releases grief without object or source — a weight that settles into the target's chest and makes every action feel pointless, every effort feel like rehearsing a failure that has already occurred, until even standing feels like too much.", "ability_type": "magic", "level": 5, "elements": ["dark", "ice", "water", "dark", "ice"], "base_power": 20, "ap_cost": 194, "effect": "status", "status_keys": ["attack_debuff", "defense_debuff", "dexterity_debuff", "elemental_debuff"], "can_aoe": True, "non_player_ability": True},
    # lament_trial — hazard: the silence after
    {"id": "hollow_silence", "name": "Hollow Silence", "description": "Lament does not suppress sound. It removes the part of the target that wanted to speak — leaving behind a hollow where language used to live, unable to reach anyone who might hear it, the mind stumbling in the empty space.", "ability_type": "magic", "level": 5, "elements": ["dark", "water", "ice", "water", "dark"], "base_power": 40, "ap_cost": 182, "effect": "status", "status_keys": ["silence", "intelligence_debuff", "attack_debuff"], "can_aoe": False, "non_player_ability": True},
    # lament_trial — hazard: nothing remains
    {"id": "the_emptiness", "name": "The Emptiness", "description": "Lament exposes the target to the sensation of complete absence — not darkness, not silence, but the precise feeling of there being nothing where something should be. Thought slows, purpose dissolves, and even the impulse to speak fades to nothing.", "ability_type": "magic", "level": 5, "elements": ["dark", "ice", "dark", "water", "ice"], "base_power": 20, "ap_cost": 176, "effect": "status", "status_keys": ["intelligence_debuff", "stun", "defense_debuff", "dexterity_debuff", "continuous_damage"], "can_aoe": False, "non_player_ability": True},
    # paradox_trial — hazard: both states at once, destructive
    {"id": "paradox_embrace", "name": "Paradox Embrace", "description": "Paradox holds both the attack and its absence at the same time — a strike that is simultaneously real and not, landing in the space where certainty used to be and detonating there.", "ability_type": "magic", "level": 5, "elements": ["dark", "light", "electric", "dark", "light"], "base_power": 208, "ap_cost": 188, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # revelry_trial — damage: AoE sensory cascade
    {"id": "euphoric_cascade", "name": "Euphoric Cascade", "description": "Revelry floods the field with a cascade of overwhelming sensation — light, sound, heat, pressure, all at once. It doesn't discriminate between friend and foe. That's part of the appeal.", "ability_type": "magic", "level": 5, "elements": ["fire", "air", "electric", "fire", "light"], "base_power": 178, "ap_cost": 190, "effect": "damage", "can_aoe": True, "non_player_ability": True},
    # revelry_trial — hazard: too much at once
    {"id": "sensory_overload", "name": "Sensory Overload", "description": "Revelry drives stimulation past the threshold of processing and into the territory of collapse — the target's mind fuses input and response into a single undifferentiated noise that cannot be directed, cannot be spoken through, cannot be steadied.", "ability_type": "magic", "level": 5, "elements": ["fire", "electric", "air", "light", "fire"], "base_power": 20, "ap_cost": 195, "effect": "status", "status_keys": ["confuse", "silence", "dexterity_debuff", "elemental_debuff"], "can_aoe": True, "non_player_ability": True},
    # garbage_trial — hazard: the thought you didn't want
    {"id": "intrusive_truth", "name": "Intrusive Truth", "description": "Garbage inserts a single unwanted thought with surgical precision — not a lie, not an exaggeration, just something true that the target had successfully not been thinking about until this exact moment, and now cannot stop thinking about, cannot reason around, cannot voice.", "ability_type": "magic", "level": 5, "elements": ["dark", "air", "earth", "dark", "air"], "base_power": 20, "ap_cost": 182, "effect": "status", "status_keys": ["intelligence_debuff", "confuse", "continuous_damage"], "can_aoe": False, "non_player_ability": True},
    # garbage_trial — hazard: turned against yourself
    {"id": "self_sabotage", "name": "Self Sabotage", "description": "Garbage doesn't attack the target. It hands them the attack and steps back. The doubt is already there — it just needed to be pointed in the right direction, and now it turns every strength inward.", "ability_type": "magic", "level": 5, "elements": ["dark", "earth", "air", "dark", "earth"], "base_power": 25, "ap_cost": 180, "effect": "status", "status_keys": ["intelligence_debuff", "strength_debuff", "continuous_damage"], "can_aoe": False, "non_player_ability": True},
    # cataclysm_trial — damage: data-driven ending
    {"id": "inevitable_failure", "name": "Inevitable Failure", "description": "Cataclysm applies every recorded failure simultaneously — every mistake, every hesitation, every miscalculation stripped of context and re-delivered as pure structural consequence. The collapse was always going to happen. The data said so, and the body agrees.", "ability_type": "magic", "level": 5, "elements": ["fire", "dark", "earth", "dark", "fire"], "base_power": 90, "ap_cost": 188, "effect": "status", "status_keys": ["constitution_debuff", "defense_debuff", "attack_debuff"], "can_aoe": True, "non_player_ability": True},
    # dominion — tank: the lattice that closes around everything
    {"id": "void_lattice", "name": "Void Lattice", "description": "Dominion extends a lattice of dark systemic force that contracts around a single target with the patient certainty of something designed from the beginning to have no exit. It does not hurry. It does not need to.", "ability_type": "magic", "level": 5, "elements": ["dark", "dark", "earth", "dark", "light"], "base_power": 205, "ap_cost": 188, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # the_void — damage: the ending itself
    {"id": "eternal_void", "name": "Eternal Void", "description": "The Void does not strike. It arrives — the complete and total absence of everything, delivered to a single point with the finality of something that was never not going to happen. The silence after is not silence. It is the end of the category that silence belonged to.", "ability_type": "magic", "level": 5, "elements": ["dark", "dark", "dark", "dark", "dark"], "base_power": 270, "ap_cost": 240, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # the_void — damage: no limit, no boundary, AoE
    {"id": "unfinity", "name": "Unfinity", "description": "The Void applies the concept of no boundary as a weapon — a wave of annihilation that does not select targets because selection implies a limit, and there are none. What remains after is not wreckage. It is simply less.", "ability_type": "magic", "level": 5, "elements": ["dark", "dark", "dark", "dark", "light"], "base_power": 180, "ap_cost": 200, "effect": "damage", "can_aoe": True, "non_player_ability": True},
]