# Skill abilities for level5
LEVEL_5_SKILL_ABILITY_SEEDS = [
    {"id": "water_earth_skill_lv5_sap_overgrowth", "name": "Sap Overgrowth", "description": "A sticky bloom that weakens plating and hide.", "ability_type": "skill", "level":5, "elements": ["water", "earth", "fire", "air", "light"], "base_power":5, "ap_cost":160, "effect": "status", "status_keys": ["defense_debuff", "dexterity_debuff", "stun", "continuous_damage"], "can_aoe": True},
    {"id": "earth_dark_skill_lv5_venom_trace", "name": "Venom Trace", "description": "A lingering toxin that deals ongoing harm.", "ability_type": "skill", "level":5, "elements": ["earth", "dark", "fire", "water", "air"], "base_power":15, "ap_cost":170, "effect": "status", "status_keys": ["continuous_damage", "elemental_debuff", "elemental_debuff"], "can_aoe": True},
    {"id": "water_skill_lv5_riptide_chain", "name": "Riptide Chain", "description": "A linked rip that catches multiple foes.", "ability_type": "skill", "level":5, "elements": ["water", "water", "air", "light", "earth"], "base_power":165, "ap_cost":170, "effect": "damage", "can_aoe": True},
    {"id": "fire_skill_lv5_ember_wake", "name": "Ember Wake", "description": "A wake of embers follows your strike.", "ability_type": "skill", "level":5, "elements": ["fire", "earth", "air", "light", "dark"], "base_power":165, "ap_cost":170, "effect": "damage", "can_aoe": True},

  #### NON PLAYER ABILITIES
    # rapture_trial — damage: pure adrenaline burst
    {"id": "adrenaline_surge", "name": "Adrenaline Surge", "description": "Rapture floods the body with manufactured adrenaline until every nerve is screaming forward — a burst of violence so fast and total that it doesn't feel like a choice so much as a detonation.", "ability_type": "skill", "level": 5, "elements": ["fire", "electric", "air", "fire", "electric"], "base_power": 160, "ap_cost": 126, "effect": "damage", "can_aoe": False, "non_player_ability": True},
    # rapture_trial — damage AoE: all-in, no recovery
    {"id": "reckless_abandon", "name": "Reckless Abandon", "description": "Rapture throws every resource into a single eruption of force with no thought for what comes after — the joy is in the going, not the surviving.", "ability_type": "skill", "level": 5, "elements": ["fire", "air", "electric", "air", "fire"], "base_power": 128, "ap_cost": 145, "effect": "damage", "can_aoe": True, "non_player_ability": True},
    # rapture_trial — damage: the high that demands more
    {"id": "thrill_addiction", "name": "Thrill Addiction", "description": "Rapture locks the target into an escalating feedback loop of stimulation — each hit wires the nervous system for more, and the damage compounds as the body struggles to process the overload, its guard forgotten in the rush.", "ability_type": "skill", "level": 5, "elements": ["fire", "electric", "air", "electric", "fire"], "base_power": 65, "ap_cost": 168, "effect": "status", "status_keys": ["continuous_damage", "defense_debuff"], "can_aoe": False, "non_player_ability": True},
    # revelry_trial — damage: pure speed burst
    {"id": "the_rush", "name": "The Rush", "description": "Revelry moves at the frequency of pure exhilaration — a strike so fast it lands before the target's perception catches up, hitting the body and the will simultaneously.", "ability_type": "skill", "level": 5, "elements": ["fire", "air", "electric", "fire", "air"], "base_power": 168, "ap_cost": 130, "effect": "damage", "can_aoe": False, "non_player_ability": True},
]
