# Spirit abilities for level 5
LEVEL_5_SPIRIT_ABILITY_SEEDS = [
    {"id": "light_light_light_light_light_spirit_lv5_apotheosis", "name": "Apotheosis", "description": "An overwhelming beam of pure light that extensively mends a single ally.", "ability_type": "spirit", "level":5, "elements": ["light", "light", "light", "light", "light"], "base_power":182, "ap_cost":163, "effect": "heal", "can_aoe": False},
    {"id": "light_light_light_air_water_spirit_lv5_prismatic_cascade", "name": "Prismatic Cascade", "description": "A vast cascade of light, air and water that restores many allies.", "ability_type": "spirit", "level":5, "elements": ["light", "light", "light", "air", "water"], "base_power":125, "ap_cost":148, "effect": "heal", "can_aoe": True},
    {"id": "light_light_light_dark_dark_spirit_lv5_resurrection_rite", "name": "Resurrection Rite", "description": "A solemn rite that fully restores life to a fallen ally (percentage-based revive).", "ability_type": "spirit", "level":5, "elements": ["light", "light", "light", "dark", "dark"], "base_power":150, "ap_cost":250, "effect": "revive", "can_aoe": True},
    {"id": "light_spirit_lv5_ardent_inspire", "name": "Ardent Inspire", "description": "Rousing light that sharpens ally blows.", "ability_type": "spirit", "level":5, "elements": ["light", "fire", "water", "earth", "air"], "base_power":0, "ap_cost":160, "effect": "status", "status_keys": ["attack_buff", "elemental_attack_buff", "dexterity_buff", "intelligence_buff", "dexterity_buff", "intelligence_buff"], "can_aoe": True},
    {"id": "light_water_spirit_lv5_halo_coat", "name": "Halo Coat", "description": "A soft shining coat that soothes and deflects.", "ability_type": "spirit", "level":5, "elements": ["light", "water", "earth", "air", "fire"], "base_power":0, "ap_cost":160, "effect": "status", "status_keys": ["defense_buff", "elemental_defense_buff", "dexterity_buff", "regen"], "can_aoe": True},
    {"id": "water_spirit_lv5_stream_savant", "name": "Stream Savant", "description": "A flowing clarity of mind drawn from water's patience.", "ability_type": "spirit", "level":5, "elements": ["water", "fire", "earth", "air", "light"], "base_power":0, "ap_cost":160, "effect": "status", "status_keys": ["intelligence_buff", "regen", "dexterity_buff", "elemental_defense_buff"], "can_aoe": True},
    {"id": "light_spirit_lv5_echoing_prayer", "name": "Echoing Prayer", "description": "A radiant hymn that bolsters allies' resolve.", "ability_type": "spirit", "level":5, "elements": ["light", "water", "light", "air", "earth"], "base_power":60, "ap_cost":180, "effect": "cure", "status_keys": ["all"], "can_aoe": True},
    {"id": "spirit_lv5_guardian_oath", "name": "Guardian Oath", "description": "An oath that grants nearby allies temporary fortitude.", "ability_type": "spirit", "level":5, "elements": ["light", "earth", "water", "air", "fire"], "base_power":0, "ap_cost":190, "effect": "status", "status_keys": ["defense_buff","defense_buff","defense_buff","regen", "elemental_defense_buff","regen", "elemental_defense_buff"], "can_aoe": True},
    {"id": "water_spirit_lv5_soothing_tide", "name": "Soothing Tide", "description": "A flowing ward that steadies and protects allies.", "ability_type": "spirit", "level":5, "elements": ["water", "light", "earth", "air", "fire"], "base_power":5, "ap_cost":165, "effect": "cure", "status_keys": ["defense_debuff", "continuous_damage", "elemental_debuff", "strength_debuff", "intelligence_debuff", "attack_debuff", ], "can_aoe": True},
 
    #### NON PLAYER ABILITIES
    # edict_trial — tank: procedural inevitability (spirit)
    {"id": "procedural_inevitability", "name": "Procedural Inevitability", "description": "Edict invokes a power beyond argument — the process has already determined the outcome. Every resistance is already accounted for in the procedure, hardening the system against all deviation.", "ability_type": "spirit", "level": 5, "elements": ["dark", "light", "earth", "dark", "light"], "base_power": 18, "ap_cost": 188, "effect": "status", "status_keys": ["defense_buff", "elemental_defense_buff", "constitution_buff", "regen"], "can_aoe": True, "non_player_ability": True},
    # glamour_trial — support: certainty field
    {"id": "certainty_field", "name": "Certainty Field", "description": "Glamour projects an aura of absolute conviction — doubt dissolves, resistance feels irrational, and the enemy's will to act wavers and scatters beneath the weight of manufactured certainty.", "ability_type": "spirit", "level": 5, "elements": ["light", "air", "ice", "light", "air"], "base_power": 0, "ap_cost": 112, "effect": "status", "status_keys": ["intelligence_debuff", "confuse", "attack_debuff"], "can_aoe": True, "non_player_ability": True},
    # glamour_trial — support: doubt erasure (spirit)
    {"id": "doubt_erasure", "name": "Doubt Erasure", "description": "Glamour reaches into the target's mind and cleanly excises uncertainty — filling the void with a calm, purposeful compliance that feels entirely self-generated, leaving no room for protest.", "ability_type": "spirit", "level": 5, "elements": ["light", "ice", "light", "air", "light"], "base_power": 35, "ap_cost": 186, "effect": "status", "status_keys": ["confuse", "silence", "defense_debuff", "defense_debuff", "constitution_debuff"], "can_aoe": False, "non_player_ability": True},
    # glamour_trial — support: calm enforcement (spirit)
    {"id": "calm_enforcement", "name": "Calm Enforcement", "description": "Glamour enforces serenity — a total suppression of aggression and noise. The target is left functional, compliant, and unable to act against the system's design, their fury drained to nothing.", "ability_type": "spirit", "level": 5, "elements": ["light", "air", "light", "ice", "dark"], "base_power": 8, "ap_cost": 168, "effect": "status", "status_keys": ["silence", "attack_debuff", "elemental_debuff", "constitution_debuff", "constitution_debuff"], "can_aoe": False, "non_player_ability": True},
    # oracle — hazard: the prophecy cannot be escaped
    {"id": "inescapable_prophecy", "name": "Inescapable Prophecy", "description": "Oracle speaks the target's ending aloud — a single, certain sentence that unravels their sense of agency and leaves them spiralling in the predetermined loop of what was already written, frozen at the moment of realization.", "ability_type": "spirit", "level": 5, "elements": ["dark", "light", "ice", "dark", "air"], "base_power": 2, "ap_cost": 200, "effect": "status", "status_keys": ["confuse", "stun", "continuous_damage", "elemental_debuff"], "can_aoe": False, "non_player_ability": True},
    # oracle — hazard: a moment locked in time
    {"id": "fate_lock", "name": "Fate Lock", "description": "Oracle reaches into the timeline and pins the target to a single frozen instant — a moment that was always meant to be their last breath, held indefinitely.", "ability_type": "spirit", "level": 5, "elements": ["light", "dark", "ice", "air", "light"], "base_power": 1, "ap_cost": 230, "effect": "status", "status_keys": ["petrify", "stun", "confuse", "silence"], "can_aoe": True, "non_player_ability": True},
    # reliquary — hazard: a wound the collection will not let close
    {"id": "eternal_wound", "name": "Eternal Wound", "description": "Reliquary catalogues the target's worst injury and preserves it perfectly — the wound cannot scar, cannot close, and bleeds with the patient certainty of something that was always meant to last forever, leaving the flesh around it defenceless.", "ability_type": "spirit", "level": 5, "elements": ["dark", "earth", "ice", "dark", "water"], "base_power": 15, "ap_cost": 165, "effect": "status", "status_keys": ["continuous_damage", "defense_debuff", "elemental_debuff"], "can_aoe": False, "non_player_ability": True},
    # reliquary — hazard/damage: the weight of preserved grief
    {"id": "burden_of_the_lost", "name": "Burden of the Lost", "description": "Reliquary opens its archive and places every preserved loss directly onto the target — the collective weight of what can never be recovered presses down until endurance falters, guard sags, and the will to strike back drains away.", "ability_type": "spirit", "level": 5, "elements": ["dark", "water", "earth", "ice", "dark"], "base_power": 15, "ap_cost": 114, "effect": "status", "status_keys": ["constitution_debuff", "defense_debuff", "attack_debuff", "stun", "dexterity_debuff"], "can_aoe": False, "non_player_ability": True},
    # garbage_trial — hazard: knowledge that harms, spirit
    {"id": "unwanted_knowing", "name": "Unwanted Knowing", "description": "Garbage doesn't explain or argue. It simply makes the target aware of something they cannot unknow — a truth that sits in the mind like an object in a wound, preventing any thought around it from closing cleanly, and stealing the words they would use to answer.", "ability_type": "spirit", "level": 5, "elements": ["dark", "air", "earth", "dark", "water"], "base_power": 12, "ap_cost": 186, "effect": "status", "status_keys": ["confuse", "silence", "continuous_damage", "elemental_debuff"], "can_aoe": False, "non_player_ability": True},
    # dominion — tank: the fate already written, delivered as decree
    {"id": "inescapable_fate", "name": "Inescapable Fate", "description": "Dominion does not threaten. It informs. The ending has already been resolved — the only remaining step is acknowledgement. The target is frozen not by force but by the complete and rational understanding that nothing they do changes the outcome.", "ability_type": "spirit", "level": 5, "elements": ["dark", "light", "dark", "light", "dark"], "base_power": 0, "ap_cost": 230, "effect": "status", "status_keys": ["petrify", "stun", "confuse", "silence"], "can_aoe": True, "non_player_ability": True},
    # the_void — damage: dissolution as mercy
    {"id": "absolution", "name": "Absolution", "description": "The Void does not offer forgiveness. It offers dissolution — the end of the burden of existing, delivered with the calm of something that has never considered an alternative. The target sleeps not because they are tired, but because the Void has decided they are finished, and even their voice is unmade.", "ability_type": "spirit", "level": 5, "elements": ["dark", "dark", "light", "dark", "dark"], "base_power": 10, "ap_cost": 184, "effect": "status", "status_keys": ["sleep", "silence", "elemental_debuff"], "can_aoe": True, "non_player_ability": True},
]