LEVEL_5_TECH_ABILITY_SEEDS = [
    {"id": "air_earth_tech_lv5_reinforce_frame", "name": "Reinforce Frame", "description": "Mechanical overclock to harden armor and body.", "ability_type": "tech", "level":5, "elements": ["air", "earth", "fire", "water", "light"], "base_power":0, "ap_cost":190, "effect": "status", "status_keys": ["regen", "defense_buff", "defense_buff", "elemental_defense_buff", "constitution_buff", "constitution_buff"], "can_aoe": True},
    {"id": "dark_tech_lv5_spectral_bind", "name": "Spectral Bind", "description": "Ethereal chains that pin foes in place.", "ability_type": "tech", "level":5, "elements": ["dark", "air", "water", "earth", "light"], "base_power":0, "ap_cost":190, "effect": "status", "status_keys": ["defense_debuff", "stun", "silence", "dexterity_debuff", "strength_debuff"], "can_aoe": True},
    {"id": "light_tech_lv5_prism_barrage", "name": "Prism Barrage", "description": "Concentrated light shards fired in a cone.", "ability_type": "tech", "level":5, "elements": ["light", "light", "air", "fire", "earth"], "base_power":192, "ap_cost":172, "effect": "damage", "can_aoe": False},
    {"id": "tech_lv5_mechanized_salvo", "name": "Mechanized Salvo", "description": "A barrage of mechanized munitions.", "ability_type": "tech", "level":5, "elements": ["air", "earth", "fire", "water", "dark"], "base_power":205, "ap_cost":182, "effect": "damage", "can_aoe": False},
    {"id": "water_tech_lv5_maelstrom_field", "name": "Maelstrom Field", "description": "A spinning field of pressurized water.", "ability_type": "tech", "level":5, "elements": ["water", "air", "dark", "earth", "light"], "base_power":205, "ap_cost":188, "effect": "damage", "can_aoe": False},
    {"id": "light_tech_lv5_luminous_shieldwall", "name": "Luminous Shieldwall", "description": "A wall of light that blocks and reflects.", "ability_type": "tech", "level":5, "elements": ["light", "earth", "air", "water", "fire"], "base_power":20, "ap_cost":180, "effect": "status", "status_keys": ["elemental_defense_buff", "elemental_defense_buff", "regen", "regen", "defense_buff", "constitution_buff"], "can_aoe": True},
    {"id": "air_tech_lv5_ionic_overload", "name": "Ionic Overload", "description": "Overcharge that arcs between constructs and flesh.", "ability_type": "tech", "level":5, "elements": ["air", "light", "electric", "fire", "dark"], "base_power":205, "ap_cost":186, "effect": "damage", "can_aoe": False},
    {"id": "tech_lv5_plasma_spike", "name": "Plasma Spike", "description": "A concentrated plasma impalement.", "ability_type": "tech", "level":5, "elements": ["fire", "light", "air", "earth", "water"], "base_power":183, "ap_cost":163, "effect": "damage", "can_aoe": False},

    {"id": "dark_dark_dark_fire_light", "name": "Singularity Incineration Field", "description": "A field of collapsing singularities that incinerates everything in its radius, leaving only a void of light and shadow.", "ability_type": "tech", "level": 5, "elements": ["dark", "dark", "dark", "dark", "light"], "base_power": 160, "ap_cost": 180, "effect": "damage", "can_aoe": True},
    {"id": "light_light_light_light_air", "name": "OIPW", "description": "Optically Induced Plasma wave. A wave of light so intense it strips electrons directly off atoms, creating a self-sustaining plasma wavefront.", "ability_type": "tech", "level": 5, "elements": ["light", "light", "light", "light", "air"], "base_power": 200, "ap_cost": 180, "effect": "damage", "can_aoe": False},
    {"id": "light_light_light_dark_dark", "name": "Ablation Drive", "description": "A weaponized tech using intense radiation to vaporize the outer layer of an object causing it to explode or dissolve into plasma.", "ability_type": "tech", "level": 5, "elements": ["light", "light", "light", "dark", "dark"], "base_power": 150, "ap_cost": 180, "effect": "damage", "can_aoe": True},
    #### NON PLAYER ABILITIES
    # crux_trial — hazard: logic contradiction overload
    {"id": "contradiction_loop", "name": "Contradiction Loop", "description": "Crux identifies an irresolvable logical contradiction in its target and feeds it back endlessly — every response the target gives only deepens the trap, until the mind stalls and the voice fails.", "ability_type": "tech", "level": 5, "elements": ["electric", "dark", "air", "electric", "dark"], "base_power": 30, "ap_cost": 210, "effect": "status", "status_keys": ["confuse", "silence", "attack_buff"], "can_aoe": False, "non_player_ability": True},
    # crux_trial — hazard: simulated reality insertion
    {"id": "simulated_truth", "name": "Simulated Truth", "description": "Crux overlays a convincing false simulation over the target's senses — what they see, hear and feel is entirely constructed data designed to mislead, and every reaction they base on it is wrong.", "ability_type": "tech", "level": 5, "elements": ["electric", "light", "dark", "air", "electric"], "base_power": 0, "ap_cost": 210, "effect": "status", "status_keys": ["intelligence_debuff", "confuse", "dexterity_debuff", "elemental_debuff", "continuous_damage"], "can_aoe": False, "non_player_ability": True},
    # edict_trial — tank: system-wide lockdown
    {"id": "system_lockdown", "name": "System Lockdown", "description": "Edict enforces a total system lockdown — no ability fires, no action is permitted, no protest is recognised. The rule simply is, and the body seizes to obey it.", "ability_type": "tech", "level": 5, "elements": ["dark", "earth", "light", "dark", "earth"], "base_power": 0, "ap_cost": 210, "effect": "status", "status_keys": ["silence", "stun"], "can_aoe": True, "non_player_ability": True},
    # paradox_trial — hazard: a truth that breaks logic
    {"id": "impossible_truth", "name": "Impossible Truth", "description": "Paradox delivers a statement that is simultaneously and provably both true and false — injecting it directly into the target's reasoning architecture. The mind attempts to resolve it. It cannot. It loops, it stalls, it goes quiet.", "ability_type": "tech", "level": 5, "elements": ["dark", "light", "electric", "dark", "air"], "base_power": 20, "ap_cost": 210, "effect": "status", "status_keys": ["confuse", "stun", "continuous_damage"], "can_aoe": False, "non_player_ability": True},
    # cataclysm_trial — damage: optimised collapse, AoE
    {"id": "systematic_destruction", "name": "Systematic Destruction", "description": "Cataclysm does not strike randomly. It identifies the load-bearing point of everything standing and removes it — an efficient, well-documented sequence of deletions that turns structure into rubble through pure procedural logic.", "ability_type": "tech", "level": 5, "elements": ["fire", "dark", "earth", "fire", "dark"], "base_power": 168, "ap_cost": 210, "effect": "damage", "can_aoe": True, "non_player_ability": True},
    # cataclysm_trial — hazard: iterative refinement toward failure
    {"id": "refinement_loop", "name": "Refinement Loop", "description": "Cataclysm runs the same targeted sequence repeatedly, refining it each iteration — not to eliminate the target outright, but to remove every defensive variable until the next iteration has nothing left to adapt to.", "ability_type": "tech", "level": 5, "elements": ["fire", "earth", "dark", "fire", "earth"], "base_power": 95, "ap_cost": 210, "effect": "status", "status_keys": ["defense_debuff", "elemental_debuff", "constitution_debuff"], "can_aoe": False, "non_player_ability": True},
    # dominion — tank: the system that calculates every exit and removes them
    {"id": "inevitability_matrix", "name": "Inevitability Matrix", "description": "Dominion deploys a matrix that does not threaten — it calculates. Every available action, every possible deviation, every contingency is identified and closed. What remains is not a trap. It is simply the only thing left, and it presses in from every side.", "ability_type": "tech", "level": 5, "elements": ["dark", "earth", "dark", "earth", "light"], "base_power": 30, "ap_cost": 210, "effect": "status", "status_keys": ["defense_debuff", "elemental_debuff", "stun"], "can_aoe": True, "non_player_ability": True},
]