# Swamp Small City (Gnashwater Hollow) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "gnash_thug", "name": "Gnash Thug", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 210,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (40, 150),
  "basic_attack": "gnash shiv", "strong_attack": "hollow ambush",
  "player_abilities": [], "base_str": 10, "base_dex": 12, "base_con": 8, "base_int": 2, "base_hp": 240, "base_ap": 10,
  "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
 {"id": "gnash_wraith", "name": "Gnash Wraith", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 23, "rarity": "uncommon", "base_xp": 280,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (15, 55),
  "basic_attack": "swamp touch", "strong_attack": "gnash wail",
  "player_abilities": ["dark_faith_lv1_shade_whisper"],
  "base_str": 3, "base_dex": 10, "base_con": 5, "base_int": 12, "base_hp": 210, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "gnash_raider", "name": "Gnash Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 28, "rarity": "common", "base_xp": 290,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (70, 240),
  "basic_attack": "gnash slash", "strong_attack": "hollow fury",
  "player_abilities": [], "base_str": 14, "base_dex": 10, "base_con": 12, "base_int": 2, "base_hp": 320, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "gnash_witch", "name": "Gnash Witch", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 36, "rarity": "uncommon", "base_xp": 460,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (80, 280),
  "basic_attack": "bog hex", "strong_attack": "gnashwater curse",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_faith_lv1_shade_whisper"],
  "base_str": 3, "base_dex": 8, "base_con": 5, "base_int": 18, "base_hp": 260, "base_ap": 16,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 4},
 {"id": "gnash_bandit_lord", "name": "Gnash Bandit Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 46, "rarity": "superrare", "base_xp": 2600,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (600, 2000),
  "basic_attack": "gnash lord's blade", "strong_attack": "hollow decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 34, "base_dex": 16, "base_con": 30, "base_int": 8, "base_hp": 1700, "base_ap": 12,
  "str_per_level": 7, "dex_per_level": 3, "con_per_level": 6, "int_per_level": 1},
 {"id": "gnash_bog_titan", "name": "Gnash Bog Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 74, "rarity": "superrare", "base_xp": 15000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (4500, 15000),
  "basic_attack": "bog titan slam", "strong_attack": "gnashwater annihilation",
  "player_abilities": ["level_1_hostile_ability_bone_spear"],
  "base_str": 82, "base_dex": 10, "base_con": 76, "base_int": 10, "base_hp": 18000, "base_ap": 12,
  "str_per_level": 16, "dex_per_level": 2, "con_per_level": 15, "int_per_level": 2},
 {"id": "gnashwater_world_god", "name": "The Gnashwater World God", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 90000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (30000, 100000),
  "basic_attack": "world gnash mandate", "strong_attack": "gnashwater apocalypse",
  "player_abilities": ["dark_dark_magic_lv2_umbra_storm", "dark_dark_dark_magic_lv3_shadow_blast"],
  "base_str": 24, "base_dex": 24, "base_con": 24, "base_int": 128, "base_hp": 70000, "base_ap": 108,
  "str_per_level": 4, "dex_per_level": 4, "con_per_level": 4, "int_per_level": 26},
]
