# Shallows Large City (Brineward Harbor) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "harbor_thug", "name": "Harbor Thug", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 240,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (50, 180),
  "basic_attack": "dock punch", "strong_attack": "harbor ambush",
  "player_abilities": [], "base_str": 12, "base_dex": 10, "base_con": 10, "base_int": 3, "base_hp": 300, "base_ap": 10,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "brine_shade", "name": "Brine Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 320,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (20, 80),
  "basic_attack": "brine touch", "strong_attack": "harbor wail",
  "player_abilities": ["level_1_hostile_ability_streamlet"],
  "base_str": 4, "base_dex": 14, "base_con": 6, "base_int": 14, "base_hp": 260, "base_ap": 14,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 3},
 {"id": "brineward_pirate", "name": "Brineward Pirate", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 26, "rarity": "common", "base_xp": 320,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (100, 340),
  "basic_attack": "cutlass slash", "strong_attack": "pirate's raid",
  "player_abilities": [], "base_str": 14, "base_dex": 14, "base_con": 12, "base_int": 4, "base_hp": 360, "base_ap": 12,
  "str_per_level": 3, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
 {"id": "sea_witch_lg", "name": "Sea Witch", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 31, "rarity": "uncommon", "base_xp": 500,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (100, 360),
  "basic_attack": "tide hex", "strong_attack": "deep sea curse",
  "player_abilities": ["water_magic_lv1_spray_shard", "water_dark_magic_lv2_abyssal_tide"],
  "base_str": 4, "base_dex": 12, "base_con": 6, "base_int": 22, "base_hp": 300, "base_ap": 20,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 5},
 {"id": "harbor_crime_lord", "name": "Harbor Crime Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 38, "rarity": "rare", "base_xp": 900,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (360, 1200),
  "basic_attack": "lord's blade", "strong_attack": "harbor decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 26, "base_dex": 14, "base_con": 24, "base_int": 8, "base_hp": 800, "base_ap": 12,
  "str_per_level": 5, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 1},
 {"id": "harbor_sea_dragon", "name": "Harbor Sea Dragon", "hostile_type": "creature", "role": "damage", "min_spawn_level": 50, "rarity": "superrare", "base_xp": 5500,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (1200, 4000),
  "basic_attack": "sea claw", "strong_attack": "harbor tsunami",
  "player_abilities": ["water_magic_lv1_spray_shard", "water_water_magic_lv2_deluge_burst"],
  "base_str": 50, "base_dex": 16, "base_con": 46, "base_int": 10, "base_hp": 4800, "base_ap": 12,
  "str_per_level": 10, "dex_per_level": 2, "con_per_level": 9, "int_per_level": 2},
 {"id": "brineward_lich", "name": "Brineward Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 65, "rarity": "superrare", "base_xp": 11000,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (3000, 10000),
  "basic_attack": "brine death bolt", "strong_attack": "harbor lich storm",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
  "base_str": 10, "base_dex": 14, "base_con": 12, "base_int": 62, "base_hp": 4000, "base_ap": 52,
  "str_per_level": 1, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 13},
 {"id": "tide_titan_lg", "name": "Tide Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 82, "rarity": "superrare", "base_xp": 28000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (10000, 34000),
  "basic_attack": "tide titan slam", "strong_attack": "harbor annihilation",
  "player_abilities": ["water_water_water_magic_lv3_tsunami_burst"],
  "base_str": 100, "base_dex": 14, "base_con": 94, "base_int": 14, "base_hp": 34000, "base_ap": 16,
  "str_per_level": 20, "dex_per_level": 2, "con_per_level": 19, "int_per_level": 2},
 {"id": "brineward_world_god", "name": "The Brineward World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 120000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (50000, 160000),
  "basic_attack": "world tide decree", "strong_attack": "harbor world end",
  "player_abilities": ["water_water_water_magic_lv3_tsunami_burst"],
  "base_str": 138, "base_dex": 30, "base_con": 130, "base_int": 32, "base_hp": 100000, "base_ap": 26,
  "str_per_level": 27, "dex_per_level": 6, "con_per_level": 26, "int_per_level": 6},
]
