"""Marrowroot's Root-Hollow Dungeon Seed Configuration"""

from typing import Dict, Any

# Tile constants for dungeon rendering and builder decisions
OPEN_AREA_TILE   = "░"       # soft forest floor
IMPASSABLE_TILE  = "♣"      # dense root walls
IMPASSABLE_CHANCE = 0.04
OPEN_AREA_COLOR  = "#4a6830"
IMPASSABLE_COLOR = "#1e3010"
BORDER_TILE      = "·"
BORDER_COLOR     = "#385028"

FLOOR_HOSTILES = {
    1: [
        'fungal_bloom',
        'dire_wolf',
        'sap_spirit',
        'void_bloom',
        'thorn_hunter',
        'feral_druid_shade',
        'ancient_root_beast'
    ]
}

HOSTILE_SEEDS = [  # all level 8–10, ~10 hostiles total
    # Floor 1 - Root-Hollow (forest beasts, corrupted druids, void-touched flora)
    {
        'id': 'fungal_bloom',
        'name': 'Fungal Bloom',
        'hostile_type': 'creature',
        'min_spawn_level': 18,
        'role': 'damage',
        'rarity': 'common',
        'base_xp': 20,
        'common_drop': 'herb_minor',
        'rare_drop': None,
        'money_range': (2, 12),
        'basic_attack': 'spore spray',
        'strong_attack': 'mycelium blast',
        'player_abilities': ['earth_skill_lv1_soporific_veil'],
        'base_str': 4,
        'base_dex': 4,
        'base_con': 4,
        'base_int': 1,
        'base_hp': 26,
        'base_ap': 3,
        'str_per_level': 1,
        'dex_per_level': 1,
        'con_per_level': 2,
        'int_per_level': 0,
        'resistances': ['earth'],
        'immunities': [],
        'weaknesses': ['fire']
    },
    {
        'id': 'dire_wolf',
        'name': 'Dire Wolf',
        'hostile_type': 'creature',
        'min_spawn_level': 19,
        'role': 'damage',
        'rarity': 'common',
        'base_xp': 36,
        'common_drop': 'stimulant_small',
        'rare_drop': 'stimulant_large',
        'money_range': (6, 30),
        'basic_attack': 'bark bite',
        'strong_attack': 'timber pounce',
        'player_abilities': [],
        'base_str': 5,
        'base_dex': 6,
        'base_con': 4,
        'base_int': 2,
        'base_hp': 34,
        'base_ap': 4,
        'str_per_level': 2,
        'dex_per_level': 2,
        'con_per_level': 1,
        'int_per_level': 0,
        'resistances': ['earth'],
        'immunities': [],
        'weaknesses': ['fire']
    },
    {
        'id': 'sap_spirit',
        'name': 'Sap Spirit',
        'hostile_type': 'spirit',
        'min_spawn_level': 21,
        'role': 'support',
        'rarity': 'uncommon',
        'base_xp': 60,
        'common_drop': 'herb_med',
        'rare_drop': 'herb_major',
        'money_range': (10, 50),
        'basic_attack': 'sap lash',
        'strong_attack': 'healing resin',
        'player_abilities': ['earth_spirit_lv1_earthen_blessing'],
        'base_str': 3,
        'base_dex': 4,
        'base_con': 6,
        'base_int': 6,
        'base_hp': 70,
        'base_ap': 5,
        'str_per_level': 1,
        'dex_per_level': 1,
        'con_per_level': 2,
        'int_per_level': 2,
        'resistances': ['earth'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['fire']
    },
    {
        'id': 'void_bloom',
        'name': 'Void Bloom',
        'hostile_type': 'plant',
        'min_spawn_level': 20,
        'role': 'hazard',
        'rarity': 'uncommon',
        'base_xp': 120,
        'common_drop': 'herb_minor',
        'rare_drop': 'herb_major',
        'money_range': (20, 90),
        'basic_attack': 'spore burst',
        'strong_attack': 'void pollen',
        'player_abilities': ['dark_tech_lv1_void_grenade'],
        'base_str': 3,
        'base_dex': 3,
        'base_con': 7,
        'base_int': 5,
        'base_hp': 140,
        'base_ap': 6,
        'str_per_level': 1,
        'dex_per_level': 1,
        'con_per_level': 3,
        'int_per_level': 2,
        'resistances': ['continuous_damage'],
        'immunities': ['sleep'],
        'weaknesses': ['fire']
    },
    {
        'id': 'thorn_hunter',
        'name': 'Thorn Hunter',
        'hostile_type': 'humanoid',
        'min_spawn_level': 21,
        'role': 'damage',
        'rarity': 'rare',
        'base_xp': 200,
        'common_drop': 'herb_minor',
        'rare_drop': 'tome_con',
        'money_range': (30, 120),
        'basic_attack': 'thorn spear',
        'strong_attack': 'rooted charge',
        'player_abilities': ['dark_skill_lv1_tranq_dart'],
        'base_str': 7,
        'base_dex': 6,
        'base_con': 7,
        'base_int': 3,
        'base_hp': 160,
        'base_ap': 5,
        'str_per_level': 2,
        'dex_per_level': 2,
        'con_per_level': 2,
        'int_per_level': 1,
        'resistances': ['earth'],
        'immunities': [],
        'weaknesses': ['fire']
    },
    {
        'id': 'feral_druid_shade',
        'name': 'Feral Druid Shade',
        'hostile_type': 'spirit',
        'min_spawn_level': 21,
        'role': 'hazard',
        'rarity': 'uncommon',
        'base_xp': 24,
        'common_drop': 'stimulant_small',
        'rare_drop': None,
        'money_range': (4, 16),
        'basic_attack': 'wild swipe',
        'strong_attack': 'howl of the grove',
        'player_abilities': ['light_dark_magic_lv2_twilight_bleed'],
        'base_str': 1,
        'base_dex': 4,
        'base_con': 4,
        'base_int': 7,
        'base_hp': 30,
        'base_ap': 3,
        'str_per_level': 1,
        'dex_per_level': 1,
        'con_per_level': 1,
        'int_per_level': 1,
        'resistances': ['earth'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['fire']
    },
    {
        'id': 'ancient_root_beast',
        'name': 'Ancient Root Beast',
        'hostile_type': 'creature',
        'min_spawn_level': 24,
        'role': 'damage',
        'rarity': 'superrare',
        'base_xp': 300,
        'common_drop': 'herb_major',
        'rare_drop': 'tome_con_superrare',
        'money_range': (50, 200),
        'basic_attack': 'root crush',
        'strong_attack': 'ancient upheaval',
        'player_abilities': ['earth_water_technique_lv2_mire_cleave','dark_magic_lv1_shadow_tendril'],
        'base_str': 10,
        'base_dex': 5,
        'base_con': 12,
        'base_int': 4,
        'base_hp': 420,
        'base_ap': 6,
        'str_per_level': 3,
        'dex_per_level': 1,
        'con_per_level': 3,
        'int_per_level': 1,
        'resistances': ['earth'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['fire']
    }
]

DUNGEON_NPCS = [ {'id': 'marrowroot','location': 'final_chamber'} ]
DUNGEON_ITEMS = [ {'id': 'herb_major', 'location': 'treasure_room'} ]

BOSS_MOB = { 'id': 'marrowroot_1',
             'name': 'Elder Marrowroot',
             'hostiles': [
                'marrowroot_spawn',
                'marrowroot_spawn',
                'marrowroot_1']
            }

BOSS_HOSTILES = [
    {
        "id": "marrowroot_spawn", "name": "Marrowroot Spawn", "hostile_type": "melee", "role": "hazard",
        "min_spawn_level": 23, "rarity": "superrare", "base_xp": 480,
        "common_drop": "herb_major", "rare_drop": "tome_con", "money_range": (45,180),
        "basic_attack": "thorn slash", "strong_attack": "root bind",
        "player_abilities": ["earth_dark_technique_lv2_dark_impact", "dark_magic_lv1_shadow_tendril"],
        "base_str": 10, "base_dex": 6, "base_con": 12, "base_int": 6,
        "base_hp": 2100, "base_ap": 300,
        "str_per_level": 2, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 1,
        'resistances': ['earth'],
        'immunities': ['continuous_damage'],
        'weaknesses': ['fire']
    },
    {
        "id": "marrowroot_1", "name": "Elder Marrowroot", "hostile_type": "magic", "role": "boss",
        "min_spawn_level": 30, "rarity": "notfound", "base_xp": 1200,
        "common_drop": "herb_major", "rare_drop": "tome_con", "money_range": (100,300),
        "basic_attack": "root lash", "strong_attack": "void‑touched bloom",
        "player_abilities": ["earth_earth_earth_spirit_lv3_gaia_earthshaker", "light_dark_spirit_lv2_dusk_confessional", "light_dark_magic_lv2_twilight_bleed"],
        "base_str": 12, "base_dex": 8, "base_con": 12, "base_int": 16,
        "base_hp": 2500, "base_ap": 400,
        "str_per_level": 2, "dex_per_level": 1, "con_per_level": 3, "int_per_level": 2,
        'resistances': [],
        'immunities': ['sleep', 'confuse', 'stun', 'petrify'],
        'weaknesses': []
    }
]

DUNGEON_SETTINGS: Dict[str, Any] = {
    "dungeon_id": "marrowroot_lair",
    "seed": abs(hash("marrowroot_lair")),
    "floor_count": 1,
    "room_size_min_max": (81, 120),  # a 9x9 area is 81
    "rooms_per_floor": 10,
    "max_neighbors_per_room": 3,
    "additional_connection_chance": 0.0,
    "min_max_distance_between_rooms": (5,12),
    "min_max_corridor_width": (3,6),
    "display_name": "Marrowroot's Root-Hollow",
    "open_area_tile": OPEN_AREA_TILE,
    "impassable_tile": IMPASSABLE_TILE,
    "open_area_color":  OPEN_AREA_COLOR,
	"impassable_color": IMPASSABLE_COLOR,
	"border_tile":      BORDER_TILE,
	"border_color":     BORDER_COLOR,
    "impassable_chance": IMPASSABLE_CHANCE,
    "floor_hostiles": FLOOR_HOSTILES,
    "hostile_seeds": HOSTILE_SEEDS,
    "npcs": DUNGEON_NPCS,
	"items": DUNGEON_ITEMS,
    "boss_mob": BOSS_MOB,
    "boss_hostiles": BOSS_HOSTILES,
    "visible_distance": 5
}
