# Shallows Mid City (Blackwake Bay) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "blackwake_smuggler", "name": "Blackwake Smuggler", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 220,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (60, 200),
  "basic_attack": "smuggler's shiv", "strong_attack": "bay ambush",
  "player_abilities": [], "base_str": 10, "base_dex": 14, "base_con": 8, "base_int": 4, "base_hp": 280, "base_ap": 12,
  "str_per_level": 2, "dex_per_level": 2, "con_per_level": 2, "int_per_level": 0},
 {"id": "wake_shade", "name": "Wake Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 22, "rarity": "uncommon", "base_xp": 300,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (15, 60),
  "basic_attack": "wake touch", "strong_attack": "bay wail",
  "player_abilities": ["level_1_hostile_ability_streamlet"],
  "base_str": 3, "base_dex": 12, "base_con": 5, "base_int": 12, "base_hp": 240, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 3},
 {"id": "bay_berserker", "name": "Bay Berserker", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 27, "rarity": "common", "base_xp": 320,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (80, 280),
  "basic_attack": "anchor bash", "strong_attack": "bay fury",
  "player_abilities": [], "base_str": 14, "base_dex": 10, "base_con": 12, "base_int": 2, "base_hp": 360, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "blackwake_lord", "name": "Blackwake Pirate Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 36, "rarity": "rare", "base_xp": 760,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (280, 900),
  "basic_attack": "captain's blade", "strong_attack": "pirate lord decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 24, "base_dex": 14, "base_con": 22, "base_int": 8, "base_hp": 700, "base_ap": 12,
  "str_per_level": 4, "dex_per_level": 2, "con_per_level": 4, "int_per_level": 1},
 {"id": "bay_sea_witch", "name": "Bay Sea Witch", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 44, "rarity": "rare", "base_xp": 1100,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (200, 700),
  "basic_attack": "bay hex", "strong_attack": "blackwake curse",
  "player_abilities": ["water_magic_lv1_spray_shard", "water_dark_magic_lv2_abyssal_tide"],
  "base_str": 4, "base_dex": 12, "base_con": 6, "base_int": 28, "base_hp": 640, "base_ap": 24,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 6},
 {"id": "blackwake_lich", "name": "Blackwake Lich", "hostile_type": "undead", "role": "hazard", "min_spawn_level": 60, "rarity": "superrare", "base_xp": 7500,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (1500, 5000),
  "basic_attack": "bay death bolt", "strong_attack": "lich tide storm",
  "player_abilities": ["dark_magic_lv1_shadow_tendril", "dark_dark_magic_lv2_umbra_storm"],
  "base_str": 8, "base_dex": 12, "base_con": 10, "base_int": 55, "base_hp": 2600, "base_ap": 46,
  "str_per_level": 1, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 11},
 {"id": "bay_titan", "name": "Bay Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 80, "rarity": "superrare", "base_xp": 22000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (7000, 24000),
  "basic_attack": "bay titan slam", "strong_attack": "blackwake annihilation",
  "player_abilities": ["water_water_water_magic_lv3_tsunami_burst"],
  "base_str": 88, "base_dex": 14, "base_con": 82, "base_int": 12, "base_hp": 26000, "base_ap": 14,
  "str_per_level": 17, "dex_per_level": 2, "con_per_level": 16, "int_per_level": 2},
 {"id": "blackwake_world_god", "name": "The Blackwake World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 100000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (40000, 130000),
  "basic_attack": "world bay decree", "strong_attack": "blackwake apocalypse",
  "player_abilities": ["water_water_water_magic_lv3_tsunami_burst"],
  "base_str": 24, "base_dex": 30, "base_con": 24, "base_int": 140, "base_hp": 80000, "base_ap": 115,
  "str_per_level": 5, "dex_per_level": 6, "con_per_level": 5, "int_per_level": 28},
]
