# Technique seeds extracted from level_3_player_ability_seeds
LEVEL_3_TECHNIQUE_SEEDS = [
  ## Single-target Damage (8)
  {"id":"dark_fire_ice_technique_lv3_flame_wraith_strike","name":"Flame Wraith Strike","description":"A spectral blaze that scorches then chills the foe, leaving them slowed.","ability_type":"technique","level":3,"elements":["dark","fire","ice"],"base_power":92,"ap_cost":70,"effect":"damage","secondary_status":"slow","can_aoe":False},
  {"id":"dark_ice_air_technique_lv3_frost_bite_strike","name":"Frost Bite Strike","description":"A biting gust of shadowed frost that numbs and reduces action speed.","ability_type":"technique","level":3,"elements":["dark","ice","air"],"base_power":90,"ap_cost":68,"effect":"damage","secondary_status":"dexterity_debuff","can_aoe":False},
  {"id":"dark_air_earth_technique_lv3_shadow_quake_strike","name":"Shadow Quake Strike","description":"A concentrated tremor of void-wind that disrupts defenses.","ability_type":"technique","level":3,"elements":["dark","air","earth"],"base_power":95,"ap_cost":72,"effect":"damage","secondary_status":"defense_debuff","can_aoe":False},
  {"id":"dark_earth_electric_technique_lv3_void_shock_strike","name":"Void Shock Strike","description":"A crushing jolt of shadow and charge that drains resolve.","ability_type":"technique","level":3,"elements":["dark","earth","electric"],"base_power":94,"ap_cost":70,"effect":"damage","secondary_status":"strength_debuff","can_aoe":False},
  {"id":"dark_electric_water_technique_lv3_night_tide_strike","name":"Night Tide Strike","description":"A darkened current that lashes and confuses the target.","ability_type":"technique","level":3,"elements":["dark","electric","water"],"base_power":88,"ap_cost":66,"effect":"damage","secondary_status":"confuse","can_aoe":False},
  {"id":"dark_water_fire_technique_lv3_abyssal_flame_strike","name":"Abyssal Flame Strike","description":"A consuming dark flame that burns and weakens the foe's attacks.","ability_type":"technique","level":3,"elements":["dark","water","fire"],"base_power":93,"ap_cost":70,"effect":"damage","secondary_status":"attack_debuff","can_aoe":False},
  {"id":"dark_earth_fire_technique_lv3_oblivion_burn_strike","name":"Oblivion Burn Strike","description":"A searing eruption of void-fire that damages and reduces constitution.","ability_type":"technique","level":3,"elements":["dark","earth","fire"],"base_power":91,"ap_cost":68,"effect":"damage","secondary_status":"constitution_debuff","can_aoe":False},
  {"id":"air_electric_fire_technique_lv3_stormbrand_pierce","name":"Stormbrand Pierce","description":"A razor wind charged with lightning and flame that pierces armor.","ability_type":"technique","level":3,"elements":["air","electric","fire"],"base_power":90,"ap_cost":68,"effect":"damage","secondary_status":"armor_break","can_aoe":False},
  {"id":"water_fire_ice_technique_lv3_steamfrost_lance","name":"Steamfrost Lance","description":"Scalding steam and freezing spray combine into a focused lance.","ability_type":"technique","level":3,"elements":["water","fire","ice"],"base_power":89,"ap_cost":66,"effect":"damage","secondary_status":"elemental_debuff","can_aoe":False},

  ## AOE Damage (5)
  {"id":"fire_fire_fire_technique_lv3_inferno_wave","name":"Inferno Wave","description":"A sweeping wall of flame that sears all in its path.","ability_type":"technique","level":3,"elements":["fire","fire","fire"],"base_power":76,"ap_cost":80,"effect":"damage","can_aoe":True},
  {"id":"water_water_water_technique_lv3_tsunami_burst","name":"Tsunami Burst","description":"A rolling surge that drenches and knocks back multiple foes.","ability_type":"technique","level":3,"elements":["water","water","water"],"base_power":74,"ap_cost":78,"effect":"damage","secondary_status":"knockback","can_aoe":True},
  {"id":"earth_earth_earth_technique_lv3_earthshaker","name":"Earthshaker","description":"A ground-shattering slam that damages and stuns nearby enemies.","ability_type":"technique","level":3,"elements":["earth","earth","earth"],"base_power":78,"ap_cost":82,"effect":"damage","secondary_status":"stun","can_aoe":True},
  {"id":"air_air_air_technique_lv3_storm_surge","name":"Storm Surge","description":"A violent gale that batters every foe in a wide arc.","ability_type":"technique","level":3,"elements":["air","air","air"],"base_power":75,"ap_cost":78,"effect":"damage","can_aoe":True},
  {"id":"electric_electric_electric_technique_lv3_thunderstorm","name":"Thunderstorm","description":"A crackling storm that arcs between multiple enemies.","ability_type":"technique","level":3,"elements":["electric","electric","electric"],"base_power":77,"ap_cost":80,"effect":"damage","secondary_status":"stun_chance","can_aoe":True},

  ## Buffs (4)
  {"id":"ice_earth_water_technique_lv3_glacial_guard","name":"Glacial Guard","description":"A cold, earthen tide that hardens allies' defenses and resists elements.","ability_type":"technique","level":3,"elements":["ice","earth","water"],"base_power":0,"ap_cost":60,"effect":"status","status_keys":["elemental_attack_buff"],"can_aoe":False},
  {"id":"air_electric_fire_technique_lv3_tempest_charge","name":"Tempest Charge","description":"A charged wind that sharpens allies' strikes and speed.","ability_type":"technique","level":3,"elements":["air","electric","fire"],"base_power":0,"ap_cost":58,"effect":"status","status_keys":["elemental_attack_buff"],"can_aoe":False},
  {"id":"light_earth_water_technique_lv3_solar_haven","name":"Solar Haven","description":"A focused light-earth blessing that restores resolve and fortifies defense.","ability_type":"technique","level":3,"elements":["light","earth","water"],"base_power":0,"ap_cost":62,"effect":"status","status_keys":["elemental_attack_buff"],"can_aoe":False},
  {"id":"light_air_electric_technique_lv3_solar_aegis_minor","name":"Solar Aegis Minor","description":"A compact aegis that grants allies elemental resistance and quick recovery.","ability_type":"technique","level":3,"elements":["light","air","electric"],"base_power":0,"ap_cost":55,"effect":"status","status_keys":["elemental_attack_buff"],"can_aoe":False},

  ## Debuffs Single-target (4)
  {"id":"fire_ice_air_technique_lv3_scorchfreeze_cripple","name":"Scorchfreeze Cripple","description":"A blistering-cold strike that reduces the target's strength and mobility.","ability_type":"technique","level":3,"elements":["fire","ice","air"],"base_power":20,"ap_cost":50,"effect":"status","status_keys":["strength_debuff"],"can_aoe":False},
  {"id":"ice_air_earth_technique_lv3_hailbind","name":"Hailbind","description":"A freezing barrage that slows and lowers dexterity.","ability_type":"technique","level":3,"elements":["ice","air","earth"],"base_power":18,"ap_cost":48,"effect":"status","status_keys":["dexterity_debuff"],"can_aoe":False},
  {"id":"earth_electric_water_technique_lv3_mire_sap","name":"Mire Sap","description":"A charged mud strike that saps constitution and weakens defenses.","ability_type":"technique","level":3,"elements":["earth","electric","water"],"base_power":16,"ap_cost":50,"effect":"status","status_keys":["constitution_debuff"],"can_aoe":False},
  {"id":"electric_water_fire_technique_lv3_shock_corrode","name":"Shock Corrode","description":"A corrosive current that lowers the target's attack potency.","ability_type":"technique","level":3,"elements":["electric","water","fire"],"base_power":18,"ap_cost":50,"effect":"status","status_keys":["attack_debuff"],"can_aoe":False},

  ## Extra Single-target Status Effects (2)
  {"id":"air_dark_technique_lv3_immortalize","name":"Immortalize","description":"A focused whirl that petrifies the target.","ability_type":"technique","level":3,"elements":["air","dark","dark"],"base_power":10,"ap_cost":65,"effect":"status","status_keys":["silence"],"can_aoe":False},
  {"id":"light_water_ice_technique_lv3_luminous_lull","name":"Luminous Lull","description":"A soothing beam of light and water that can put a single foe to sleep.","ability_type":"technique","level":3,"elements":["light","water","ice"],"base_power":12,"ap_cost":60,"effect":"status","status_keys":["sleep"],"can_aoe":False},

  ## NON PLAYER ABILITIES
  {"id": "detached_slaughter", "name": "Detached Slaughter", "description": "A sweeping series of strikes conducted without hesitation or mercy, cutting through all nearby targets with cold indifference.", "ability_type": "technique", "level": 3, "elements": ["ice", "dark", "air"], "base_power": 80, "ap_cost": 85, "effect": "damage", "can_aoe": True, "non_player_ability": True},
  {"id": "seizing_the_moment", "name": "Seizing the Moment", "description": "Rapture exploits a single instant of vulnerability — a devastating single strike timed to land the moment the target's guard wavers.", "ability_type": "technique", "level": 3, "elements": ["dark", "fire", "air"], "base_power": 90, "ap_cost": 72, "effect": "damage", "can_aoe": False, "non_player_ability": True},
  {"id": "predator_rush", "name": "Predator Rush", "description": "A thunderous charge across the arena that slams through any enemy in the path — raw physical domination disguised as momentum.", "ability_type": "technique", "level": 3, "elements": ["dark", "fire", "fire"], "base_power": 82, "ap_cost": 78, "effect": "damage", "can_aoe": True, "non_player_ability": True},
  {"id": "rot_of_potential", "name": "Rot of Potential", "description": "Garbage drives itself into the target with the full force of every squandered chance and broken dream — a savage, disgusted strike that leaves ruin where meaning used to be.", "ability_type": "technique", "level": 3, "elements": ["dark", "earth", "fire"], "base_power": 98, "ap_cost": 82, "effect": "damage", "can_aoe": False, "non_player_ability": True},
]