# Level11-20 hostile seeds for Bleakwatch Outpost (small-city)
# Export a list named SEEDS_LV11TO20 used by constants_enemies_small_city.py
SEEDS_LV11TO20 = [
 {"id": "lane_runner", "name": "Lane Runner", "hostile_type": "humanoid", "role": "damage", "min_spawn_level":11, "rarity": "common", "base_xp":90,
 "common_drop": "herb_med", "rare_drop": None, "money_range": (10,50),
 "basic_attack": "purse swipe", "strong_attack": "cold dash", "player_abilities": None,
 "base_str":3, "base_dex":6, "base_con":3, "base_int":2, "base_hp":120, "base_ap":4,
 "str_per_level":1, "dex_per_level":2, "con_per_level":1, "int_per_level":0},

 {"id": "frozen_courier3", "name": "Frozen Courier", "hostile_type": "humanoid", "role": "damage", "min_spawn_level":11, "rarity": "common", "base_xp":92,
 "common_drop": "herb_med", "rare_drop": None, "money_range": (8,44),
 "basic_attack": "package toss", "strong_attack": "sled shove", "player_abilities": None,
 "base_str":2, "base_dex":7, "base_con":3, "base_int":2, "base_hp":130, "base_ap":4,
 "str_per_level":1, "dex_per_level":2, "con_per_level":1, "int_per_level":0},

 {"id": "sly_scout", "name": "Sly Scout", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level":11, "rarity": "uncommon", "base_xp":110,
 "common_drop": "stimulant_small", "rare_drop": None, "money_range": (12,60),
 "basic_attack": "quick prod", "strong_attack": "tripwire kick", "player_abilities": ["level_1_hostile_ability_shadow_flicker"],
 "base_str":2, "base_dex":8, "base_con":3, "base_int":3, "base_hp":120, "base_ap":5,
 "str_per_level":0, "dex_per_level":2, "con_per_level":1, "int_per_level":1},

 {"id": "vicar_watch", "name": "Vicar of the Watch", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level":11, "rarity": "rare", "base_xp":200,
 "common_drop": "herb_major", "rare_drop": "tome_con", "money_range": (18,96),
 "basic_attack": "blight murmur", "strong_attack": "wasting blight", "player_abilities": ["level_1_hostile_ability_dark_skill_corrosive_spit", "level_1_hostile_ability_arcane_blast"],
 "base_str":3, "base_dex":3, "base_con":6, "base_int":9, "base_hp":120, "base_ap":8,
 "str_per_level":1, "dex_per_level":1, "con_per_level":2, "int_per_level":2},

 {"id": "blubber_widow", "name": "Blubber Widow", "hostile_type": "creature", "role": "damage", "min_spawn_level":11, "rarity": "rare", "base_xp":220,
 "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (30,160),
 "basic_attack": "slap of blubber", "strong_attack": "suffocating embrace", "player_abilities": ["level_1_hostile_ability_dark_skill_corrosive_spit"],
 "base_str":7, "base_dex":3, "base_con":9, "base_int":4, "base_hp":220, "base_ap":6,
 "str_per_level":3, "dex_per_level":0, "con_per_level":2, "int_per_level":1},

 {"id": "dock_lug", "name": "Dock Lug", "hostile_type": "humanoid", "role": "damage", "min_spawn_level":12, "rarity": "common", "base_xp":100,
 "common_drop": "herb_med", "rare_drop": None, "money_range": (14,68),
 "basic_attack": "rope jab", "strong_attack": "crane swing", "player_abilities": None,
 "base_str":5, "base_dex":4, "base_con":6, "base_int":2, "base_hp":150, "base_ap":5,
 "str_per_level":2, "dex_per_level":1, "con_per_level":2, "int_per_level":0},

 {"id": "harbor_fix", "name": "Harbor Fixer", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level":12, "rarity": "uncommon", "base_xp":120,
 "common_drop": "stimulant_small", "rare_drop": "tome_dex", "money_range": (16,80),
 "basic_attack": "gadget jab", "strong_attack": "arc stutter", "player_abilities": ["level_1_hostile_ability_electric_tech_hack_overload"],
 "base_str":2, "base_dex":5, "base_con":4, "base_int":8, "base_hp":140, "base_ap":6,
 "str_per_level":1, "dex_per_level":1, "con_per_level":1, "int_per_level":2},

 {"id": "ice_weaver", "name": "Ice Weaver", "hostile_type": "elemental", "role": "hazard", "min_spawn_level":12, "rarity": "rare", "base_xp":260,
 "common_drop": "stimulant_med", "rare_drop": "tome_int", "money_range": (30,140),
 "basic_attack": "needle stitch", "strong_attack": "web of frost", "player_abilities": ["lv2_hostile_ability_ice_light_magic_frost_nova"],
 "base_str":4, "base_dex":6, "base_con":6, "base_int":8, "base_hp":160, "base_ap":8,
 "str_per_level":1, "dex_per_level":2, "con_per_level":2, "int_per_level":2},

 {"id": "night_shank_small", "name": "Night Shank", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level":12, "rarity": "rare", "base_xp":200,
 "common_drop": "stimulant_small", "rare_drop": "stimulant_large", "money_range": (30,140),
 "basic_attack": "grease strike", "strong_attack": "silent garrote", "player_abilities": ["lv2_hostile_ability_dark_dark_faith_void_veil"],
 "base_str":3, "base_dex":8, "base_con":4, "base_int":5, "base_hp":92, "base_ap":8,
 "str_per_level":1, "dex_per_level":3, "con_per_level":1, "int_per_level":2},

 {"id": "glacial_marauder", "name": "Glacial Marauder", "hostile_type": "humanoid", "role": "damage", "min_spawn_level":13, "rarity": "common", "base_xp":140,
 "common_drop": "herb_med", "rare_drop": None, "money_range": (18,90),
 "basic_attack": "club swing", "strong_attack": "crab toss", "player_abilities": None,
 "base_str":6, "base_dex":3, "base_con":6, "base_int":2, "base_hp":180, "base_ap":5,
 "str_per_level":2, "dex_per_level":0, "con_per_level":2, "int_per_level":0},

 {"id": "ghost_monger", "name": "Ghost Monger", "hostile_type": "shadow", "role": "hazard", "min_spawn_level":13, "rarity": "uncommon", "base_xp":140,
 "common_drop": "herb_med", "rare_drop": "stimulant_small", "money_range": (8,48),
 "basic_attack": "shadow jab", "strong_attack": "vanishing rip", "player_abilities": ["level_1_hostile_ability_shadow_flicker"],
 "base_str":3, "base_dex":7, "base_con":3, "base_int":4, "base_hp":120, "base_ap":6,
 "str_per_level":1, "dex_per_level":3, "con_per_level":1, "int_per_level":1},

 {"id": "sled_fisher", "name": "Sled Fisher", "hostile_type": "creature", "role": "damage", "min_spawn_level":14, "rarity": "common", "base_xp":160,
 "common_drop": "herb_med", "rare_drop": None, "money_range": (22,110),
 "basic_attack": "barbed jab", "strong_attack": "ice maul", "player_abilities": None,
 "base_str":6, "base_dex":4, "base_con":6, "base_int":3, "base_hp":200, "base_ap":5,
 "str_per_level":2, "dex_per_level":1, "con_per_level":2, "int_per_level":0},

 {"id": "sleet_illusionist", "name": "Sleet Illusionist", "hostile_type": "humanoid", "role": "hazard", "min_spawn_level":14, "rarity": "superrare", "base_xp":300,
 "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (40,180),
 "basic_attack": "flicker bolt", "strong_attack": "mirage storm", "player_abilities": ["lv2_hostile_ability_dark_dark_faith_void_veil", "level_1_hostile_ability_light_faith_prism_burst"],
 "base_str":3, "base_dex":6, "base_con":5, "base_int":12, "base_hp":200, "base_ap":10,
 "str_per_level":1, "dex_per_level":2, "con_per_level":1, "int_per_level":3},

 {"id": "harpoon_fisher", "name": "Harpoon Fisher", "hostile_type": "humanoid", "role": "damage", "min_spawn_level":15, "rarity": "common", "base_xp":180,
 "common_drop": "herb_med", "rare_drop": None, "money_range": (40,180),
 "basic_attack": "harpoon jab", "strong_attack": "impale throw", "player_abilities": None,
 "base_str":8, "base_dex":5, "base_con":8, "base_int":3, "base_hp":240, "base_ap":6,
 "str_per_level":3, "dex_per_level":1, "con_per_level":2, "int_per_level":0},

 {"id": "iceborn_watchman", "name": "Iceborn Watchman", "hostile_type": "construct", "role": "support", "min_spawn_level":15, "rarity": "rare", "base_xp":320,
 "common_drop": "stimulant_large", "rare_drop": "kevlar_vest", "money_range": (60,240),
 "basic_attack": "piston slam", "strong_attack": "hydraulic crush", "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
 "base_str":14, "base_dex":1, "base_con":18, "base_int":1, "base_hp":300, "base_ap":4,
 "str_per_level":4, "dex_per_level":0, "con_per_level":3, "int_per_level":0},

 {"id": "crumbled_ogre", "name": "Crumbled Ogre", "hostile_type": "humanoid", "role": "damage", "min_spawn_level":15, "rarity": "rare", "base_xp":360,
 "common_drop": "herb_major", "rare_drop": "sawed_off", "money_range": (40,200),
 "basic_attack": "boulder smash", "strong_attack": "earthquake stomp", "player_abilities": None,
 "base_str":12, "base_dex":1, "base_con":12, "base_int":1, "base_hp":380, "base_ap":4,
 "str_per_level":4, "dex_per_level":0, "con_per_level":3, "int_per_level":0},

 {"id": "bone_watchman", "name": "Bone Watchman", "hostile_type": "undead", "role": "hazard", "min_spawn_level":13, "rarity": "uncommon", "base_xp":220,
 "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (30,160),
 "basic_attack": "ribcage smash", "strong_attack": "necrotic wail", "player_abilities": ["lv2_hostile_ability_dark_dark_faith_void_veil"],
 "base_str":7, "base_dex":4, "base_con":9, "base_int":5, "base_hp":180, "base_ap":8,
 "str_per_level":3, "dex_per_level":0, "con_per_level":2, "int_per_level":1},

 {"id": "keeper_wraith", "name": "Keeper Wraith", "hostile_type": "undead", "role": "hazard", "min_spawn_level":17, "rarity": "superrare", "base_xp":520,
 "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (80,320),
 "basic_attack": "lantern swipe", "strong_attack": "necrotic flare", "player_abilities": ["lv2_hostile_ability_dark_air_skill_nightmare_wave", "lv2_hostile_ability_dark_dark_faith_void_veil"],
 "base_str":9, "base_dex":6, "base_con":10, "base_int":10, "base_hp":320, "base_ap":12,
 "str_per_level":3, "dex_per_level":1, "con_per_level":2, "int_per_level":2},

 {"id": "freeze_hound", "name": "Freeze Hound", "hostile_type": "creature", "role": "damage", "min_spawn_level":16, "rarity": "common", "base_xp":200,
 "common_drop": "herb_major", "rare_drop": None, "money_range": (40,180),
 "basic_attack": "frost bite", "strong_attack": "rending maul", "player_abilities": None,
 "base_str":8, "base_dex":6, "base_con":8, "base_int":2, "base_hp":260, "base_ap":6,
 "str_per_level":3, "dex_per_level":1, "con_per_level":2, "int_per_level":0},

 {"id": "fjord_guard", "name": "Fjord Guard", "hostile_type": "humanoid", "role": "support", "min_spawn_level":16, "rarity": "uncommon", "base_xp":220,
 "common_drop": "stimulant_large", "rare_drop": None, "money_range": (40,200),
 "basic_attack": "guard stab", "strong_attack": "colossal sweep", "player_abilities": ["level_1_hostile_ability_reinforce_frame"],
 "base_str":8, "base_dex":3, "base_con":10, "base_int":3, "base_hp":280, "base_ap":6,
 "str_per_level":3, "dex_per_level":0, "con_per_level":3, "int_per_level":0},

 {"id": "ice_warden", "name": "Ice Warden", "hostile_type": "humanoid", "role": "damage", "min_spawn_level":17, "rarity": "common", "base_xp":240,
 "common_drop": "stimulant_med", "rare_drop": None, "money_range": (50,220),
 "basic_attack": "warden slash", "strong_attack": "freezing command", "player_abilities": None,
 "base_str":9, "base_dex":5, "base_con":10, "base_int":4, "base_hp":300, "base_ap":7,
 "str_per_level":3, "dex_per_level":1, "con_per_level":3, "int_per_level":1},

 {"id": "arctic_brute", "name": "Arctic Brute", "hostile_type": "humanoid", "role": "damage", "min_spawn_level":18, "rarity": "common", "base_xp":280,
 "common_drop": "stimulant_med", "rare_drop": None, "money_range": (60,260),
 "basic_attack": "maul strike", "strong_attack": "colossal crush", "player_abilities": None,
 "base_str":12, "base_dex":3, "base_con":12, "base_int":2, "base_hp":360, "base_ap":5,
 "str_per_level":4, "dex_per_level":0, "con_per_level":3, "int_per_level":0},
]
