# Snow Small City (Bleakwatch Outpost) — hostile seeds levels 21-100.

RANDOM_HOSTILE_SEEDS = [
 {"id": "outpost_thug", "name": "Outpost Thug", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 21, "rarity": "common", "base_xp": 210,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (40, 150),
  "basic_attack": "frost punch", "strong_attack": "outpost ambush",
  "player_abilities": [], "base_str": 12, "base_dex": 8, "base_con": 10, "base_int": 2, "base_hp": 260, "base_ap": 8,
  "str_per_level": 2, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "bleak_shade", "name": "Bleak Shade", "hostile_type": "spirit", "role": "hazard", "min_spawn_level": 23, "rarity": "uncommon", "base_xp": 270,
  "common_drop": "herb_major", "rare_drop": None, "money_range": (15, 55),
  "basic_attack": "bleak touch", "strong_attack": "tundra wail",
  "player_abilities": ["ice_magic_lv1_frostbolt"],
  "base_str": 3, "base_dex": 8, "base_con": 5, "base_int": 12, "base_hp": 210, "base_ap": 12,
  "str_per_level": 0, "dex_per_level": 1, "con_per_level": 1, "int_per_level": 3},
 {"id": "bleak_raider", "name": "Bleak Raider", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 28, "rarity": "common", "base_xp": 280,
  "common_drop": "stimulant_large", "rare_drop": None, "money_range": (70, 240),
  "basic_attack": "tundra slash", "strong_attack": "bleak fury",
  "player_abilities": [], "base_str": 14, "base_dex": 8, "base_con": 12, "base_int": 2, "base_hp": 320, "base_ap": 8,
  "str_per_level": 3, "dex_per_level": 1, "con_per_level": 2, "int_per_level": 0},
 {"id": "bleakwatch_lord", "name": "Bleakwatch Outpost Lord", "hostile_type": "humanoid", "role": "damage", "min_spawn_level": 36, "rarity": "rare", "base_xp": 620,
  "common_drop": "stimulant_large", "rare_drop": "herb_major", "money_range": (200, 700),
  "basic_attack": "lord's frost blade", "strong_attack": "bleak decree",
  "player_abilities": ["level_1_hostile_ability_inspire"],
  "base_str": 22, "base_dex": 10, "base_con": 20, "base_int": 6, "base_hp": 600, "base_ap": 10,
  "str_per_level": 4, "dex_per_level": 1, "con_per_level": 4, "int_per_level": 1},
 {"id": "bleakwatch_frost_witch", "name": "Bleakwatch Frost Witch", "hostile_type": "magic", "role": "hazard", "min_spawn_level": 46, "rarity": "superrare", "base_xp": 2500,
  "common_drop": "tome_int", "rare_drop": "herb_major", "money_range": (500, 1800),
  "basic_attack": "frost hex", "strong_attack": "bleak curse",
  "player_abilities": ["ice_magic_lv1_frostbolt", "ice_ice_magic_lv2_glacier_burst"],
  "base_str": 4, "base_dex": 12, "base_con": 6, "base_int": 34, "base_hp": 900, "base_ap": 30,
  "str_per_level": 0, "dex_per_level": 2, "con_per_level": 1, "int_per_level": 7},
 {"id": "tundra_titan_sm", "name": "Tundra Titan", "hostile_type": "elemental", "role": "damage", "min_spawn_level": 72, "rarity": "superrare", "base_xp": 14000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (4000, 14000),
  "basic_attack": "tundra titan slam", "strong_attack": "bleakwatch annihilation",
  "player_abilities": ["ice_ice_ice_magic_lv3_hailstorm"],
  "base_str": 80, "base_dex": 10, "base_con": 76, "base_int": 12, "base_hp": 18000, "base_ap": 14,
  "str_per_level": 16, "dex_per_level": 2, "con_per_level": 15, "int_per_level": 2},
 {"id": "bleakwatch_world_god", "name": "The Bleakwatch World God", "hostile_type": "elemental", "role": "hazard", "min_spawn_level": 100, "rarity": "superrare", "base_xp": 90000,
  "common_drop": "herb_major", "rare_drop": "herb_major", "money_range": (30000, 100000),
  "basic_attack": "world frost mandate", "strong_attack": "bleakwatch apocalypse",
  "player_abilities": ["ice_ice_ice_magic_lv3_hailstorm"],
  "base_str": 22, "base_dex": 22, "base_con": 22, "base_int": 128, "base_hp": 70000, "base_ap": 108,
  "str_per_level": 4, "dex_per_level": 4, "con_per_level": 4, "int_per_level": 26},
]
